<?php echo Util::getAgentRegistrationTab("identification",$this->agent_id); 

if(!empty($this->item)){
    if(is_array($this->item))
        $item = $this->item;
    else 
        $item = $this->item->toArray();
}
//$item = !empty($this->item)?$this->item->toArray():'';
$panNumber = isset($item['pan_number'])?$item['pan_number']:'';



echo $this->form;
?>
<script type="text/javascript">
jQuery.validator.setDefaults({
	debug: true,
	success: "valid"
});
</script>
<script type="text/javascript" charset="utf-8"> 
   $(document).ready(function() {
       
       var panStatus = '<?php echo $panNumber;?>';
       var panStatusOnError = $('#pan_number_status').val();
       //alert(panStatusOnPost);
       if(panStatus=='Applied' || panStatusOnError=='Applied'){
            $('#pan_number').val('');
            $('#pan_number-label').hide(); // Hide divs
            $('#pan_number').hide(); // Hide divs
       }
       
       $('#passport_expiry-label').hide(); // Hide divs
       $('#passport_expiry').hide(); // Hide divs
       var idtype = $('#Identification_type').val();
       var addtype = $('#address_proof_type').val();
       if(idtype == 'passport' || addtype == 'passport'){
          $('#passport_expiry-label').show(); // Hide divs
          $('#passport_expiry').show(); // Hide divs 
       }
       
       
                 $("#Identification_type").change(function() {
        if(this.value) {
            var type = this.value; 
            var addtype = $('#address_proof_type').val();
            if(type == 'passport' || addtype == 'passport'){
            
          $('#passport_expiry-label').show(); // Show divs
          $('#passport_expiry').show(); // Show divs 
       }
       else {
       $('#passport_expiry-label').hide(); // Hide divs
       $('#passport_expiry').hide(); // Hide divs
       }
            
            
            
        }
    }); 
    
    
           $("#address_proof_type").change(function() {
        if(this.value) {
            var type = this.value; 
            var idtype = $('#Identification_type').val();
            if(type == 'passport' || idtype == 'passport'){
                 
            
          $('#passport_expiry-label').show(); // Hide divs
          $('#passport_expiry').show(); // Hide divs 
       }
            else {
       $('#passport_expiry-label').hide(); // Hide divs
       $('#passport_expiry').hide(); // Hide divs
       }
            
            
        }
    });

    
    
     $('form').submit(function(){
       var idtype = $('#Identification_type').val();  
       var adtype = $('#address_proof_type').val();
       var idnum = $('#Identification_number').val();  
       var adnum = $('#address_proof_number').val();
       var pannum = $('#pan_number').val();
       var pannumstatus = $('#pan_number_status').val();
       var dob = $.trim($("#date_of_birth").val()); 
      
      /**** date of birth validation ****/
       if(dob!='' && dob!='00-00-0000') {
            
            var arr_dt = dob.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            var one_year=1000*60*60*24*365
            var age = Math.round((curdate - x)/one_year);
            if(age < 18)
                {
                    alert('Minimum age should be 18 years.');
                    $("#date_of_birth").val('');
                    $("#date_of_birth").focus();
                    return false;
                } else {             
                    if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#date_of_birth").val('');
                            $("#date_of_birth").focus();
                            return false;
                  }
             
         } } else {
                    alert('Please specify Date of Birth.');
                    $("#date_of_birth").focus();
                    return false;
               } 
          /**** date of birth validation over ****/
          
          
          
       if (idtype == 'pan' && pannumstatus == '<?php echo STATUS_ALREADY;?>'){
        if (idnum != pannum){
                  alert ('Pan Number entered does not match');
                  return false;  
              }
       }
       if (idtype == adtype ){
               if (idnum != adnum){
                 alert ('Identification and Address proof number need to be same');
                 return false;  
             }
           
           }
       if (idtype == 'passport' || adtype == 'passport'){
           var passportExpiry = $('#passport_expiry').val();
           if(passportExpiry == '00-00-0000' || passportExpiry == ''){  
              alert ('Please enter Passport Expiry date');
              $("#passport_expiry").focus();
              return false;
           } else {             
                    if (!passportExpiry.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Passport Expiry Date');
                            $("#passport_expiry").val('');
                            $("#passport_expiry").focus();
                            return false;
                  }
         }
       }
       
       
       if(idtype=='pan' && idnum!='' && pannumstatus=='Applied'){
           alert('PAN Status cannot be Applied For as you specified PAN above in Identification Type');
           return false;          
       }
       
          return true;
   }); 
}); 

$("#pan_number_status").change(function(){    
        handlePancard() ;                    
    });
    
    
     function handlePancard(){
         var panNumberStatus = $("#pan_number_status").val(); 
         //alert('dfas');
          if(panNumberStatus=='already') {
                $('#pan_number-label').show(); // Hide divs
                $('#pan_number').show(); // Hide divs
                $('#pan_number').val('');
          } else if(panNumberStatus=='Applied') {                       
                $('#pan_number-label').hide(); // Hide divs
                $('#pan_number').hide(); // Hide divs
              
          }  
     } 

</script>