  <?php //echo Util::getCardholderSignupTab("step1"); ?> 
  <div class="Boldtext">Enroll Remitter</div> 
  <span><?php echo $this->msg?></span>
  <?php echo $this->form; 
  
  $ifscCode = isset($this->remitterData['ifsc_code'])?trim($this->remitterData['ifsc_code']):'';
  $user = Zend_Auth::getInstance()->getIdentity();
  $minAge = $this->minAge;
//  $session = new Zend_Session_Namespace('App.Agent.Controller');  
//  $cardholderStep1 = isset($session->cardholder_step1)?$session->cardholder_step1:'';
  ?>
  
  
  <script type="text/javascript">
    var sendAuthButton = false;  
   function sendAuthCode(){
        $("#send_auth_code").val('1');
         sendAuthButton = true;
        $("#frmAdddetails").submit();   
      
   }
      
   $(document).ready(function() {
       
    agentId = "<?php echo $user->id;?>";
    productId = $("#product_id").val();
    
    //alert(productId);
    if(productId>0){
       // alert(productId+'----'+agentId);
        $.ajax({
                    url: '/ajax/get-remitter-registration-fee/q/'+productId+'/agent_id/'+agentId,
                        success: function(response) {
                                //alert(response);
                                $("#regn_fee").val(response);  
                                 console.log(response);

                        }

            });
    }
    
    $("#product_id").change(function(){
    productId = $("#product_id").val();  
           // alert('ds');
            $.ajax({
                url: '/ajax/get-remitter-registration-fee/q/'+$("#product_id").val()+'/agent_id/'+agentId,
                    success: function(response) {
                            //alert(response);
                            $("#regn_fee").val(response);  
                             console.log(response);
                       
                    }
         
        });
    });
    
   
//    productId = $("#product_id").val();  
//    
//    if(productId>0){
//        $.ajax({
//                    url: '/ajax/get-remitter-registration-fee/q/'+$("#product_id").val()+'/agent_id/'+agentId,
//                        success: function(response) {
//                                //alert(response);
//                                $("#regn_fee").val(response);  
//                                 console.log(response);
//
//                        }
//
//            });
//    }
//    
//    $("#product_id").change(function(){
//    productId = $("#product_id").val();  
//           // alert('ds');
//            $.ajax({
//                url: '/ajax/get-remitter-registration-fee/q/'+$("#product_id").val()+'/agent_id/'+agentId,
//                    success: function(response) {
//                            //alert(response);
//                            $("#regn_fee").val(response);  
//                             console.log(response);
//                       
//                    }
//         
//        });
//    });
    
    
        $("#bank_name").change(function(){
           // alert('ds');
            $.ajax({
                url: '/ajax/get-ifsc/q/'+$("#bank_name").val(),
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            //alert(response);
                            $("#branch_name").val('');  
                            $("#branch_city").val('');  
                            $("#branch_address").val('');
                            $("#ifsc_code").html("");
                            $("#ifsc_code").append(response);
                            console.log(response);
                            
                        }
                    }
         
        });
    });  
    
    var ifsc = "<?php echo $ifscCode;?>";
     //alert(ifsc);
    var bankName = $("#bank_name").val();
    //alert(bankName);
    if(bankName!=''){
       $.ajax({
                url: '/ajax/get-ifsc/q/'+$("#bank_name").val(),
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            //alert('one');
                            if(ifsc==''){
                                $("#branch_name").val('');  
                                $("#branch_city").val('');  
                                $("#branch_address").val('');
                            }
                            $("#ifsc_code").html("");
                            $("#ifsc_code").append(response);
                            $("#ifsc_code option[value='"+ifsc+"']").attr("selected", "selected");
                            console.log(response);
                            
                        }
                    }
         
        });
    }
    
    //alert(ifsc);
    if(ifsc !=''){
        //alert('adfasd');
     $.ajax({
                url: '/ajax/get-bankdetails/q/'+ifsc,
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            //alert(response);
                            var resArr = response.split('^');
                            $("#branch_name").val(resArr['0']);  
                            $("#branch_city").val(resArr['1']);  
                            $("#branch_address").val(resArr['2']);  
                          
                            console.log(response);
                            
                        }
                    }
         
        });
    }
   
   
     
         $("#ifsc_code").change(function(){
            $.ajax({
                url: '/ajax/get-bankdetails/q/'+$("#ifsc_code").val(),
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            var resArr = response.split('^');
                            
                           
                            $("#branch_name").val(resArr['0']);  
                            $("#branch_city").val(resArr['1']);  
                            $("#branch_address").val(resArr['2']);  
                          
                            console.log(response);
                            
                        }
                    }
         
        });
    });  
    
    
  
 
  $("#mobile").change(function(){
            $.ajax({
                url: '/ajax/mobiledup/q/'+$("#mobile").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

        //                        console.log($("#mobile_number-element ul.errors").html());
                               
                                  $("#mobile_number").after('<div class="errors">'+response+'</div>');
                             
                        }                      
                    },
                    error: function(xhr) {}
        });
    });    
    
    
   /* var cardholderAuth = "<?=$session->cardholder_auth;?>";
    var step1 = "<? echo isset($session->cardholder_step1)?$session->cardholder_step1:'';?>";
    if(cardholderAuth!='' && step1==1){
        $("#mobile_country_code").attr("disabled","disabled");
        $("#mobile_number").attr("disabled","disabled");
    }*/


    // email duplicacy check
    $("#email").change(function(){
            $.ajax({
                url: '/ajax/emaildup/q/'+$("#email").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

        //                        
                                  $("#email").after('<ul class="errors">'+response+'</div>');
                              
                        }                      
                    },
                    error: function(xhr) {}
        });
    });
    
    
    
     $('#btn_add').click(function(){
        //alert('inside');
       var authCode = "<?php echo $this->remitter_auth;?>";
       var dob = $.trim($("#dob").val()); 
       var arr_dt = dob.split("-");
       var x = new Date();
       x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
       var curdate = new Date();
       var one_year=1000*60*60*24*365
       var age = Math.round((curdate - x)/one_year);
       var minAge = "<?php echo $minAge;?>";
            
      //alert(authCode);
      /**** date of birth validation ****/
       if(authCode!='') {
           if($("#dob").val()==''){
               alert('Please enter Date of birth');
               $("#dob").focus();
               return false;
           } else if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#dob").val('');
                            $("#dob").focus();
                            return false;
                  }
              else if(age < minAge)   
              {
                alert('Minimum age should be '+minAge+' years');
                $("#dob").val('');
                $("#dob").focus();
                return false;
              }
           }
             
   
   });
   
   
        
    }); // ready closes here
   //});   
    
//});  


    
    /*$('form').submit(function(){
       //var dob = $.trim($("#date_of_birth").val()); 
      
      /**** date of birth validation ****/
     /*  if(dob!='') {
            
            var arr_dt = dob.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            var one_year=1000*60*60*24*365
            var age = Math.round((curdate - x)/one_year);
            if(age < 18)
                {
                    alert('Minimum age should be 18 years');
                    $("#date_of_birth").val('');
                    $("#date_of_birth").focus();
                    return false;
                } else {             
                    if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#date_of_birth").val('');
                            $("#date_of_birth").focus();
                            return false;
                  }
             
         } } else if(!sendAuthButton) {
                    alert('Please specify date of birth');
                    $("#date_of_birth").focus();
                    return false;
               } 
          /**** date of birth validation over ****/
          
        
    //return true;
         
//});
   
  
 <?php
    $session = new Zend_Session_Namespace('App.Agent.Controller');    
 ?>
     var remitter_auth = <?php echo isset($session->remitter_auth)?$session->remitter_auth:0;?>;
     var validated_remitter_auth = <?php echo isset($session->validated_remitter_auth)?$session->validated_remitter_auth:0;?>    

     //alert(cardholder_auth);
     
     if(remitter_auth!='' && remitter_auth>0){       
         //$("#btn_auth_code").attr("disabled","disabled");
         $("#btn_auth_code").html('Resend Authorization Code');
         //$('#btn_auth_code').after("<a id='resend_auth' href=''> Resend Auth Code</a>").show('slow');
         //$('#resend_auth_code').val('resend');
         
     }   
     
     if(validated_remitter_auth==1){
         $("#mobile").attr("readonly","readonly");
     }
     
  </script>