<?php
/**
 * Displays the No Cookie error
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_error
 * @copyright company
 */
?>
<div class="Boldtext">Cookie is disabled</div>

<p>You need to change a setting in your web browser</p>

<p>We requires a browser feature called Cookie. All modern browsers support Cookie. You probably just need to change a setting in order to turn it on.</p>

Thank you.