<?php
/**
 * Displays the No Script error
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_error
 * @copyright company
 */
?>
<div class="Boldtext">Javascript is disabled</div>


<p>You need to change a setting in your web browser</p>

<p>We requires a browser feature called JavaScript. All modern browsers support JavaScript. You probably just need to change a setting in order to turn it on.</p>

<p>Please see: How to enable JavaScript in your browser. - Link : http://www.google.com/support/bin/answer.py?answer=23852</p>

<p>If you use ad-blocking software, it may require you to allow JavaScript. Once you've enabled JavaScript you can try loading this page again.</p>

Thank you.