<div class="Boldtext">Edit Hospital</div> 
<?php echo $this->form; ?>





<script type="text/javascript">
$(document).ready(function() {    
     



 var city = "<?php echo $this->city;?>";
 var pincode = "<?php echo $this->pincode;?>";
 //alert($("#state").val());
 if($("#city").val() != ''){
  $.ajax({
                url: '/ajax/get-pincode/q/'+city,
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#pin_code").html("");                            
                            $("#pin_code").append(response);
                            $("#pin_code option[value='"+pincode+"']").attr("selected", "selected");
                        }
                    }     
        });
 }  
 if($("#state").val() != ''){
         $.ajax({
                url: '/ajax/get-city/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                         
                        } else {
                            //alert(response);
                            //$("#city").html("");
                            //$("#city").append(response);
                            $("#city option[value='"+city+"']").attr("selected", "selected");
                            //console.log(response);
                        }
                    },
         
        });
}  
      
  
  $("#state").change(function(){
    
            $.ajax({
                url: '/ajax/get-city/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                            //$("#res_state-element ul.errors").html('');
                        } else {
                            $("#city").html("");
                            //$("#res_city").append('<option value=Achalpur>Achalpur</option>');
                            $("#city").append(response);
                           // document.getElementById("res_city").innerhtml = '<option="Achalpur">Achalpur</option>';
                            console.log(response);
                        }
                    },
        });
    }); 
 $("#city").change(function(){
            $.ajax({
                url: '/ajax/get-pincode/q/'+$("#city").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#pin_code").html("");                            
                            $("#pin_code").append(response);
                        }
                    }     
        });
    });    
    
});     

</script>