<?php 
  
  echo Util::getCardholderEditTab("step1", Util::getEncrypt($this->chDetails['cardholder_id'])); ?> 
  <span><?=$this->msg?></span>
  <?php echo $this->form; ?> 
  
  
  <script type="text/javascript">
  var sendAuthButton = false;  
  function sendAuthCode(){
        $("#send_auth_code").val('1');
         sendAuthButton = true;
        $("#frmStep1").submit();       
   }
      
   
$(document).ready(function() {
    //alert($("#arn").val());
    
    $("#arn").change(function(){
            $.ajax({
                url: '/ajax/arndup/q/'+$("#arn").val()+'/tablename/cardholder_details',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

         
                                  $("#arn").after('<div class="errors">'+response+'</div>');
                              
                        }                      
                    },
                    error: function(xhr) {}
        });
    });  
    
    
    
  $("#mobile_number").change(function(){
            $.ajax({
                url: '/ajax/mobiledup/q/'+$("#mobile_number").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

        //                        console.log($("#mobile_number-element ul.errors").html());
                               
                                  $("#mobile_number").after('<div class="errors">'+response+'</div>');
                             
                        }                      
                    },
                    error: function(xhr) {}
        });
    });    
    
    
   /* var cardholderAuth = "<?=$session->cardholder_auth;?>";
    var step1 = "<? echo isset($session->cardholder_step1)?$session->cardholder_step1:'';?>";
    if(cardholderAuth!='' && step1==1){
        $("#mobile_country_code").attr("disabled","disabled");
        $("#mobile_number").attr("disabled","disabled");
    }*/


    // email duplicacy check
    $("#email").change(function(){
            $.ajax({
                url: '/ajax/emaildup/q/'+$("#email").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

        //                        
                                  $("#email").after('<ul class="errors">'+response+'</div>');
                              
                        }                      
                    },
                    error: function(xhr) {}
        });
    });
        
    
    // mvc type check
    $("#customer_mvc_type").change(function(){
    
       handleMVCType();       
    });
    
    $("#customer_mvc_type").keypress(function(){
       handleMVCType();       
    });
    
    function handleMVCType(){        
        var mvcType = $("#customer_mvc_type").val();  
       
          if(mvcType=='mvcc') {
             
              $("#send_download_link-label").show();
              $("#send_download_link-element").show();
              $("#device_id-label").show();
              $("#device_id-element").show();
              $("#send_download_link").show();
              $("#device_id").show();              
          } else if(mvcType=='mvci' || mvcType=='') { 
            
              $("#send_download_link-label").hide();
              $("#send_download_link").hide();
              $("#send_download_link-element").hide();
              $("#device_id-label").hide();
              $("#device_id").val('');
              $("#device_id-element").hide(); 
              $("#device_id").hide(); 
          }         
    }
    handleMVCType();
    
    $("#send_download_link").click(function(){
         $("#send_download_link-element ul.errors").html('');
         
        if($("#mobile_number").val() == '') {
            $("#send_download_link").after('<div class="errors">Please enter mobile number</div>');
            return false;
        }
        if($("#mobile_country_code").val() == '') {
            $("#send_download_link").after('<div class="errors">Please select mobile country code</div>');
            return false;
        }
       //if($("#mobile_number").val().length != 0 && $("#mobile_country_code").val().length != 0){ 
        var validMobnumber = $("#mobile_country_code").val()+$("#mobile_number").val();
            $.ajax({
                url: '/ajax/send-download-link/mob/'+validMobnumber,
                    success: function(response) {
        //                        console.log($("#mobile_number-element ul.errors").html());
                              if($(".errors").html() == '' || $(".errors").val() == 'undefined' 
                                  || $(".errors").val() == null) {
        //                          console.log("aa");  
                                  $("#send_download_link").after('<div class="errors">'+response+'</div>');
                              } else {
        //                          console.log("bb");
                                  $(".errors").html('');
                                  $(".errors").html('<div class="errors">'+response+'</div>');
                              }
                      //  }                      
                    },
                    error: function(xhr) {}
        });
    //}
    
    });    
    // age check between 18 to 60 years
//$("input#date_of_birth").change(function() {
//
//        if(this.value) {
//            var dob = this.value; 
//            
//            var arr_dt = dob.split("-");
//            var x = new Date();
//            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
//            var curdate = new Date();
//            var one_year=1000*60*60*24*365
//            var age = Math.round((curdate - x)/one_year);
//            if(age < 18)
//                {
//                    alert('You need to be atleast 18 years to enroll');
//                    this.value = '';
//                    return false;
//                }
//          
//        }
//    });
    
    
    $('form').submit(function(){
       var mvcType = $("#customer_mvc_type").val();   
       var dob = $.trim($("#date_of_birth").val()); 
      
      /**** date of birth validation ****/
       if(dob!='') {
            
            var arr_dt = dob.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            var one_year=1000*60*60*24*365
            var age = Math.round((curdate - x)/one_year);
            if(age < 18)
                {
                    alert('Minimum age should be 18 years');
                    $("#date_of_birth").val('');
                    $("#date_of_birth").focus();
                    return false;
                } else {             
                    if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#date_of_birth").val('');
                            $("#date_of_birth").focus();
                            return false;
                  }
             
         } } else if(!sendAuthButton) {
                    alert('Please specify date of rirth');
                    $("#date_of_birth").focus();
                    return false;
               } 
          /**** date of birth validation over ****/
          
          
          if(mvcType=='mvcc') {
               if($("#device_id").val()=== ''){
                   alert('Please enter device Id');
                   return false;
               }
          } 
    return true;
         
});


});  


    
    
 <?php
    $session = new Zend_Session_Namespace('App.Operation.Controller');    
 ?>
     var cardholder_auth = <?php echo isset($session->cardholder_auth)?$session->cardholder_auth:0;?>;
     //alert(cardholder_auth);
     
     if(cardholder_auth!='' && cardholder_auth>0){       
         $("#btn_auth_code").attr("disabled","disabled");
     }        
  </script>