<div class="Boldtext">Balance Sync Exception Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->from!='' && $this->to!=''){
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
   $config['columnNames'] = array(
        'Agent Code',
        'Agent Name',
        'Card Pack ID',
        'Amount',
        'Error Reason',
        'Date & Time',
        'ECS Customer registration status'
    );
    
$config['showActions'] =FALSE;
$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
																
                        <td><?php echo $item['agent_code'];?></td> 
                        <td><?php echo $item['agent_name'];?></td>
                        <td><?php echo $item['card_pack_id'];?></td> 
                        <td><?php echo $item['val'];?></td>
                        <td><?php echo $item['reason'];?></td> 
                        <td><?php echo $item['date_created'];?></td> 
                        <td><?php echo ucfirst($item['status_ecs']); ?></td>
                    
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 

<?php
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls">        
    <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">   
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        
            var url = '<?php echo $this->formatURL("/corp_ratnakar_reports/exporbalancesyncexception?to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']);?>';    
            $(location).attr('href',url);
    });
    
    $('form').submit(function() {  
        var from = $.trim($("#from_date").val()); 
        var to = $.trim($("#to_date").val());       
        var from_dt = from.split("-");
        var to_dt = to.split("-");
        var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
        var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
        var diff = y - x;
        var one_day=1000*60*60*24;
        var date_range = diff/one_day;
        var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
        /**** From and To date validation ****/
        if(from=='' && to==''){
            alert('Please select from and to date.');
            $("#from_date").focus();
            return false;
        } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
            alert('Please specify both From and To date.');
            $("#from_date").focus();
            return false;
        } else if(diff < 0){
            alert('From date cannot be greater than To date.');
            $("#from_date").focus();
            return false; 
        } else if(date_range > max_range){
            alert('Report can be fetched for a duration not more than '+max_range+' days');
            $("#to_date").focus();
            return false; 
        }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>