 <?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = $this->setting_section_name;
$config['emptyMessage'] = 'No agent setting found.';
$config['no_add']=1;  //to not have add button

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Description',
    'Value',
    'Added By',
    'IP',
    'Created Date'   
);

$config['columnIndexes'] = array(
    'name',
    'description',
    'value',
    'ops_name',
    'ip',
    'date_created'    
);

$config['actions'] = array(
     'edit' =>array(
        'action'        => 'edit',
        'title'         => 'Edit',
        'parameter'     => TRUE,
        'icon'          => TRUE,
        'img_url'       => '/images/icons/edit.png',
        //'link_class'    => 'btn',
        'img_alt'       => 'edit',
    )  
);


$config['linkOrder'] = array('edit');
$config['showComma'] = array('value');
// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);

//echo "<pre>";print_r($this->paginator);exit;