<?php
/**
 * View that allows the user to change his/her mobile number
 *
 * @category agent
 * @package agent_views
 * @subpackage agent_views_profile
 * @copyright transerv
 */
?>
<div class="Boldtext">Change Mobile Number</div>
<?php echo $this->form;?>

<?php
/*
 * echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);
 */

?>
