<div class="Boldtext"><?= $this->heading ?></div> 
<div class="tablebox">
    <table style="width: 100%">
        <tr>
            <th style="width:20%">Active Balance</th>            
            <td style="width: 80%" align="left"><?php echo '<span class="WebRupee"></span>' . $this->balance; ?></td>
        </tr>
        <?php if (isset($this->virtualbalance)) { ?>
            <tr>
                <th style="width:20%">Virtual Balance</th>            
                <td style="width: 80%" align="left"><?php echo '<span class="WebRupee"></span>' . $this->virtualbalance; ?></td>
            </tr>
        <?php } ?>
    </table>
</div>
