<script>
$("div:contains('as per our records')").css("text-decoration", "underline");</script>
<?php
/**
 * View for the login action
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */
?>
<div class="Boldtext">Confirm Details</div>
 <?php echo $this->form;?>



<script type="text/javascript">
$(document).ready(function() {    
    

    
     $('form').submit(function(){
       
       var email = $("#email").val(); 
       var mobile = $("#mobile1").val(); 
       var date_of_birth = $.trim($("#date_of_birth").val()); 
  
    
       if(email=='' || date_of_birth=='' || mobile == ''){
            alert('Please specify all fields.');
            return false;
       } 
               
     return true; 
   });    
});
</script>