<?php
/**
 * Delete a product
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Delete Corporate';
$config['areYouSureMessage'] = 'Are you sure you want to delete corporate details?';

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'ECS Corporate Id',
    'City',
);
$config['columnIndexes'] = array(
    'name',
    'ecs_corp_id',
    'city'
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);