<div class="Boldtext">Corporates Search</div>
<?php
/**
 * Displays all the searched and corporate active users
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

$config = array();

// messages
$config['pageTitle'] = 'Corporate Listing';
$config['addMessage'] = 'Add New Corporate'; 
$config['emptyMessage'] = 'There is no corporate added at this time.';
$config['no_add'] = true;

// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Last Name',
    'Corporate Code',
    'Contact Phone',
    'Contact Email',
    'City',
    'State',
    'District',
    'Enroll Status',
    'Email Verification Status',
    'Status'
);
$config['columnIndexes'] = array(
    'first_name',
    'last_name',
    'corporate_code',
    'mobile',
    'email',
    'estab_city',
    'estab_state',
    'estab_district',
    'enroll_status',
    'email_verification_status',
    'status'
);

$config['showActions'] = false;

$config['linkCol'] = array(
            array(
                'linkColName'       => 'corporate_code',
                'linkController'    => 'corporates',
                'linkAction'        => 'view',
                'linkTitle'         => 'View Corporate Details',
                'linkParamReqd'     => TRUE,
                'linkParamName'     => 'id',
            )
        );

$config['noteText'] = 'Corporate cannot be deleted';
// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);
?>
<script type="text/javascript">
    $(document).ready(function(){     
        $("#searchCriteria").change(function(){
            $("#keyword").val('');
        });
    });
    
    $('form').submit(function(){
        var search_criteria = $("#searchCriteria").val(); 
        var keyword = $("#keyword").val(); 
        
        if(search_criteria == '')
        {
            alert('Please select search criteria');
            return false;
        }
        else if(keyword == '')
        {
            alert('Please provide search value');
            $("#keyword").focus();
            return false;
        }
        return true;
    });
</script>