<?php
/**
 * Displays an user
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */

$config = array();
$id = $this->item['id'];
$config['id'] =$this->item['id'];
$config['balance'] = $this->balance;
$config['corporate_id'] = $this->corporate_id;
$config['productarray'] =$this->productArr;
$config['limitarray'] =$this->limitArr;
$config['documentarray'] =$this->document;
$config['detailsarray'] =$this->item;


echo $this->partial(
        
    'partials/default-corporate-detail-view.phtml',
    array(
        'config' => $config,
        'item' => $this->item
    )
);

print '<script type="text/javascript">
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1", {defaultTab:0});
</script>';
