<?php
$config = array();
// column names & indexes
/*$config['columnNames'] = array(
    'Authorize Status',
    'Response Code',
    'Response Description',
);
$config['columnIndexes'] = array(
    'auth_status',
    'resp_code',
    'resp_desc'
);

echo $this->partial(
        'partials/default-listing.phtml', array(
    'config' => $config,
     'paginator' => $this->paginator
        )
);
*/
?>



<div class="Boldtext">Transaction Details</div> 
<div class="tablebox">
   
    <table style="width: 100%">
        
            <tr>
                <th style="width:20%">Authorize Status</th>            
                <td style="width: 80%" align="left"><?php echo $this->info['auth_status'];?></td>
            </tr>         
            <tr>
                <th style="width:20%">Response Code</th>            
                <td style="width: 80%" align="left"><?php echo $this->info['resp_code'];?></td>
            </tr>         
            <tr>
                <th style="width:20%">Response Description</th>            
                <td style="width: 80%" align="left"><?php echo $this->info['resp_desc'];?></td>
            </tr>         
             
    </table>
   
</div>
