<div class="Boldtext">Ratnakar Remittance</div> 
<?php
echo $this->form;
if (!empty($this->paginator)) {
    $config = array();
    // messages
    $config['pageTitle'] = 'Transactions';
    $config['no_add'] = TRUE;
    if($this->showBackLink){
    	$config['back_url'] = '/remit_ratnakar_beneficiary/searchremitter?flgSess=1';
    }
    $config['showActions'] = FALSE;
    $config['emptyMessage'] = 'There is no transaction associated with this mobile number.';
   
    $config['columnNames'] = array(
        'Transaction Date',        
        'Reference No.',
        'UTR No.',
        'Remitter Name',
        'Beneficary Name',
        'Amount',
        'Status',
'Transfer Mode'
    );
    $config['columnIndexes'] = array(
        'date_created',
        'txn_code',
        'utr',
        'name',
        'beneficiary_name',
        'amount',
        'status',
'flag',
    );
$config['actions'] = array();
$config['showComma'] = array('amount');
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$cntColNames = count($config['columnNames']) - 1;
$neftStatus = Zend_Registry::get("REMIT_STATUS");
?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>
<?php if($this->showBackLink){ ?>
<div style="width:950px;">
    <a href="<?php echo $this->formatURL($config['back_url']);?>" class="ocean" style="float:right;" title="Back">Back</a>
</div><!--Inner Style Div END-->
<?php }     ?>
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
                <th><span>ReQuery</span></th>
            
</tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            
            foreach($this->paginator as $item) : 
                   $datePrev = '';  ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][0]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo $neftStatus[$item[$config['columnIndexes'][6]]]; ?></td>

<td><?php $flag = $item[$config['columnIndexes'][7]];
                        		  if($flag==2){
                        		  	echo "IMPS";
                        		  }else if($flag==3){
                        		  	echo "NEFT";
                        		  }else{
                        		  	echo "";
                        		  }
                        	?>
                        </td>

                                               <td><?php if(STATUS_PROCESSED == $item->status ||STATUS_SUCCESS == $item->status || STATUS_HOLD == $item->status ){ ?><a href="<?php echo $this->formatURL('/remit_ratnakar_remitter/requery/transid/'.$item->remittance_request_id);?>"  title="Re-Query">Re-Query</a> <?php }?></td>
                        
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+2;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } }
?>

<script type="text/javascript">
    var mobileno = /^[0-9]{10,10}$/;
    $('#submit').click(function(e){
        if($("#mobile").val() == '') {
            alert("Please provide mobile number");
            $("#mobile").focus();
            return false;
        } else if(mobileno.test($('#mobile').val()) == false){
            alert("Invalid Mobile Number");
            $('#mobile').focus();
            return false;
        }
        return true;
    });
</script>