<script type="text/javascript" charset="utf-8"> 
   $(document).ready(function() {
       
       $('.cancel').attr('href',document.referrer);
        
       $("input#date_start").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x <= curdate)
            {
                alert("Please enter start date greater than today's date");
                this.value = '';
                return false;
            }else{      
            
                    if (!date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                        alert('Please enter valid start date');
                        $("#date_start").val('');
                        $("#date_start").focus();
                        return false;
                    }
                } 

        }
        
    });
    $("form").submit(function(){
       
        if($("#date_start").val() == '')
        {
            alert('Please enter valid start date');
            $("#date_start").focus();
            return false;
        }
        else 
        {
            var date_start = $("#date_start").val();
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x <= curdate)
            {
                alert("Please enter start date greater than today's date");
                $("#date_start").val('');
                $("#date_start").focus();
                return false;
            } else{      
            
                    if (!date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                        alert('Please enter valid start date');
                        $("#date_start").val('');
                        $("#date_start").focus();
                        return false;
                    }
                } 

        }
            
        return true;
    });       

}); 

</script><?php
/**
 * Edit a privilege
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Edit Assigned Corporate Limit';

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);