<div class="Boldtext">Cardholder Batch Status</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Cardholder Batch: '.$this->batch_name;
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';
//$config['addURL'] = '/agents/signup/';

// column names & indexes
$config['columnNames'] = array(
    'Member Id',
    'Employee Id',
    'Card Number',
    'Name',
    'Name on Card',
    'Gender',
    'Date of Birth',
    'Mobile',
    'Email',
    'Employer Name',
    'Corporate Id',
    'Status',
    'Failed Reason',
    );
$config['columnIndexes'] = array(
    'member_id',
    'employee_id',
    'card_number',
    'cardholder_name',
    'name_on_card',
    'gender',
    'date_of_birth',
    'mobile',
    'email',
    'employer_name',
    'corporate_id',
    'status',
    'failed_reason',
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("STATUS");
?>
<?php echo $this->form; ?> 
<?php if($this->sub):?>  
<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                    //foreach($dateArr as $item) :?>
            

                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                    
                        <td><?php echo $item['member_id'];?></td>
                        <td><?php echo $item['employee_id'];?></td>
                        <td><a href="<?php echo $this->formatURL('/corp_kotak_cardholder/view?id='.$item['id'].'&viewc=batchstatus&'.$this->backLink);?>"><?php echo Util::maskCard($item['card_number']);?></a></td>
                        <td><?php echo $item['cardholder_name'];?></td>
                        <td><?php echo $item['name_on_card'];?></td>
                        <td><?php echo ucfirst($item['gender']);?></td>
                        <td><?php echo Util::returnDateFormatted($item['date_of_birth'], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item['mobile']?></td>
                        <td><?php echo $item['email']?></td>
                        <td><?php echo $item['employer_name']?></td>
                        <td><?php echo $item['corporate_id']?></td>
                        <td><?php  echo $cardholderStatus[$item['status']]?></td>
                        <td><?php  echo $item['failed_reason']?></td>
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php }
?>
<?php endif;?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
       
         var url = '<?php echo $this->formatURL("/corp_kotak_cardholder/exportbatchstatus?batch_name=".$this->batch_name."&product_id=".$this->product_id."&start_date=".$this->start_date."&end_date=".$this->end_date);?>';    
         $(location).attr('href',url);
       
    });
    
    
    
   var batch = $("#batch").val();
   
   if($("#start_date").val() != '' && $("#end_date").val() != '' && $("#product_id").val() != ''){
        $.ajax({ 
                url: '/ajax/getkotak-batchbydate/q/'+$("#start_date").val()+'/p/'+$("#end_date").val()+'/r/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else { 
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
                            $("#batch_name option[value='"+batch+"']").attr("selected", "selected");
//                            console.log(response);                            
                        }
                    }     
        });
    }  
      
    $("#end_date").change(function(){
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      //return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        if($("#start_date").val() != ''){
            $.ajax({
                url: '/ajax/getkotak-batchbydate/q/'+$("#start_date").val()+'/p/'+$("#end_date").val()+'/r/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
//                             console.log(response);                            
                        }
                    }     
        });
        }
        else{
        alert('Please fill in From Date');
        }
    }); 
    
    $("#start_date").change(function(){
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate){
                alert("Please enter From date not greater than today's date");
                this.value = '';
                return false;
            }else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      //return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#start_date").focus();
                      return false;
                    }
            }
        }
        
        if($("#end_date").val() != ''){
            $.ajax({
                url: '/ajax/getkotak-batchbydate/q/'+$("#start_date").val()+'/p/'+$("#end_date").val()+'/r/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
//                             console.log(response);                            
                        }
                    }     
        });
        }
        else{
        alert('Please fill in To date Date');
        }
    });
    
    
    $("#product_id").change(function(){
        if($("#start_date").val() != '' && $("#end_date").val() != ''){
            $.ajax({
                url: '/ajax/getkotak-batchbydate/q/'+$("#start_date").val()+'/p/'+$("#end_date").val()+'/r/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
//                             console.log(response);                            
                        }
                    }     
            });
        }
        
     }); 
    
    
    $('form').submit(function(){
  
       var from = $.trim($("#start_date").val()); 
       var to = $.trim($("#end_date").val()); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       /**** From and To date validation ****/
       if((from == '') || (to == '') ) {
                    alert('Please specify both From and To date.');
                    $("#from_date").focus();
                    return false;
        }  
       else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify both From and To date.');
                    $("#from_date").focus();
                    return false;
        } else if(diff < 0){
           alert('From date cannot be greater than To date.');
             $("#from_date").focus();
             return false; 
        }
              
        /**** From and To date validation over ****/
          
        return true; 
   });
    
    
});
</script>