<div class="Boldtext">KYC Upgrade Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'KYC Upgrade Report';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';
//$config['addURL'] = '/agents/signup/';

// column names & indexes
$config['columnNames'] = array(
    'Member Id',
    'Employee Id',
    'Card Number',
    'Name',
    'Name on Card',
    'Gender',
    'Date of Birth',
    'Mobile',
    'Email',
    'CRN',
    'Product Code',
    'Bank Name',
    'Aadhar Number',
    'Creation Date',
    'Customer Address 1',
    'Customer Address 2',
    'Pin Code',
    'State',
    'Upgrade Date',
    'KYC Status',
    );

$cntColNames = count($config['columnNames']) ;
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;

?>
<?php echo $this->form; ?> 
<?php if($this->sub):?>  
<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                    //foreach($dateArr as $item) :?>
            

                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                    
                        <td><?php echo $item['member_id'];?></td>
                        <td><?php echo $item['employee_id'];?></td>
                        <td><?php echo Util::maskCard($item['card_number'],4);?></td>
                        <!-- <td><a href="<?php echo $this->formatURL('/corp_kotak_cardholder/view?id='.$item['id'].'&viewc=batchstatus'.'&'.$this->backLink);?>"><?php echo $item['card_number'];?></a></td> -->
                        <td><?php echo ucfirst($item['cardholder_name']);?></td>
                        <td><?php echo $item['name_on_card'];?></td>
                        <td><?php echo ucfirst($item['gender']);?></td>
                        <td><?php echo Util::returnDateFormatted($item['date_of_birth'], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item['mobile']?></td>
                        <td><?php echo $item['email']?></td>
                        <td><?php echo $item['crn']?></td>
                        <td><?php echo ''; ?></td>
                        <td><?php echo $this->bank_name; ?></td>
                        <td><?php echo $item['aadhaar_no']?></td>
                        <td><?php echo Util::returnDateFormatted($item['date_created'], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item['address_line1']?></td>
                        <td><?php echo $item['address_line2']?></td>
                        <td><?php echo $item['pincode']?></td>
                        <td><?php echo ucfirst($item['state']); ?></td>
                        <td><?php echo Util::returnDateFormatted($item['date_toggle_kyc'], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo strtoupper($item['customer_type']); ?></td>
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php }
?>
<?php endif;?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
       
         var url = '<?php echo $this->formatURL("/corp_kotak_cardholder/exportkycupgradereport?product_id=".$this->product_id."&from_date=".$this->from_date."&to_date=".$this->to_date."&dur=".$this->dur);?>';    
         $(location).attr('href',url);
       
    });
    
    $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       /**** From and To date validation ****/
      if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
            alert('Please select either duration or from and to date.');
            $("#dur").focus();
            return false;
      } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                    alert('Please specify From date.');
                    $("#from_date").focus();
                    return false;
               }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify To date.');
                    $("#to_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date cannot be greater than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });
    
    
});
</script>