<?php
/**
 * Displays an user
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */
$config = array();
$config['pageTitle'] = sprintf('Detailed view for %s', $this->item['first_name']);


// column names & indexes
$config['columnNames'] = array(
    'CRN',
    'Card Number',
    'AFN',
    'Member Id',
    'Employee Id',
    'First Name',
    'Middle Name',
    'Last Name',
    'Name on Card',
    'Gender',
    'Date of Birth',
    'Mobile',
    'Email',
    'Address 1',
    'Address 2',
    'City',
    'Pincode',
    'Employer Name',
    'Corporate Id',
    'Status',
    'Failed Date',
    'Failed Reason',
);
$config['columnIndexes'] = array(
    'crn',
    'card_number',
    'afn',
    'member_id',
    'employee_id',
    'first_name',
    'middle_name',
    'last_name',
    'name_on_card',
    'gender',
    'date_of_birth',
    'mobile',
    'email',
    'address_line1',
    'address_line2',
    'city',
    'pincode',
    'employer_name',
    'corporate_id',
    'status',
    'date_failed',
    'failed_reason'
);

$config['backlink'] = $this->backlink;

echo $this->partial(
        'partials/default-view.phtml', array(
    'config' => $config,
    'item' => $this->item
        )
);
 $document = $this->documents;

 if(empty($document))
           {
               echo '<div class="norecord">No Documents uploaded!</div>';
             
            }else{
           
                $imgPath = '/images/icons/others.png';
               
                if ($document['id_proof_doc'] > 0) {
               $formatUrlId = $this->formatURL("/filedownload/index?file=".$document['id_proof_doc']."&path=kotak_customer");
               
               ?><a href="<?php echo $formatUrlId; ?>"><img src=<?php echo $imgPath;?> width="100" height="100" border="0" title="Id proof document"/></a>
               <?php }
                if ($document['address_proof_doc'] > 0) {
                 $formatUrlAdd = $this->formatURL("/filedownload/index?file=".$document['address_proof_doc']."&path=kotak_customer");
                 ?><a href="<?php echo $formatUrlAdd; ?>"><img src=<?php echo $imgPath;?> width="100" height="100" border="0" title="Address proof document"/></a>
            <?php  
                 }
                 
                 }           
//card holder purses cofig var
$cardholderPursesCofig['pageTitle'] = $this->item['first_name'] . ' ' . $this->item['middle_name'] . ' ' . $this->item['last_name'] . "'s Purses";
$cardholderPursesCofig['no_add'] = true;
$cardholderPursesCofig['showActions'] = FALSE;

if (empty($this->cardholderPurses)) {
    echo '<div class="norecord">There is no purse available for this Card Holder!</div>';
} else {

    // column names & indexes
    $cardholderPursesCofig['columnNames'] = array(
        'Name',
        'Description',
        'Amount'
    );
    $cardholderPursesCofig['columnIndexes'] = array(
        'name',
        'description',
        'amount'
    );

    // render the default listing
    echo $this->partial(
            'partials/default-listing.phtml', array(
        'config' => $cardholderPursesCofig,
        'paginator' => $this->cardholderPurses,
            )
    );
}
?>

<div class="back" style="margin-left:30px;margin-top:15px"><a class="alt" href="<?php echo $this->formatURL($this->backlink); ?>">← Back</a></div>
