 <?php echo Util::getCardholderSignupTab("step1"); ?> 
 <div class="Boldtext">Step1 Details</div> 
  <span><?php echo $this->msg?></span>
  <?php 
  echo $this->form;  
  $session = new Zend_Session_Namespace('App.Agent.Controller');  
  $cardholderStep1 = isset($session->cardholder_step1)?$session->cardholder_step1:'';
  ?>
  
  
  <script type="text/javascript">
    var sendAuthButton = false;  
   function sendAuthCode(){
        $("#send_auth_code").val('1');
         sendAuthButton = true;
        $("#frmStep1").submit();   
      
   }
      
/* temporarily commented for revert
$(document).ready(function() {
    //alert($("#arn").val());
     
      var errorExists = "<?php //echo isset($this->errorExists)?$this->errorExists:'';?>";    
     var cardholderStep1 = "<?php //echo $cardholderStep1;?>";
     if(errorExists || !cardholderStep1){
         $("#btn_next").attr("disabled","disabled");
     }
     
    $("#btn_discard").click(function(){
        discardResp = confirm('Are you sure you want to discard this customer enrollment form?');

        if(discardResp==true){
           return true;
        }else {
            return false;
        }
     });
     
   });*/
   
   
    $("#arn").change(function(){
            $.ajax({
                url: '/ajax/arndup/q/'+$("#arn").val()+'/tablename/cardholder_details',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

         
                                  $("#arn").after('<div class="errors">'+response+'</div>');
                              
                        }                      
                    },
                    error: function(xhr) {}
        });
    });  
    
    
    
  $("#mobile_number").change(function(){
            $.ajax({
                url: '/ajax/mobiledup/q/'+$("#mobile_number").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            //alert('from mobile num');
                            $(".errors").html('');
                        } else {

        //                        console.log($("#mobile_number-element ul.errors").html());
                               
                                  $("#mobile_number").after('<div class="errors">'+response+'</div>');
                             
                        }                      
                    },
                    error: function(xhr) {}
        });
    });    
    
    
   /* var cardholderAuth = "<?=$session->cardholder_auth;?>";
    var step1 = "<? echo isset($session->cardholder_step1)?$session->cardholder_step1:'';?>";
    if(cardholderAuth!='' && step1==1){
        $("#mobile_country_code").attr("disabled","disabled");
        $("#mobile_number").attr("disabled","disabled");
    }*/


    // email duplicacy check
    $("#email").change(function(){
            $.ajax({
                url: '/ajax/emaildup/q/'+$("#email").val()+'/tablename/cardholder',
                    success: function(response) {
                        if(response == 1) {
                            $(".errors").html('');
                        } else {

        //                        
                                  $("#email").after('<ul class="errors">'+response+'</div>');
                              
                        }                      
                    },
                    error: function(xhr) {}
        });
    });
        
    
    // mvc type check
    $("#customer_mvc_type").change(function(){
       handleMVCType();       
    });
    
    $("#customer_mvc_type").keypress(function(){
       handleMVCType();       
    });
    
    
    function handleMVCType(){        
        var mvcType = $("#customer_mvc_type").val();  
       
          if(mvcType=='mvcc') {
              $("#send_download_link-label").show();
              $("#send_download_link-element").show();
              $("#device_id-label").show();
              $("#device_id-element").show();
              $("#send_download_link").show();
              $("#device_id").show();     
              if($("#div_send_download_link")!=null){
                 $("#div_send_download_link").show();   
              }
          } else if(mvcType=='mvci' || mvcType=='') { 
             
              $("#send_download_link-label").hide();
              $("#send_download_link").hide();
              $("#send_download_link-element").hide();
              $("#device_id-label").hide();
              $("#device_id").val('');
              $("#device_id-element").hide(); 
              $("#device_id").hide(); 
              $("#div_send_download_link").hide();  
          }         
    }
    handleMVCType();
    
    $("#send_download_link").click(function(){
         //$("#send_download_link-element").html('');
         
        if($("#mobile_number").val() == '') {
            if(document.getElementById('div_send_download_link') == null){
                $("#send_download_link").after('<div class="btn_download_errors" id="div_send_download_link">Please enter mobile number</div>');
            } else {
                $("#div_send_download_link").replaceWith('<div class="btn_download_errors" id="div_send_download_link">Please enter mobile number</div>');
            }
            return false;
        }
        
        if($("#mobile_country_code").val() == '') {
            //alert('from mobile country code');
          if(document.getElementById('div_send_download_link') == null){
            $("#send_download_link").after('<div class="btn_download_errors" id="div_send_download_link">Please select mobile country code</div>');
          } else {
                //alert('aaaa');
                //<div class="errors" id="div_send_download_link">Please select mobile country code</div>
                //$("#div_send_download_link").html('');
                $("#div_send_download_link").replaceWith('<div class="btn_download_errors" id="div_send_download_link">Please select mobile country code</div>');
                //alert($("#div_send_download_link").html);
                //alert('bbbb');
            }
            //alert('bbbb');
            return false;
           // alert('cccccc');
        }
        
       //if($("#mobile_number").val().length != 0 && $("#mobile_country_code").val().length != 0){ 
        var validMobnumber = $("#mobile_country_code").val()+$("#mobile_number").val();
            $.ajax({
                url: '/ajax/send-download-link/mob/'+validMobnumber,
                    success: function(response) {
        //                        console.log($("#mobile_number-element ul.errors").html());
                              if($(".btn_download_errors").html() == '' || $(".btn_download_errors").val() == 'undefined' 
                                  || $(".btn_download_errors").val() == null) {
        //                          console.log("aa");  
                                  $("#send_download_link").after('<div class="btn_download_errors" id="div_send_download_link">'+response+'</div>');
                              } else {
        //                          console.log("bb");
                                  //$(".btn_download_errors").html('');
                                  //$(".btn_download_errors").html('<div class="errors" id="div_send_download_link">'+response+'</div>');
                                    $("#div_send_download_link").replaceWith('<div class="btn_download_errors" id="div_send_download_link">'+response+'</div>');
                              }
                      //  }                      
                    },
                    error: function(xhr) {}
        });
    //}
    
    });    
    
//});  


    
    $('form').submit(function(){
       var mvcType = $("#customer_mvc_type").val();   
       var dob = $.trim($("#date_of_birth").val()); 
      
      /**** date of birth validation ****/
       if(dob!='') {
            
            var arr_dt = dob.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            var one_year=1000*60*60*24*365
            var age = Math.round((curdate - x)/one_year);
            if(age < 18)
                {
                    alert('Minimum age should be 18 years');
                    $("#date_of_birth").val('');
                    $("#date_of_birth").focus();
                    return false;
                } else {             
                    if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#date_of_birth").val('');
                            $("#date_of_birth").focus();
                            return false;
                  }
             
         } } else if(!sendAuthButton) {
                    alert('Please specify date of birth');
                    $("#date_of_birth").focus();
                    return false;
               } 
          /**** date of birth validation over ****/
          
          
          if(mvcType=='mvcc') {
               if($("#device_id").val()=== ''){
                   alert('Please enter device Id');
                   return false;
               }
          } 
    return true;
         
});
    
    
 <?php
    $session = new Zend_Session_Namespace('App.Agent.Controller');    
 ?>
     var cardholder_auth = <?php echo isset($session->cardholder_auth)?$session->cardholder_auth:0;?>;
     var validated_cardholder_auth = <?php echo isset($session->validated_cardholder_auth)?$session->validated_cardholder_auth:0;?>    

     //alert(cardholder_auth);
     
     if(cardholder_auth!='' && cardholder_auth>0){       
         //$("#btn_auth_code").attr("disabled","disabled");
         $("#btn_auth_code").html('Resend Authorization Code');
         //$('#btn_auth_code').after("<a id='resend_auth' href=''> Resend Auth Code</a>").show('slow');
         //$('#resend_auth_code').val('resend');
         

     }   
     
     if(validated_cardholder_auth==1){
         $("#mobile_number").attr("readonly","readonly");
     }
    
     
     
     
  </script>