<?php 
    $helper = $this->listingUtilities(array());
?>
<div class="Boldtext">Kotak Amul</div>

<div class="innerbox">
    <ul>
        <?php
              if ($helper->can('adddetails', 'corp_kotak_customer')) {?>
              <li class="systemli"><a href="<?php echo $this->formatURL('/corp_kotak_customer/adddetails/');?>" title="Add Cardholder">Add Cardholder</a>: Add cardholder</li>
              <div class="clear"></div>
             <?php }
              if ($helper->can('opsrejected', 'corp_kotak_customer')) {?>
              <li class="systemli"><a href="<?php echo $this->formatURL('/corp_kotak_customer/opsrejected/');?>" title="Operation Rejected Applications">Operation Rejected Applications</a>: Operation Rejected Applications</li>
              <div class="clear"></div>
             <?php }
              
          ?>
    </ul>
    <div class="clear"></div>
</div>