<div class="Boldtext">Disbursement Report - Summary Report - Payment</div>
<?php 
echo $this->form;
if($this->records){ 
//array_pop($this->globalBuckets);
unset($this->globalBuckets['9']);
$globalBuckets = $this->globalBuckets;
//print_r($globalBuckets); exit;
$config['pageTitle'] = 'Search Disbursement Details';
$config['no_add'] = TRUE;
$itemPerPage = $this->items_per_page;
//echo "<pre>";print_r($this->globalBuckets);
// render the default listing


/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

    
// messages
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;

$cntColNames = count($this->globalBuckets) - 1 ;
$helper = $this->listingUtilities(array());
// render the default listing
?>
<style>
table tr td:first-child {
    padding: 10px;
}    
</style>
<div class="Boldtext">Detail Summary Report - Payment</div>
<div class="tablebox">
     <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
          <thead><!-- universal table heading --> 
            <tr>
               <th colspan=2 height="62" align="left" valign=middle >Payment Status</th>
               <th align="left" valign=middle>TTUM Generated</th>
               <th align="left" valign=middle>TTUM Processed</th>
               <th align="left" valign=middle>Hold</th>
               <th align="left" valign=middle>Processed Manually</th>
               <th align="left" valign=middle>Pending</th>
               <th align="left" valign=middle>Total</th>
            </tr> 
          </thead>
          <tbody>
          
         
        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : //echo "<br>"; print_r($item); exit;
               ?>
                
               <tr>
                    <td rowspan=2 height="34" align="left" valign=middle >Disbursement No-<?php echo $item['disbursement_number']; ?></td>
                    <td align="left" valign=middle>Count</td>
                    <td align="left" valign=middle><?php if($item['ttum_generated']['count']) echo $item['ttum_generated']['count'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_processed']['count']) echo $item['ttum_processed']['count'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_hold']['count']) echo $item['ttum_hold']['count'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_manual']['count']) echo $item['ttum_manual']['count'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_pending']['count']) echo $item['ttum_pending']['count'];?></td>
                    <td align="left" valign=middle><?php echo $item['count'];?></td>
               </tr>
               <tr>
                    <td align="left" valign=middle style="border-left: 1px solid #E0E0E0;">Amount</td>
                    <td align="left" valign=middle><?php if($item['ttum_generated']['total']) echo $item['ttum_generated']['total'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_processed']['total']) echo $item['ttum_processed']['total'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_hold']['total']) echo $item['ttum_hold']['total'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_manual']['total']) echo $item['ttum_manual']['total'];?></td>
                    <td align="left" valign=middle><?php if($item['ttum_pending']['total']) echo $item['ttum_pending']['total'];?></td>
                    <td align="left" valign=middle><?php echo $item['total'];?></td>
               </tr>
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
                
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="8">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
   </div>
<div>&nbsp;</div>
</div>


<div>&nbsp;</div>
<?php if(count($this->paginator)>0){?>
<div class="show-xls"> 
  <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php } ?>
    
<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } }?>
<script>
$(document).ready(function() {
    $("#btn_exportcsv").click(function(){
            var url = '<?php echo $this->formatURL("/corp_boi_index/exportsummarypaymentreport?disbursement_number=".$this->formData['disbursement_number']."&payment_status=".implode(",",$this->formData['payment_status'])."&account_number=".$this->formData['account_number']."&aadhar_no=".$this->formData['aadhar_no']."&tp_name=".$this->formData['tp_name']);?>';    
            $(location).attr('href',url);
    });
    $("#disbursement_number").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");
    //$("#bucket").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");
});
</script>
