<div class="Boldtext">Update Disbursement Status</div>
<?php 

echo $this->form;
if($this->records){
$config['pageTitle'] = 'Update Disbursement Status';
$config['no_add'] = TRUE;
$itemPerPage = $this->items_per_page;
// column names & indexes
    $config['columnNames'] = array(
        'Payment Status',
        'Txn Identifier Type',
        'Disbursement Number',
        'Account Number',
        'IFSC Code',
        'Aadhaar No',
        'Bucket',
        'Amount',
        'Currency',
        'Narration',
        'Wallet Code',
        'Card Type',
        'Mode'
    );
    $config['columnIndexes'] = array(
        'payment_status',
        'txn_identifier',
        'disbursement_number',
        'account_number',
        'ifsc_code',
        'aadhar_no',
        'bucket',
        'amount',
        'currency',
        'narration',
        'wallet_code',
        'card_type',
        'mode',
    );




// render the default listing


/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

    
// messages
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;

$cntColNames = count($config['columnNames']) - 1 ;
$helper = $this->listingUtilities(array());
// render the default listing


 ?>

<div class="Boldtext">Update Disbursement Status</div>
<div class="tablebox">
 <form name ="frm1" id ="frm1" action ="<?php echo $this->formatURL('/corp_boi_index/updatestatusconfirm')?>" method = "POST"> 
     <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>


           <thead><!-- universal table heading --> 
            <tr>
               <th><input type="checkbox" id="selectall"/></th>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>
         
        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : //print_r($item); exit;
               ?>
                
                <tr>

                    <?php  /********** displaying the inner columns **********/
                    
                    $cardId = $item['id'];
                    ?>
                  
                    <td><?php if($item['bucket']==1 && !in_array($item['payment_status'],array(STATUS_PROCESSED,STATUS_MANUAL))){?><input type="checkbox" class="reqid" name="reqid[]" value="<?php echo $cardId; ?>"/><?php }?></td>
                    <td><?php echo strtoupper($item[$config['columnIndexes'][0]]);?></td> 
                    <td><?php echo $item[$config['columnIndexes'][1]];?></td> 
                    <td><?php echo $item[$config['columnIndexes'][2]];?></td> 
                    <td><?php echo $item[$config['columnIndexes'][3]];?></td> 
                    <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                    <td><?php echo $item[$config['columnIndexes'][5]];?></td> 
                    <td><?php echo $item[$config['columnIndexes'][6]];?></td> 
                    <td><?php echo $item[$config['columnIndexes'][7]];?></td> 
                    <td><?php echo strtoupper($item[$config['columnIndexes'][8]]);?></td> 
                    <td><?php echo strtoupper($item[$config['columnIndexes'][9]]);?></td> 
                    <td><?php echo strtoupper($item[$config['columnIndexes'][10]]);?></td>
                    <td><?php echo strtoupper($item[$config['columnIndexes'][11]]);?></td>
                    <td><?php echo strtoupper($item[$config['columnIndexes'][12]]);?></td> 
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
                
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
   </div>
<div>&nbsp;</div>
<div style="width:950px; margin:auto;">
<?php $status = Util::getPaymentStatus();
$status['']='None';
?>
<span>Apply Status: </span> &nbsp;
<select name="status" id="status">
<?php foreach($status as $key => $val):?>
<option value="<?php echo $key;?>" label="<?php echo $val;?>"><?php echo $val;?></option>
<?php endforeach;?>
</select>
<input id="upload_cardholder" class="tangerine" type="submit" title="Update" value="Update" name="submit_success">
</div>
</form>
</div>


<div>&nbsp;</div>

    
<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } }?>
<script>
$(document).ready(function() {
    $("#btn_exportcsv").click(function(){
            var url = '<?php echo $this->formatURL("/corp_boi_index/exportdisbursementreport?disbursement_number=".$this->formData['disbursement_number']."&bucket=".$this->formData['bucket']."&account_number=".$this->formData['account_number']."&aadhar_no=".$this->formData['aadhar_no']);?>';    
            $(location).attr('href',url);
    });
    $("#disbursement_number").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");
    $("#aadhar_no").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");
    $("#account_number").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");
    //$("#bucket").after("<br/><span style='font-size:10px;font-weight:normal;'>*Separated by a comma (,)</span>");

    $("#frm1").submit(function(e) {
        if(!$('input[type=checkbox]:checked').length) {
            //stop the form from submitting
            e.preventDefault();
            alert("Please select at least one to record.");
            return false;
        }
        if(!$("#status").val()) {
            //stop the form from submitting
            e.preventDefault();
            alert("Please select payment status.");
            return false;
        }
        return true;
    });  
    $("#selectall").click(function () {
         $('.reqid').attr('checked', this.checked);
    });

    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".reqid").click(function(){
       if($(".reqid").length == $(".reqid:checked").length) {
        $("#selectall").attr("checked", "checked");
        } else {
        $("#selectall").removeAttr("checked");
        }
    });

});


</script>
