<div class="Boldtext">Authorized Funding Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->from!='' && $this->to!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Transaction Date',
    'Partner Code',
    'Partner Name',
    'Opening Balance (for the day)',
    'Total Partner Funding Amount (Authorized)',
    'Remarks (Partner Comments)',
    //'Closing Balance',
    
);

$config['columnIndexes'] = array(
    'txn_datetime',
    'agent_code',
    'agent_name',
    'agent_opening_balance',
    'txn_amount',
    'comments',
    //'agent_closing_balance',
    
);

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$config['showComma'] = array('txn_amount');
$cntColNames = count($config['columnNames']) - 1;

$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$noteText = isset($config['noteText']) ? $config['noteText'] : '' ;
?>

<div class="Boldtext"><?php echo $helper->pageTitle();;?></div>

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'> 
                        
           <thead><!-- universal table heading --> 
               <tr>
                   <?php /********** display the column names **********/ ?>
                   <?php foreach($helper->getColumnNames() as $columnName) : ?>
                       <th><span><?php echo $columnName;?></span></th>
                   <?php endforeach;?>
                   <?php /********** finished displaying the column names **********/ ?>
                   <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                       <th class="last tc"><span><?php echo 'Actions';?></span></th>
                   <?php endif; ?>
               </tr> 
           </thead>
           <tbody>

           <?php /********** do we have items? **********/ ?>
           <?php if (count($this->paginator)) : ?>
               <?php /********** we do! start displaying the items **********/ ?>
               <?php foreach($this->paginator as $item) : ?>
                   <?php $helper->data = $item; ?>
                   <tr>
                       <!--<td class="tc">
                           <input type="checkbox" name="checkall" value="true" />
                       </td>--> 
                       <?php /********** displaying the inner columns **********/ ?>
                       <?php 
                       //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                       ?>
                       <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                           <td>
                               <?php 

                                   $helper->displayItem($item, $index);

                               ?>
                           </td>
                       <?php endforeach;?>
                       <?php /********** finished displaying the inner columns **********/ ?>
                       <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                           <td class="tc">
                               <?php echo $helper->links($item);

                               ?>
                           </td> 
                       <?php endif; ?>
                   </tr>    
               <?php endforeach;?>
               <?php /********** finished displaying the items **********/ ?>
           <?php else:?>
               <?php /********** we don't have any items **********/ ?>
               <tr>
                   <td colspan="<?php $helper->columnCount()+1;?>">
                       <?php $helper->emptyMessage();?>
                   </td>
               </tr>
           <?php endif;?>
           <?php /********** finished do we have items? **********/ ?>
           </tbody> 
       </table>
    </div>
</div> 
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php

if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
      
            var url = '<?php echo $this->formatURL("/reports/exportagentfundrequests?dur=".$this->formData['dur']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']);?>';    
            
            $(location).attr('href',url);
    });  
    
      $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
     $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
      /**** From and To date validation ****/
      if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
            alert('Please select either duration or from and to date.');
            $("#dur").focus();
            return false;
      } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                    alert('Please specify From date.');
                    $("#from_date").focus();
                    return false;
               }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify To date.');
                    $("#to_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date cannot be greater than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });  
});
</script>