<div class="Boldtext">Fee Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';

if($frmSubmit){
    
$config = array();

// messages
$config['pageTitle'] = $this->pageTitle;
$config['emptyMessage'] = 'No record found.';


// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Agent Code',
    'Agent Name',
    'Agent City',
    'Agent Pincode', 
    'Transaction Ref Number',
    'Transaction Narration',
    'Transaction Amount',
    'Product Code',
    //'Fee Plan',
    'Fee',
    'Service Tax',
    'Reversal Fee',
    'Reversal Service Tax',
    
);

$config['columnIndexes'] = array(
    'date_formatted',
    'agent_code',
    'name',
    'estab_city',
    'estab_pincode',
    'txn_code',
    'transaction_type_name',
    'transaction_amount',
    'product_code',
    //'plan_fee_name',
    'fee_amount',
    'service_tax_amount',
    'reversal_fee',
    'reversal_service_tax',
    
);

$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
                
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][7]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][9]]);?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][10]]);?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][11]]);?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][12]]);?></td>

                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } 


/*// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);*/

}

//echo "<pre>";print_r($this->paginator);exit;

?>


<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        
        var dur = '<?php $dur = isset($this->formData['duration'])?$this->formData['duration']:''; echo $dur;?>';
        var agentId = '<?php echo $this->formData['agent_id'];?>';
        if(dur==''){
            alert('Please specify duration');
        }
        else{
               
            var url = '<?php echo $this->formatURL("/reports/exportfeereport?duration=".$this->formData['duration']."&agent_id=".$this->formData['agent_id']."&bank_unicode=".$this->formData['bank_unicode']);?>';   
            $(location).attr('href',url);
       }
    });     
});
</script>