<div class="Boldtext">Kyc Upgradation Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

if($this->from!='' && $this->to!=''){

$config = array();

// messages
$config['pageTitle'] = isset($this->title) ? $this->title : '';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Cardholder Name',
    'CRN',
    'Mobile Number',
    'Product Name',
    'Bank Name',
    'Employee Id',
    'Id Proof Type',
    'Id Proof Number',
    'Customer Address1',
    'Customer Address2',
    'Pincode',
    'State',    
    'Status',
    'Upgrade Date'
    );

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$backURL = isset($config['back_url']) ? $config['back_url'] : '' ;
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
$state = new CityList();
?>

<div class="Boldtext"><?php $helper->pageTitle();?></div>

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
    <div class="tablebox">
        <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <thead><!-- universal table heading --> 
                    <tr>
                        <?php /********** display the column names **********/ ?>
                        <?php foreach($helper->getColumnNames() as $columnName) : ?>
                            <th><span><?php echo $columnName;?></span></th>
                        <?php endforeach;?>
                        <?php /********** finished displaying the column names **********/ ?>
                        <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                            <th colspan="2"><span><?php echo 'Actions';?></span></th>
                        <?php endif; ?>
                    </tr> 
                </thead>
                <tbody>

                <?php /********** do we have items? **********/ ?>
                <?php if (count($this->paginator)) : ?>
                    <?php /********** we do! start displaying the items **********/ ?>
                    <?php foreach($this->paginator as $item) : ?>
                        <tr>
                            <?php /********** displaying the inner columns **********/ ?>                            
                                <td><?php echo $item['date_created'];?></td>
                                <td><?php echo $item['name'];?></td>
                                <td><?php echo $item['crn'];?></td>
                                <td><?php echo $item['mobile'];?></td>
                                <td><?php echo $item['product_name'];?></td>
                                <td><?php echo $item['bank_name'];?></td>
                                <td><?php echo $item['employee_id'];?></td>
                                <td><?php echo $item['id_proof_type'];?></td>
                                <td><?php echo $item['id_proof_number'];?></td>
                                <td><?php echo $item['address_line1'];?></td>
                                <td><?php echo $item['address_line2'];?></td>
                                <td><?php echo $item['pincode'];?></td>
                                <td><?php
                                    echo ucwords($state->getStateName($item['state']));
                                ?></td>
                                <td><?php echo $cardholderStatus[$item['status']];?></td>
                                <td><?php echo $item['date_updated'];?></td>                                
                            <?php /********** finished displaying the inner columns **********/ ?>
                            <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                                    <?php echo $helper->links($item);
                                    ?>
                            <?php endif; ?>
                        </tr>    
                    <?php endforeach;?>
                    <?php /********** finished displaying the items **********/ ?>
                <?php else:?>
                    <?php /********** we don't have any items **********/ ?>
                    <tr>
                        <td colspan="<?php $count = $helper->columnCount();
                        echo $count++;?>">
                            <?php $helper->emptyMessage();?>
                        </td>
                    </tr>
                <?php endif;?>
                <?php /********** finished do we have items? **********/ ?>
                </tbody> 
            </table>
        </div>
    </div> 
</form>
<?php 
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<div class="show-xls"> 
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>

<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){        
            var url = '<?php echo $this->formatURL("/corp_ratnakar_cardholder/exportkycupgradation?dur=".$this->formData['dur']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']);?>';    
            $(location).attr('href',url);       
    });

     $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       /**** From and To date validation ****/
      if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
            alert('Please select either duration or from and to date.');
            $("#dur").focus();
            return false;
      } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
            alert('Please specify From date.');
            $("#from_date").focus();
            return false;
       }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
            alert('Please specify To date.');
            $("#to_date").focus();
            return false;
       } else if(diff < 0){
          alert('From date cannot be greater than To date.');
            $("#from_date").focus();
            return false; 
       }
       else if(date_range > max_range){
          alert('Report can be fetched for a duration not more than '+max_range+' days');
            $("#to_date").focus();
            return false; 
       }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>
