<div class="Boldtext">Pending KYC Docs</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
// messages
$config['pageTitle'] = 'Pending KYC Docs';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'There is no pending KYC docs added at this time.';
//$config['addURL'] = '/agents/signup/';

// column names & indexes
$config['columnNames'] = array(
    'Medi Assist Id',
    'Employee Id',
    'Card Number',
    'Name',
    'Name on Card',
    'Gender',
    'Date of Birth',
    'Mobile',
    'Email',
    'Employer Name',
    'Corporate Id',
    'Activation Date',
    'Status',
    );
$config['columnIndexes'] = array(
    'medi_assist_id',
    'employee_id',
    'card_number',
    'cardholder_name',
    'name_on_card',
    'gender',
    'date_of_birth',
    'mobile',
    'email',
    'employer_name',
    'corporate_id',
    'date_activation',
    'status',
);

$cntColNames = count($config['columnNames']) ;
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("REMIT_STATUS");
?>
<?php echo $this->form; ?> 
<?php if(!empty($this->paginator)):?>
<div class="Boldtext"><?php $helper->pageTitle();?></div>
 <?php endif;?>         


<?php if(!empty($this->paginator)):?>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                  <th><span>Actions</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) :?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
               
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><a href="<?php echo $this->formatURL('/corp_ratnakar_cardholder/view?id='.$item['id'].'&'.$this->backLink);?>"><?php echo util::maskCard($item[$config['columnIndexes'][2]], 4);?></a></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][6]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]]?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][11]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $cardholderStatus[$item[$config['columnIndexes'][12]]]?></td>
                        <td><a href="<?php echo $this->formatURL('/corp_ratnakar_cardholder/addcardholderdocs?id='.$item['id'].'&product_id='.$item['product_id'].'&back_link_var=pendingkyc&'.$this->backLink);?>">Upload Documents</a></td>
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php endif;?>