<div class="Boldtext">Update Mobile Number</div> 
  <span><?php echo $this->msg?></span>
  
  <?php echo $this->form; 
  $resMsg = isset($this->info['ResponseMessage'])?$this->info['ResponseMessage']:'';
  if($resMsg!=''){
      
       $config = array();
    // column names & indexes
    $config['columnNames'] = array(
        'Response Code',
        'Response Message',
        'CRN',
    );
    $config['columnIndexes'] = array(
        'ResponseCode',
        'ResponseMessage',
        'crn',
    );

    echo $this->partial(
        'partials/default-helpdesk-listing.phtml',
        array(
            'config' => $config,
            'info' => $this->info
        )
    );
  } ?>

  <script type="text/javascript">
      
   function sendAuthCode(){
        $("#send_auth_code").val('1');
        $("#frmUpdateMob").submit();       
   }
      
    $(document).ready(function() {
       $('.cancel').attr('href','#');
       $('.cancel').click(function(){
             location.reload();
       });
       
       
    });
    
 <?php $session = new Zend_Session_Namespace('App.Operation.Controller'); ?>
     var update_mobile_auth = <?php echo isset($session->update_mobile_auth)?$session->update_mobile_auth:0;?>;
     //alert(cardholder_auth);
     
     if(update_mobile_auth!='' && update_mobile_auth>0){       
         $("#btn_auth_code").attr("disabled","disabled");
     }         
  </script>