<?php

/**
 * Displays all pending agent request
 * @copyright company
 */
//Util::pr($this->paginator,1);

$config = array();
// messages
$config['pageTitle'] = 'My Fund Requests';
$config['emptyMessage'] = 'There is no pending requests at this time.';

$config['no_add'] = TRUE;
$config['showActions'] = false;
// column names & indexes
$config['columnNames'] = array(
    'Request Date',
    'Journal/Cheque No.',
    'Amount',
    'Status',
);
$config['columnIndexes'] = array(
    'date_request',
    'funding_no',
    'amount',
    'status',
);

$config['linkCol'] = array(
    array(
        'linkColName' => 'date_request',
        'linkController' => 'agentfunding',
        'linkAction' => 'viewfundrequest',
        'linkTitle' => 'View Details',
        'linkParamReqd' => TRUE,
        'linkParamName' => 'id',
        'linkParamValue' => 'id',
    ),
);


echo $this->partial(
        'partials/default-listing.phtml', array(
    'config' => $config,
    'paginator' => $this->paginator,
        )
);
