<?php

/**
 * Transfer Fund to Sub agent
 * @copyright company
 */
//Util::pr($this->paginator,1);



$config = array();
// messages
$config['pageTitle'] = 'Agent Transactions';
$config['emptyMessage'] = 'There is no transaction.';

$config['no_add'] = TRUE;
$config['showActions'] = false;

// column names & indexes

$config['columnNames'] = array(
    'Agent Name',    
    'Amount',    
    'Transaction Type',    
    'Transaction Date',    
);

$config['columnIndexes'] = array(
    'agent_name',    
    'amount',    
    'transaction_name',    
    'date_created',    
);



?>
<div class="Boldtext">Agent Fund Transfer</div>
<?php
echo $this->form;

echo $this->partial(
        'partials/default-listing.phtml', array(
    'config' => $config,
    'paginator' => $this->paginator,
        )
);
