 <?php
 //echo '<pre>';print_r($this->paginator);exit;
/**
 * Displays all the importing crns
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';

//if($frmSubmit){
    
$config = array();

// messages
$config['pageTitle'] = 'Preview CRN List';
$config['emptyMessage'] = 'No record found.';


// column names & indexes
$config['columnNames'] = array(
    'CRN',
    'Relation',
    'Product',
    'Promotion',
    'Branch', 
    'Statement Plan', 
    'Transaction Plan',
    'Embossed Line3',
    'Embossed Line4',
    'Extra'
);

$config['columnIndexes'] = array(
    'crn',
    'relation',
    'product',
    'promotion',
    'branch',
    'statement_plan',
    'transaction_plan',
    'embossed_line3',
    'embossed_line4',
    'extra'
);

$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
                
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                        
                        

                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
echo $this->form;
?>