<?php
/**
 * View for the Agent Phone verification action in Agentsignup controllers index action
 *
 * @category operation
 * @package operation_views
  * @copyright Transerv
 */
?>
<div id="login">
    <h2>Log in</h2>
    <div id="inner-login">
        <?php if (isset($this->error)):?>
            <div class="msg msg-error">
                <p><?php echo '<strong>Oops!</strong><br />Phone number alreay registered';?></p>
            </div>
        <?php endif;?>
        <?php echo $this->form;?>
    </div>
</div>

