<?php
/**
 * View that defines the default listing UI 
 *
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage partials
 * @copyright company
 */
$helper = $this->listingUtilities($this->config);
?>

<div class="reportbox">

<?php $indexes = array_combine($helper->getColumnNames(), $helper->getColumnIndexes()); ?>
        <?php foreach($helper->getColumnNamesAndValues($this->info) as $columnName => $columnValue) : ?>

<div class="formrow-view">
  <div class="form-name-column-view"><?php echo $columnName;?>:</div>
  <div class="form-field-column-view">
  <div id="inner"><span style="font-family:Arial, Helvetica, sans-serif; font-size:12px; font-weight:normal;">
          <?php $helper->displayItem($columnValue, $indexes[$columnName]);?>
      </span>
   
    </div>
  </div>
</div>

 <?php endforeach;?>



    <div class="clear"></div>
    </div><!---Inner-box End--->