<?php
/**
 * View that defines the default listing UI 
 *
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage partials
 * @copyright company
 */
$helper = $this->listingUtilities($this->config);
$addURL = isset($this->config['addURL']) ? $this->config['addURL'] : '' ;
$addImg = isset($this->config['addImg']) ? $this->config['addImg'] : '' ;
$addbutton = isset($this->config['no_add']) ? $this->config['no_add'] : '' ;
$noteText = isset($this->config['noteText']) ? $this->config['noteText'] : '' ;
?>

<div class="Boldtext"><?php $helper->pageTitle();?></div>
        
<?php if(!$addbutton):?>
    <?php if($helper->canShowAddButton() && $helper->canAdd()):?>
        <?php if(isset($addURL) && $addURL !='') {
                    $href = $addURL;
                } else {
                    $href = $helper->addUrl(FALSE);
                }?> 
<div class="filterbox">

<div style="width:950px;">

<!--<div class="addnew-comm"><img src="" border="0" usemap="#Map" />
  <map name="Map" id="Map">
    <area shape="rect" coords="5,5,216,25" href="<?php echo $href; ?>" />
  </map>
</div>-->
    <a class="ocean" href="<?php echo $this->formatURL($href);?>" style="float:right;" title="<?php $helper->addMessage();?>"><?php $helper->addMessage();?></a>
</div><!--Inner Style Div END-->


</div>
        
<?php endif;?> 
<?php endif;?>            

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
    
        <div class="tablebox">
            <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <thead><!-- universal table heading --> 
                    <tr>
                        <?php /********** display the column names **********/ ?>
                        <?php foreach($helper->getColumnNames() as $columnName) : ?>
                            <th><span><?php echo $columnName;?></span></th>
                        <?php endforeach;?>
                        <?php /********** finished displaying the column names **********/ ?>
                        <?php if(!isset($this->config['showActions']) || (isset($this->config['showActions']) && $this->config['showActions'])) : ?>
                            <th colspan="2"><span><?php echo 'Actions';?></span></th>
                        <?php endif; ?>
                    </tr> 
                </thead>
                <tbody>

                <?php /********** do we have items? **********/ ?>
                <?php if (count($this->paginator)) : ?>
                    <?php /********** we do! start displaying the items **********/ ?>
                    <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <!--<td class="tc">
                                <input type="checkbox" name="checkall" value="true" />
                            </td>--> 
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php 
                            //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                            ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                    
                                        $helper->displayItem($item, $index);
                                    
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                            <?php if(!isset($this->config['showActions']) || (isset($this->config['showActions']) && $this->config['showActions'])) : ?>
                                <!--<td style="margin:0; padding:0;">
                                    <div class="iconbox">-->
                                    <?php echo $helper->links($item);
                                    ?>
                                    <!--</div>
                                </td> -->
                            <?php endif; ?>
                        </tr>    
                    <?php endforeach;?>
                    <?php /********** finished displaying the items **********/ ?>
                <?php else:?>
                    <?php /********** we don't have any items **********/ ?>
                    <tr>
                        <td colspan="<?php echo $helper->columnCount(FALSE)+1;?>">
                            <?php $helper->emptyMessage();?>
                        </td>
                    </tr>
                <?php endif;?>
                <?php /********** finished do we have items? **********/ ?>
                </tbody> 
            </table>
        </div>
    </div>

</form>

<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php if(isset($noteText) && $noteText != '') {
    ?>
    <div class="note"><b>*Note: </b><?php echo $noteText;?></div>
<?php } ?>