<script>
  $(document).ready(function(){
      
    $('.cancel').attr('href',document.referrer);
   
});
</script>
      <?php
/**
 * Delete a product
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Delete product limit: '.$this->name;
$config['areYouSureMessage'] = 'Are you sure you want to delete the product Limit?';

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Product Limit Code',
    
);
$config['columnIndexes'] = array(
    'name',
    'product_limit_code',
    
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);