<div class="Boldtext">Agent Wise Authorized Funding Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';
$agentId = isset($this->id)?$this->id:'';

if($agentId!='' && $this->from!='' && $this->to!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Transaction Date',
    'Agent Code',
    'Agent Name',
    'Opening Balance (for the day)',
    'Total Agent Funding Amount (Authorized)',
    'Authorized By',
    'Remarks (Agent Comments)',
    'Closing Balance',
    
);

$config['columnIndexes'] = array(
    'txn_datetime',
    'agent_code',
    'agent_name',
    'agent_opening_balance',
    'txn_amount',
    'ops_name',
    'comments',
    'agent_closing_balance',
    
);

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$config['showComma'] = array('txn_amount');
$cntColNames = count($config['columnNames']) - 1;

$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$noteText = isset($config['noteText']) ? $config['noteText'] : '' ;
?>

<div class="Boldtext"><?php echo $helper->pageTitle();;?></div>

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'> 
                        
           <thead><!-- universal table heading --> 
               <tr>
                   <?php /********** display the column names **********/ ?>
                   <?php foreach($helper->getColumnNames() as $columnName) : ?>
                       <th><span><?php echo $columnName;?></span></th>
                   <?php endforeach;?>
                   <?php /********** finished displaying the column names **********/ ?>
                   <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                       <th class="last tc"><span><?php echo 'Actions';?></span></th>
                   <?php endif; ?>
               </tr> 
           </thead>
           <tbody>

           <?php /********** do we have items? **********/ ?>
           <?php if (count($this->paginator)) : ?>
               <?php /********** we do! start displaying the items **********/ ?>
               <?php foreach($this->paginator as $item) : ?>
                   <?php $helper->data = $item; ?>
                   <tr>
                       <!--<td class="tc">
                           <input type="checkbox" name="checkall" value="true" />
                       </td>--> 
                       <?php /********** displaying the inner columns **********/ ?>
                       <?php 
                       //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                       ?>
                       <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                           <td>
                               <?php 

                                   $helper->displayItem($item, $index);

                               ?>
                           </td>
                       <?php endforeach;?>
                       <?php /********** finished displaying the inner columns **********/ ?>
                       <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                           <td class="tc">
                               <?php echo $helper->links($item);

                               ?>
                           </td> 
                       <?php endif; ?>
                   </tr>    
               <?php endforeach;?>
               <?php /********** finished displaying the items **********/ ?>
           <?php else:?>
               <?php /********** we don't have any items **********/ ?>
               <tr>
                   <td colspan="<?php $helper->columnCount()+1;?>">
                       <?php $helper->emptyMessage();?>
                   </td>
               </tr>
           <?php endif;?>
           <?php /********** finished do we have items? **********/ ?>
           </tbody> 
       </table>
    </div>
</div> 
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php

if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        var agentId = '<?php echo $this->formData['id'];?>';
        if(dur==''){
            alert('Please specify duration');
        }else if(agentId==''){
            alert('Please specify agent name');
        }
        else{
            var url = '<?php echo $this->formatURL("/reports/exportagentwisefundrequests?dur=".$this->formData['dur']."&id=".$this->formData['id']);?>';    
            $(location).attr('href',url);
       }
    });     
});
</script>