<div class="Boldtext">Agent Transaction Summary Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

if($this->from!='' && $this->to!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;
$TXN_TYPE_LABELS = Zend_Registry::get("TXN_TYPE_LABELS");

// column names & indexes
$config['columnNames'] = array(
    'Transaction Date',
    'Agent Code',
    'Agent Name',
    'Agent City',
    'Agent Pincode',
    'Transaction Code',
    'Transaction Amount',
    'CRN',
    'Customer Mobile Number',
    'Product Code',
    'Transaction Reference Number',
);

$config['columnIndexes'] = array(
    'txn_date',
    'agent_code',
    'agent_name',       
    'estab_city',
    'estab_pincode',
    'txn_type',
    'amount',
    'crn',      
    'mobile_number',    
    'ecs_product_code',    
    'txn_code',    
);

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$cntColNames = count($config['columnNames']) - 1 ;
// render the default listing
/*echo $this->partial(
    'partials/report-agent-load-reload.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);*/


?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
               
                    //foreach($dateArr as $item) :
                    $tnxCode = $item[$config['columnIndexes'][5]];
                    $item[$config['columnIndexes'][5]] = isset($TXN_TYPE_LABELS[$tnxCode])?$TXN_TYPE_LABELS[$tnxCode]:''; 
                ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][6]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]];?></td>
                    <?php /********** finished displaying the inner columns **********/ ?>
                    <?php $datePrev = $item[$config['columnIndexes'][0]];?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } }?>


<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        if(dur==''){
            alert('Please specify duration');
        } else {
            var url = '<?php echo $this->formatURL("/reports/exportagenttransaction?dur=".$this->formData['dur']);?>';    
            $(location).attr('href',url);
       }
    });     
});
</script>