<div class="Boldtext">Agent Wise Transactions Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';
$agentName = isset($this->agentInfo->name)?$this->agentInfo->name:'';

if($agentName!='' && $this->from!='' && $this->to!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Agent Wise Load/Reload Report for '.$this->agent_name.' for period '.$duration;

$config['emptyMessage'] = 'No record found.';
$config['addMessage'] = 'Back'; 
$srcLink='';

if($this->src=='alr'){
    $srcLink = '/reports/agentwisetransactions?sub=sub&dur='.$this->callingRprtDur;
}

$config['addURL'] = $srcLink;
if($this->callingRprtDur=='' || $srcLink==''){
    $config['no_add']=1;
}

$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Transaction Narration',
    'Transaction Amount',        
    'CRN',
   // 'Customer Name',
    'Mobile Number',
    'Product Code',
    'Transaction Ref Number',   
    //'Bank Name'   
);

$config['columnIndexes'] = array(
    'txn_date',
    'txn_type', 
    'amount',
      
    'crn',
   // 'cardholder_name',
    'mobile_number',
    'ecs_product_code',  
    'txn_code',    
   // 'bank_name'
);

$config['actions'] = array();
$config['showComma'] = array('amount');
//$agentName = $this->agentInfo->agent_name;
$agentEmail= $this->agentInfo->email;
$agentCode = $this->agentInfo->agent_code;
$agentMobile = $this->agentInfo->mobile1;
$agentCity = $this->agentInfo->estab_city;
$agentPincode = $this->agentInfo->estab_pincode;
$TXN_TYPE_LABELS = Zend_Registry::get("TXN_TYPE_LABELS");

$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$noteText = isset($config['noteText']) ? $config['noteText'] : '' ;
$cntColNames = count($config['columnNames']) - 1;


?>

<div class="Boldtext"><?php echo $helper->pageTitle();;?></div>

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'> 
        <thead><!-- universal table heading --> 
            <tr>
               <th><span>Agent Name:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentName;?><br/>
               </td>
           </tr> 

           <tr>
               <th><span>Agent Email:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentEmail;?><br/>
               </td>
           </tr>                     

           <tr>
               <th><span>Agent Code:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentCode;?><br/>
               </td>
           </tr> 
           <tr>
               <th><span>Agent Mobile Number:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentMobile;?><br/>
               </td>
           </tr> 
           <tr>
               <th><span>Agent City:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentCity;?><br/>
               </td>
           </tr> 

           <tr>
               <th><span>Agent Pin Code:  </span></th>
                <td colspan="<?php echo $cntColNames;?>" align="left"><?php echo $agentPincode;?><br/>
               </td>
           </tr>
           <tr>
                <td colspan="<?php echo $cntColNames+1;?>" align="left">&nbsp;</td>
            </tr>

       </thead>


       
        <tbody>

       <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                   $tnxCode = $item[$config['columnIndexes'][1]];
                   $item[$config['columnIndexes'][1]] = isset($TXN_TYPE_LABELS[$tnxCode])?$TXN_TYPE_LABELS[$tnxCode]:''; 
                ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][2]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                    <?php /********** finished displaying the inner columns **********/ ?>
                    <?php $datePrev = $item[$config['columnIndexes'][0]];?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
            </table>
        </div>
</div> 
</form>
<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } }?>





<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        var agentId = '<?php echo $this->formData['id'];?>';
        if(dur==''){
            alert('Please specify duration');
        }else if(agentId==''){
            alert('Please specify agent name');
        }
        else{
            var url = '<?php echo $this->formatURL("/reports/exportagentwisetransactions?dur=".$this->formData['dur']."&id=".$this->formData['id']);?>';    
            $(location).attr('href',url);
       }
    });     
});
</script>