<div class="Boldtext">Beneficiary Registration Report</div>
<?php
/**
 * Displays the Beneficiary Registrations for Banks
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';
$bankUnicodeArr = Util::bankUnicodesArray();
if($frmSubmit){
    
$config = array();
  	 							

// messages
$config['pageTitle'] = isset($this->pageTitle)?$this->pageTitle:'';
$config['emptyMessage'] = 'There is no beneficiary registered at this time.';

// column names & indexes
$config['showActions'] = FALSE;
$config['no_add'] = true;

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Nick Name',
    'Mobile',
    'IFSC Code',
    'Bank Account Number',
    'Bank Name',
    'Branch Name',
    'Branch City',
    'Bank Account Type',
    'Email',
    'Status'
    
);
$config['columnIndexes'] = array(
    'name',
    'nick_name',
    'mobile',
    'ifsc_code',
    'bank_account_number',
    'bank_name',
    'branch_name',
    'branch_city',
    'bank_account_type',
    'email',
    'status'
    
);

$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$backURL = isset($config['back_url']) ? $config['back_url'] : '' ;
?>
<div class="Boldtext"><?php $helper->pageTitle();?></div>

<?php if(!$addbutton):?>
    <?php if($helper->canShowAddButton() && $helper->canAdd()):?>
        <?php 
            if(isset($addURL) && $addURL !='') {
                    $href = $addURL;
            } else {
                    $href = $helper->addUrl(FALSE);
            }
        ?> 
<div class="filterbox">
    <div style="width:950px;">
        <a href="<?php echo $this->formatURL($href);?>" class="ocean" style="float:right;" title="<?php $helper->addMessage();?>"><?php $helper->addMessage();?></a>
    </div><!--Inner Style Div END-->
</div>

<?php endif;?> 
<?php endif;?> 
<?php if($backURL): $href = $backURL;?>
<div class="filterbox"> 

<div style="width:950px;">
    <a href="<?php echo $this->formatURL($href);?>" class="ocean" style="float:right;" title="Back">Back</a>
</div><!--Inner Style Div END-->

</div>
<?php endif;?>

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
    <div class="tablebox">
            <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <thead><!-- universal table heading --> 
                    <tr>
                        <?php /********** display the column names **********/ ?>
                        <?php foreach($helper->getColumnNames() as $columnName) : ?>
                            <th><span><?php echo $columnName;?></span></th>
                        <?php endforeach;?>
                        <?php /********** finished displaying the column names **********/ ?>
                        <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                            <th colspan="2"><span><?php echo 'Actions';?></span></th>
                        <?php endif; ?>
                    </tr> 
                </thead>
                <tbody>

                <?php /********** do we have items? **********/ ?>
                <?php if (count($this->paginator)) : ?>
                    <?php /********** we do! start displaying the items **********/ ?>
                    <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                        $helper->displayItem($item, $index);
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                            <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                            <?php echo $helper->links($item);; ?>
                            <?php endif; ?>
                        </tr>    
                    <?php endforeach;?>
                    <?php /********** finished displaying the items **********/ ?>
                <?php else:?>
                    <?php /********** we don't have any items **********/ ?>
                    <tr>
                        <td colspan="<?php echo $helper->columnCount(FALSE)+1;?>">
                            <?php $helper->emptyMessage();?>
                        </td>
                    </tr>
                <?php endif;?>
                <?php /********** finished do we have items? **********/ ?>
                </tbody> 
            </table>
        </div>
    </div>
</form>
<div>&nbsp;</div> 

<?php
if(count($this->paginator) > 1) { ?>
<div class="pagination">
    <?php echo $this->paginator; ?>
</div>
<?php } ?>

<?php if(count($this->paginator)>0) { ?>
<div class="show-xls"> 
  <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {
   
    $("#btn_exportcsv").click(function(){
            var url = '<?php echo $this->formatURL("/reports/exportbeneregistration?to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']."&bank_unicode=".$this->formData['bank_unicode']."&dur=".$this->formData['dur']);?>';    
            $(location).attr('href',url);
    });  
    
    $('form').submit(function(){
  
       var bank_unicode = $.trim($("#bank_unicode").val());
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val();
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       
     
      /**** From and To date validation ****/
       $('#bank_unicode').css('background', '#fff');
       $('#dur').css('background', '#fff');
       $('#from_date').css('background', '#fff');
       $('#to_date').css('background', '#fff');
      
         if( (bank_unicode == '') || (bank_unicode == '0') ){
             alert("Please select bank name.");
              $('#bank_unicode').css('background', '#ff0'); // will change the background to red
              $("#bank_unicode").focus();
              return false;
         }else if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
                alert('Please select either duration or from and to date.');
                $('#dur').css('background', '#ff0');    
                $("#dur").focus();
            return false;
         } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                alert('Please specify From date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false;
            }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                 alert('Please specify To date.');
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                 return false;
            } else if(diff < 0){
               alert('From date cannot be greater than To date.');
                $('#from_date').css('background', '#ff0');
                 $("#from_date").focus();
                 return false; 
            }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $('#to_date').css('background', '#ff0');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>