<div class="Boldtext">Login Summary Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

$userType = isset($this->formData['user_type'])?$this->formData['user_type']:'';

if($userType!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->pageTitle)?$this->pageTitle:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

if ($this->formData['user_type'] == DbTable::TABLE_AGENTS){

// column names & indexes
$config['columnNames'] = array(
'User Code',
'User Name',
'Mobile',
'Email',
'Date',
'Login step1 failed attempts count',
'Login step2 failed attempts count',
'Successful login count',
'Status'
);

$config['columnIndexes'] = array(
    'user_code',
    'user_name',
    'mobile',
    'email',
    'date',
    'step1_failed_count',
    'step2_failed_count',
    'success_login_count',
    'user_status'
);

} else {
    
    // column names & indexes
$config['columnNames'] = array(
'User Name',
'Mobile',
'Email',
'Date',
'Login step1 failed attempts count',
'Login step2 failed attempts count',
'Successful login count',
'Status'
);

$config['columnIndexes'] = array(
    'user_name',
    'mobile',
    'email',
    'date',
    'step1_failed_count',
    'step2_failed_count',
    'success_login_count',
    'user_status'
);

}

$config['showActions'] =FALSE;
$config['duration'] = $duration;
$config['showComma'] = array('amt');
$cntColNames = count($config['columnNames']);
// render the default listing
?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>
<div style ="clear:both;"></div>
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                
                <tr>
               
                    <?php /********** displaying the inner columns **********/

                    if ($this->formData['user_type'] == DbTable::TABLE_AGENTS){ ?>
                        
                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][4]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                       
                    <?php } /********** finished displaying the inner columns **********/ 
                    else { ?>
                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][3]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                    <?php } ?>
                    
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php }  }
?>
<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
       
        var user_type = '<?php echo $this->formData['user_type'];?>';
        if(user_type==''){
            alert('Please specify user type');
        } else {
             var url = '<?php echo $this->formatURL("/reports/exportloginsummary?from_date=".$this->formData['from_date']."&to_date=".$this->formData['to_date']."&user_type=".$this->formData['user_type']);?>';    
            $(location).attr('href',url);
       }
    }); 
    
     $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                 $('#from_date').css('background', '#ff0');
                 $("#from_date").focus();
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $('#from_date').css('background', '#ff0');
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $('#to_date').css('background', '#ff0');
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
    
    $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var user = $.trim($("#user_type").val()); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
        /**** From and To date validation ****/
       $('#from_date').css('background', '#fff');
       $('#to_date').css('background', '#fff');
       if(user==''){
                alert('Please select User type');
                $('#user_type').css('background', '#ff0');    
                $("#user_type").focus();
            return false;
         }
          else if((from=='' && to=='')){
                alert('Please select from and to date.');
                $('#from_date').css('background', '#ff0');    
                $("#from_date").focus();
            return false;
         } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                alert('Please specify From date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false;
            }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                 alert('Please specify To date.');
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                 return false;
            } else if(diff < 0){
                alert('From date cannot be greater than To date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false; 
            }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                  $('#to_date').css('background', '#ff0');
                  $("#to_date").focus();
                  return false; 
               }
              
          
     return true; 
   });    
});
</script>
