<div class="Boldtext">Multi Wallet Balance Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';
 $bankUnicodeArr = Util::bankUnicodesArray();
if($frmSubmit){
    
$config = array();

// messages
$config['pageTitle'] = $this->pageTitle;
$config['emptyMessage'] = 'No record found.';


// column names & indexes
$config['columnNames'] = array(
    'Product Name',
    'Bank Name',
    'Medi Assist Id / Partner Ref No',
    'Currency ',
    'Wallet Code',
    'Closing Balance as on date',
    'Status'
);

$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;

$status = Util::getCardHolderStatusList();
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>
<div style="clear:both;"></div>
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0' >
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php foreach($this->paginator as $item) : ?>
                
                <tr>
                    <td><?php echo $item['product_name'];?></td> 
                    <td><?php echo $item['bank_name'];?></td>
                    <td><?php if(!empty($item['member_id'])){ echo $item['member_id']; } else { echo $item['partner_ref_no']; }?></td>
                    <td><?php echo CURRENCY_INR;?></td>
                    <td><?php echo $item['wallet_code'];?></td>
                    <td><?php echo $item['closing_balance'];?></td>
                    <td><?php echo $status[$item['status']];?></td>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 

<?php
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<div class="show-xls"> 
  <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    
    var product = $("#product").val();
    if($("#bank_unicode").val() != ''){
     $.ajax({
            url: '/ajax/get-bankproductslist/q/'+$("#bank_unicode").val()+'/p/1',
            success: function(response) {
                if(response == 1) {                            
                } else {                            
                    $("#product_id").html("");                            
                    $("#product_id").append(response);
                    $("#product_id option[value='"+product+"']").attr("selected", "selected");
                     console.log(response);                            
                }
            }     
        });
    }

    $("#bank_unicode").change(function(){
        $.ajax({
            url: '/ajax/get-bankproductslist/q/'+$("#bank_unicode").val()+'/p/1',
                success: function(response) {
                    if(response == 1) {                            
                    } else {                            
                        $("#product_id").html("");                            
                        $("#product_id").append(response);
                         console.log(response);                            
                }
            }    
        });
    });      

    $("#btn_exportcsv").click(function(){
        var url = '<?php echo $this->formatURL("/reports/exportmultiwalletbalance?to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']."&product_id=".$this->formData['product_id']."&bank_unicode=".$this->formData['bank_unicode']);?>';
        $(location).attr('href',url);
   });  

   $("input#from_date").change(function() {
       if(this.value) {
           var date_start = this.value; 
           var arr_dt = date_start.split("-");
           var x = new Date();
           x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
           var curdate = new Date();
           if(x > curdate)
           {
               alert("Please enter From date not greater than today's date");
               this.value = '';
               return false;
           }
           else{
                if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                  return true;
                }else{
                    alert('Please enter valid From date');
                  this.value = '';
                  $("#from_date").focus();
                  return false;
                }
            }
       }
   });

    $("input#to_date").change(function() {
       if(this.value) {
           var date_start = this.value; 
           var arr_dt = date_start.split("-");
           var x = new Date();
           x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
           var curdate = new Date();
           if(x > curdate)
           {
               alert("Please enter To date not greater than today's date");
               this.value = '';
               return false;
           }
           else{
                if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                     return true;
                   }else{
                       alert('Please enter valid To date');
                     this.value = '';
                     $("#to_date").focus();
                     return false;
                   }
               }
        }
   });

   $('form').submit(function(){

    var bank = $.trim($("#bank_unicode").val());
    var product_name = $.trim($("#product_id").val());
    var from = $.trim($("#from_date").val()); 
    var to = $.trim($("#to_date").val()); 
    var from_dt = from.split("-");
    var to_dt = to.split("-");
    var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
    var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
    var diff = y - x;
    var one_day=1000*60*60*24;
    var date_range = diff/one_day;
    var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
    
    if(bank == '') {
        alert('Please select Bank Name');
        $("#bank_unicode").focus();
        return false;
    }
    
    if(product_name == '') {
        alert('Please select Product');
        $("#product_id").focus();
        return false;
    }
    /**** From and To date validation ****/
    if((from == '') || (to == '') ) {
            alert('Please specify both From and To date.');
            $("#from_date").focus();
            return false;
    }  
    else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
         alert('Please specify both From and To date.');
         $("#from_date").focus();
         return false;
    } else if(diff < 0){
       alert('From date cannot be greater than To date.');
         $("#from_date").focus();
         return false; 
    }
    else if(date_range > max_range){
       alert('Report can be fetched for a duration not more than '+max_range+' days');
         $("#to_date").focus();
         return false; 
    }

    /**** From and To date validation over ****/

    return true; 
  });    
});
</script>