<div class="Boldtext">Unsettled Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$config = array();
$TXN_TYPE_LABELS = Zend_Registry::get("TXN_TYPE_LABELS");

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

if($this->sub){
// column names & indexes
$config['columnNames'] = array(
   'Transaction Date & Time',
   'Product Name',
   'Bank Name',
   'Agent/Corporate Code',
   'Agent/Corporate Name',
   'Card Pack Id',
   'Card Number',
   'Member ID/CRN',
   'Shmart Transaction Code',
   'Transaction Amount',
   'Transaction Type',
   'Transaction Status',
   'Wallet Code',
   'Cr/Dr',
   'RRN No',
   'Acknowledge No.',
   'Decline Reason',
   'MCC',
   'TID',
   'MID',
   'Channel',
   'Reversal Flag',
   'Reversal Date',
   'Mode',
   'Transaction Narration',
   'Settlement Flag',
   
    );
$config['columnIndexes'] = array(
    'date_load',
    'product_name',
    'Ratnakar Bank',
    'code',
    'name',
    'card_pack_id',
    'card_number',
    'member_id',
    'txn_code',
    'txn_type',
    'status',
    'wlt_code',
    'mode',
    'sequence_no',
    '',
    '',
    '',
    '',
    '',
    'mode',
    'is_reversal',
    'date_reversal',
    'status_settlement',
    'narration',
    'status_settlement',
    
);

$cntColNames = count($config['columnNames']);
?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
              <td><?php echo $item['date_load'];?></td>
              <td><?php echo $item['product_name'];?></td>
                        <td>Ratnakar Bank</td>
                        
                        <td><?php echo $item['code'];?></td>
                        <td><?php echo $item['name'];?></td>
                        <td>-</td>
                        <td><?php echo Util::maskCard($item['card_number'],4);?></td>
                        <td><?php echo $item['member_id'];?></td>
                        <td><?php echo $item['txn_code'];?></td>
                        <td><?php echo $item['amount'];?></td>
                        <td><?php $txn = isset($TXN_TYPE_LABELS[$item['txn_type']])?$TXN_TYPE_LABELS[$item['txn_type']]:'';echo $txn;?></td>
                        <td><?php echo ucfirst($item['status']);?></td>
                        <td><?php echo $item['wlt_code'];?></td>
                        <td><?php echo ucfirst($item['mode']);?></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
        <td><?php echo strtoupper($item['load_channel']);?></td>
        <td><?php echo ucwords($item['is_reversal']);?></td>
        <td><?php echo $item['date_reversal'];?></td>
        <td><?php echo ucfirst($item['mode']);?></td>
        <td><?php echo $item['narration'];?></td>
        <td><?php echo ucfirst(STATUS_UNSETTLED);?></td>
        
              
                    <?php /********** finished displaying the inner columns **********/ ?>
                   
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php if(count($this->paginator)>0) { ?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<div class="show-xls"> 
  <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php }  }?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
       
            var url = '<?php echo $this->formatURL("/reports/exportunsettledreport?product_id=".$this->formData['product_id']."&card_number=".$this->formData['card_number']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']."&settlement_ref_no=".$this->formData['settlement_ref_no']."&dur=".$this->formData['dur']);?>';
            $(location).attr('href',url);
       
    });  
     $('form').submit(function(){
       
       var product_id = $.trim($("#product_id").val()); 
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";

       
       /**** From and To date validation ****/
       $('#product_id').css('background', '#fff');
       $('#from_date').css('background', '#fff');
       $('#to_date').css('background', '#fff');
         if(product_id == ''){
            alert('Select product name');
            $('#product_id').css('background', '#ff0');
            $("#product_id").select();
            return false; 
         }else if(diff < 0){
               alert('From date cannot be greater than To date.');
                $('#from_date').css('background', '#ff0');
                 $("#from_date").focus();
                 return false; 
            }else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $('#to_date').css('background', '#ff0');
                    $("#to_date").focus();
                    return false; 
               }
          
       /**** From and To date validation over ****/
          
     return true; 
   }); 
 
});
</script>
