<div class="Boldtext">Login Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->from!='' && $this->to!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Cardholder Activations Report for period '.$duration;
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

if ($this->formData['user_type'] == 't_agents'){
    // column names & indexes
$config['columnNames'] = array(
'User Name',
'User Code',
'Username',
'System IP',
'Login Step 1 Date & Time',
'Login Step 2 Date & Time',
'Log Out Date & Time',
'Current Login status',
'Failed Reason',
'Last Password Change Date',
'Current User Status'    
);

$config['columnIndexes'] = array(
    'user_name',
    'user_code',
    'logusername',
    'system_ip',
    'login1_datetime',
    'login2_datetime',
    'datetime_logout',
    'login_status',
    'failed_reason',
    'pwd_change_date',
    'user_status'
);

}
else{
    // column names & indexes
$config['columnNames'] = array(
'User Name',
'Username',
'System IP',
'Login Step 1 Date & Time',
'Login Step 2 Date & Time',
'Log Out Date & Time',
'Current Login status',
'Failed Reason',
'Last Password Change Date',
'Current User Status'    
);

$config['columnIndexes'] = array(
    'user_name',
    'logusername',
    'system_ip',
    'login1_datetime',
    'login2_datetime',
    'datetime_logout',
    'login_status',
    'failed_reason',
    'pwd_change_date',
    'user_status'
);

}

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$config['showComma'] = array('amt');
// render the default listing
?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                
                <tr>
               
                    <?php /********** displaying the inner columns **********/ 
                    if ($item['portal'] == MODULE_AGENT){
    ?>


                    <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo  Util::restoreIpAddressFromat($item[$config['columnIndexes'][3]]);?></td>
                        <td><?php echo  Util::returnDateFormatted($item[$config['columnIndexes'][4]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][6]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][9]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]];?></td>
                       
                     <?php } else{ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo  Util::restoreIpAddressFromat($item[$config['columnIndexes'][2]]);?></td>
                        <td><?php echo  Util::returnDateFormatted($item[$config['columnIndexes'][3]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][4]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][8]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                        
                        
                        
                     <?php } 
                    /********** finished displaying the inner columns **********/ ?>
                    <?php $datePrev = $item[$config['columnIndexes'][0]];?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php }  }
?>
<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        if(dur==''){
            alert('Please specify duration');
        } else {
             var url = '<?php echo $this->formatURL("/reports/exportuserlogin?dur=".$this->formData['dur']."&user_type=".$this->formData['user_type']);?>';    
            $(location).attr('href',url);
       }
    });     
});
</script>
