<div class="Boldtext">Transaction Report Wallet-wise</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->from!='' && $this->to!=''){
 $bankUnicodeArr = Util::bankUnicodesArray();     
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Cardholder Activations Report for period '.$duration;
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

if($this->formData['bank_unicode'] == $bankUnicodeArr['2']){
// column names & indexes
$config['columnNames'] = array(
    'Transaction Date & Time',
    'Product Name',
    'Bank Name',
    'Card Number',
    'Card Pack Id',
    'Medi Assist ID / Partner Ref No',
    'Transaction Type',
    'Transaction Status',
    'Wallet Code',
    'Mode',
    'Amount',
    'Transaction Amount',
    'Fee',
    'Service Tax',
    'RRNO / Transaction Ref No.',
    'Acknowledge No.',
    'Decline Reason',
    'MCC',
    'TID',
    'MID',
    'Channel',
    'Reversal Flag',
    'Reversal Date',
    'Original Txn No',
    'Original Transaction Date & Time',
    'Transaction Narration',
    'Settlement Flag',
    'Settlement Date',
    'Benf. A/c No',
    'Benf. A/c Name',
    'Response file Reference Number',
    'Block Date',
    'Unblock Date'
    );
$config['columnIndexes'] = array(
    'txn_date',
    'product_name',
    'bank_name',
    'card_number',
    'card_pack_id',
    'member_id',
    'txn_type',
    'status',
    'wallet_hr_dr',
    'wallet_hr_cr',
    'wallet_ins_dr',
    'wallet_ins_cr', 	
    'wallet_gen_dr',
    'wallet_gen_cr', 	
    'trans_amount',
    'txn_no',
    'txn_code',
    'failed_reason',
    'mcc_code',
    'tid',
    'mid', 	 	 	 	
    'channel',
    'rev_indicator',
    'date_reversal',
    'original_txn_no',
    'original_transaction_date',
    'wlt_code',
    'mode',
    'narration',
    'status_settlement',
    'date_settlement',
    'bene_act_no',
    'bene_act_name',
    'settlement_ref_no',
    'date_blocked',
    'date_unblocked'
);
}
else{
   // column names & indexes
$config['columnNames'] = array(
    'Transaction Date & Time',
    'Product Name',
    'Bank Name',
    'Card Number',
    'Card Pack Id',
    'Member ID',
    'Transaction Type',
    'Transaction Status',
    'Wallet Code',
    'Mode',
    'Wallet A Dr',
    'Wallet A Cr',
    'RRNO',
    'Acknowledge No.',
    'Decline Reason',
    'MCC',
    'TID',
    'MID',
    'Channel',
    'Reversal flag',    
    'Transaction Narration'
    );
}
$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
               ?>
                <?php 
                    //foreach($dateArr as $item) :?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo Util::returnDateFormatted($item['txn_date'], "Y-m-d", "d-m-Y", "-", "-");?></td>
                        <td><?php echo $item['product_name'];?></td>
                        <td><?php echo $item['bank_name'];?></td>
                        <td><?php echo $item['card_number'];?></td>
                        <td><?php echo $item['card_pack_id'];?></td>
                        <td><?php echo $item['member_id'];?></td>
                        <td><?php echo $item['txn_type'];?></td>
                        <td><?php echo $item['status'];?></td>
                        <td><?php echo $item['wlt_code'];?></td>
                        <td><?php echo strtoupper($item['mode']);?></td>
                         
                        <?php if($this->formData['bank_unicode'] == $bankUnicodeArr['2']){ ?>
                            <td><?php echo Util::numberFormat($item['wallet_hr_dr']);?></td>
                        <?php } else { ?>
                            <td><?php echo Util::numberFormat($item['wallet_hr_dr']);?></td>
                            <td><?php echo Util::numberFormat($item['wallet_hr_cr']);?></td>
                        <?php } ?>
                            
                        <?php if($this->formData['bank_unicode'] == $bankUnicodeArr['2']){ ?>
                            <td><?php echo Util::numberFormat($item['trans_amount']);?></td>
                            <td><?php echo Util::numberFormat($item['fee_amt']); ?></td>
                            <td><?php echo Util::numberFormat($item['service_tax']); ?></td>
                        <?php } ?>
                       
                        <td><?php echo $item['txn_no'];?></td>
                        <td><?php echo $item['txn_code'];?></td>
                        <td><?php echo $item['failed_reason'];?></td>
                        <td><?php echo $item['mcc_code'];?></td>
                        <td><?php echo $item['tid'];?></td>
                        <td><?php echo $item['mid'];?></td>
                        <td><?php echo strtoupper($item['channel']);?></td>
                        <td><?php echo $item['rev_indicator'];?></td>

                        <?php if($this->formData['bank_unicode'] == $bankUnicodeArr['2']){ ?>
                            <td><?php echo $item['date_reversal'];?></td>
                            <td><?php echo $item['original_txn_no'];?></td>
                            <td><?php echo $item['original_transaction_date'];?></td>                            
                        <?php } ?>
                        
                        <td><?php echo $item['narration'];?></td>
                        <?php if($this->formData['bank_unicode'] == $bankUnicodeArr['2']){ ?>
                        <td><?php echo $item['status_settlement']; ?></td>
                        <td> <?php echo $item['date_settlement'];?> </td>
                        <td><?php echo $item['bene_act_no'];?></td>
                        <td><?php echo $item['bene_act_name'];?></td>
                        <td><?php echo $item['settlement_ref_no'];?></td>
			<td><?php echo $item['date_blocked'];?></td>
			<td><?php echo $item['date_unblocked'];?></td>
                        <?php } ?>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php
if(count($this->paginator)>0){?>

<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } } ?>



<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        
            var url = '<?php echo $this->formatURL("/reports/exportwallettxn?dur=".$this->formData['dur']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date'].'&product_id='.$this->formData['product_id'].'&bank_unicode='.$this->formData['bank_unicode'].'&wallet_type='.$this->formData['wallet_type']);?>';    
            $(location).attr('href',url);
       
    });
 var product = $("#product").val();
 if($("#bank_unicode").val() != ''){
  $.ajax({
                url: '/ajax/get-bankproductscommon/q/'+$("#bank_unicode").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#product_id").html("");                            
                            $("#product_id").append(response);
                            $("#product_id option[value='"+product+"']").attr("selected", "selected");
                             console.log(response);                            
                        }
                    }     
        });
 }

  $("#bank_unicode").change(function(){
            $.ajax({
                url: '/ajax/get-bankproductscommon/q/'+$("#bank_unicode").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#product_id").html("");                            
                            $("#product_id").append(response);
                             console.log(response);                            
                        }
                    }     
        });
    });      
     $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       /**** From and To date validation ****/
      if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
            alert('Please select either duration or from and to date.');
            $("#dur").focus();
            return false;
      } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                    alert('Please specify From date.');
                    $("#from_date").focus();
                    return false;
               }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify To date.');
                    $("#to_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date cannot be greater than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>