<div class="Boldtext"><?= $this->heading ?></div>
<span><?php echo $this->msg ?></span>

<div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'> 
        <tbody>
            <tr>
                <th style="width:20%">Cardholder Name: </th>
                <td style="width: 80%" align="left"><?php echo $this->chInfo['name']; ?></td>
            </tr>

            <tr>
                <th style="width:20%">Cardholder Email: </th>
                <td style="width: 80%" align="left"><?php echo $this->chInfo['email']; ?></td> 
            </tr>
            <tr>
                <th style="width:20%">Cardholder Mobile: (+91) </th>
                <td style="width: 80%" align="left"><?php echo $this->chInfo['mobile']; ?></td>
            </tr>

        </tbody>
    </table>
</div>
<?php
echo $this->form;
$session = new Zend_Session_Namespace('App.Agent.Controller');
?>
<style>
#send_auth_code-label {
    margin: 20px;
}


</style>
<script type="text/javascript">
    $(document).ready(function () {
        var cardholder_auth = '<?php echo isset($session->ch_fund_load_auth) ? $session->ch_fund_load_auth : 0; ?>';
        $("#btn_auth_code").click(function () {
             if ($.trim($("#amount").val()) == '') {
                alert('Please enter load amount');
                $("#amount").focus();
                return false;
            }
            $("#send_auth_code").val('1');
            $("#is_submit").val('0');
            $("#frmFund").submit();
        });
//        if (cardholder_auth != '' && cardholder_auth > 0) {
//            $("#btn_auth_code").attr('value', 'Resend Authorization Code');
//            $("#amount").attr('readonly', 'readonly');
//        }

        $("#btn_submit").click(function () {
            if ($.trim($("#amount").val()) == '') {
                alert('Please enter load amount');
                $("#amount").focus();
                return false;
            }else if ($.trim($("#amount").val()) < 1) {
                alert('Please enter valid amount');
                $("#amount").focus();
                return false;
            }
            $("#is_submit").val('1');
            $("#send_auth_code").val('0');
            $("#btn_submit").attr("disabled", "disabled");
            $("#frmFund").submit();
        });


        $('#amount').live('keyup', function() {
            $( "#send_auth_code-label" ).html('<img src="/images/ajax-loader.gif">');
            var productId = $.trim($("#product_id").val());
            var amount = $.trim($("#amount").val());
            $.ajax({
               url: '/ajax/get-loadfee/amt/'+amount+'/proid/'+productId,
               success: function(response) {
                       $( "#send_auth_code-label" ).html(response);
              }
            });
        });
        
    });
</script>