<script type="text/javascript" charset="utf-8"> 
   $(document).ready(function() {
        $('.cancel').attr('href',document.referrer);
         $("input#txn_flat").blur(function() {
        if(this.value) {
            
            $("#txn_pcnt").attr('disabled', 'disabled'); 
            $("#txn_min").attr('disabled', 'disabled'); 
            $("#txn_max").attr('disabled', 'disabled'); 

        }
         var val = this.value;
         if(val.length == 0) {
             $("#txn_pcnt").removeAttr("disabled");
             $("#txn_min").removeAttr("disabled");
             $("#txn_max").removeAttr("disabled"); 
         }
        
    });
    $("input#txn_pcnt").blur(function() {
        if(this.value) {
           
            $("#txn_flat").attr('disabled', 'disabled'); 
            
        }
            var val = this.value;
         if(val.length == 0) {
            $("#txn_flat").removeAttr("disabled"); 
             
         }

        });
      
      
      
      
           
        
      
  

}); 

</script>
<?php
/**
 * Add a new Agent Fee in the application
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright Transerv
 */

$config = array();
$config['pageTitle'] = 'Plan Name: '.$this->name;
$config['noteText'] = 'Commission Plans, once assigned, cannot be modified. In case of a new requirement, a new Commission plan should be defined.';

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);


?>