<?php
/**
 * View for the login action
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */
?>
 <div class="login-title">CORPORATE LOGIN</div>

        
        <?php 
            if (isset($this->errType)){
                switch($this->errType){
                    case 'err_sess':
                        $errMsg = '<strong>Oops!</strong><br />Either Session timed out or someone else is trying to login with your credentials. Please re-login.';
                        break;
                    case 'incorrectuser':
                        $errMsg = '<strong>Oops!</strong><br />Invalid Username or Password';
                        break;
                    case 'incorrectpass':
                        $errMsg = '<strong>Oops!</strong><br />Invalid Username or Password. You have '.$this->num.' login attempts remaining.';
                        break;
                    case 'notverified':
                        $errMsg = '<strong>Oops!</strong><br />Your Email id is not verified. Please contact the Corporate Help Center.';
                        break;
                    case 'notapproved':
                        $errMsg = '<strong>Oops!</strong><br />Your account is not approved by Corporate Help Center.';
                        break;
                    case 'blocked':
                        $errMsg = '<strong>Oops!</strong><br />Your account is inactive. Please contact the Corporate Help Center.';
                        break;
                    case 'locked':
                        $errMsg = '<strong>Oops!</strong><br />Your account is locked. Please contact the Corporate Help Center.';
                        break;
                    case 'rejected':
                        $errMsg = '<strong>Oops!</strong><br />Your account has been rejected. Please contact the Corporate Help Center.';
                        break;
                    
                }
                ?>
                <div class="error">
                <p><?php  echo $errMsg; ?></p>
            </div>       
         <?php       
            }
        ?>
         
                
        
            
        <?php echo $this->form;?>
         <div class="div3">
             <div class="row"><a href="<?php echo $this->formatURL('/profile/forgot-password/');?>">forgot password?</a></div>
             <div class="row"><!--<a href="<?php echo $this->formatURL('/profile/resend-verificationlink/');?>">Already a card holder?</a>--><br>
<span class="card-holder"> Register online and generate your password instantaneously </span></div>
 
        </div>
    
    <div class="clear"></div>
<script type="text/javascript">
    $("#profile-login").submit(function () {
        var pass = $("#password").val();
        var encodedString = crypt_fn('<?php echo App_DI_Container::get('ConfigObject')->{corporate}->security->loginClientKey; ?>', pass);
        $("#password").val(encodedString);
    });
</script>