<script type="text/javascript">
$(document).ready(function() {
    
   
     
  $('form').submit(function() {
    var pass = $("#password").val();
    var confpass = $("#retype_new_password").val();
    
   if(pass != confpass){
  alert('Password and retyped password Values do not match');
  return false;
   }
   else
       return true;
   
});
    
});      
  </script><?php
/**
 * View that allows the user to change his/her password
 *
 * @category agent
 * @package agent_views
 * @subpackage agent_views_profile
 * @copyright transerv
 */
$config = array();

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);

