<?php
/**
 * Delete a product
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Approve Corporate: '.$this->item->name;
$config['areYouSureMessage'] = 'Are you sure you want to approve this Corporate?';

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Email',
    'Mobile',
   );
$config['columnIndexes'] = array(
    'name',
    'email',
    'mobile',
   );

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);