<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Rejected Corporates Listing';

$config['emptyMessage'] = 'There is no rejected Corporate list at this time.';

$config['no_add']=1;  //to not have add button
// column names & indexes
$config['columnNames'] = array(
    
    'Name',
    'Email',
    'Agent Code',
    'Mobile No.',
    'Registration Date',
   // 'Status'

);
$config['columnIndexes'] = array(
    
     'name',    
    'email',
    'corporate_code',
    'mobile',
    'reg_datetime',
   // 'status'
    
);

$config['showActions'] = false;

$config['viewLinkColumn'] = 'name';
//$config['linkOrder'] = array('approve','reject');
// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);