<?php
/**
 * Displays an user
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */

$config = array();
$id = $this->item['id'];

$rejectUrl = $this->formatURL("/approveagent/reject?id=".$id);
$rejectstatusaction ="<a href='".$rejectUrl."' title ='Reject'>Reject</a>";

$approveUrl = $this->formatURL("/approveagent/approve?id=".$id);
$approvestatusaction ="<a href='".$approveUrl."' title ='Approve'>Approve</a>";
 
//$config['pageTitle'] = sprintf('Detailed view for: %s - %s (%s / %s)', ucwords($this->item['name']),$this->item['agent_code'],$approvestatusaction,$rejectstatusaction);
$config['pageTitle'] = sprintf('Detailed view for: %s - %s ', ucwords($this->item['name']),$this->item['agent_code']);
// column names & indexes
$config['columnNames'] = array(
    'AFN',
    'Agent Code',
    'Email',
    'Name',
    'Phone number',
    'Office Address',
    'Education level',
    'Metric School Name',
    'Intermediate School Name',
    'Graduation Degree',
    'Graduation College',
    'Post Graduation Degree',
    'Post Graduation College',
    'Date Of Birth',
    'Gender',
    'Identification Type',
    'ID number',
    'PAN',
    'Address Type',
    'Address Line 1',
    'Address Line 2',
    'City',
    'Taluka',
    'District',
    'State',
    'Country',
    'Pincode',
    'Bank Name',
    'Bank Account Number',
    'Bank Id',
    'Bank Location',
    'Bank City',
    'Bank IFCS',
    'bank Branch ID',
    'Bank Area',
    'Registration Type',
    
    
);
$config['columnIndexes'] = array(
    'afn',
    'agent_code',
    'email',
    'name',    
    'mobile1',
    'office',
    'education_level',
    'matric_school_name',
    'intermediate_school_name',
    'graduation_degree',
    'graduation_college',
    'p_graduation_degree',
    'p_graduation_college',
    'date_of_birth',
    'gender',
    'Identification_type',
    'Identification_number',
    'pan_number',
    'res_type',
    'res_address1',
    'res_address2',
    'res_city',
    'res_taluka',
    'res_district',
    'res_state',
    'res_country',
    'res_pincode',
    'bank_name',
    'bank_account_number',
    'bank_id',
    'bank_location',
    'bank_city',
    'bank_ifsc_code',
    'branch_id',
    'bank_area',
    'registration_type',
    
    
);

$config['backlink'] = $this->backlink;
$config['balance'] = $this->balance;
$config['agent_id'] = $this->agent_id;
$config['productarray'] =$this->productArr;
$config['limitarray'] =$this->limitArr;
$config['documentarray'] =$this->document;
$config['detailsarray'] =$this->item;

echo $this->partial(
        
    'partials/default-pending-agent-detail-view.phtml',
    array(
        'config' => $config,
        'item' => $this->item
    )
);

print '<script type="text/javascript">
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1", {defaultTab:0});
</script>';