<?php
/**
 * Agent details
 *
 * @category opertaion
 * @package operation_views
 * @copyright Transerv
 */
$data = array();
$helper = $this->listingUtilities($data);
$data = $this->data;
?>

<div class="header"> 
    <h1>Agent Document list 

    </h1>
</div>

<div class="finalaction">

    
<?php 
if(empty($data))
    echo 'No Documents uploaded';
foreach ($data as $doc) : 
           $imgIcon = $doc['doc_type'];

switch ($imgIcon) {
            case "passport":
                $docTypeImg = 'passport.png';
                break;
            case "photo":
                $docTypeImg = 'photo.png';
                break;
            case "shopphoto":
               $docTypeImg = 'shopphoto.png';
                break;
            case "idprooof":
                $docTypeImg = 'idproof.png';
                break;
            case "pan":
                $docTypeImg = 'pan.png';
                break;
            case "addressproof":
                $docTypeImg = 'addressproof.png';
                break;
            case "others":
                $docTypeImg = 'others.png';
                break;
     }
$imgPath = '/images/icons/'.$docTypeImg;
if($helper->can('file', 'filedownload')) {
    $formatUrl = $this->formatURL("/filedownload/file?file=".$doc['file_name']); 
?>
<a href="<?php echo $formatUrl; ?>"><img src="<?php echo $imgPath;?>" width="100" height="100"/></a>
<?php } ?>
<?php endforeach; ?>
   

</div>