<?php
/**
 * Delete a privilege
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Unblock Agent';
$config['areYouSureMessage'] = 'Are you sure you want to unblock the agent?';

// column names & indexes
$config['columnNames'] = array(
    'Name'
);
$config['columnIndexes'] = array(
    'name'
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);
?>
<script type="text/javascript" charset="utf-8"> 
   $(document).ready(function() {
       
       var url = '<?php echo $this->queryString;?>';
       $('.cancel').attr('href',url);
        
       
}); 

</script>