<div class="Boldtext">Consolidated Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->formData['sub'] == 1){
$bankUnicodeArr = Util::bankUnicodesArray();    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Cardholder Activations Report for period '.$duration;
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'AOF Reference Number',
    'Application Date',
    'Name (of the Trainee)',
    'NSDC Enrollment Number',
    'Aadhaar No.',
    'Linked Branch ID',
    'Transerv Status',
    'Bank Status',
    'Account No.',
    'IFSC Code',
    'Card No.',
    'Debit Mandate Amount',
    'NSDC Wallet Load Date',
    'NSDC Load Amount',
    'Available Balance on Wallet',
    'Amount debited through POS',
    'Wallet Auto Debit Date',
    'Wallet Auto Debit Amount',
    'Traning Center BC Name',
    'Training Center ID',
    'Training Center Name',
    'Training Partner Name',
//    'Current Balance on Wallet',
    
    );
$config['columnIndexes'] = array(
    'ref_num',
    'date_created',
    'name',
    'nsdc_enrollment_no',
    'aadhaar_no',
    'sol_id',
    'status_ops',
    'status_bank',
    'account_no',
    'ifsc_code',
    'card_number',
    'debit_mandate_amount',
    'date_load',
    'load_amount',
//    'wallet_bal',
    'current_wallet_balance',
    'debit_amount_pos',
    'date_auto_debit',
    'auto_debit_amount',
    'by_agent_name',
    'training_center_id',
    'traning_center_name',
    'training_partner_name',
   
);

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
// render the default listing
$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");

?>


<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                     
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]]; ?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][11]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][12]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][13]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][14]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][15]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][16]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][17]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][18]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][19]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][20]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][21]];?></td>
                       
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } ?>
<?php 
}?>



<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        
            var url = '<?php echo $this->formatURL("/corp_boi_reports/exportconsolidatedreport?dur=".$this->formData['dur']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date'].'&product_id='.$this->formData['product_id'].'&bank_unicode='.$this->formData['bank_unicode'].'&ref_num='.$this->formData['ref_num'].'&status='.$this->formData['status'].'&nsdc_enrollment_no='.$this->formData['nsdc_enrollment_no'].'&account_no='.$this->formData['account_no'].'&aadhaar_no='.$this->formData['aadhaar_no'].'&agent_id='.$this->formData['agent_id']);?>';    
            $(location).attr('href',url);
       
    });

    
     $('form').submit(function(){
       var ref_num = $.trim($("#ref_num").val()); 
       var agent_id = $.trim($("#agent_id").val()); 
       var aadhaar = $.trim($("#aadhaar_no").val()); 
       var account_no = $.trim($("#account_no").val()); 
       var checker_date = $.trim($("#date_approval").val()); 
       var nsdc_no = $.trim($("#nsdc_enrollment_no").val()); 
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var duration = $("#dur").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
      /**** From and To date validation ****/
      var validateDate = 0;
      /**** From and To date validation ****/
      if(ref_num == '' && aadhaar == '' && account_no == '' && checker_date == '' && nsdc_no == ''  ) {
            if(duration =='' && from =='' && to ==''){
                    alert('Please select either one search criteria or date range');
                    return false;
            }
            else{
                validateDate = 1;
            }
       }
       else {
	if(from != '' || to != '') {
		 validateDate = 1;
	}
    }
    
    
      if(validateDate && agent_id !=''){  
      
       /**** From and To date validation ****/
      if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
            alert('Please select either duration or from and to date.');
            $("#dur").focus();
            return false;
      } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                    alert('Please specify From date.');
                    $("#from_date").focus();
                    return false;
               }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify To date.');
                    $("#to_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date cannot be greater than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
         
     return true; 
      }
   });    
});

</script>