
    <div class="index-left-box">"For those who dare to dream, there is a whole world to win… </div>
    <div class="index-right-box landing-bold"><span style="float:right;">Enable customers to transact online</span></div>
    
    <div class="index-left-box">Dream and dare." </div>
    <div class="index-right-box landing-bold"><span style="float:right;">Be an enabler for e-commerce revolution in India</span></div>
    
    <div class="clear"></div>
    <div class="index-left-box"></div>
    <div class="index-right-box landing-bold"></div>

    <div class="clear"></div>
    <div class="dotted"></div>

    <div class="index-left-box">
        <div class="landing-bold dotted-vertical">About Us</div>
        <div class="landing dotted-vertical">
            TranServ was formed with the primary objective to offer <b>end to end Prepaid Program Management Service</b> using Cards and Mobile Technology. We have been engaged by  multiple banks to create and distribute various financial products and services.  
We appoint business partners who are located across India to source new customers and enable them to transact electronically. <a href="#">Know  more</a>
        </div>
       
    </div>
    <div class="index-right-box">
        <div class="landing-bold">Contact Us</div>
        <div class="landing">
         Customer Care Number: <?php echo AGENT_AUTH_CALL_CENTRE_NUMBER;?><br/>
        </p>

        <p><div class="landing-bold">Safe and Secure</div>
            <a href="#" title="www.shmart.in">www.shmart.in</a> is a safe and secure website.
        </p>
        </div>
    </div>