<script type="text/javascript">
$(document).ready(function() {

  $("#name").change(function(){
            $.ajax({
                url: '/ajax/get-ifsc/q/'+$("#name").val(),
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            $("#branch_name").val('');  
                            $("#city").val('');  
                            $("#address").val(''); 
                            $("#ifsc_code").html("");                           
                            $("#ifsc_code").append(response);
                            console.log(response);
                            
                        }
                    }
         
        });
    });   
 
 $("#ifsc_code").change(function(){
            $.ajax({
                url: '/ajax/get-bankdetails/q/'+$("#ifsc_code").val(),
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            var resArr = response.split('^');
                            
                           
                            $("#branch_name").val(resArr['0']);  
                            $("#city").val(resArr['1']);  
                            $("#address").val(resArr['2']);  
                          
                            console.log(response);
                            
                        }
                    }
         
        });
    });   
 
  

});      
</script>
<?php
/**
 * Add a new privilege in the application
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Add new Bank';

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);
