<?php //echo $this->form; ?>

<div class="Boldtext">Check Balance</div> 
<div class="tablebox">
   
    <table style="width: 100%">
        
            <tr>
                <th style="width:20%">Active Balance (<span class="WebRupee"></span>)</th>            
                <td style="width: 80%" align="left"><?php echo $this->balance;?></td>
            </tr>         
             
    </table>
   
</div>
