<?php
/**
 * Displays the user's dashboard
 *
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */
  ?>

<!--First Row-->
<div class="today_date"><?php echo Util::getFormattedDate('F d, Y');?></div>
<div style ="clear:both;"></div>
<div class="grid-heading">General Updates</div>
<!-- <div class="grid3col_chart">
  <div class="column_chart_comm first">
    Div that will hold the column chart for commission amount
    <div id="chart_div_commission"></div>  
  </div>
   
  
</div>-->

<div style ="clear:both;"></div>
<!--Second Row-->
<!-- <div class="grid-heading">MVC Updates</div>
<div class="grid3col">
  <div class="column first">
      <div class="column-heading">My balance<br>(for the current month)</div>
  <?php echo CURRENCY_INR.' '.Util::numberFormat($agentBal);?>
  </div>
  <div class="column">
      <div class="column-heading">My Earnings<br>(for the current month)</div>
     <?php echo CURRENCY_INR.' '.Util::numberFormat($agentEarnings); ?>
  </div>
  <div class="column last">
      <div class="column-heading">New enrollments<br>(for the current month)</div>
     <?php echo $totalCHRegistered;?>
  </div>
</div>
 <div class="grid3col">
  <div class="column first">
      <div class="column-heading">Load amount<br>(for the current month)</div>
  <?php echo CURRENCY_INR.' '.Util::numberFormat($totalLoadedAmount);?>
  </div>
  <div class="column">
      <div class="column-heading">No. of reloads<br>(for the current month)</div>
     <?php echo $totalCHReloaded;?>
  </div>
  <div class="column last">
      <div class="column-heading">Total reload amount<br>(for the current month)</div>
     <?php echo CURRENCY_INR.' '.Util::numberFormat($totalReloadedAmount);?>
  </div>
</div>
<div style ="clear:both;"></div>-->
<!--Third Row-->

<!-- <div class="grid3col_chart">
  <div class="column_chart first">
    Div that will hold the column chart for remittance amount
    <div id="chart_div_remittance"></div>  
  </div>
     <div class="column_chart">
     <div id="chart_div_remitterrgn"></div>  
  </div>
  
</div>-->
 <div style ="clear:both;">

