<div class="Boldtext">Bank Status Application List</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
echo $this->form;
// messages
$config['pageTitle'] = 'Bank Status Application';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found';
if(isset($this->paginator)){
// column names & indexes
$config['columnNames'] = array(
    'Name',
//    'Last Name',
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Date of Birth',
    'Mobile',
    'Email',
    'Debit Mandate Amount',
//    'Comments',
    'Bank Status',
    );
$config['columnIndexes'] = array(
    'name',
//    'last_name',
    'member_id',
    'card_number',
    'card_pack_id',
    'date_of_birth',
    'mobile',
    'email',
    'debit_mandate_amount',
//    'comments',
    'status_bank',
);
$config['viewLinkColumn'] = 'name';
$cntColNames = count($config['columnNames']) ;



$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>

 
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox" style="clear:both;">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                  <th><span>Actions</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
           <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <!--<td class="tc">
                                <input type="checkbox" name="checkall" value="true" />
                            </td>--> 
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php 
                            //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                            ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                    
                                        $helper->displayItem($item, $index);
                                    
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                                <td>
                                    <?php if($item['status_bank'] == STATUS_REJECTED){ ?>
                                
                        <?php if ($helper->can('resubmit','corp_kotak_customer')) {?>
                        <a href="<?php echo $this->formatURL('/corp_kotak_customer/resubmit?id='.$item['id']);?>"><?php echo 'Resubmit';?></a>
                        <?php } ?>
                                    <?php }
                                    else
                                    {
                                        echo '-';
                                    }?>
                                </td>
                                 <td>
                                    <?php if($item['status_bank'] == STATUS_REJECTED){ ?>
                                
                        <?php if ($helper->can('view','corp_kotak_customer')) {?>
                        <a href="<?php echo $this->formatURL('/corp_kotak_customer/view?id='.$item['id']);?>"><?php echo 'View Comments';?></a>
                        <?php } ?>
                                    <?php }
                                    else
                                    {
                                        echo '-';
                                    }?>
                                </td>
                        </tr>    
                    <?php endforeach;?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php } ?>
<script type="text/javascript">
$(document).ready(function() {    
  
    
          
       $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
     $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       
 
      /**** From and To date validation ****/
     if(((from == '' || from =='00-00-0000')) || ((to == '' || to=='00-00-0000') )) {
                    alert('Please specify both From and To date.');
                    $("#from_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date greater be less than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>
