<div class="Boldtext">Card Mapping File Report</div>
<script>
  $(document).ready(function(){
     
     $("#searchCriteria").change(function(){
         
         $("#keyword").val('');
       });      
         
     });
</script>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Card Mapping File Report';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';

// column names & indexes
$config['columnNames'] = array(
    'Product Name',
    'Card Number',
    'BOI Account Number',
    'BOI Customer ID',
    'Date Registration',
    'Failed Reason',
    'Status'
    );
$config['columnIndexes'] = array(
    'name',
    'card_number',
    'boi_account_number',
    'boi_customer_id',
    'date_ecs',
    'failed_reason',
    'status'
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>
<?php echo $this->form; 
if ($this->records) {
?> 

<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo util::maskCard($item[$config['columnIndexes'][1]],4);?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][3]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][4]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][6]]);?></td>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    
    <?php endif; 
       if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } ?>
</div>
<?php } ?>
<script>
$(document).ready(function() {
    $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
    
   
      $("#btn_exportcsv").click(function(){
        
            var url = '<?php echo $this->formatURL("/corp_boi_customer/exportcardmappingstatus?batchname=".$this->formData['batchname']."&from_date=".$this->formData['from_date']."&to_date=".$this->formData['to_date']);?>';    
            $(location).attr('href',url);
       
    });
});
</script>
