SET @flag_id := (SELECT id FROM `t_flags` where name ='operation-corporates'); 

SET @ops_id = '3';

INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'view', @flag_id, 'View Corporate Details');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @ops_id, @flag_id, @priv_id, '1');


INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'view', @flag_id, 'View Corporate Details');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @ops_id, @flag_id, @priv_id, '1');


ALTER TABLE `corporate_bind_product_commission` CHANGE `product_limit_id` `corporate_limit_id` INT( 11 ) UNSIGNED NOT NULL ;



INSERT INTO `purse_master` VALUES ('12', '3', '3', '1', 'RCG310', 'Medi-Assist GPR Wallet', 'Medi-Assist GPR Wallet', '50000', 'no', 'no', 'none', '0', '0', '0', '0', '50000', '5', '50000', '40', '300000', '450', '3600000', 'mcc', 'no', '1', '50000', '10', '50000', '90', '300000', '1000', '3600000', '3', '2014-06-26 15:44:59', '2014-06-26 15:45:09', '2014-06-26 15:48:48', '101', 'active');

INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '742', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '763', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '780', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1520', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1711', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1731', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1740', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1750', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1761', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1771', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '1799', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '2741', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '2791', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '2842', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3000', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3001', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3002', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3003', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3004', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3005', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3006', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3007', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3008', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3009', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3010', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3011', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3012', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3013', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3014', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3015', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3016', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3017', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3018', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3019', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3020', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3021', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3022', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3023', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3024', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3025', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3026', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3027', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3028', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3029', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3030', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3031', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3032', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3033', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3034', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3035', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3036', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3037', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3038', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3039', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3040', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3041', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3042', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3043', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3044', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3045', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3046', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3047', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3048', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3049', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3050', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3051', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3052', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3053', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3054', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3055', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3056', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3057', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3058', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3059', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3060', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3061', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3062', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3063', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3064', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3065', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3066', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3067', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3068', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3069', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3070', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3071', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3072', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3073', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3074', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3075', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3076', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3077', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3078', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3079', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3080', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3081', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3082', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3083', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3084', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3085', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3086', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3087', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3088', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3089', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3090', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3091', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3092', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3093', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3094', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3095', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3096', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3097', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3098', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3099', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3100', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3101', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3102', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3103', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3104', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3105', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3106', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3107', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3108', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3109', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3110', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3111', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3112', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3113', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3114', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3115', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3116', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3117', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3118', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3119', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3120', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3121', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3122', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3123', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3124', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3125', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3126', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3127', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3128', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3129', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3130', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3131', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3132', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3133', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3134', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3135', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3136', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3137', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3138', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3139', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3140', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3141', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3142', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3143', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3144', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3145', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3146', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3147', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3148', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3149', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3150', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3151', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3152', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3153', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3154', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3155', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3156', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3157', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3158', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3159', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3160', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3161', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3162', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3163', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3164', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3165', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3166', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3167', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3168', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3169', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3170', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3171', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3172', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3173', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3174', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3175', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3176', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3177', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3178', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3179', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3180', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3181', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3182', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3183', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3184', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3185', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3186', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3187', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3188', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3189', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3190', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3191', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3192', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3193', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3194', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3195', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3196', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3197', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3198', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3199', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3200', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3201', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3202', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3203', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3204', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3205', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3206', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3207', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3208', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3209', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3210', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3212', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3213', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3214', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3215', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3216', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3217', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3218', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3219', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3220', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3221', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3222', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3223', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3224', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3225', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3226', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3227', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3228', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3229', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3230', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3231', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3232', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3233', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3234', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3235', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3236', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3237', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3238', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3239', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3240', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3241', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3242', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3243', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3244', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3245', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3246', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3247', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3248', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3249', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3250', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3251', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3252', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3253', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3254', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3255', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3256', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3257', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3258', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3259', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3260', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3261', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3262', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3263', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3264', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3265', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3266', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3267', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3268', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3269', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3270', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3271', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3272', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3273', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3274', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3275', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3276', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3277', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3278', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3279', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3280', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3281', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3282', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3283', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3284', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3285', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3286', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3287', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3288', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3289', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3290', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3291', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3292', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3293', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3294', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3295', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3296', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3297', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3298', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3299', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3351', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3352', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3353', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3354', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3355', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3356', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3357', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3358', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3359', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3360', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3361', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3362', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3363', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3364', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3365', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3366', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3367', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3368', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3369', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3370', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3371', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3372', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3373', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3374', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3375', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3376', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3377', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3378', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3379', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3380', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3381', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3382', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3383', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3384', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3385', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3386', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3387', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3388', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3389', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3390', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3391', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3392', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3393', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3394', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3395', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3396', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3397', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3398', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3399', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3400', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3401', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3402', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3403', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3404', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3405', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3406', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3407', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3408', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3409', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3410', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3411', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3412', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3413', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3414', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3415', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3416', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3417', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3418', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3419', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3420', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3421', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3422', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3423', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3424', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3425', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3426', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3427', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3428', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3429', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3430', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3431', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3432', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3433', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3434', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3435', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3436', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3437', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3438', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3439', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3440', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3441', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3501', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3502', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3503', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3504', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3505', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3506', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3507', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3508', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3509', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3510', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3511', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3512', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3513', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3514', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3515', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3516', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3517', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3518', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3519', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3520', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3521', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3522', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3523', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3524', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3525', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3526', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3527', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3528', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3529', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3530', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3531', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3532', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3533', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3534', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3535', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3536', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3537', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3538', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3539', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3540', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3541', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3542', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3543', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3544', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3545', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3546', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3547', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3548', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3549', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3550', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3551', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3552', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3553', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3554', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3555', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3556', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3557', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3558', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3559', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3560', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3561', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3562', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3563', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3564', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3565', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3566', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3567', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3568', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3569', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3570', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3571', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3572', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3573', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3574', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3575', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3576', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3577', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3578', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3579', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3580', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3581', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3582', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3583', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3584', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3585', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3586', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3587', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3588', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3589', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3590', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3591', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3592', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3593', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3594', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3595', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3596', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3597', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3598', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3599', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3600', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3601', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3602', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3603', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3604', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3605', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3606', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3607', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3608', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3609', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3610', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3611', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3612', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3613', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3614', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3615', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3616', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3617', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3618', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3619', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3620', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3621', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3622', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3623', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3624', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3625', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3626', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3627', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3628', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3629', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3630', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3631', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3632', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3633', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3634', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3635', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3636', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3637', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3638', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3639', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3640', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3641', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3642', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3643', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3644', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3645', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3646', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3647', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3648', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3649', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3650', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3651', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3652', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3653', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3654', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3655', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3656', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3657', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3658', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3659', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3660', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3661', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3662', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3663', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3664', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3665', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3666', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3667', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3668', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3669', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3670', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3671', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3672', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3673', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3674', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3675', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3676', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3677', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3678', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3679', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3680', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3681', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3682', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3683', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3684', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3685', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3686', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3687', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3688', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3689', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3690', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3691', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3692', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3693', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3694', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3695', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3696', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3697', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3698', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3699', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3700', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3701', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3702', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3703', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3704', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3705', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3706', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3707', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3708', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3709', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3710', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3711', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3712', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3713', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3714', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3715', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3716', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3717', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3718', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3719', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3720', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3721', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3722', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3723', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3724', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3725', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3726', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3727', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3728', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3729', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3730', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3731', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3732', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3733', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3734', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3735', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3736', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3737', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3738', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3739', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3740', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3741', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3742', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3743', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3744', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3745', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3746', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3747', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3748', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3749', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3750', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3751', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3752', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3753', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3754', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3755', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3756', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3757', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3758', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3759', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3760', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3761', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3762', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3763', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3764', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3765', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3766', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3767', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3768', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3769', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3770', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3771', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3772', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3773', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3774', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3775', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3776', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3777', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3778', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3779', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3780', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3781', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3782', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3783', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3784', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3785', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3786', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3787', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3788', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3789', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3790', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '3835', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4011', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4111', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4112', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4119', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4121', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4131', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4214', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4215', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4225', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4411', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4457', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4468', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4511', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4582', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4722', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4723', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4784', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4789', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4812', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4814', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4815', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4816', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4821', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4829', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4899', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '4900', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5013', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5021', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5039', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5044', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5045', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5046', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5047', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5051', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5065', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5072', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5074', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5085', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5094', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5099', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5111', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5122', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5131', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5137', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5139', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5169', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5172', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5192', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5193', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5198', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5199', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5200', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5231', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5251', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5261', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5271', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5300', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5309', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5310', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5311', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5331', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5399', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5411', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5422', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5441', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5451', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5462', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5499', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5511', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5521', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5531', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5532', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5533', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5541', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5542', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5551', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5561', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5571', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5592', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5598', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5599', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5611', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5621', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5631', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5641', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5651', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5655', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5661', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5681', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5691', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5697', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5698', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5699', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5712', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5713', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5714', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5718', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5719', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5722', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5732', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5733', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5734', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5735', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5811', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5812', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5813', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5814', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5832', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5912', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5921', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5931', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5932', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5933', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5935', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5937', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5940', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5941', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5942', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5943', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5944', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5945', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5946', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5947', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5948', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5949', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5950', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5960', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5961', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5962', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5963', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5964', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5965', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5966', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5967', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5968', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5969', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5970', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5971', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5972', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5973', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5975', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5976', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5977', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5978', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5983', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5992', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5993', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5994', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5995', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5996', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5997', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5998', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '5999', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6012', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6051', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6300', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6381', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6399', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '6513', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7011', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7012', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7032', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7033', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7210', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7216', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7217', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7221', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7230', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7251', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7261', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7273', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7276', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7277', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7278', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7296', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7297', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7298', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7299', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7311', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7321', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7332', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7333', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7338', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7339', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7342', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7349', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7361', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7372', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7375', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7379', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7392', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7393', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7394', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7395', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7399', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7511', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7512', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7513', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7519', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7523', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7531', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7534', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7535', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7538', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7542', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7549', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7622', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7623', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7629', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7631', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7641', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7692', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7699', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7829', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7832', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7841', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7911', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7922', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7929', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7932', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7933', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7941', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7991', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7992', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7993', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7994', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7995', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7996', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7997', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7998', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '7999', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8011', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8021', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8031', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8041', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8042', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8043', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8044', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8049', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8050', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8062', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8071', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8099', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8111', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8220', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8241', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8244', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8249', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8299', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8351', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8398', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8641', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8651', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8661', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8675', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8699', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8734', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8911', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8931', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '8999', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9211', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9222', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9223', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9311', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9399', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9402', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9405', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9700', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9701', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9702', 'active');
INSERT INTO `bind_purse_mcc` VALUES  (NULL, 12, '9950', 'active');


/*

NOTE: 
Need to add for purse_master = 12 for all rat purse_master = 2 ids

*/

DROP TABLE IF EXISTS `agent_import`;
CREATE TABLE `agent_import` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `application_form_no` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `middle_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `mobile2` varchar(255) DEFAULT NULL,
  `institution_name` varchar(255) DEFAULT NULL,
  `centre_id` varchar(255) DEFAULT NULL,
  `terminal_id_1` varchar(255) DEFAULT NULL,
  `terminal_id_2` varchar(255) DEFAULT NULL,
  `terminal_id_3` varchar(255) DEFAULT NULL,
  `education_level` varchar(255) DEFAULT NULL,
  `matric_school_name` varchar(255) DEFAULT NULL,
  `intermediate_school_name` varchar(255) DEFAULT NULL,
  `graduation_degree` varchar(255) DEFAULT NULL,
  `graduation_college` varchar(255) DEFAULT NULL,
  `post_graduation_degree` varchar(255) DEFAULT NULL,
  `post_graduation_college` varchar(255) DEFAULT NULL,
  `other_degree` varchar(255) DEFAULT NULL,
  `other_college` varchar(255) DEFAULT NULL,
  `date_of_birth` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `Identification_type` varchar(255) DEFAULT NULL,
  `Identification_number` varchar(255) DEFAULT NULL,
  `passport_expiry` varchar(255) DEFAULT NULL,
  `address_proof_type` varchar(255) DEFAULT NULL,
  `address_proof_number` varchar(255) DEFAULT NULL,
  `pan_number` varchar(255) DEFAULT NULL,
  `establishment_name` varchar(255) DEFAULT NULL,
  `establishment_address1` varchar(255) DEFAULT NULL,
  `establishment_address2` varchar(255) DEFAULT NULL,
  `establishment_city` varchar(255) DEFAULT NULL,
  `establishment_taluka` varchar(255) DEFAULT NULL,
  `establishment_district` varchar(255) DEFAULT NULL,
  `establishment_state` varchar(255) DEFAULT NULL,
  `establishment_country` varchar(255) DEFAULT NULL,
  `establishment_pincode` varchar(255) DEFAULT NULL,
  `residence_type` varchar(255) DEFAULT NULL,
  `residence_address1` varchar(255) DEFAULT NULL,
  `residence_address2` varchar(255) DEFAULT NULL,
  `residence_city` varchar(255) DEFAULT NULL,
  `residence_taluka` varchar(255) DEFAULT NULL,
  `residence_district` varchar(255) DEFAULT NULL,
  `residence_state` varchar(255) DEFAULT NULL,
  `residence_country` varchar(255) DEFAULT NULL,
  `residence_pincode` varchar(255) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `bank_account_number` varchar(255) DEFAULT NULL,
  `bank_location` varchar(255) DEFAULT NULL,
  `bank_city` varchar(255) DEFAULT NULL,
  `bank_ifsc_code` varchar(255) DEFAULT NULL,
  `Linked_branch_id` varchar(255) DEFAULT NULL,
  `bank_area` varchar(255) DEFAULT NULL,
  `import_status` enum('pending','complete','duplicate','failed') DEFAULT 'pending',
  `distributor_code` varchar(255) DEFAULT NULL,
  `failed_message` varchar(255) DEFAULT NULL,
  `agent_id` int(11) unsigned DEFAULT NULL,
  `distributor_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;


ALTER TABLE `agent_import` CHANGE `import_status` `import_status` ENUM('pending','complete','duplicate','failed','temp') NULL DEFAULT 'temp';


SET @flag_id := (SELECT id FROM `t_flags` where name ='operation-reports'); 
SET @ops_id = '3';

INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'beneregistration', @flag_id, 'Beneficiary Registration Report');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @ops_id, @flag_id, @priv_id, '1');


INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'exportbeneregistration', @flag_id, 'Export Beneficiary Registration Report');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @ops_id, @flag_id, @priv_id, '1');

INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'exportsearchagentimport', @flag_id, 'Export Search Agent Import');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @ops_id, @flag_id, @priv_id, '1'); 


SET @grp_id = '3';
SET @flag_id := (SELECT id FROM `t_flags` where name ='operation-agentfunding'); 
INSERT INTO `t_privileges` (`id`, `name`, `flag_id`, `description`) VALUES (NULL, 'uploadkotakbanktatement', @flag_id, 'Upload Kotak Bank Statement');
SET @priv_id = last_insert_id();
INSERT INTO `t_flippers` (`id`, `group_id`, `flag_id`, `privilege_id`, `allow`) VALUES (NULL, @grp_id, @flag_id, @priv_id, '1');