CREATE TABLE IF NOT EXISTS `kotak_corp_cardholders_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_customer_id` int(11) unsigned NOT NULL,
  `product_id` int(11) unsigned NOT NULL,
  `kotak_customer_id` int(11) unsigned NOT NULL,
  `customer_master_id` int(11) unsigned NOT NULL,
  `crn` bigint(20) unsigned NOT NULL,
  `unicode` varchar(16) NOT NULL,
  `card_number` varchar(16) NOT NULL,
  `card_pack_id` varchar(20) NOT NULL,
  `afn` varchar(10) NOT NULL,
  `member_id` varchar(10) NOT NULL,
  `employee_id` varchar(10) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) NOT NULL,
  `name_on_card` varchar(100) NOT NULL,
  `gender` enum('male','female') NOT NULL DEFAULT 'male',
  `date_of_birth` varchar(10) NOT NULL,
  `aadhaar_no` varchar(20) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `landline` varchar(15) DEFAULT NULL,
  `address_line1` varchar(50) NOT NULL,
  `address_line2` varchar(50) DEFAULT NULL,
  `city` varchar(50) NOT NULL,
  `state` varchar(50) NOT NULL,
  `pincode` int(10) NOT NULL,
  `mother_maiden_name` varchar(25) NOT NULL,
  `employer_name` varchar(50) NOT NULL,
  `corporate_id` varchar(16) NOT NULL,
  `comm_address_line1` varchar(50) DEFAULT NULL,
  `comm_address_line2` varchar(50) NOT NULL,
  `comm_city` varchar(50) NOT NULL,
  `comm_pin` int(10) NOT NULL,
  `comm_state` varchar(50) NOT NULL,
  `id_proof_type` varchar(30) NOT NULL,
  `id_proof_number` varchar(50) NOT NULL,
  `id_proof_doc_id` int(11) unsigned NOT NULL,
  `address_proof_type` varchar(30) NOT NULL,
  `address_proof_number` varchar(50) NOT NULL,
  `address_proof_doc_id` int(11) unsigned NOT NULL,
  `photo_doc_id` int(11) unsigned NOT NULL,
  `other_id_proof` varchar(255) DEFAULT NULL,
  `by_ops_id` int(11) NOT NULL,
  `by_agent_id` int(11) unsigned NOT NULL,
  `batch_id` int(11) unsigned NOT NULL,
  `batch_name` varchar(100) NOT NULL,
  `society_id` varchar(10) NOT NULL,
  `society_name` varchar(50) NOT NULL,
  `nominee_name` varchar(100) NOT NULL,
  `nominee_relationship` varchar(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `place_application` varchar(100) NOT NULL,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delivery_file_id` int(11) unsigned DEFAULT NULL,
  `date_activation` datetime NOT NULL,
  `failed_reason` varchar(200) NOT NULL,
  `date_failed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` enum('active','inactive','pending','ecs_failed') NOT NULL DEFAULT 'pending',
  `status_bank` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ops` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ecs` enum('pending','failure','success','waiting') NOT NULL DEFAULT 'waiting',
  `status_detail` enum('active','inactive') NOT NULL DEFAULT 'inactive',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `agent_funding`
ADD COLUMN `mode`  enum('cr','dr') NOT NULL DEFAULT 'cr' AFTER `amount`,
ADD COLUMN `txn_type`  char(4) NOT NULL DEFAULT 'AGFL' AFTER `mode`;