ALTER TABLE `t_agents` ADD `training_center_id` VARCHAR( 20 ) NOT NULL AFTER `parent_agent_id` ,
ADD `training_center_name` VARCHAR( 80 ) NOT NULL AFTER `training_center_id` ,
ADD `training_partner_name` VARCHAR( 80 ) NOT NULL AFTER `training_center_name` ,
ADD `debit_mandate_amount` VARCHAR( 10 ) NOT NULL AFTER `training_partner_name`;

--
-- Table structure for table `boi_corp_cardholders`
--

CREATE TABLE IF NOT EXISTS `boi_corp_cardholders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(11) unsigned NOT NULL,
  `boi_customer_id` int(11) unsigned NOT NULL,
  `customer_master_id` int(11) unsigned NOT NULL,
  `xls_boi_customer_id` varchar(16) NOT NULL,
  `nsdc_enrollment_no` varchar(16) NOT NULL,
  `sol_id` varchar(5) NOT NULL,
  `crn` bigint(20) unsigned NOT NULL,
  `unicode` varchar(16) NOT NULL,
  `card_number` varchar(16) NOT NULL,
  `card_pack_id` varchar(20) NOT NULL,
  `afn` varchar(10) NOT NULL,
  `member_id` varchar(10) NOT NULL,
  `employee_id` varchar(10) NOT NULL,
  `title` varchar(5) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) NOT NULL,
  `name_on_card` varchar(100) NOT NULL,
  `gender` enum('male','female') NOT NULL DEFAULT 'male',
  `date_of_birth` varchar(10) NOT NULL,
  `occupation` varchar(5) NOT NULL,
  `perm_country` varchar(2) NOT NULL DEFAULT 'IN',
  `aadhaar_no` varchar(20) NOT NULL,
  `pan` varchar(10) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `landline` varchar(15) DEFAULT NULL,
  `address_type` char(1) NOT NULL DEFAULT 'C',
  `address_line1` varchar(50) NOT NULL,
  `address_line2` varchar(50) DEFAULT NULL,
  `city` varchar(50) NOT NULL,
  `state` varchar(50) NOT NULL,
  `pincode` int(10) NOT NULL,
  `country_id` int(11) NOT NULL,
  `mother_maiden_name` varchar(25) NOT NULL,
  `employer_name` varchar(50) NOT NULL,
  `employer_address_line1` varchar(45) NOT NULL,
  `employer_address_line2` varchar(45) NOT NULL,
  `employer_address_city` varchar(20) NOT NULL,
  `employer_address_state` varchar(20) NOT NULL,
  `employer_address_country_id` int(5) NOT NULL,
  `employer_address_pincode` varchar(15) NOT NULL,
  `employer_contact_no` varchar(15) NOT NULL,
  `corporate_id` varchar(16) NOT NULL,
  `comm_address_line1` varchar(50) DEFAULT NULL,
  `comm_address_line2` varchar(50) NOT NULL,
  `comm_city` varchar(50) NOT NULL,
  `comm_pin` int(10) NOT NULL,
  `comm_state` varchar(50) NOT NULL,
  `comm_country_id` int(11) NOT NULL,
  `nre_flag` char(1) NOT NULL DEFAULT 'N',
  `nre_nationality` varchar(5) NOT NULL,
  `passport` varchar(12) NOT NULL,
  `passport_issue_date` date NOT NULL,
  `passport_expiry_date` date NOT NULL,
  `marital_status` char(1) NOT NULL,
  `cust_comm_code` char(1) NOT NULL,
  `other_bank_account_no` varchar(20) NOT NULL,
  `other_bank_account_type` varchar(20) NOT NULL,
  `other_bank_name` varchar(50) NOT NULL,
  `other_bank_branch` varchar(50) NOT NULL,
  `id_proof_type` varchar(30) NOT NULL,
  `id_proof_number` varchar(50) NOT NULL,
  `id_proof_doc_id` int(11) unsigned NOT NULL,
  `address_proof_type` varchar(30) NOT NULL,
  `address_proof_number` varchar(50) NOT NULL,
  `address_proof_doc_id` int(11) unsigned NOT NULL,
  `photo_doc_id` int(11) unsigned NOT NULL,
  `other_id_proof` varchar(255) DEFAULT NULL,
  `by_ops_id` int(11) NOT NULL,
  `by_agent_id` int(11) unsigned NOT NULL,
  `batch_id` int(11) unsigned NOT NULL,
  `batch_name` varchar(100) NOT NULL,
  `society_id` varchar(10) NOT NULL,
  `society_name` varchar(50) NOT NULL,
  `minor_flg` char(1) NOT NULL DEFAULT 'N',
  `minor_guardian_code` varchar(10) NOT NULL,
  `minor_guardian_name` varchar(80) NOT NULL,
  `minor_guardian_address_line1` varchar(45) NOT NULL,
  `minor_guardian_address_line2` varchar(45) NOT NULL,
  `minor_guardian_city` varchar(20) NOT NULL,
  `minor_guardian_state` varchar(20) NOT NULL,
  `minor_guardian_pincode` varchar(15) NOT NULL,
  `minor_guardian_country_id` int(5) NOT NULL,
  `mode_of_operation` varchar(3) NOT NULL DEFAULT '001',
  `nomination_flg` varchar(1) NOT NULL,
  `nominee_name` varchar(100) NOT NULL,
  `nominee_relationship` varchar(20) NOT NULL,
  `nominee_city_cd` varchar(5) NOT NULL,
  `nominee_minor_guradian_cd` varchar(5) NOT NULL,
  `nominee_dob` date NOT NULL,
  `nominee_minor_flag` char(1) NOT NULL,
  `amount_open` varchar(40) NOT NULL,
  `mode_of_payment_open` varchar(40) NOT NULL,
  `account_no` varchar(16) NOT NULL,
  `cust_id` varchar(9) NOT NULL,
  `sqlid` varchar(40) NOT NULL,
  `finacle_status` char(1) NOT NULL,
  `update_sql_status` char(1) NOT NULL,
  `staff_flg` char(1) NOT NULL DEFAULT 'N',
  `staff_no` varchar(20) NOT NULL,
  `minor_title_guradian_code` varchar(5) NOT NULL,
  `passport_details` varchar(25) NOT NULL,
  `introducer_title_code` varchar(5) NOT NULL,
  `introducer_code` varchar(40) NOT NULL,
  `introducer_name` varchar(80) NOT NULL,
  `existing_cust_flg` char(1) NOT NULL DEFAULT 'N',
  `account_currency_code` varchar(3) NOT NULL DEFAULT 'INR',
  `cust_id_ver_flg` char(1) NOT NULL,
  `account_id_ver_flg` char(1) NOT NULL,
  `schm_code` varchar(20) NOT NULL,
  `orgaization_type` varchar(5) NOT NULL,
  `introducer_flg` char(1) NOT NULL,
  `introducer_cust_id` varchar(9) NOT NULL,
  `cust_currency_code` varchar(3) NOT NULL DEFAULT 'INR',
  `account_type_id` varchar(10) NOT NULL,
  `ref_num` varchar(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `place_application` varchar(100) NOT NULL,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delivery_file_id` int(11) unsigned DEFAULT NULL,
  `date_activation` datetime NOT NULL,
  `failed_reason` varchar(200) NOT NULL,
  `date_failed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_crn_update` datetime DEFAULT NULL,
  `date_authorize` datetime DEFAULT NULL,
  `recd_doc` enum('yes','no') NOT NULL DEFAULT 'no',
  `date_recd_doc` date DEFAULT NULL,
  `recd_doc_id` int(11) unsigned NOT NULL,
  `date_approval` datetime DEFAULT NULL,
  `status` enum('active','inactive','pending','ecs_failed') NOT NULL DEFAULT 'pending',
  `status_bank` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ops` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ecs` enum('pending','failure','success','waiting') NOT NULL DEFAULT 'waiting',
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `boi_corp_cardholders_details`
--

CREATE TABLE IF NOT EXISTS `boi_corp_cardholders_details` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(11) unsigned NOT NULL,
  `boi_customer_id` int(11) unsigned NOT NULL,
  `customer_master_id` int(11) unsigned NOT NULL,
  `xls_boi_customer_id` varchar(16) NOT NULL,
  `nsdc_enrollment_no` varchar(16) NOT NULL,
  `sol_id` varchar(5) NOT NULL,
  `crn` bigint(20) unsigned NOT NULL,
  `unicode` varchar(16) NOT NULL,
  `card_number` varchar(16) NOT NULL,
  `card_pack_id` varchar(20) NOT NULL,
  `afn` varchar(10) NOT NULL,
  `member_id` varchar(10) NOT NULL,
  `employee_id` varchar(10) NOT NULL,
  `title` varchar(5) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) NOT NULL,
  `name_on_card` varchar(100) NOT NULL,
  `gender` enum('male','female') NOT NULL DEFAULT 'male',
  `date_of_birth` varchar(10) NOT NULL,
  `occupation` varchar(5) NOT NULL,
  `perm_country` varchar(2) NOT NULL DEFAULT 'IN',
  `aadhaar_no` varchar(20) NOT NULL,
  `pan` varchar(10) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `landline` varchar(15) DEFAULT NULL,
  `address_type` char(1) NOT NULL DEFAULT 'C',
  `address_line1` varchar(50) NOT NULL,
  `address_line2` varchar(50) DEFAULT NULL,
  `city` varchar(50) NOT NULL,
  `state` varchar(50) NOT NULL,
  `pincode` int(10) NOT NULL,
  `country_id` int(11) NOT NULL,
  `mother_maiden_name` varchar(25) NOT NULL,
  `employer_name` varchar(50) NOT NULL,
  `employer_address_line1` varchar(45) NOT NULL,
  `employer_address_line2` varchar(45) NOT NULL,
  `employer_address_city` varchar(20) NOT NULL,
  `employer_address_state` varchar(20) NOT NULL,
  `employer_address_country_id` int(5) NOT NULL,
  `employer_address_pincode` varchar(15) NOT NULL,
  `employer_contact_no` varchar(15) NOT NULL,
  `corporate_id` varchar(16) NOT NULL,
  `comm_address_line1` varchar(50) DEFAULT NULL,
  `comm_address_line2` varchar(50) NOT NULL,
  `comm_city` varchar(50) NOT NULL,
  `comm_pin` int(10) NOT NULL,
  `comm_state` varchar(50) NOT NULL,
  `comm_country_id` int(11) NOT NULL,
  `nre_flag` char(1) NOT NULL DEFAULT 'N',
  `nre_nationality` varchar(5) NOT NULL,
  `passport` varchar(12) NOT NULL,
  `passport_issue_date` date NOT NULL,
  `passport_expiry_date` date NOT NULL,
  `marital_status` char(1) NOT NULL,
  `cust_comm_code` char(1) NOT NULL,
  `other_bank_account_no` varchar(20) NOT NULL,
  `other_bank_account_type` varchar(20) NOT NULL,
  `other_bank_name` varchar(50) NOT NULL,
  `other_bank_branch` varchar(50) NOT NULL,
  `id_proof_type` varchar(30) NOT NULL,
  `id_proof_number` varchar(50) NOT NULL,
  `id_proof_doc_id` int(11) unsigned NOT NULL,
  `address_proof_type` varchar(30) NOT NULL,
  `address_proof_number` varchar(50) NOT NULL,
  `address_proof_doc_id` int(11) unsigned NOT NULL,
  `photo_doc_id` int(11) unsigned NOT NULL,
  `other_id_proof` varchar(255) DEFAULT NULL,
  `by_ops_id` int(11) NOT NULL,
  `by_agent_id` int(11) unsigned NOT NULL,
  `batch_id` int(11) unsigned NOT NULL,
  `batch_name` varchar(100) NOT NULL,
  `society_id` varchar(10) NOT NULL,
  `society_name` varchar(50) NOT NULL,
  `minor_flg` char(1) NOT NULL DEFAULT 'N',
  `minor_guardian_code` varchar(10) NOT NULL,
  `minor_guardian_name` varchar(80) NOT NULL,
  `minor_guardian_address_line1` varchar(45) NOT NULL,
  `minor_guardian_address_line2` varchar(45) NOT NULL,
  `minor_guardian_city` varchar(20) NOT NULL,
  `minor_guardian_state` varchar(20) NOT NULL,
  `minor_guardian_pincode` varchar(15) NOT NULL,
  `minor_guardian_country_id` int(5) NOT NULL,
  `mode_of_operation` varchar(3) NOT NULL DEFAULT '001',
  `nomination_flg` varchar(1) NOT NULL,
  `nominee_name` varchar(100) NOT NULL,
  `nominee_relationship` varchar(20) NOT NULL,
  `nominee_city_cd` varchar(5) NOT NULL,
  `nominee_minor_guradian_cd` varchar(5) NOT NULL,
  `nominee_dob` date NOT NULL,
  `nominee_minor_flag` char(1) NOT NULL,
  `amount_open` varchar(40) NOT NULL,
  `mode_of_payment_open` varchar(40) NOT NULL,
  `account_no` varchar(16) NOT NULL,
  `cust_id` varchar(9) NOT NULL,
  `sqlid` varchar(40) NOT NULL,
  `finacle_status` char(1) NOT NULL,
  `update_sql_status` char(1) NOT NULL,
  `staff_flg` char(1) NOT NULL DEFAULT 'N',
  `staff_no` varchar(20) NOT NULL,
  `minor_title_guradian_code` varchar(5) NOT NULL,
  `passport_details` varchar(25) NOT NULL,
  `introducer_title_code` varchar(5) NOT NULL,
  `introducer_code` varchar(40) NOT NULL,
  `introducer_name` varchar(80) NOT NULL,
  `existing_cust_flg` char(1) NOT NULL DEFAULT 'N',
  `account_currency_code` varchar(3) NOT NULL DEFAULT 'INR',
  `cust_id_ver_flg` char(1) NOT NULL,
  `account_id_ver_flg` char(1) NOT NULL,
  `schm_code` varchar(20) NOT NULL,
  `orgaization_type` varchar(5) NOT NULL,
  `introducer_flg` char(1) NOT NULL,
  `introducer_cust_id` varchar(9) NOT NULL,
  `cust_currency_code` varchar(3) NOT NULL DEFAULT 'INR',
  `account_type_id` varchar(10) NOT NULL,
  `ref_num` varchar(20) NOT NULL,
  `date_created` datetime NOT NULL,
  `place_application` varchar(100) NOT NULL,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `delivery_file_id` int(11) unsigned DEFAULT NULL,
  `date_activation` datetime NOT NULL,
  `failed_reason` varchar(200) NOT NULL,
  `date_failed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_crn_update` datetime DEFAULT NULL,
  `date_authorize` datetime DEFAULT NULL,
  `recd_doc` enum('yes','no') NOT NULL DEFAULT 'no',
  `date_recd_doc` date DEFAULT NULL,
  `recd_doc_id` int(11) unsigned NOT NULL,
  `date_approval` datetime DEFAULT NULL,
  `status` enum('active','inactive','pending','ecs_failed') NOT NULL DEFAULT 'pending',
  `status_bank` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ops` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `status_ecs` enum('pending','failure','success','waiting') NOT NULL DEFAULT 'waiting',
  `status_detail` enum('active','inactive') NOT NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1 ;
