
DROP TABLE IF EXISTS `bind_purse_mcc`;
CREATE TABLE `bind_purse_mcc` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `purse_master_id` int(11) unsigned NOT NULL,
  `mcc_code` varchar(10) NOT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `card_auth_request`;
CREATE TABLE `card_auth_request` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(11) unsigned NOT NULL,
  `customer_master_id` int(11) unsigned NOT NULL,
  `cardholder_id` int(11) unsigned NOT NULL,
  `purse_master_id` int(11) unsigned NOT NULL,
  `customer_purse_id` int(11) unsigned NOT NULL,
  `card_number` varchar(30) NOT NULL,
  `tid` varchar(20) NOT NULL,
  `mcc_code` varchar(10) NOT NULL,
  `mid` varchar(20) NOT NULL,
  `amount_txn` decimal(14,2) NOT NULL,
  `amount_billed` decimal(14,2) NOT NULL,
  `currency_iso` char(3) NOT NULL,
  `narration` varchar(50) NOT NULL,
  `txn_no` varchar(30) NOT NULL,
  `mode` enum('dr','cr') NOT NULL,
  `rev_indicator` enum('y','n') NOT NULL DEFAULT 'n',
  `original_txn_no` varchar(30) DEFAULT NULL,
  `txn_code` int(11) unsigned NOT NULL,
  `date_created` datetime DEFAULT NULL,
  `date_reversal` datetime NOT NULL,
  `date_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `failed_reason` varchar(200) DEFAULT NULL,
  `status` enum('pending','failed','reversal','completed','incomplete') NOT NULL DEFAULT 'pending',
  `response_code` varchar(10) DEFAULT NULL,
  `response_msg` varchar(50) DEFAULT NULL,
  `is_active` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `mcc_master`;
CREATE TABLE `mcc_master` (
  `mcc_code` varchar(10) NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `sub_category` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `mcc_master` (`mcc_code`, `category`, `sub_category`) VALUES
('742', 'Veterinary Services', 'Veterinary Services'),
('763', 'Agricultural Cooperative', 'Agricultural Co-operatives'),
('780', 'Landscaping Services', 'Horticultural Services, Landscaping Services'),
('1520', 'General Contractors', 'General Contractors-Residential and Commercial'),
('1711', 'Heating, Plumbing, A/C', 'Air Conditioning Contractors ? Sales and Installation, Heating Contractors ? Sales, Service, Install'),
('1731', 'Electrical Contractors', 'Electrical Contractors'),
('1740', 'Masonry, Stonework, and Plaster', 'Insulation ? Contractors, Masonry, Stonework Contractors, Plastering Contractors, Stonework and Maso'),
('1750', 'Carpentry Contractors', 'Carpentry Contractors'),
('1761', 'Roofing/Siding, Sheet Metal', 'Roofing ? Contractors, Sheet Metal Work ? Contractors, Siding ? Contractors'),
('1771', 'Concrete Work Contractors', 'Contractors ? Concrete Work'),
('1799', 'Special Trade Contractors', 'Contractors ? Special Trade, Not Elsewhere Classified'),
('2741', 'Miscellaneous Publishing and Printing', 'Miscellaneous Publishing and Printing'),
('2791', 'Typesetting, Plate Making, and Related Services', 'Typesetting, Plate Making, & Related Services'),
('2842', 'Specialty Cleaning', 'Specialty Cleaning, Polishing, and Sanitation Preparations'),
('3000', 'Airlines', 'UNITED AIRLINES'),
('3001', 'Airlines', 'AMERICAN AIRLINES'),
('3002', 'Airlines', 'PAN AMERICAN'),
('3003', 'Airlines', 'Airlines'),
('3004', 'Airlines', 'TRANS WORLD AIRLINES'),
('3005', 'Airlines', 'BRITISH AIRWAYS'),
('3006', 'Airlines', 'JAPAN AIRLINES'),
('3007', 'Airlines', 'AIR FRANCE'),
('3008', 'Airlines', 'LUFTHANSA'),
('3009', 'Airlines', 'AIR CANADA'),
('3010', 'Airlines', 'KLM (ROYAL DUTCH AIRLINES)'),
('3011', 'Airlines', 'AEORFLOT'),
('3012', 'Airlines', 'QUANTAS'),
('3013', 'Airlines', 'ALITALIA'),
('3014', 'Airlines', 'SAUDIA ARABIAN AIRLINES'),
('3015', 'Airlines', 'SWISSAIR'),
('3016', 'Airlines', 'SAS'),
('3017', 'Airlines', 'SOUTH AFRICAN AIRWAYS'),
('3018', 'Airlines', 'VARIG (BRAZIL)'),
('3019', 'Airlines', 'Airlines'),
('3020', 'Airlines', 'AIR-INDIA'),
('3021', 'Airlines', 'AIR ALGERIE'),
('3022', 'Airlines', 'PHILIPPINE AIRLINES'),
('3023', 'Airlines', 'MEXICANA'),
('3024', 'Airlines', 'PAKISTAN INTERNATIONAL'),
('3025', 'Airlines', 'AIR NEW ZEALAND'),
('3026', 'Airlines', 'Airlines'),
('3027', 'Airlines', 'UTA/INTERAIR'),
('3028', 'Airlines', 'AIR MALTA'),
('3029', 'Airlines', 'SABENA'),
('3030', 'Airlines', 'AEROLINEAS ARGENTINAS'),
('3031', 'Airlines', 'OLYMPIC AIRWAYS'),
('3032', 'Airlines', 'EL AL'),
('3033', 'Airlines', 'ANSETT AIRLINES'),
('3034', 'Airlines', 'AUSTRAINLIAN AIRLINES'),
('3035', 'Airlines', 'TAP (PORTUGAL)'),
('3036', 'Airlines', 'VASP (BRAZIL)'),
('3037', 'Airlines', 'EGYPTAIR'),
('3038', 'Airlines', 'KUWAIT AIRLINES'),
('3039', 'Airlines', 'AVIANCA'),
('3040', 'Airlines', 'GULF AIR (BAHRAIN)'),
('3041', 'Airlines', 'BALKAN-BULGARIAN AIRLINES'),
('3042', 'Airlines', 'FINNAIR'),
('3043', 'Airlines', 'AER LINGUS'),
('3044', 'Airlines', 'AIR LANKA'),
('3045', 'Airlines', 'NIGERIA AIRWAYS'),
('3046', 'Airlines', 'CRUZEIRO DO SUL (BRAZIJ)'),
('3047', 'Airlines', 'THY (TURKEY)'),
('3048', 'Airlines', 'ROYAL AIR MAROC'),
('3049', 'Airlines', 'TUNIS AIR'),
('3050', 'Airlines', 'ICELANDAIR'),
('3051', 'Airlines', 'AUSTRIAN AIRLINES'),
('3052', 'Airlines', 'LANCHILE'),
('3053', 'Airlines', 'AVIACO (SPAIN)'),
('3054', 'Airlines', 'LADECO (CHILE)'),
('3055', 'Airlines', 'LAB (BOLIVIA)'),
('3056', 'Airlines', 'QUEBECAIRE'),
('3057', 'Airlines', 'EASTWEST AIRLINES (AUSTRALIA)'),
('3058', 'Airlines', 'DELTA'),
('3059', 'Airlines', 'Airlines'),
('3060', 'Airlines', 'NORTHWEST'),
('3061', 'Airlines', 'CONTINENTAL'),
('3062', 'Airlines', 'WESTERN'),
('3063', 'Airlines', 'US AIR'),
('3064', 'Airlines', 'Airlines'),
('3065', 'Airlines', 'AIRINTER'),
('3066', 'Airlines', 'SOUTHWEST'),
('3067', 'Airlines', 'Airlines'),
('3068', 'Airlines', 'Airlines'),
('3069', 'Airlines', 'Airlines'),
('3070', 'Airlines', 'Airlines'),
('3071', 'Airlines', 'AIR BRITISH COLUBIA'),
('3072', 'Airlines', 'Airlines'),
('3073', 'Airlines', 'Airlines'),
('3074', 'Airlines', 'Airlines'),
('3075', 'Airlines', 'SINGAPORE AIRLINES'),
('3076', 'Airlines', 'AEROMEXICO'),
('3077', 'Airlines', 'THAI AIRWAYS'),
('3078', 'Airlines', 'CHINA AIRLINES'),
('3079', 'Airlines', 'Airlines'),
('3080', 'Airlines', 'Airlines'),
('3081', 'Airlines', 'NORDAIR'),
('3082', 'Airlines', 'KOREAN AIRLINES'),
('3083', 'Airlines', 'AIR AFRIGUE'),
('3084', 'Airlines', 'EVA AIRLINES'),
('3085', 'Airlines', 'MIDWEST EXPRESS AIRLINES, INC.'),
('3086', 'Airlines', 'Airlines'),
('3087', 'Airlines', 'METRO AIRLINES'),
('3088', 'Airlines', 'CROATIA AIRLINES'),
('3089', 'Airlines', 'TRANSAERO'),
('3090', 'Airlines', 'Airlines'),
('3091', 'Airlines', 'Airlines'),
('3092', 'Airlines', 'Airlines'),
('3093', 'Airlines', 'Airlines'),
('3094', 'Airlines', 'ZAMBIA AIRWAYS'),
('3095', 'Airlines', 'Airlines'),
('3096', 'Airlines', 'AIR ZIMBABWE'),
('3097', 'Airlines', 'Airlines'),
('3098', 'Airlines', 'Airlines'),
('3099', 'Airlines', 'CATHAY PACIFIC'),
('3100', 'Airlines', 'MALAYSIAN AIRLINE SYSTEM'),
('3101', 'Airlines', 'Airlines'),
('3102', 'Airlines', 'IBERIA'),
('3103', 'Airlines', 'GARUDA (INDONESIA)'),
('3104', 'Airlines', 'Airlines'),
('3105', 'Airlines', 'Airlines'),
('3106', 'Airlines', 'BRAATHENS S.A.F.E. (NORWAY)'),
('3107', 'Airlines', 'Airlines'),
('3108', 'Airlines', 'Airlines'),
('3109', 'Airlines', 'Airlines'),
('3110', 'Airlines', 'WINGS AIRWAYS'),
('3111', 'Airlines', 'BRITISH MIDLAND'),
('3112', 'Airlines', 'WINDWARD ISLAND'),
('3113', 'Airlines', 'Airlines'),
('3114', 'Airlines', 'Airlines'),
('3115', 'Airlines', 'Airlines'),
('3116', 'Airlines', 'Airlines'),
('3117', 'Airlines', 'VIASA'),
('3118', 'Airlines', 'VALLEY AIRLINES'),
('3119', 'Airlines', 'Airlines'),
('3120', 'Airlines', 'Airlines'),
('3121', 'Airlines', 'Airlines'),
('3122', 'Airlines', 'Airlines'),
('3123', 'Airlines', 'Airlines'),
('3124', 'Airlines', 'Airlines'),
('3125', 'Airlines', 'TAN'),
('3126', 'Airlines', 'TALAIR'),
('3127', 'Airlines', 'TACA INTERNATIONAL'),
('3128', 'Airlines', 'Airlines'),
('3129', 'Airlines', 'SURINAM AIRWAYS'),
('3130', 'Airlines', 'SUN WORLD INTERNATIONAL'),
('3131', 'Airlines', 'Airlines'),
('3132', 'Airlines', 'Airlines'),
('3133', 'Airlines', 'SUNBELT AIRLINES'),
('3134', 'Airlines', 'Airlines'),
('3135', 'Airlines', 'SUDAN AIRWAYS'),
('3136', 'Airlines', 'Airlines'),
('3137', 'Airlines', 'SINGLETON'),
('3138', 'Airlines', 'SIMMONS AIRLINES'),
('3139', 'Airlines', 'Airlines'),
('3140', 'Airlines', 'Airlines'),
('3141', 'Airlines', 'Airlines'),
('3142', 'Airlines', 'Airlines'),
('3143', 'Airlines', 'SCENIC AIRLINES'),
('3144', 'Airlines', 'VIRGIN ATLANTIC'),
('3145', 'Airlines', 'SAN JUAN AIRLINES'),
('3146', 'Airlines', 'LUXAIR'),
('3147', 'Airlines', 'Airlines'),
('3148', 'Airlines', 'Airlines'),
('3149', 'Airlines', 'Airlines'),
('3150', 'Airlines', 'Airlines'),
('3151', 'Airlines', 'AIR ZAIRE'),
('3152', 'Airlines', 'Airlines'),
('3153', 'Airlines', 'Airlines'),
('3154', 'Airlines', 'PRINCEVILLE'),
('3155', 'Airlines', 'Airlines'),
('3156', 'Airlines', 'Airlines'),
('3157', 'Airlines', 'Airlines'),
('3158', 'Airlines', 'Airlines'),
('3159', 'Airlines', 'PBA'),
('3160', 'Airlines', 'Airlines'),
('3161', 'Airlines', 'ALL NIPPON AIRWAYS'),
('3162', 'Airlines', 'Airlines'),
('3163', 'Airlines', 'Airlines'),
('3164', 'Airlines', 'NORONTAIR'),
('3165', 'Airlines', 'NEW YORK HELICOPTER'),
('3166', 'Airlines', 'Airlines'),
('3167', 'Airlines', 'Airlines'),
('3168', 'Airlines', 'Airlines'),
('3169', 'Airlines', 'Airlines'),
('3170', 'Airlines', 'NOUNT COOK'),
('3171', 'Airlines', 'CANADIAN AIRLINES INTERNATIONAL'),
('3172', 'Airlines', 'NATIONAIR'),
('3173', 'Airlines', 'Airlines'),
('3174', 'Airlines', 'Airlines'),
('3175', 'Airlines', 'Airlines'),
('3176', 'Airlines', 'METROFLIGHT AIRLINES'),
('3177', 'Airlines', 'Airlines'),
('3178', 'Airlines', 'MESA AIR'),
('3179', 'Airlines', 'Airlines'),
('3180', 'Airlines', 'Airlines'),
('3181', 'Airlines', 'MALEV'),
('3182', 'Airlines', 'LOT (POLAND)'),
('3183', 'Airlines', 'Airlines'),
('3184', 'Airlines', 'LIAT'),
('3185', 'Airlines', 'LAV (VENEZUELA)'),
('3186', 'Airlines', 'LAP (PARAGUAY)'),
('3187', 'Airlines', 'LACSA (COSTA RICA)'),
('3188', 'Airlines', 'Airlines'),
('3189', 'Airlines', 'Airlines'),
('3190', 'Airlines', 'JUGOSLAV AIR'),
('3191', 'Airlines', 'ISLAND AIRLINES'),
('3192', 'Airlines', 'IRAN AIR'),
('3193', 'Airlines', 'INDIAN AIRLINES'),
('3194', 'Airlines', 'Airlines'),
('3195', 'Airlines', 'Airlines'),
('3196', 'Airlines', 'HAWAIIAN AIR'),
('3197', 'Airlines', 'HAVASU AIRLINES'),
('3198', 'Airlines', 'Airlines'),
('3199', 'Airlines', 'Airlines'),
('3200', 'Airlines', 'FUYANA AIRWAYS'),
('3201', 'Airlines', 'Airlines'),
('3202', 'Airlines', 'Airlines'),
('3203', 'Airlines', 'GOLDEN PACIFIC AIR'),
('3204', 'Airlines', 'FREEDOM AIR'),
('3205', 'Airlines', 'Airlines'),
('3206', 'Airlines', 'Airlines'),
('3207', 'Airlines', 'Airlines'),
('3208', 'Airlines', 'Airlines'),
('3209', 'Airlines', 'Airlines'),
('3210', 'Airlines', 'Airlines'),
('3211', 'Airlines', 'Airlines'),
('3212', 'Airlines', 'DOMINICANA'),
('3213', 'Airlines', 'Airlines'),
('3214', 'Airlines', 'Airlines'),
('3215', 'Airlines', 'DAN AIR SERVICES'),
('3216', 'Airlines', 'CUMBERLAND AIRLINES'),
('3217', 'Airlines', 'CSA'),
('3218', 'Airlines', 'CROWN AIR'),
('3219', 'Airlines', 'COPA'),
('3220', 'Airlines', 'COMPANIA FAUCETT'),
('3221', 'Airlines', 'TRANSPORTES AEROS MILITARES ECCUATORANOS'),
('3222', 'Airlines', 'COMMAND AIRWAYS'),
('3223', 'Airlines', 'COMAIR'),
('3224', 'Airlines', 'Airlines'),
('3225', 'Airlines', 'Airlines'),
('3226', 'Airlines', 'Airlines'),
('3227', 'Airlines', 'Airlines'),
('3228', 'Airlines', 'CAYMAN AIRWAYS'),
('3229', 'Airlines', 'SAETA SOCIAEDAD ECUATORIANOS DE TRANSPORTES AEREOS'),
('3230', 'Airlines', 'Airlines'),
('3231', 'Airlines', 'SASHA SERVICIO AERO DE HONDURAS'),
('3232', 'Airlines', 'Airlines'),
('3233', 'Airlines', 'CAPITOL AIR'),
('3234', 'Airlines', 'BWIA'),
('3235', 'Airlines', 'BROKWAY AIR'),
('3236', 'Airlines', 'Airlines'),
('3237', 'Airlines', 'Airlines'),
('3238', 'Airlines', 'BEMIDJI AIRLINES'),
('3239', 'Airlines', 'BAR HARBOR AIRLINES'),
('3240', 'Airlines', 'BAHAMASAIR'),
('3241', 'Airlines', 'AVIATECA (GUATEMALA)'),
('3242', 'Airlines', 'AVENSA'),
('3243', 'Airlines', 'AUSTRIAN AIR SERVICE'),
('3244', 'Airlines', 'Airlines'),
('3245', 'Airlines', 'Airlines'),
('3246', 'Airlines', 'Airlines'),
('3247', 'Airlines', 'Airlines'),
('3248', 'Airlines', 'Airlines'),
('3249', 'Airlines', 'Airlines'),
('3250', 'Airlines', 'Airlines'),
('3251', 'Airlines', 'ALOHA AIRLINES'),
('3252', 'Airlines', 'ALM'),
('3253', 'Airlines', 'AMERICA WEST'),
('3254', 'Airlines', 'TRUMP AIRLINE'),
('3255', 'Airlines', 'Airlines'),
('3256', 'Airlines', 'ALASKA AIRLINES'),
('3257', 'Airlines', 'Airlines'),
('3258', 'Airlines', 'Airlines'),
('3259', 'Airlines', 'AMERICAN TRANS AIR'),
('3260', 'Airlines', 'Airlines'),
('3261', 'Airlines', 'AIR CHINA'),
('3262', 'Airlines', 'RENO AIR, INC.'),
('3263', 'Airlines', 'Airlines'),
('3264', 'Airlines', 'Airlines'),
('3265', 'Airlines', 'Airlines'),
('3266', 'Airlines', 'AIR SEYCHELLES'),
('3267', 'Airlines', 'AIR PANAMA'),
('3268', 'Airlines', 'Airlines'),
('3269', 'Airlines', 'Airlines'),
('3270', 'Airlines', 'Airlines'),
('3271', 'Airlines', 'Airlines'),
('3272', 'Airlines', 'Airlines'),
('3273', 'Airlines', 'Airlines'),
('3274', 'Airlines', 'Airlines'),
('3275', 'Airlines', 'Airlines'),
('3276', 'Airlines', 'Airlines'),
('3277', 'Airlines', 'Airlines'),
('3278', 'Airlines', 'Airlines'),
('3279', 'Airlines', 'Airlines'),
('3280', 'Airlines', 'AIR JAMAICA'),
('3281', 'Airlines', 'Airlines'),
('3282', 'Airlines', 'AIR DJIBOUTI'),
('3283', 'Airlines', 'Airlines'),
('3284', 'Airlines', 'AERO VIRGIN ISLANDS'),
('3285', 'Airlines', 'AERO PERU'),
('3286', 'Airlines', 'AEROLINEAS NICARAGUENSIS'),
('3287', 'Airlines', 'AERO COACH AVAIATION'),
('3288', 'Airlines', 'Airlines'),
('3289', 'Airlines', 'Airlines'),
('3290', 'Airlines', 'Airlines'),
('3291', 'Airlines', 'ARIANA AFGHAN'),
('3292', 'Airlines', 'CYPRUS AIRWAYS'),
('3293', 'Airlines', 'ECUATORIANA'),
('3294', 'Airlines', 'ETHIOPIAN AIRLINES'),
('3295', 'Airlines', 'KENYA AIRLINES'),
('3296', 'Airlines', 'Airlines'),
('3297', 'Airlines', 'Airlines'),
('3298', 'Airlines', 'AIR MAURITIUS'),
('3299', 'Airlines', 'WIDERO?S FLYVESELSKAP'),
('3351', 'Car Rental', 'AFFILIATED AUTO RENTAL'),
('3352', 'Car Rental', 'AMERICAN INTL RENT-A-CAR'),
('3353', 'Car Rental', 'BROOKS RENT-A-CAR'),
('3354', 'Car Rental', 'ACTION AUTO RENTAL'),
('3355', 'Car Rental', 'Car Rental'),
('3356', 'Car Rental', 'Car Rental'),
('3357', 'Car Rental', 'HERTZ RENT-A-CAR'),
('3358', 'Car Rental', 'Car Rental'),
('3359', 'Car Rental', 'PAYLESS CAR RENTAL'),
('3360', 'Car Rental', 'SNAPPY CAR RENTAL'),
('3361', 'Car Rental', 'AIRWAYS RENT-A-CAR'),
('3362', 'Car Rental', 'ALTRA AUTO RENTAL'),
('3363', 'Car Rental', 'Car Rental'),
('3364', 'Car Rental', 'AGENCY RENT-A-CAR'),
('3365', 'Car Rental', 'Car Rental'),
('3366', 'Car Rental', 'BUDGET RENT-A-CAR'),
('3367', 'Car Rental', 'Car Rental'),
('3368', 'Car Rental', 'HOLIDAY RENT-A-WRECK'),
('3369', 'Car Rental', 'Car Rental'),
('3370', 'Car Rental', 'RENT-A-WRECK'),
('3371', 'Car Rental', 'Car Rental'),
('3372', 'Car Rental', 'Car Rental'),
('3373', 'Car Rental', 'Car Rental'),
('3374', 'Car Rental', 'Car Rental'),
('3375', 'Car Rental', 'Car Rental'),
('3376', 'Car Rental', 'AJAX RENT-A-CAR'),
('3377', 'Car Rental', 'Car Rental'),
('3378', 'Car Rental', 'Car Rental'),
('3379', 'Car Rental', 'Car Rental'),
('3380', 'Car Rental', 'Car Rental'),
('3381', 'Car Rental', 'EUROP CAR'),
('3382', 'Car Rental', 'Car Rental'),
('3383', 'Car Rental', 'Car Rental'),
('3384', 'Car Rental', 'Car Rental'),
('3385', 'Car Rental', 'TROPICAL RENT-A-CAR'),
('3386', 'Car Rental', 'SHOWCASE RENTAL CARS'),
('3387', 'Car Rental', 'ALAMO RENT-A-CAR'),
('3388', 'Car Rental', 'Car Rental'),
('3389', 'Car Rental', 'AVIS RENT-A-CAR'),
('3390', 'Car Rental', 'DOLLAR RENT-A-CAR'),
('3391', 'Car Rental', 'EUROPE BY CAR'),
('3392', 'Car Rental', 'Car Rental'),
('3393', 'Car Rental', 'NATIONAL CAR RENTAL'),
('3394', 'Car Rental', 'KEMWELL GROUP RENT-A-CAR'),
('3395', 'Car Rental', 'THRIFTY RENT-A-CAR'),
('3396', 'Car Rental', 'TILDEN TENT-A-CAR'),
('3397', 'Car Rental', 'Car Rental'),
('3398', 'Car Rental', 'ECONO-CAR RENT-A-CAR'),
('3399', 'Car Rental', 'Car Rental'),
('3400', 'Car Rental', 'AUTO HOST COST CAR RENTALS'),
('3401', 'Car Rental', 'Car Rental'),
('3402', 'Car Rental', 'Car Rental'),
('3403', 'Car Rental', 'Car Rental'),
('3404', 'Car Rental', 'Car Rental'),
('3405', 'Car Rental', 'ENTERPRISE RENT-A-CAR'),
('3406', 'Car Rental', 'Car Rental'),
('3407', 'Car Rental', 'Car Rental'),
('3408', 'Car Rental', 'Car Rental'),
('3409', 'Car Rental', 'GENERAL RENT-A-CAR'),
('3410', 'Car Rental', 'Car Rental'),
('3411', 'Car Rental', 'Car Rental'),
('3412', 'Car Rental', 'A-1 RENT-A-CAR'),
('3413', 'Car Rental', 'Car Rental'),
('3414', 'Car Rental', 'GODFREY NATL RENT-A-CAR'),
('3415', 'Car Rental', 'Car Rental'),
('3416', 'Car Rental', 'Car Rental'),
('3417', 'Car Rental', 'Car Rental'),
('3418', 'Car Rental', 'Car Rental'),
('3419', 'Car Rental', 'ALPHA RENT-A-CAR'),
('3420', 'Car Rental', 'ANSA INTL RENT-A-CAR'),
('3421', 'Car Rental', 'ALLSTAE RENT-A-CAR'),
('3422', 'Car Rental', 'Car Rental'),
('3423', 'Car Rental', 'AVCAR RENT-A-CAR'),
('3424', 'Car Rental', 'Car Rental'),
('3425', 'Car Rental', 'AUTOMATE RENT-A-CAR'),
('3426', 'Car Rental', 'Car Rental'),
('3427', 'Car Rental', 'AVON RENT-A-CAR'),
('3428', 'Car Rental', 'CAREY RENT-A-CAR'),
('3429', 'Car Rental', 'INSURANCE RENT-A-CAR'),
('3430', 'Car Rental', 'MAJOR RENT-A-CAR'),
('3431', 'Car Rental', 'REPLACEMENT RENT-A-CAR'),
('3432', 'Car Rental', 'RESERVE RENT-A-CAR'),
('3433', 'Car Rental', 'UGLY DUCKLING RENT-A-CAR'),
('3434', 'Car Rental', 'USA RENT-A-CAR'),
('3435', 'Car Rental', 'VALUE RENT-A-CAR'),
('3436', 'Car Rental', 'AUTOHANSA RENT-A-CAR'),
('3437', 'Car Rental', 'CITE RENT-A-CAR'),
('3438', 'Car Rental', 'INTERENT RENT-A-CAR'),
('3439', 'Car Rental', 'MILLEVILLE RENT-A-CAR'),
('3440', 'Car Rental', 'VIA ROUTE RENT-A-CAR'),
('3441', 'Car Rental', 'Car Rental'),
('3501', 'Hotels/Motels/Inns/Resorts', 'HOLIDAY INNS, HOLIDAY INN EXPRESS'),
('3502', 'Hotels/Motels/Inns/Resorts', 'BEST WESTERN HOTELS'),
('3503', 'Hotels/Motels/Inns/Resorts', 'SHERATON HOTELS'),
('3504', 'Hotels/Motels/Inns/Resorts', 'HILTON HOTELS'),
('3505', 'Hotels/Motels/Inns/Resorts', 'FORTE HOTELS'),
('3506', 'Hotels/Motels/Inns/Resorts', 'GOLDEN TULIP HOTELS'),
('3507', 'Hotels/Motels/Inns/Resorts', 'FRIENDSHIP INNS'),
('3508', 'Hotels/Motels/Inns/Resorts', 'QUALITY INNS, QUALITY SUITES'),
('3509', 'Hotels/Motels/Inns/Resorts', 'MARRIOTT HOTELS'),
('3510', 'Hotels/Motels/Inns/Resorts', 'DAYS INN, DAYSTOP'),
('3511', 'Hotels/Motels/Inns/Resorts', 'ARABELLA HOTELS'),
('3512', 'Hotels/Motels/Inns/Resorts', 'INTER-CONTINENTAL HOTELS'),
('3513', 'Hotels/Motels/Inns/Resorts', 'WESTIN HOTELS'),
('3514', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3515', 'Hotels/Motels/Inns/Resorts', 'RODEWAY INNS'),
('3516', 'Hotels/Motels/Inns/Resorts', 'LA QUINTA MOTOR INNS'),
('3517', 'Hotels/Motels/Inns/Resorts', 'AMERICANA HOTELS'),
('3518', 'Hotels/Motels/Inns/Resorts', 'SOL HOTELS'),
('3519', 'Hotels/Motels/Inns/Resorts', 'PULLMAN INTERNATIONAL HOTELS'),
('3520', 'Hotels/Motels/Inns/Resorts', 'MERIDIEN HOTELS'),
('3521', 'Hotels/Motels/Inns/Resorts', 'CREST HOTELS (see FORTE HOTELS)'),
('3522', 'Hotels/Motels/Inns/Resorts', 'TOKYO HOTEL'),
('3523', 'Hotels/Motels/Inns/Resorts', 'PENNSULA HOTEL'),
('3524', 'Hotels/Motels/Inns/Resorts', 'WELCOMGROUP HOTELS'),
('3525', 'Hotels/Motels/Inns/Resorts', 'DUNFEY HOTELS'),
('3526', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3527', 'Hotels/Motels/Inns/Resorts', 'DOWNTOWNER-PASSPORT HOTEL'),
('3528', 'Hotels/Motels/Inns/Resorts', 'RED LION HOTELS, RED LION INNS'),
('3529', 'Hotels/Motels/Inns/Resorts', 'CP HOTELS'),
('3530', 'Hotels/Motels/Inns/Resorts', 'RENAISSANCE HOTELS, STOUFFER HOTELS'),
('3531', 'Hotels/Motels/Inns/Resorts', 'ASTIR HOTELS'),
('3532', 'Hotels/Motels/Inns/Resorts', 'SUN ROUTE HOTELS'),
('3533', 'Hotels/Motels/Inns/Resorts', 'HOTEL IBIS'),
('3534', 'Hotels/Motels/Inns/Resorts', 'SOUTHERN PACIFIC HOTELS'),
('3535', 'Hotels/Motels/Inns/Resorts', 'HILTON INTERNATIONAL'),
('3536', 'Hotels/Motels/Inns/Resorts', 'AMFAC HOTELS'),
('3537', 'Hotels/Motels/Inns/Resorts', 'ANA HOTEL'),
('3538', 'Hotels/Motels/Inns/Resorts', 'CONCORDE HOTELS'),
('3539', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3540', 'Hotels/Motels/Inns/Resorts', 'IBEROTEL HOTELS'),
('3541', 'Hotels/Motels/Inns/Resorts', 'HOTEL OKURA'),
('3542', 'Hotels/Motels/Inns/Resorts', 'ROYAL HOTELS'),
('3543', 'Hotels/Motels/Inns/Resorts', 'FOUR SEASONS HOTELS'),
('3544', 'Hotels/Motels/Inns/Resorts', 'CIGA HOTELS'),
('3545', 'Hotels/Motels/Inns/Resorts', 'SHANGRI-LA INTERNATIONAL'),
('3546', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3547', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3548', 'Hotels/Motels/Inns/Resorts', 'HOTELES MELIA'),
('3549', 'Hotels/Motels/Inns/Resorts', 'AUBERGE DES GOVERNEURS'),
('3550', 'Hotels/Motels/Inns/Resorts', 'REGAL 8 INNS'),
('3551', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3552', 'Hotels/Motels/Inns/Resorts', 'COAST HOTELS'),
('3553', 'Hotels/Motels/Inns/Resorts', 'PARK INNS INTERNATIONAL'),
('3554', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3555', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3556', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3557', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3558', 'Hotels/Motels/Inns/Resorts', 'JOLLY HOTELS'),
('3559', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3560', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3561', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3562', 'Hotels/Motels/Inns/Resorts', 'COMFORT INNS'),
('3563', 'Hotels/Motels/Inns/Resorts', 'JOURNEY?S END MOTLS'),
('3564', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3565', 'Hotels/Motels/Inns/Resorts', 'RELAX INNS'),
('3566', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3567', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3568', 'Hotels/Motels/Inns/Resorts', 'LADBROKE HOTELS'),
('3569', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3570', 'Hotels/Motels/Inns/Resorts', 'FORUM HOTELS'),
('3571', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3572', 'Hotels/Motels/Inns/Resorts', 'MIYAKO HOTELS'),
('3573', 'Hotels/Motels/Inns/Resorts', 'SANDMAN HOTELS'),
('3574', 'Hotels/Motels/Inns/Resorts', 'VENTURE INNS'),
('3575', 'Hotels/Motels/Inns/Resorts', 'VAGABOND HOTELS'),
('3576', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3577', 'Hotels/Motels/Inns/Resorts', 'MANDARIN ORIENTAL HOTEL'),
('3578', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3579', 'Hotels/Motels/Inns/Resorts', 'HOTEL MERCURE'),
('3580', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3581', 'Hotels/Motels/Inns/Resorts', 'DELTA HOTEL'),
('3582', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3583', 'Hotels/Motels/Inns/Resorts', 'SAS HOTELS'),
('3584', 'Hotels/Motels/Inns/Resorts', 'PRINCESS HOTELS INTERNATIONAL'),
('3585', 'Hotels/Motels/Inns/Resorts', 'HUNGAR HOTELS'),
('3586', 'Hotels/Motels/Inns/Resorts', 'SOKOS HOTELS'),
('3587', 'Hotels/Motels/Inns/Resorts', 'DORAL HOTELS'),
('3588', 'Hotels/Motels/Inns/Resorts', 'HELMSLEY HOTELS'),
('3589', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3590', 'Hotels/Motels/Inns/Resorts', 'FAIRMONT HOTELS'),
('3591', 'Hotels/Motels/Inns/Resorts', 'SONESTA HOTELS'),
('3592', 'Hotels/Motels/Inns/Resorts', 'OMNI HOTELS'),
('3593', 'Hotels/Motels/Inns/Resorts', 'CUNARD HOTELS'),
('3594', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3595', 'Hotels/Motels/Inns/Resorts', 'HOSPITALITY INTERNATIONAL'),
('3596', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3597', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3598', 'Hotels/Motels/Inns/Resorts', 'REGENT INTERNATIONAL HOTELS'),
('3599', 'Hotels/Motels/Inns/Resorts', 'PANNONIA HOTELS'),
('3600', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3601', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3602', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3603', 'Hotels/Motels/Inns/Resorts', 'NOAH?S HOTELS'),
('3604', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3605', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3606', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3607', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3608', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3609', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3610', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3611', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3612', 'Hotels/Motels/Inns/Resorts', 'MOVENPICK HOTELS'),
('3613', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3614', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3615', 'Hotels/Motels/Inns/Resorts', 'TRAVELODGE'),
('3616', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3617', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3618', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3619', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3620', 'Hotels/Motels/Inns/Resorts', 'TELFORD INTERNATIONAL'),
('3621', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3622', 'Hotels/Motels/Inns/Resorts', 'MERLIN HOTELS'),
('3623', 'Hotels/Motels/Inns/Resorts', 'DORINT HOTELS'),
('3624', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3625', 'Hotels/Motels/Inns/Resorts', 'HOTLE UNIVERSALE'),
('3626', 'Hotels/Motels/Inns/Resorts', 'PRINCE HOTELS'),
('3627', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3628', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3629', 'Hotels/Motels/Inns/Resorts', 'DAN HOTELS'),
('3630', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3631', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3632', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3633', 'Hotels/Motels/Inns/Resorts', 'RANK HOTELS'),
('3634', 'Hotels/Motels/Inns/Resorts', 'SWISSOTEL'),
('3635', 'Hotels/Motels/Inns/Resorts', 'RESO HOTELS'),
('3636', 'Hotels/Motels/Inns/Resorts', 'SAROVA HOTELS'),
('3637', 'Hotels/Motels/Inns/Resorts', 'RAMADA INNS, RAMADA LIMITED'),
('3638', 'Hotels/Motels/Inns/Resorts', 'HO JO INN, HOWARD JOHNSON'),
('3639', 'Hotels/Motels/Inns/Resorts', 'MOUNT CHARLOTTE THISTLE'),
('3640', 'Hotels/Motels/Inns/Resorts', 'HYATT HOTEL'),
('3641', 'Hotels/Motels/Inns/Resorts', 'SOFITEL HOTELS'),
('3642', 'Hotels/Motels/Inns/Resorts', 'NOVOTEL HOTELS'),
('3643', 'Hotels/Motels/Inns/Resorts', 'STEIGENBERGER HOTELS'),
('3644', 'Hotels/Motels/Inns/Resorts', 'ECONO LODGES'),
('3645', 'Hotels/Motels/Inns/Resorts', 'QUEENS MOAT HOUSES'),
('3646', 'Hotels/Motels/Inns/Resorts', 'SWALLOW HOTELS'),
('3647', 'Hotels/Motels/Inns/Resorts', 'HUSA HOTELS'),
('3648', 'Hotels/Motels/Inns/Resorts', 'DE VERE HOTELS'),
('3649', 'Hotels/Motels/Inns/Resorts', 'RADISSON HOTELS'),
('3650', 'Hotels/Motels/Inns/Resorts', 'RED ROOK INNS'),
('3651', 'Hotels/Motels/Inns/Resorts', 'IMPERIAL LONDON HOTEL'),
('3652', 'Hotels/Motels/Inns/Resorts', 'EMBASSY HOTELS'),
('3653', 'Hotels/Motels/Inns/Resorts', 'PENTA HOTELS'),
('3654', 'Hotels/Motels/Inns/Resorts', 'LOEWS HOTELS'),
('3655', 'Hotels/Motels/Inns/Resorts', 'SCANDIC HOTELS'),
('3656', 'Hotels/Motels/Inns/Resorts', 'SARA HOTELS'),
('3657', 'Hotels/Motels/Inns/Resorts', 'OBEROI HOTELS'),
('3658', 'Hotels/Motels/Inns/Resorts', 'OTANI HOTELS'),
('3659', 'Hotels/Motels/Inns/Resorts', 'TAJ HOTELS INTERNATIONAL'),
('3660', 'Hotels/Motels/Inns/Resorts', 'KNIGHTS INNS'),
('3661', 'Hotels/Motels/Inns/Resorts', 'METROPOLE HOTELS'),
('3662', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3663', 'Hotels/Motels/Inns/Resorts', 'HOTELES EL PRESIDENTS'),
('3664', 'Hotels/Motels/Inns/Resorts', 'FLAG INN'),
('3665', 'Hotels/Motels/Inns/Resorts', 'HAMPTON INNS'),
('3666', 'Hotels/Motels/Inns/Resorts', 'STAKIS HOTELS'),
('3667', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3668', 'Hotels/Motels/Inns/Resorts', 'MARITIM HOTELS'),
('3669', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3670', 'Hotels/Motels/Inns/Resorts', 'ARCARD HOTELS'),
('3671', 'Hotels/Motels/Inns/Resorts', 'ARCTIA HOTELS'),
('3672', 'Hotels/Motels/Inns/Resorts', 'CAMPANIEL HOTELS'),
('3673', 'Hotels/Motels/Inns/Resorts', 'IBUSZ HOTELS'),
('3674', 'Hotels/Motels/Inns/Resorts', 'RANTASIPI HOTELS'),
('3675', 'Hotels/Motels/Inns/Resorts', 'INTERHOTEL CEDOK'),
('3676', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3677', 'Hotels/Motels/Inns/Resorts', 'CLIMAT DE FRANCE HOTELS'),
('3678', 'Hotels/Motels/Inns/Resorts', 'CUMULUS HOTELS'),
('3679', 'Hotels/Motels/Inns/Resorts', 'DANUBIUS HOTEL'),
('3680', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3681', 'Hotels/Motels/Inns/Resorts', 'ADAMS MARK HOTELS'),
('3682', 'Hotels/Motels/Inns/Resorts', 'ALLSTAR INNS'),
('3683', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3684', 'Hotels/Motels/Inns/Resorts', 'BUDGET HOST INNS'),
('3685', 'Hotels/Motels/Inns/Resorts', 'BUDGETEL HOTELS'),
('3686', 'Hotels/Motels/Inns/Resorts', 'SUISSE CHALETS'),
('3687', 'Hotels/Motels/Inns/Resorts', 'CLARION HOTELS'),
('3688', 'Hotels/Motels/Inns/Resorts', 'COMPRI HOTELS'),
('3689', 'Hotels/Motels/Inns/Resorts', 'CONSORT HOTELS'),
('3690', 'Hotels/Motels/Inns/Resorts', 'COURTYARD BY MARRIOTT'),
('3691', 'Hotels/Motels/Inns/Resorts', 'DILLION INNS'),
('3692', 'Hotels/Motels/Inns/Resorts', 'DOUBLETREE HOTELS'),
('3693', 'Hotels/Motels/Inns/Resorts', 'DRURY INNS'),
('3694', 'Hotels/Motels/Inns/Resorts', 'ECONOMY INNS OF AMERICA'),
('3695', 'Hotels/Motels/Inns/Resorts', 'EMBASSY SUITES'),
('3696', 'Hotels/Motels/Inns/Resorts', 'EXEL INNS'),
('3697', 'Hotels/Motels/Inns/Resorts', 'FARFIELD HOTELS'),
('3698', 'Hotels/Motels/Inns/Resorts', 'HARLEY HOTELS'),
('3699', 'Hotels/Motels/Inns/Resorts', 'MIDWAY MOTOR LODGE'),
('3700', 'Hotels/Motels/Inns/Resorts', 'MOTEL 6'),
('3701', 'Hotels/Motels/Inns/Resorts', 'GUEST QUARTERS (Formally PICKETT SUITE HOTELS)'),
('3702', 'Hotels/Motels/Inns/Resorts', 'THE REGISTRY HOTELS'),
('3703', 'Hotels/Motels/Inns/Resorts', 'RESIDENCE INNS'),
('3704', 'Hotels/Motels/Inns/Resorts', 'ROYCE HOTELS'),
('3705', 'Hotels/Motels/Inns/Resorts', 'SANDMAN INNS'),
('3706', 'Hotels/Motels/Inns/Resorts', 'SHILO INNS'),
('3707', 'Hotels/Motels/Inns/Resorts', 'SHONEY?S INNS'),
('3708', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3709', 'Hotels/Motels/Inns/Resorts', 'SUPER8 MOTELS'),
('3710', 'Hotels/Motels/Inns/Resorts', 'THE RITZ CARLTON HOTELS'),
('3711', 'Hotels/Motels/Inns/Resorts', 'FLAG INNS (AUSRALIA)'),
('3712', 'Hotels/Motels/Inns/Resorts', 'GOLDEN CHAIN HOTEL'),
('3713', 'Hotels/Motels/Inns/Resorts', 'QUALITY PACIFIC HOTEL'),
('3714', 'Hotels/Motels/Inns/Resorts', 'FOUR SEASONS HOTEL (AUSTRALIA)'),
('3715', 'Hotels/Motels/Inns/Resorts', 'FARIFIELD INN'),
('3716', 'Hotels/Motels/Inns/Resorts', 'CARLTON HOTELS'),
('3717', 'Hotels/Motels/Inns/Resorts', 'CITY LODGE HOTELS'),
('3718', 'Hotels/Motels/Inns/Resorts', 'KAROS HOTELS'),
('3719', 'Hotels/Motels/Inns/Resorts', 'PROTEA HOTELS'),
('3720', 'Hotels/Motels/Inns/Resorts', 'SOUTHERN SUN HOTELS'),
('3721', 'Hotels/Motels/Inns/Resorts', 'HILTON CONRAD'),
('3722', 'Hotels/Motels/Inns/Resorts', 'WYNDHAM HOTEL AND RESORTS'),
('3723', 'Hotels/Motels/Inns/Resorts', 'RICA HOTELS'),
('3724', 'Hotels/Motels/Inns/Resorts', 'INER NOR HOTELS'),
('3725', 'Hotels/Motels/Inns/Resorts', 'SEAINES PLANATION'),
('3726', 'Hotels/Motels/Inns/Resorts', 'RIO SUITES'),
('3727', 'Hotels/Motels/Inns/Resorts', 'BROADMOOR HOTEL'),
('3728', 'Hotels/Motels/Inns/Resorts', 'BALLY?S HOTEL AND CASINO'),
('3729', 'Hotels/Motels/Inns/Resorts', 'JOHN ASCUAGA?S NUGGET'),
('3730', 'Hotels/Motels/Inns/Resorts', 'MGM GRAND HOTEL'),
('3731', 'Hotels/Motels/Inns/Resorts', 'HARRAH?S HOTELS AND CASINOS'),
('3732', 'Hotels/Motels/Inns/Resorts', 'OPRYLAND HOTEL'),
('3733', 'Hotels/Motels/Inns/Resorts', 'BOCA RATON RESORT'),
('3734', 'Hotels/Motels/Inns/Resorts', 'HARVEY/BRISTOL HOTELS'),
('3735', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3736', 'Hotels/Motels/Inns/Resorts', 'COLORADO BELLE/EDGEWATER RESORT'),
('3737', 'Hotels/Motels/Inns/Resorts', 'RIVIERA HOTEL AND CASINO'),
('3738', 'Hotels/Motels/Inns/Resorts', 'TROPICANA RESORT AND CASINO'),
('3739', 'Hotels/Motels/Inns/Resorts', 'WOODSIDE HOTELS AND RESORTS'),
('3740', 'Hotels/Motels/Inns/Resorts', 'TOWNPLACE SUITES'),
('3741', 'Hotels/Motels/Inns/Resorts', 'MILLENIUM BROADWAY HOTEL'),
('3742', 'Hotels/Motels/Inns/Resorts', 'CLUB MED'),
('3743', 'Hotels/Motels/Inns/Resorts', 'BILTMORE HOTEL AND SUITES'),
('3744', 'Hotels/Motels/Inns/Resorts', 'CAREFREE RESORTS'),
('3745', 'Hotels/Motels/Inns/Resorts', 'ST. REGIS HOTEL'),
('3746', 'Hotels/Motels/Inns/Resorts', 'THE ELIOT HOTEL'),
('3747', 'Hotels/Motels/Inns/Resorts', 'CLUBCORP/CLUB RESORTS'),
('3748', 'Hotels/Motels/Inns/Resorts', 'WELESLEY INNS'),
('3749', 'Hotels/Motels/Inns/Resorts', 'THE BEVERLY HILLS HOTEL'),
('3750', 'Hotels/Motels/Inns/Resorts', 'CROWNE PLAZA HOTELS'),
('3751', 'Hotels/Motels/Inns/Resorts', 'HOMEWOOD SUITES'),
('3752', 'Hotels/Motels/Inns/Resorts', 'PEABODY HOTELS'),
('3753', 'Hotels/Motels/Inns/Resorts', 'GREENBRIAH RESORTS'),
('3754', 'Hotels/Motels/Inns/Resorts', 'AMELIA ISLAND PLANATION'),
('3755', 'Hotels/Motels/Inns/Resorts', 'THE HOMESTEAD'),
('3756', 'Hotels/Motels/Inns/Resorts', 'SOUTH SEAS RESORTS'),
('3757', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3758', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3759', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3760', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3761', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3762', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3763', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3764', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3765', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3766', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3767', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3768', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3769', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3770', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3771', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3772', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3773', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3774', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3775', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3776', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3777', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3778', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3779', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3780', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3781', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3782', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3783', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3784', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3785', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3786', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3787', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3788', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3789', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3790', 'Hotels/Motels/Inns/Resorts', 'Hotels/Motels/Inns/Resorts'),
('3835', '', '* MASTERS ECONOMY INNS'),
('4011', 'Railroads', 'Railroads'),
('4111', 'Commuter Transport, Ferries', 'Local/Suburban Commuter Passenger Transportation ? Railroads, Feries, Local Water Transportation.'),
('4112', 'Passenger Railways', 'Passenger Railways'),
('4119', 'Ambulance Services', 'Ambulance Services'),
('4121', 'Taxicabs/Limousines', 'Taxicabs and Limousines'),
('4131', 'Bus Lines', 'Bus Lines, Including Charters, Tour Buses'),
('4214', 'Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Loc', 'Motor Freight Carriers, Moving and Storage Companies, Trucking ? Local/Long Distance, Delivery Servi'),
('4215', 'Courier Services ', 'Courier Services ? Air or Ground, Freight forwarders'),
('4225', 'Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage ', 'Public warehousing, Storage'),
('4411', 'Cruise Lines', 'Cruise and Steamship Lines'),
('4457', 'Boat Rentals and Leases', 'Boat Rentals and Leases'),
('4468', 'Marinas, Service and Supplies', 'Marinas, Marine Service, and Supplies'),
('4511', 'Airlines, Air Carriers', 'Airlines, Air Carriers ( not listed elsewhere)'),
('4582', 'Airports, Flying Fields', 'Airports, Airport Terminals, Flying Fields'),
('4722', 'Travel Agencies, Tour Operators', 'Travel Agencies and Tour Operations'),
('4723', 'TUI Travel - Germany', 'Package Tour Operators (For use in Germany only)'),
('4784', 'Tolls/Bridge Fees', 'Toll and Bridge Fees'),
('4789', 'Transportation Services (Not Elsewhere Classified)', 'Transportation Services, Not elsewhere classified)'),
('4812', 'Telecommunication Equipment and Telephone Sales', 'Telecommunications Equipment including telephone sales'),
('4814', 'Telecommunication Services', 'Fax services, Telecommunication Services'),
('4815', '', 'VisaPhone'),
('4816', 'Computer Network Services', 'Computer Network Services'),
('4821', 'Telegraph Services', 'Telegraph services'),
('4829', 'Wires, Money Orders', 'Money Orders ? Wire Transfer'),
('4899', 'Cable, Satellite, and Other Pay Television and Radio', 'Cable and other pay television (previously Cable Services)'),
('4900', 'Utilities ', 'Electric, Gas, Sanitary and Water Utilities'),
('5013', 'Motor Vehicle Supplies and New Parts', 'Motor vehicle supplies and new parts'),
('5021', 'Office and Commercial Furniture', 'Office and Commercial Furniture'),
('5039', 'Construction Materials (Not Elsewhere Classified)', 'Construction Materials, Not Elsewhere Classified'),
('5044', 'Photographic, Photocopy, Microfilm Equipment, and Supplies', 'Office, Photographic, Photocopy, and Microfilm Equipment'),
('5045', 'Computers, Peripherals, and Software', 'Computers, Computer Peripheral Equipment, Software'),
('5046', 'Commercial Equipment (Not Elsewhere Classified)', 'Commercial Equipment, Not Elsewhere Classified'),
('5047', 'Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies', 'Medical, Dental Ophthalmic, Hospital Equipment and Supplies'),
('5051', 'Metal Service Centers', 'Metal Service Centers and Offices'),
('5065', 'Electrical Parts and Equipment', 'Electrical Parts and Equipment'),
('5072', 'Hardware, Equipment, and Supplies', 'Hardware Equipment and Supplies'),
('5074', 'Plumbing, Heating Equipment, and Supplies', 'Plumbing and Heating Equipment and Supplies'),
('5085', 'Industrial Supplies (Not Elsewhere Classified)', 'Industrial Supplies, Not Elsewhere Classified'),
('5094', 'Precious Stones and Metals, Watches and Jewelry', 'Precious Stones and Metals, Watches and Jewelry'),
('5099', 'Durable Goods (Not Elsewhere Classified)', 'Durable Goods, Not Elsewhere Classified'),
('5111', 'Stationary, Office Supplies, Printing and Writing Paper', 'Stationery, Office Supplies, Printing, and Writing Paper'),
('5122', 'Drugs, Drug Proprietaries, and Druggist Sundries', 'Drugs, Drug Proprietors, and Druggist?s Sundries'),
('5131', 'Piece Goods, Notions, and Other Dry Goods', 'Piece Goods, Notions, and Other Dry Goods'),
('5137', 'Uniforms, Commercial Clothing', 'Men?s Women?s and Children?s Uniforms and Commercial Clothing'),
('5139', 'Commercial Footwear', 'Commercial Footwear'),
('5169', 'Chemicals and Allied Products (Not Elsewhere Classified)', 'Chemicals and Allied Products, Not Elsewhere Classified'),
('5172', 'Petroleum and Petroleum Products', 'Petroleum and Petroleum Products'),
('5192', 'Books, Periodicals, and Newspapers', 'Books, Periodicals, and Newspapers'),
('5193', 'Florists Supplies, Nursery Stock, and Flowers', 'Florists? Supplies, Nursery Stock and Flowers'),
('5198', 'Paints, Varnishes, and Supplies', 'Paints, Varnishes, and Supplies'),
('5199', 'Nondurable Goods (Not Elsewhere Classified)', 'Non-durable Goods, Not Elsewhere Classified'),
('5200', 'Home Supply Warehouse Stores', 'Home Supply Warehouse Stores'),
('5211', 'Lumber, Building Materials Stores', 'Lumber and Building Materials Stores'),
('5231', 'Glass, Paint, and Wallpaper Stores', 'Glass, Paint, and Wallpaper Stores'),
('5251', 'Hardware Stores', 'Hardware Stores'),
('5261', 'Nurseries, Lawn and Garden Supply Stores', 'Nurseries ? Lawn and Garden Supply Store'),
('5271', 'Mobile Home Dealers', 'Mobile Home Dealers'),
('5300', 'Wholesale Clubs', 'Wholesale Clubs'),
('5309', 'Duty Free Stores', 'Duty Free Store'),
('5310', 'Discount Stores', 'Discount Stores'),
('5311', 'Department Stores', 'Department Stores'),
('5331', 'Variety Stores', 'Variety Stores'),
('5399', 'Miscellaneous General Merchandise', 'Misc. General Merchandise'),
('5411', 'Grocery Stores, Supermarkets', 'Grocery Stores, Supermarkets'),
('5422', 'Freezer and Locker Meat Provisioners', 'Meat Provisioners ? Freezer and Locker'),
('5441', 'Candy, Nut, and Confectionery Stores', 'Candy, Nut, and Confectionery Stores'),
('5451', 'Dairy Products Stores', 'Dairy Products Stores'),
('5462', 'Bakeries', 'Bakeries'),
('5499', 'Miscellaneous Food Stores - Convenience Stores and Specialty Markets', 'Misc. Food Stores ? Convenience Stores and Specialty Markets'),
('5511', 'Car and Truck Dealers (New & Used) Sales, Service, Repairs Parts and Leasing ', 'Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing'),
('5521', 'Car and Truck Dealers (Used Only) Sales, Service, Repairs Parts and Leasing ', 'Automobile and Truck Dealers (Used Only)'),
('5531', 'Auto and Home Supply Stores', 'Automobile Supply Stores'),
('5532', 'Automotive Tire Stores', 'Automotive Tire Stores'),
('5533', 'Automotive Parts and Accessories Stores', 'Automotive Parts, Accessories Stores'),
('5541', 'Service Stations ', 'Service Stations ( with or without ancillary services)'),
('5542', 'Automated Fuel Dispensers', 'Automated Fuel Dispensers'),
('5551', 'Boat Dealers', 'Boat Dealers'),
('5561', 'Motorcycle Shops, Dealers', 'Recreational and Utility Trailers, Camp Dealers'),
('5571', 'Motorcycle Shops and Dealers', 'Motorcycle Dealers'),
('5592', 'Motor Homes Dealers', 'Motor Home Dealers'),
('5598', 'Snowmobile Dealers', 'Snowmobile Dealers'),
('5599', 'Miscellaneous Auto Dealers ', 'Miscellaneous Auto Dealers '),
('5611', 'Men?s and Boy?s Clothing and Accessories Stores', 'Men?s and Boy?s Clothing and Accessories Stores'),
('5621', 'Women?s Ready-To-Wear Stores', 'Women?s Ready-to-Wear Stores'),
('5631', 'Women?s Accessory and Specialty Shops', 'Women?s Accessory and Specialty Shops'),
('5641', 'Children?s and Infant?s Wear Stores', 'Children?s and Infant?s Wear Stores'),
('5651', 'Family Clothing Stores', 'Family Clothing Stores'),
('5655', 'Sports and Riding Apparel Stores', 'Sports Apparel, Riding Apparel Stores'),
('5661', 'Shoe Stores', 'Shoe Stores'),
('5681', 'Furriers and Fur Shops', 'Furriers and Fur Shops'),
('5691', 'Men?s, Women?s Clothing Stores', 'Men?s and Women?s Clothing Stores'),
('5697', 'Tailors, Alterations', 'Tailors, Seamstress, Mending, and Alterations'),
('5698', 'Wig and Toupee Stores', 'Wig and Toupee Stores'),
('5699', 'Miscellaneous Apparel and Accessory Shops', 'Miscellaneous Apparel and Accessory Shops'),
('5712', 'Furniture, Home Furnishings, and Equipment Stores, Except Appliances', 'Furniture, Home Furnishings, and Equipment Stores, ExceptAppliances'),
('5713', 'Floor Covering Stores', 'Floor Covering Stores'),
('5714', 'Drapery, Window Covering, and Upholstery Stores', 'Drapery, Window Covering and Upholstery Stores'),
('5718', 'Fireplace, Fireplace Screens, and Accessories Stores', 'Fireplace, Fireplace Screens, and Accessories Stores'),
('5719', 'Miscellaneous Home Furnishing Specialty Stores', 'Miscellaneous Home Furnishing Specialty Stores'),
('5722', 'Household Appliance Stores', 'Household Appliance Stores'),
('5732', 'Electronics Stores', 'Electronic Sales'),
('5733', 'Music Stores-Musical Instruments, Pianos, and Sheet Music', 'Music Stores, Musical Instruments, Piano Sheet Music'),
('5734', 'Computer Software Stores', 'Computer Software Stores'),
('5735', 'Record Stores', 'Record Shops'),
('5811', 'Caterers', 'Caterers'),
('5812', 'Eating Places, Restaurants', 'Eating places and Restaurants'),
('5813', 'Drinking Places', 'Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques'),
('5814', 'Fast Food Restaurants', 'Fast Food Restaurants'),
('5832', '', 'Antique Shops ? Sales, Repairs, and Restoration Services'),
('5912', 'Drug Stores and Pharmacies', 'Drug Stores and Pharmacies'),
('5921', 'Package Stores-Beer, Wine, and Liquor', 'Package Stores ? Beer, Wine, and Liquor'),
('5931', 'Used Merchandise and Secondhand Stores', 'Used Merchandise and Secondhand Stores'),
('5932', 'Antique Shops', 'Antique Shops'),
('5933', 'Pawn Shops', 'Pawn Shops and Salvage Yards'),
('5935', 'Wrecking and Salvage Yards', 'Wrecking and Salvage Yards'),
('5937', 'Antique Reproductions', 'Antique Reproductions'),
('5940', 'Bicycle Shops', 'Bicycle Shops ? Sales and Service'),
('5941', 'Sporting Goods Stores', 'Sporting Goods Stores'),
('5942', 'Book Stores', 'Book Stores'),
('5943', 'Stationery Stores, Office, and School Supply Stores', 'Stationery Stores, Office and School Supply Stores'),
('5944', 'Jewelry Stores, Watches, Clocks, and Silverware Stores', 'Watch, Clock, Jewelry, and Silverware Stores'),
('5945', 'Hobby, Toy, and Game Shops', 'Hobby, Toy, and Game Shops'),
('5946', 'Camera and Photographic Supply Stores', 'Camera and Photographic Supply Stores'),
('5947', 'Gift, Card, Novelty, and Souvenir Shops', 'Card Shops, Gift, Novelty, and Souvenir Shops'),
('5948', 'Luggage and Leather Goods Stores', 'Leather Foods Stores'),
('5949', 'Sewing, Needlework, Fabric, and Piece Goods Stores', 'Sewing, Needle, Fabric, and Price Goods Stores'),
('5950', 'Glassware, Crystal Stores', 'Glassware/Crystal Stores'),
('5960', 'Direct Marketing - Insurance Services', 'Direct Marketing- Insurance Service'),
('5961', '', 'Mail Order Houses Including Catalog Order Stores, Book/Record Clubs (No longer permitted for U.S. or'),
('5962', 'Direct Marketing - Travel', 'Direct Marketing ? Travel Related Arrangements Services'),
('5963', 'Door-To-Door Sales', 'Door-to-Door Sales'),
('5964', 'Direct Marketing - Catalog Merchant', 'Direct Marketing ? Catalog Merchant'),
('5965', 'Direct Marketing - Combination Catalog and Retail Merchant', 'Direct Marketing ? Catalog and Catalog and Retail Merchant'),
('5966', 'Direct Marketing - Outbound Tele', 'Direct Marketing- Outbound Telemarketing Merchant'),
('5967', 'Direct Marketing - Inbound Tele', 'Direct Marketing ? Inbound Teleservices Merchant'),
('5968', 'Direct Marketing - Subscription', 'Direct Marketing ? Continuity/Subscription Merchant'),
('5969', 'Direct Marketing - Other ', 'Direct Marketing ? Not Elsewhere Classified'),
('5970', 'Artist?s Supply and Craft Shops', 'Artist?s Supply and Craft Shops'),
('5971', 'Art Dealers and Galleries', 'Art Dealers and Galleries'),
('5972', 'Stamp and Coin Stores', 'Stamp and Coin Stores ? Philatelic and Numismatic Supplies'),
('5973', 'Religious Goods Stores', 'Religious Goods Stores'),
('5975', 'Hearing Aids Sales and Supplies', 'Hearing Aids ? Sales, Service, and Supply Stores'),
('5976', 'Orthopedic Goods - Prosthetic Devices', 'Orthopedic Goods Prosthetic Devices'),
('5977', 'Cosmetic Stores', 'Cosmetic Stores'),
('5978', 'Typewriter Stores', 'Typewriter Stores ? Sales, Rental, Service'),
('5983', 'Fuel Dealers (Non Automotive)', 'Fuel ? Fuel Oil, Wood, Coal, Liquefied Petroleum'),
('5992', 'Florists', 'Florists'),
('5993', 'Cigar Stores and Stands', 'Cigar Stores and Stands'),
('5994', 'News Dealers and Newsstands', 'News Dealers and Newsstands'),
('5995', 'Pet Shops, Pet Food, and Supplies', 'Pet Shops, Pet Foods, and Supplies Stores'),
('5996', 'Swimming Pools Sales', 'Swimming Pools ? Sales, Service, and Supplies'),
('5997', 'Electric Razor Stores', 'Electric Razor Stores ? Sales and Service'),
('5998', 'Tent and Awning Shops', 'Tent and Awning Shops'),
('5999', 'Miscellaneous Specialty Retail', 'Miscellaneous and Specialty Retail Stores'),
('6010', 'Manual Cash Disburse', 'Financial Institutions ? Manual Cash Disbursements'),
('6011', 'Automated Cash Disburse', 'Financial Institutions ? Manual Cash Disbursements'),
('6012', 'Financial Institutions', 'Financial Institutions ? Merchandise and Services'),
('6051', 'Non-FI, Money Orders', 'Non-Financial Institutions ? Foreign Currency, Money Orders (not wire transfer) and Travelers Cheque'),
('6211', 'Security Brokers/Dealers', 'Security Brokers/Dealers'),
('6300', 'Insurance Underwriting, Premiums', 'Insurance Sales, Underwriting, and Premiums'),
('6381', '', 'Insurance Premiums, (no longer valid for first presentment work)'),
('6399', 'Insurance - Default', 'Insurance, Not Elsewhere Classified ( no longer valid forfirst presentment work)'),
('6513', 'Real Estate Agents and Managers - Rentals', 'Real Estate Agents and Managers - Rentals'),
('7011', 'Hotels, Motels, and Resorts', 'Lodging ? Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)'),
('7012', 'Timeshares', 'Timeshares'),
('7032', 'Sporting/Recreation Camps', 'Sporting and Recreational Camps'),
('7033', 'Trailer Parks, Campgrounds', 'Trailer Parks and Camp Grounds'),
('7210', 'Laundry, Cleaning Services', 'Laundry, Cleaning, and Garment Services'),
('7211', 'Laundries ', 'Laundry ? Family and Commercial'),
('7216', 'Dry Cleaners', 'Dry Cleaners'),
('7217', 'Carpet/Upholstery Cleaning', 'Carpet and Upholstery Cleaning'),
('7221', 'Photographic Studios', 'Photographic Studios'),
('7230', 'Barber and Beauty Shops', 'Barber and Beauty Shops'),
('7251', 'Shoe Repair/Hat Cleaning', 'Shop Repair Shops and Shoe Shine Parlors, and Hat Cleaning Shops'),
('7261', 'Funeral Services, Crematories', 'Funeral Service and Crematories'),
('7273', 'Dating/Escort Services', 'Dating and Escort Services'),
('7276', 'Tax Preparation Services', 'Tax Preparation Service'),
('7277', 'Counseling Services', 'Counseling Service ? Debt, Marriage, Personal'),
('7278', 'Buying/Shopping Services', 'Buying/Shopping Services, Clubs'),
('7296', 'Clothing Rental ', 'Clothing Rental ? Costumes, Formal Wear, Uniforms'),
('7297', 'Massage Parlors', 'Massage Parlors'),
('7298', 'Health and Beauty Spas', 'Health and Beauty Shops'),
('7299', 'Miscellaneous General Services', 'Miscellaneous Personal Services ( not elsewhere classifies)'),
('7311', 'Advertising Services', 'Advertising Services'),
('7321', 'Credit Reporting Agencies', 'Consumer Credit Reporting Agencies'),
('7332', '', 'Blueprinting and Photocopying Services'),
('7333', 'Commercial Photography, Art and Graphics', 'Commercial Photography, Art and Graphics'),
('7338', 'Quick Copy, Repro, and Blueprint', 'Quick Copy, Reproduction and Blueprinting Services'),
('7339', 'Secretarial Support Services', 'Stenographic and Secretarial Support Services'),
('7342', 'Exterminating Services', 'Exterminating and Disinfecting Services'),
('7349', 'Cleaning and Maintenance', 'Cleaning and Maintenance, Janitorial Services'),
('7361', 'Employment/Temp Agencies', 'Employment Agencies, Temporary Help Services'),
('7372', 'Computer Programming', 'Computer Programming, Integrated Systems Design and Data Processing Services'),
('7375', 'Information Retrieval Services', 'Information Retrieval Services'),
('7379', 'Computer Repair', 'Computer Maintenance and Repair Services, Not Elsewhere Classified'),
('7392', 'Consulting, Public Relations', 'Management, Consulting, and Public Relations Services'),
('7393', 'Detective Agencies', 'Protective and Security Services ? Including Armored Carsand Guard Dogs'),
('7394', 'Equipment Rental ', 'Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental'),
('7395', 'Photo Developing', 'Photofinishing Laboratories, Photo Developing'),
('7399', 'Miscellaneous Business Services ', 'Business Services, Not Elsewhere Classified'),
('7511', 'Truck Stop', 'Truck Stop'),
('7512', 'Car Rental Agencies', 'Car Rental Companies ( Not Listed Below)');
INSERT INTO `mcc_master` (`mcc_code`, `category`, `sub_category`) VALUES
('7513', 'Truck/Utility Trailer Rentals', 'Truck and Utility Trailer Rentals'),
('7519', 'Recreational Vehicle Rentals', 'Motor Home and Recreational Vehicle Rentals'),
('7523', 'Parking Lots, Garages', 'Automobile Parking Lots and Garages'),
('7531', 'Auto Body Repair Shops', 'Automotive Body Repair Shops'),
('7534', 'Tire Retreading and Repair', 'Tire Re-treading and Repair Shops'),
('7535', 'Auto Paint Shops', 'Paint Shops ? Automotive'),
('7538', 'Auto Service Shops', 'Automotive Service Shops'),
('7542', 'Car Washes', 'Car Washes'),
('7549', 'Towing Services', 'Towing Services'),
('7622', 'Electronics Repair Shops', 'Radio Repair Shops'),
('7623', 'A/C, Refrigeration Repair', 'Air Conditioning and Refrigeration Repair Shops'),
('7629', 'Small Appliance Repair', 'Electrical And Small Appliance Repair Shops'),
('7631', 'Watch/Jewelry Repair', 'Watch, Clock, and Jewelry Repair'),
('7641', 'Furniture Repair, Refinishing', 'Furniture, Furniture Repair, and Furniture Refinishing'),
('7692', 'Welding Repair', 'Welding Repair'),
('7699', 'Miscellaneous Repair Shops', 'Repair Shops and Related Services ?Miscellaneous'),
('7829', 'Picture/Video Production', 'Motion Pictures and Video Tape Production and Distribution'),
('7832', 'Motion Picture Theaters', 'Motion Picture Theaters'),
('7841', 'Video Tape Rental Stores', 'Video Tape Rental Stores'),
('7911', 'Dance Hall, Studios, Schools', 'Dance Halls, Studios and Schools'),
('7922', 'Theatrical Ticket Agencies', 'Theatrical Producers (Except Motion Pictures), Ticket Agencies'),
('7929', 'Bands, Orchestras', 'Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)'),
('7932', 'Billiard/Pool Establishments', 'Billiard and Pool Establishments'),
('7933', 'Bowling Alleys', 'Bowling Alleys'),
('7941', 'Sports Clubs/Fields', 'Commercial Sports, Athletic Fields, Professional Sport Clubs, and Sport Promoters'),
('7991', 'Tourist Attractions and Exhibits', 'Tourist Attractions and Exhibits'),
('7992', 'Golf Courses - Public', 'Golf Courses ? Public'),
('7993', 'Video Amusement Game Supplies', 'Video Amusement Game Supplies'),
('7994', 'Video Game Arcades', 'Video Game Arcades/Establishments'),
('7995', 'Betting/Casino Gambling', 'Betting (including Lottery Tickets, Casino Gaming Chips, Off-track Betting and Wagers)'),
('7996', 'Amusement Parks/Carnivals', 'Amusement Parks, Carnivals, Circuses, Fortune Tellers'),
('7997', 'Country Clubs', 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses'),
('7998', 'Aquariums', 'Aquariums, Sea-aquariums, Dolphinariums'),
('7999', 'Miscellaneous Recreation Services', 'Recreation Services (Not Elsewhere Classified)'),
('8011', 'Doctors', 'Doctors and Physicians (Not Elsewhere Classified)'),
('8021', 'Dentists, Orthodontists', 'Dentists and Orthodontists'),
('8031', 'Osteopaths', 'Osteopaths'),
('8041', 'Chiropractors', 'Chiropractors'),
('8042', 'Optometrists, Ophthalmologist', 'Optometrists and Ophthalmologists'),
('8043', 'Opticians, Eyeglasses', 'Opticians, Opticians Goods and Eyeglasses'),
('8044', '', 'Opticians, Optical Goods, and Eyeglasses (no longer validfor first presentments)'),
('8049', 'Chiropodists, Podiatrists', 'Podiatrists and Chiropodists'),
('8050', 'Nursing/Personal Care ', 'Nursing and Personal Care Facilities'),
('8062', 'Hospitals', 'Hospitals'),
('8071', 'Medical and Dental Labs', 'Medical and Dental Laboratories'),
('8099', 'Medical Services ', 'Medical Services and Health Practitioners (Not Elsewhere Classified)'),
('8111', 'Legal Services, Attorneys', 'Legal Services and Attorneys'),
('8211', 'Elementary, Secondary Schools', 'Elementary and Secondary Schools'),
('8220', 'Colleges, Universities', 'Colleges, Junior Colleges, Universities, and ProfessionalSchools'),
('8241', 'Correspondence Schools', 'Correspondence Schools'),
('8244', 'Business/Secretarial Schools', 'Business and Secretarial Schools'),
('8249', 'Vocational/Trade Schools', 'Vocational Schools and Trade Schools'),
('8299', 'Educational Services ', 'Schools and Educational Services ( Not Elsewhere Classified)'),
('8351', 'Child Care Services', 'Child Care Services'),
('8398', 'Charitable and Social Service Organizations - Fundraising', 'Charitable and Social Service Organizations'),
('8641', 'Civic, Social, Fraternal Associations', 'Civic, Fraternal, and Social Associations'),
('8651', 'Political Organizations', 'Political Organizations'),
('8661', 'Religious Organizations', 'Religious Organizations'),
('8675', 'Automobile Associations', 'Automobile Associations'),
('8699', 'Membership Organizations', 'Membership Organizations ( Not Elsewhere Classified)'),
('8734', 'Testing Laboratories', 'Testing Laboratories ( non-medical)'),
('8911', 'Architectural/Surveying Services', 'Architectural ? Engineering and Surveying Services'),
('8931', 'Accounting/Bookkeeping Services', 'Accounting, Auditing, and Bookkeeping Services'),
('8999', 'Professional Services', 'Professional Services ( Not Elsewhere Defined)'),
('9211', 'Court Costs, Including Alimony and Child Support - Courts of Law', 'Court Costs, including Alimony and Child Support'),
('9222', 'Fines - Government Administrative Entities', 'Fines'),
('9223', 'Bail and Bond Payments (payment to the surety for the bond, not the actual bond paid to the governme', 'Bail and Bond Payments'),
('9311', 'Tax Payments - Government Agencies', 'Tax Payments'),
('9399', 'Government Services (Not Elsewhere Classified)', 'Government Services ( Not Elsewhere Classified)'),
('9402', 'Postal Services - Government Only', 'Postal Services ? Government Only'),
('9405', 'U.S. Federal Government Agencies or Departments', 'Intra ? Government Transactions'),
('9700', '', 'Automated Referral Service ( For Visa Only)'),
('9701', '', 'Visa Credential Service ( For Visa Only)'),
('9702', '', 'GCAS Emergency Services ( For Visa Only)'),
('9950', 'Intra-Company Purchases', 'Intra ? Company Purchases ( For Visa Only)');

