-- ----------------------------
-- Table structure for `mcc_master`
-- ----------------------------
DROP TABLE IF EXISTS `mcc_master`;
CREATE TABLE `mcc_master` (
  `mcc` int(11) unsigned NOT NULL,
  `description` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of mcc_master
-- ----------------------------
INSERT INTO `mcc_master` VALUES ('742', 'Veterinary Services');
INSERT INTO `mcc_master` VALUES ('763', 'Agricultural Co-operatives');
INSERT INTO `mcc_master` VALUES ('780', 'Horticultural Services, Landscaping Services');
INSERT INTO `mcc_master` VALUES ('1520', 'General Contractors-Residential and Commercial');
INSERT INTO `mcc_master` VALUES ('1711', 'Air Conditioning Contractors – Sales and Installation, Heating Contractors – Sales, Service, Install');
INSERT INTO `mcc_master` VALUES ('1731', 'Electrical Contractors');
INSERT INTO `mcc_master` VALUES ('1740', 'Insulation – Contractors, Masonry, Stonework Contractors, Plastering Contractors, Stonework and Maso');
INSERT INTO `mcc_master` VALUES ('1750', 'Carpentry Contractors');
INSERT INTO `mcc_master` VALUES ('1761', 'Roofing – Contractors, Sheet Metal Work – Contractors, Siding – Contractors');
INSERT INTO `mcc_master` VALUES ('1771', 'Contractors – Concrete Work');
INSERT INTO `mcc_master` VALUES ('1799', 'Contractors – Special Trade, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('2741', 'Miscellaneous Publishing and Printing');
INSERT INTO `mcc_master` VALUES ('2791', 'Typesetting, Plate Making, & Related Services');
INSERT INTO `mcc_master` VALUES ('2842', 'Specialty Cleaning, Polishing, and Sanitation Preparations');
INSERT INTO `mcc_master` VALUES ('3000', 'UNITED AIRLINES');
INSERT INTO `mcc_master` VALUES ('3001', 'AMERICAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3002', 'PAN AMERICAN');
INSERT INTO `mcc_master` VALUES ('3003', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3004', 'TRANS WORLD AIRLINES');
INSERT INTO `mcc_master` VALUES ('3005', 'BRITISH AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3006', 'JAPAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3007', 'AIR FRANCE');
INSERT INTO `mcc_master` VALUES ('3008', 'LUFTHANSA');
INSERT INTO `mcc_master` VALUES ('3009', 'AIR CANADA');
INSERT INTO `mcc_master` VALUES ('3010', 'KLM (ROYAL DUTCH AIRLINES)');
INSERT INTO `mcc_master` VALUES ('3011', 'AEORFLOT');
INSERT INTO `mcc_master` VALUES ('3012', 'QUANTAS');
INSERT INTO `mcc_master` VALUES ('3013', 'ALITALIA');
INSERT INTO `mcc_master` VALUES ('3014', 'SAUDIA ARABIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3015', 'SWISSAIR');
INSERT INTO `mcc_master` VALUES ('3016', 'SAS');
INSERT INTO `mcc_master` VALUES ('3017', 'SOUTH AFRICAN AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3018', 'VARIG (BRAZIL)');
INSERT INTO `mcc_master` VALUES ('3019', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3020', 'AIR-INDIA');
INSERT INTO `mcc_master` VALUES ('3021', 'AIR ALGERIE');
INSERT INTO `mcc_master` VALUES ('3022', 'PHILIPPINE AIRLINES');
INSERT INTO `mcc_master` VALUES ('3023', 'MEXICANA');
INSERT INTO `mcc_master` VALUES ('3024', 'PAKISTAN INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3025', 'AIR NEW ZEALAND');
INSERT INTO `mcc_master` VALUES ('3026', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3027', 'UTA/INTERAIR');
INSERT INTO `mcc_master` VALUES ('3028', 'AIR MALTA');
INSERT INTO `mcc_master` VALUES ('3029', 'SABENA');
INSERT INTO `mcc_master` VALUES ('3030', 'AEROLINEAS ARGENTINAS');
INSERT INTO `mcc_master` VALUES ('3031', 'OLYMPIC AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3032', 'EL AL');
INSERT INTO `mcc_master` VALUES ('3033', 'ANSETT AIRLINES');
INSERT INTO `mcc_master` VALUES ('3034', 'AUSTRAINLIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3035', 'TAP (PORTUGAL)');
INSERT INTO `mcc_master` VALUES ('3036', 'VASP (BRAZIL)');
INSERT INTO `mcc_master` VALUES ('3037', 'EGYPTAIR');
INSERT INTO `mcc_master` VALUES ('3038', 'KUWAIT AIRLINES');
INSERT INTO `mcc_master` VALUES ('3039', 'AVIANCA');
INSERT INTO `mcc_master` VALUES ('3040', 'GULF AIR (BAHRAIN)');
INSERT INTO `mcc_master` VALUES ('3041', 'BALKAN-BULGARIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3042', 'FINNAIR');
INSERT INTO `mcc_master` VALUES ('3043', 'AER LINGUS');
INSERT INTO `mcc_master` VALUES ('3044', 'AIR LANKA');
INSERT INTO `mcc_master` VALUES ('3045', 'NIGERIA AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3046', 'CRUZEIRO DO SUL (BRAZIJ)');
INSERT INTO `mcc_master` VALUES ('3047', 'THY (TURKEY)');
INSERT INTO `mcc_master` VALUES ('3048', 'ROYAL AIR MAROC');
INSERT INTO `mcc_master` VALUES ('3049', 'TUNIS AIR');
INSERT INTO `mcc_master` VALUES ('3050', 'ICELANDAIR');
INSERT INTO `mcc_master` VALUES ('3051', 'AUSTRIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3052', 'LANCHILE');
INSERT INTO `mcc_master` VALUES ('3053', 'AVIACO (SPAIN)');
INSERT INTO `mcc_master` VALUES ('3054', 'LADECO (CHILE)');
INSERT INTO `mcc_master` VALUES ('3055', 'LAB (BOLIVIA)');
INSERT INTO `mcc_master` VALUES ('3056', 'QUEBECAIRE');
INSERT INTO `mcc_master` VALUES ('3057', 'EASTWEST AIRLINES (AUSTRALIA)');
INSERT INTO `mcc_master` VALUES ('3058', 'DELTA');
INSERT INTO `mcc_master` VALUES ('3059', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3060', 'NORTHWEST');
INSERT INTO `mcc_master` VALUES ('3061', 'CONTINENTAL');
INSERT INTO `mcc_master` VALUES ('3062', 'WESTERN');
INSERT INTO `mcc_master` VALUES ('3063', 'US AIR');
INSERT INTO `mcc_master` VALUES ('3064', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3065', 'AIRINTER');
INSERT INTO `mcc_master` VALUES ('3066', 'SOUTHWEST');
INSERT INTO `mcc_master` VALUES ('3067', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3068', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3069', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3070', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3071', 'AIR BRITISH COLUBIA');
INSERT INTO `mcc_master` VALUES ('3072', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3073', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3074', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3075', 'SINGAPORE AIRLINES');
INSERT INTO `mcc_master` VALUES ('3076', 'AEROMEXICO');
INSERT INTO `mcc_master` VALUES ('3077', 'THAI AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3078', 'CHINA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3079', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3080', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3081', 'NORDAIR');
INSERT INTO `mcc_master` VALUES ('3082', 'KOREAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3083', 'AIR AFRIGUE');
INSERT INTO `mcc_master` VALUES ('3084', 'EVA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3085', 'MIDWEST EXPRESS AIRLINES, INC.');
INSERT INTO `mcc_master` VALUES ('3086', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3087', 'METRO AIRLINES');
INSERT INTO `mcc_master` VALUES ('3088', 'CROATIA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3089', 'TRANSAERO');
INSERT INTO `mcc_master` VALUES ('3090', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3091', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3092', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3093', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3094', 'ZAMBIA AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3095', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3096', 'AIR ZIMBABWE');
INSERT INTO `mcc_master` VALUES ('3097', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3098', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3099', 'CATHAY PACIFIC');
INSERT INTO `mcc_master` VALUES ('3100', 'MALAYSIAN AIRLINE SYSTEM');
INSERT INTO `mcc_master` VALUES ('3101', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3102', 'IBERIA');
INSERT INTO `mcc_master` VALUES ('3103', 'GARUDA (INDONESIA)');
INSERT INTO `mcc_master` VALUES ('3104', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3105', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3106', 'BRAATHENS S.A.F.E. (NORWAY)');
INSERT INTO `mcc_master` VALUES ('3107', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3108', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3109', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3110', 'WINGS AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3111', 'BRITISH MIDLAND');
INSERT INTO `mcc_master` VALUES ('3112', 'WINDWARD ISLAND');
INSERT INTO `mcc_master` VALUES ('3113', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3114', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3115', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3116', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3117', 'VIASA');
INSERT INTO `mcc_master` VALUES ('3118', 'VALLEY AIRLINES');
INSERT INTO `mcc_master` VALUES ('3119', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3120', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3121', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3122', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3123', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3124', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3125', 'TAN');
INSERT INTO `mcc_master` VALUES ('3126', 'TALAIR');
INSERT INTO `mcc_master` VALUES ('3127', 'TACA INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3128', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3129', 'SURINAM AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3130', 'SUN WORLD INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3131', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3132', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3133', 'SUNBELT AIRLINES');
INSERT INTO `mcc_master` VALUES ('3134', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3135', 'SUDAN AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3136', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3137', 'SINGLETON');
INSERT INTO `mcc_master` VALUES ('3138', 'SIMMONS AIRLINES');
INSERT INTO `mcc_master` VALUES ('3139', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3140', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3141', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3142', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3143', 'SCENIC AIRLINES');
INSERT INTO `mcc_master` VALUES ('3144', 'VIRGIN ATLANTIC');
INSERT INTO `mcc_master` VALUES ('3145', 'SAN JUAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3146', 'LUXAIR');
INSERT INTO `mcc_master` VALUES ('3147', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3148', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3149', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3150', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3151', 'AIR ZAIRE');
INSERT INTO `mcc_master` VALUES ('3152', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3153', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3154', 'PRINCEVILLE');
INSERT INTO `mcc_master` VALUES ('3155', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3156', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3157', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3158', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3159', 'PBA');
INSERT INTO `mcc_master` VALUES ('3160', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3161', 'ALL NIPPON AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3162', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3163', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3164', 'NORONTAIR');
INSERT INTO `mcc_master` VALUES ('3165', 'NEW YORK HELICOPTER');
INSERT INTO `mcc_master` VALUES ('3166', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3167', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3168', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3169', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3170', 'NOUNT COOK');
INSERT INTO `mcc_master` VALUES ('3171', 'CANADIAN AIRLINES INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3172', 'NATIONAIR');
INSERT INTO `mcc_master` VALUES ('3173', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3174', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3175', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3176', 'METROFLIGHT AIRLINES');
INSERT INTO `mcc_master` VALUES ('3177', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3178', 'MESA AIR');
INSERT INTO `mcc_master` VALUES ('3179', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3180', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3181', 'MALEV');
INSERT INTO `mcc_master` VALUES ('3182', 'LOT (POLAND)');
INSERT INTO `mcc_master` VALUES ('3183', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3184', 'LIAT');
INSERT INTO `mcc_master` VALUES ('3185', 'LAV (VENEZUELA)');
INSERT INTO `mcc_master` VALUES ('3186', 'LAP (PARAGUAY)');
INSERT INTO `mcc_master` VALUES ('3187', 'LACSA (COSTA RICA)');
INSERT INTO `mcc_master` VALUES ('3188', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3189', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3190', 'JUGOSLAV AIR');
INSERT INTO `mcc_master` VALUES ('3191', 'ISLAND AIRLINES');
INSERT INTO `mcc_master` VALUES ('3192', 'IRAN AIR');
INSERT INTO `mcc_master` VALUES ('3193', 'INDIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3194', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3195', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3196', 'HAWAIIAN AIR');
INSERT INTO `mcc_master` VALUES ('3197', 'HAVASU AIRLINES');
INSERT INTO `mcc_master` VALUES ('3198', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3199', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3200', 'FUYANA AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3201', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3202', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3203', 'GOLDEN PACIFIC AIR');
INSERT INTO `mcc_master` VALUES ('3204', 'FREEDOM AIR');
INSERT INTO `mcc_master` VALUES ('3205', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3206', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3207', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3208', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3209', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3210', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3211', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3212', 'DOMINICANA');
INSERT INTO `mcc_master` VALUES ('3213', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3214', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3215', 'DAN AIR SERVICES');
INSERT INTO `mcc_master` VALUES ('3216', 'CUMBERLAND AIRLINES');
INSERT INTO `mcc_master` VALUES ('3217', 'CSA');
INSERT INTO `mcc_master` VALUES ('3218', 'CROWN AIR');
INSERT INTO `mcc_master` VALUES ('3219', 'COPA');
INSERT INTO `mcc_master` VALUES ('3220', 'COMPANIA FAUCETT');
INSERT INTO `mcc_master` VALUES ('3221', 'TRANSPORTES AEROS MILITARES ECCUATORANOS');
INSERT INTO `mcc_master` VALUES ('3222', 'COMMAND AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3223', 'COMAIR');
INSERT INTO `mcc_master` VALUES ('3224', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3225', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3226', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3227', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3228', 'CAYMAN AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3229', 'SAETA SOCIAEDAD ECUATORIANOS DE TRANSPORTES AEREOS');
INSERT INTO `mcc_master` VALUES ('3230', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3231', 'SASHA SERVICIO AERO DE HONDURAS');
INSERT INTO `mcc_master` VALUES ('3232', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3233', 'CAPITOL AIR');
INSERT INTO `mcc_master` VALUES ('3234', 'BWIA');
INSERT INTO `mcc_master` VALUES ('3235', 'BROKWAY AIR');
INSERT INTO `mcc_master` VALUES ('3236', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3237', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3238', 'BEMIDJI AIRLINES');
INSERT INTO `mcc_master` VALUES ('3239', 'BAR HARBOR AIRLINES');
INSERT INTO `mcc_master` VALUES ('3240', 'BAHAMASAIR');
INSERT INTO `mcc_master` VALUES ('3241', 'AVIATECA (GUATEMALA)');
INSERT INTO `mcc_master` VALUES ('3242', 'AVENSA');
INSERT INTO `mcc_master` VALUES ('3243', 'AUSTRIAN AIR SERVICE');
INSERT INTO `mcc_master` VALUES ('3244', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3245', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3246', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3247', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3248', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3249', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3250', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3251', 'ALOHA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3252', 'ALM');
INSERT INTO `mcc_master` VALUES ('3253', 'AMERICA WEST');
INSERT INTO `mcc_master` VALUES ('3254', 'TRUMP AIRLINE');
INSERT INTO `mcc_master` VALUES ('3255', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3256', 'ALASKA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3257', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3258', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3259', 'AMERICAN TRANS AIR');
INSERT INTO `mcc_master` VALUES ('3260', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3261', 'AIR CHINA');
INSERT INTO `mcc_master` VALUES ('3262', 'RENO AIR, INC.');
INSERT INTO `mcc_master` VALUES ('3263', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3264', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3265', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3266', 'AIR SEYCHELLES');
INSERT INTO `mcc_master` VALUES ('3267', 'AIR PANAMA');
INSERT INTO `mcc_master` VALUES ('3268', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3269', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3270', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3271', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3272', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3273', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3274', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3275', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3276', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3277', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3278', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3279', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3280', 'AIR JAMAICA');
INSERT INTO `mcc_master` VALUES ('3281', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3282', 'AIR DJIBOUTI');
INSERT INTO `mcc_master` VALUES ('3283', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3284', 'AERO VIRGIN ISLANDS');
INSERT INTO `mcc_master` VALUES ('3285', 'AERO PERU');
INSERT INTO `mcc_master` VALUES ('3286', 'AEROLINEAS NICARAGUENSIS');
INSERT INTO `mcc_master` VALUES ('3287', 'AERO COACH AVAIATION');
INSERT INTO `mcc_master` VALUES ('3288', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3289', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3290', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3291', 'ARIANA AFGHAN');
INSERT INTO `mcc_master` VALUES ('3292', 'CYPRUS AIRWAYS');
INSERT INTO `mcc_master` VALUES ('3293', 'ECUATORIANA');
INSERT INTO `mcc_master` VALUES ('3294', 'ETHIOPIAN AIRLINES');
INSERT INTO `mcc_master` VALUES ('3295', 'KENYA AIRLINES');
INSERT INTO `mcc_master` VALUES ('3296', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3297', 'Airlines');
INSERT INTO `mcc_master` VALUES ('3298', 'AIR MAURITIUS');
INSERT INTO `mcc_master` VALUES ('3299', 'WIDERO’S FLYVESELSKAP');
INSERT INTO `mcc_master` VALUES ('3351', 'AFFILIATED AUTO RENTAL');
INSERT INTO `mcc_master` VALUES ('3352', 'AMERICAN INTL RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3353', 'BROOKS RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3354', 'ACTION AUTO RENTAL');
INSERT INTO `mcc_master` VALUES ('3355', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3356', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3357', 'HERTZ RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3358', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3359', 'PAYLESS CAR RENTAL');
INSERT INTO `mcc_master` VALUES ('3360', 'SNAPPY CAR RENTAL');
INSERT INTO `mcc_master` VALUES ('3361', 'AIRWAYS RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3362', 'ALTRA AUTO RENTAL');
INSERT INTO `mcc_master` VALUES ('3363', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3364', 'AGENCY RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3365', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3366', 'BUDGET RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3367', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3368', 'HOLIDAY RENT-A-WRECK');
INSERT INTO `mcc_master` VALUES ('3369', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3370', 'RENT-A-WRECK');
INSERT INTO `mcc_master` VALUES ('3371', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3372', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3373', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3374', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3375', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3376', 'AJAX RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3377', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3378', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3379', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3380', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3381', 'EUROP CAR');
INSERT INTO `mcc_master` VALUES ('3382', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3383', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3384', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3385', 'TROPICAL RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3386', 'SHOWCASE RENTAL CARS');
INSERT INTO `mcc_master` VALUES ('3387', 'ALAMO RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3388', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3389', 'AVIS RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3390', 'DOLLAR RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3391', 'EUROPE BY CAR');
INSERT INTO `mcc_master` VALUES ('3392', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3393', 'NATIONAL CAR RENTAL');
INSERT INTO `mcc_master` VALUES ('3394', 'KEMWELL GROUP RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3395', 'THRIFTY RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3396', 'TILDEN TENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3397', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3398', 'ECONO-CAR RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3399', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3400', 'AUTO HOST COST CAR RENTALS');
INSERT INTO `mcc_master` VALUES ('3401', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3402', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3403', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3404', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3405', 'ENTERPRISE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3406', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3407', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3408', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3409', 'GENERAL RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3410', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3411', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3412', 'A-1 RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3413', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3414', 'GODFREY NATL RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3415', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3416', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3417', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3418', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3419', 'ALPHA RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3420', 'ANSA INTL RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3421', 'ALLSTAE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3422', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3423', 'AVCAR RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3424', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3425', 'AUTOMATE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3426', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3427', 'AVON RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3428', 'CAREY RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3429', 'INSURANCE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3430', 'MAJOR RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3431', 'REPLACEMENT RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3432', 'RESERVE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3433', 'UGLY DUCKLING RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3434', 'USA RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3435', 'VALUE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3436', 'AUTOHANSA RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3437', 'CITE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3438', 'INTERENT RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3439', 'MILLEVILLE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3440', 'VIA ROUTE RENT-A-CAR');
INSERT INTO `mcc_master` VALUES ('3441', 'Car Rental');
INSERT INTO `mcc_master` VALUES ('3501', 'HOLIDAY INNS, HOLIDAY INN EXPRESS');
INSERT INTO `mcc_master` VALUES ('3502', 'BEST WESTERN HOTELS');
INSERT INTO `mcc_master` VALUES ('3503', 'SHERATON HOTELS');
INSERT INTO `mcc_master` VALUES ('3504', 'HILTON HOTELS');
INSERT INTO `mcc_master` VALUES ('3505', 'FORTE HOTELS');
INSERT INTO `mcc_master` VALUES ('3506', 'GOLDEN TULIP HOTELS');
INSERT INTO `mcc_master` VALUES ('3507', 'FRIENDSHIP INNS');
INSERT INTO `mcc_master` VALUES ('3508', 'QUALITY INNS, QUALITY SUITES');
INSERT INTO `mcc_master` VALUES ('3509', 'MARRIOTT HOTELS');
INSERT INTO `mcc_master` VALUES ('3510', 'DAYS INN, DAYSTOP');
INSERT INTO `mcc_master` VALUES ('3511', 'ARABELLA HOTELS');
INSERT INTO `mcc_master` VALUES ('3512', 'INTER-CONTINENTAL HOTELS');
INSERT INTO `mcc_master` VALUES ('3513', 'WESTIN HOTELS');
INSERT INTO `mcc_master` VALUES ('3514', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3515', 'RODEWAY INNS');
INSERT INTO `mcc_master` VALUES ('3516', 'LA QUINTA MOTOR INNS');
INSERT INTO `mcc_master` VALUES ('3517', 'AMERICANA HOTELS');
INSERT INTO `mcc_master` VALUES ('3518', 'SOL HOTELS');
INSERT INTO `mcc_master` VALUES ('3519', 'PULLMAN INTERNATIONAL HOTELS');
INSERT INTO `mcc_master` VALUES ('3520', 'MERIDIEN HOTELS');
INSERT INTO `mcc_master` VALUES ('3521', 'CREST HOTELS (see FORTE HOTELS)');
INSERT INTO `mcc_master` VALUES ('3522', 'TOKYO HOTEL');
INSERT INTO `mcc_master` VALUES ('3523', 'PENNSULA HOTEL');
INSERT INTO `mcc_master` VALUES ('3524', 'WELCOMGROUP HOTELS');
INSERT INTO `mcc_master` VALUES ('3525', 'DUNFEY HOTELS');
INSERT INTO `mcc_master` VALUES ('3526', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3527', 'DOWNTOWNER-PASSPORT HOTEL');
INSERT INTO `mcc_master` VALUES ('3528', 'RED LION HOTELS, RED LION INNS');
INSERT INTO `mcc_master` VALUES ('3529', 'CP HOTELS');
INSERT INTO `mcc_master` VALUES ('3530', 'RENAISSANCE HOTELS, STOUFFER HOTELS');
INSERT INTO `mcc_master` VALUES ('3531', 'ASTIR HOTELS');
INSERT INTO `mcc_master` VALUES ('3532', 'SUN ROUTE HOTELS');
INSERT INTO `mcc_master` VALUES ('3533', 'HOTEL IBIS');
INSERT INTO `mcc_master` VALUES ('3534', 'SOUTHERN PACIFIC HOTELS');
INSERT INTO `mcc_master` VALUES ('3535', 'HILTON INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3536', 'AMFAC HOTELS');
INSERT INTO `mcc_master` VALUES ('3537', 'ANA HOTEL');
INSERT INTO `mcc_master` VALUES ('3538', 'CONCORDE HOTELS');
INSERT INTO `mcc_master` VALUES ('3539', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3540', 'IBEROTEL HOTELS');
INSERT INTO `mcc_master` VALUES ('3541', 'HOTEL OKURA');
INSERT INTO `mcc_master` VALUES ('3542', 'ROYAL HOTELS');
INSERT INTO `mcc_master` VALUES ('3543', 'FOUR SEASONS HOTELS');
INSERT INTO `mcc_master` VALUES ('3544', 'CIGA HOTELS');
INSERT INTO `mcc_master` VALUES ('3545', 'SHANGRI-LA INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3546', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3547', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3548', 'HOTELES MELIA');
INSERT INTO `mcc_master` VALUES ('3549', 'AUBERGE DES GOVERNEURS');
INSERT INTO `mcc_master` VALUES ('3550', 'REGAL 8 INNS');
INSERT INTO `mcc_master` VALUES ('3551', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3552', 'COAST HOTELS');
INSERT INTO `mcc_master` VALUES ('3553', 'PARK INNS INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3554', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3555', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3556', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3557', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3558', 'JOLLY HOTELS');
INSERT INTO `mcc_master` VALUES ('3559', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3560', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3561', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3562', 'COMFORT INNS');
INSERT INTO `mcc_master` VALUES ('3563', 'JOURNEY’S END MOTLS');
INSERT INTO `mcc_master` VALUES ('3564', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3565', 'RELAX INNS');
INSERT INTO `mcc_master` VALUES ('3566', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3567', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3568', 'LADBROKE HOTELS');
INSERT INTO `mcc_master` VALUES ('3569', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3570', 'FORUM HOTELS');
INSERT INTO `mcc_master` VALUES ('3571', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3572', 'MIYAKO HOTELS');
INSERT INTO `mcc_master` VALUES ('3573', 'SANDMAN HOTELS');
INSERT INTO `mcc_master` VALUES ('3574', 'VENTURE INNS');
INSERT INTO `mcc_master` VALUES ('3575', 'VAGABOND HOTELS');
INSERT INTO `mcc_master` VALUES ('3576', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3577', 'MANDARIN ORIENTAL HOTEL');
INSERT INTO `mcc_master` VALUES ('3578', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3579', 'HOTEL MERCURE');
INSERT INTO `mcc_master` VALUES ('3580', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3581', 'DELTA HOTEL');
INSERT INTO `mcc_master` VALUES ('3582', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3583', 'SAS HOTELS');
INSERT INTO `mcc_master` VALUES ('3584', 'PRINCESS HOTELS INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3585', 'HUNGAR HOTELS');
INSERT INTO `mcc_master` VALUES ('3586', 'SOKOS HOTELS');
INSERT INTO `mcc_master` VALUES ('3587', 'DORAL HOTELS');
INSERT INTO `mcc_master` VALUES ('3588', 'HELMSLEY HOTELS');
INSERT INTO `mcc_master` VALUES ('3589', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3590', 'FAIRMONT HOTELS');
INSERT INTO `mcc_master` VALUES ('3591', 'SONESTA HOTELS');
INSERT INTO `mcc_master` VALUES ('3592', 'OMNI HOTELS');
INSERT INTO `mcc_master` VALUES ('3593', 'CUNARD HOTELS');
INSERT INTO `mcc_master` VALUES ('3594', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3595', 'HOSPITALITY INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3596', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3597', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3598', 'REGENT INTERNATIONAL HOTELS');
INSERT INTO `mcc_master` VALUES ('3599', 'PANNONIA HOTELS');
INSERT INTO `mcc_master` VALUES ('3600', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3601', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3602', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3603', 'NOAH’S HOTELS');
INSERT INTO `mcc_master` VALUES ('3604', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3605', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3606', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3607', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3608', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3609', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3610', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3611', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3612', 'MOVENPICK HOTELS');
INSERT INTO `mcc_master` VALUES ('3613', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3614', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3615', 'TRAVELODGE');
INSERT INTO `mcc_master` VALUES ('3616', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3617', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3618', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3619', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3620', 'TELFORD INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3621', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3622', 'MERLIN HOTELS');
INSERT INTO `mcc_master` VALUES ('3623', 'DORINT HOTELS');
INSERT INTO `mcc_master` VALUES ('3624', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3625', 'HOTLE UNIVERSALE');
INSERT INTO `mcc_master` VALUES ('3626', 'PRINCE HOTELS');
INSERT INTO `mcc_master` VALUES ('3627', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3628', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3629', 'DAN HOTELS');
INSERT INTO `mcc_master` VALUES ('3630', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3631', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3632', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3633', 'RANK HOTELS');
INSERT INTO `mcc_master` VALUES ('3634', 'SWISSOTEL');
INSERT INTO `mcc_master` VALUES ('3635', 'RESO HOTELS');
INSERT INTO `mcc_master` VALUES ('3636', 'SAROVA HOTELS');
INSERT INTO `mcc_master` VALUES ('3637', 'RAMADA INNS, RAMADA LIMITED');
INSERT INTO `mcc_master` VALUES ('3638', 'HO JO INN, HOWARD JOHNSON');
INSERT INTO `mcc_master` VALUES ('3639', 'MOUNT CHARLOTTE THISTLE');
INSERT INTO `mcc_master` VALUES ('3640', 'HYATT HOTEL');
INSERT INTO `mcc_master` VALUES ('3641', 'SOFITEL HOTELS');
INSERT INTO `mcc_master` VALUES ('3642', 'NOVOTEL HOTELS');
INSERT INTO `mcc_master` VALUES ('3643', 'STEIGENBERGER HOTELS');
INSERT INTO `mcc_master` VALUES ('3644', 'ECONO LODGES');
INSERT INTO `mcc_master` VALUES ('3645', 'QUEENS MOAT HOUSES');
INSERT INTO `mcc_master` VALUES ('3646', 'SWALLOW HOTELS');
INSERT INTO `mcc_master` VALUES ('3647', 'HUSA HOTELS');
INSERT INTO `mcc_master` VALUES ('3648', 'DE VERE HOTELS');
INSERT INTO `mcc_master` VALUES ('3649', 'RADISSON HOTELS');
INSERT INTO `mcc_master` VALUES ('3650', 'RED ROOK INNS');
INSERT INTO `mcc_master` VALUES ('3651', 'IMPERIAL LONDON HOTEL');
INSERT INTO `mcc_master` VALUES ('3652', 'EMBASSY HOTELS');
INSERT INTO `mcc_master` VALUES ('3653', 'PENTA HOTELS');
INSERT INTO `mcc_master` VALUES ('3654', 'LOEWS HOTELS');
INSERT INTO `mcc_master` VALUES ('3655', 'SCANDIC HOTELS');
INSERT INTO `mcc_master` VALUES ('3656', 'SARA HOTELS');
INSERT INTO `mcc_master` VALUES ('3657', 'OBEROI HOTELS');
INSERT INTO `mcc_master` VALUES ('3658', 'OTANI HOTELS');
INSERT INTO `mcc_master` VALUES ('3659', 'TAJ HOTELS INTERNATIONAL');
INSERT INTO `mcc_master` VALUES ('3660', 'KNIGHTS INNS');
INSERT INTO `mcc_master` VALUES ('3661', 'METROPOLE HOTELS');
INSERT INTO `mcc_master` VALUES ('3662', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3663', 'HOTELES EL PRESIDENTS');
INSERT INTO `mcc_master` VALUES ('3664', 'FLAG INN');
INSERT INTO `mcc_master` VALUES ('3665', 'HAMPTON INNS');
INSERT INTO `mcc_master` VALUES ('3666', 'STAKIS HOTELS');
INSERT INTO `mcc_master` VALUES ('3667', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3668', 'MARITIM HOTELS');
INSERT INTO `mcc_master` VALUES ('3669', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3670', 'ARCARD HOTELS');
INSERT INTO `mcc_master` VALUES ('3671', 'ARCTIA HOTELS');
INSERT INTO `mcc_master` VALUES ('3672', 'CAMPANIEL HOTELS');
INSERT INTO `mcc_master` VALUES ('3673', 'IBUSZ HOTELS');
INSERT INTO `mcc_master` VALUES ('3674', 'RANTASIPI HOTELS');
INSERT INTO `mcc_master` VALUES ('3675', 'INTERHOTEL CEDOK');
INSERT INTO `mcc_master` VALUES ('3676', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3677', 'CLIMAT DE FRANCE HOTELS');
INSERT INTO `mcc_master` VALUES ('3678', 'CUMULUS HOTELS');
INSERT INTO `mcc_master` VALUES ('3679', 'DANUBIUS HOTEL');
INSERT INTO `mcc_master` VALUES ('3680', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3681', 'ADAMS MARK HOTELS');
INSERT INTO `mcc_master` VALUES ('3682', 'ALLSTAR INNS');
INSERT INTO `mcc_master` VALUES ('3683', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3684', 'BUDGET HOST INNS');
INSERT INTO `mcc_master` VALUES ('3685', 'BUDGETEL HOTELS');
INSERT INTO `mcc_master` VALUES ('3686', 'SUISSE CHALETS');
INSERT INTO `mcc_master` VALUES ('3687', 'CLARION HOTELS');
INSERT INTO `mcc_master` VALUES ('3688', 'COMPRI HOTELS');
INSERT INTO `mcc_master` VALUES ('3689', 'CONSORT HOTELS');
INSERT INTO `mcc_master` VALUES ('3690', 'COURTYARD BY MARRIOTT');
INSERT INTO `mcc_master` VALUES ('3691', 'DILLION INNS');
INSERT INTO `mcc_master` VALUES ('3692', 'DOUBLETREE HOTELS');
INSERT INTO `mcc_master` VALUES ('3693', 'DRURY INNS');
INSERT INTO `mcc_master` VALUES ('3694', 'ECONOMY INNS OF AMERICA');
INSERT INTO `mcc_master` VALUES ('3695', 'EMBASSY SUITES');
INSERT INTO `mcc_master` VALUES ('3696', 'EXEL INNS');
INSERT INTO `mcc_master` VALUES ('3697', 'FARFIELD HOTELS');
INSERT INTO `mcc_master` VALUES ('3698', 'HARLEY HOTELS');
INSERT INTO `mcc_master` VALUES ('3699', 'MIDWAY MOTOR LODGE');
INSERT INTO `mcc_master` VALUES ('3700', 'MOTEL 6');
INSERT INTO `mcc_master` VALUES ('3701', 'GUEST QUARTERS (Formally PICKETT SUITE HOTELS)');
INSERT INTO `mcc_master` VALUES ('3702', 'THE REGISTRY HOTELS');
INSERT INTO `mcc_master` VALUES ('3703', 'RESIDENCE INNS');
INSERT INTO `mcc_master` VALUES ('3704', 'ROYCE HOTELS');
INSERT INTO `mcc_master` VALUES ('3705', 'SANDMAN INNS');
INSERT INTO `mcc_master` VALUES ('3706', 'SHILO INNS');
INSERT INTO `mcc_master` VALUES ('3707', 'SHONEY’S INNS');
INSERT INTO `mcc_master` VALUES ('3708', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3709', 'SUPER8 MOTELS');
INSERT INTO `mcc_master` VALUES ('3710', 'THE RITZ CARLTON HOTELS');
INSERT INTO `mcc_master` VALUES ('3711', 'FLAG INNS (AUSRALIA)');
INSERT INTO `mcc_master` VALUES ('3712', 'GOLDEN CHAIN HOTEL');
INSERT INTO `mcc_master` VALUES ('3713', 'QUALITY PACIFIC HOTEL');
INSERT INTO `mcc_master` VALUES ('3714', 'FOUR SEASONS HOTEL (AUSTRALIA)');
INSERT INTO `mcc_master` VALUES ('3715', 'FARIFIELD INN');
INSERT INTO `mcc_master` VALUES ('3716', 'CARLTON HOTELS');
INSERT INTO `mcc_master` VALUES ('3717', 'CITY LODGE HOTELS');
INSERT INTO `mcc_master` VALUES ('3718', 'KAROS HOTELS');
INSERT INTO `mcc_master` VALUES ('3719', 'PROTEA HOTELS');
INSERT INTO `mcc_master` VALUES ('3720', 'SOUTHERN SUN HOTELS');
INSERT INTO `mcc_master` VALUES ('3721', 'HILTON CONRAD');
INSERT INTO `mcc_master` VALUES ('3722', 'WYNDHAM HOTEL AND RESORTS');
INSERT INTO `mcc_master` VALUES ('3723', 'RICA HOTELS');
INSERT INTO `mcc_master` VALUES ('3724', 'INER NOR HOTELS');
INSERT INTO `mcc_master` VALUES ('3725', 'SEAINES PLANATION');
INSERT INTO `mcc_master` VALUES ('3726', 'RIO SUITES');
INSERT INTO `mcc_master` VALUES ('3727', 'BROADMOOR HOTEL');
INSERT INTO `mcc_master` VALUES ('3728', 'BALLY’S HOTEL AND CASINO');
INSERT INTO `mcc_master` VALUES ('3729', 'JOHN ASCUAGA’S NUGGET');
INSERT INTO `mcc_master` VALUES ('3730', 'MGM GRAND HOTEL');
INSERT INTO `mcc_master` VALUES ('3731', 'HARRAH’S HOTELS AND CASINOS');
INSERT INTO `mcc_master` VALUES ('3732', 'OPRYLAND HOTEL');
INSERT INTO `mcc_master` VALUES ('3733', 'BOCA RATON RESORT');
INSERT INTO `mcc_master` VALUES ('3734', 'HARVEY/BRISTOL HOTELS');
INSERT INTO `mcc_master` VALUES ('3735', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3736', 'COLORADO BELLE/EDGEWATER RESORT');
INSERT INTO `mcc_master` VALUES ('3737', 'RIVIERA HOTEL AND CASINO');
INSERT INTO `mcc_master` VALUES ('3738', 'TROPICANA RESORT AND CASINO');
INSERT INTO `mcc_master` VALUES ('3739', 'WOODSIDE HOTELS AND RESORTS');
INSERT INTO `mcc_master` VALUES ('3740', 'TOWNPLACE SUITES');
INSERT INTO `mcc_master` VALUES ('3741', 'MILLENIUM BROADWAY HOTEL');
INSERT INTO `mcc_master` VALUES ('3742', 'CLUB MED');
INSERT INTO `mcc_master` VALUES ('3743', 'BILTMORE HOTEL AND SUITES');
INSERT INTO `mcc_master` VALUES ('3744', 'CAREFREE RESORTS');
INSERT INTO `mcc_master` VALUES ('3745', 'ST. REGIS HOTEL');
INSERT INTO `mcc_master` VALUES ('3746', 'THE ELIOT HOTEL');
INSERT INTO `mcc_master` VALUES ('3747', 'CLUBCORP/CLUB RESORTS');
INSERT INTO `mcc_master` VALUES ('3748', 'WELESLEY INNS');
INSERT INTO `mcc_master` VALUES ('3749', 'THE BEVERLY HILLS HOTEL');
INSERT INTO `mcc_master` VALUES ('3750', 'CROWNE PLAZA HOTELS');
INSERT INTO `mcc_master` VALUES ('3751', 'HOMEWOOD SUITES');
INSERT INTO `mcc_master` VALUES ('3752', 'PEABODY HOTELS');
INSERT INTO `mcc_master` VALUES ('3753', 'GREENBRIAH RESORTS');
INSERT INTO `mcc_master` VALUES ('3754', 'AMELIA ISLAND PLANATION');
INSERT INTO `mcc_master` VALUES ('3755', 'THE HOMESTEAD');
INSERT INTO `mcc_master` VALUES ('3756', 'SOUTH SEAS RESORTS');
INSERT INTO `mcc_master` VALUES ('3757', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3758', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3759', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3760', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3761', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3762', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3763', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3764', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3765', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3766', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3767', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3768', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3769', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3770', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3771', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3772', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3773', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3774', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3775', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3776', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3777', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3778', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3779', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3780', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3781', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3782', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3783', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3784', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3785', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3786', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3787', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3788', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3789', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3790', 'Hotels/Motels/Inns/Resorts');
INSERT INTO `mcc_master` VALUES ('3835', '* MASTERS ECONOMY INNS');
INSERT INTO `mcc_master` VALUES ('4011', 'Railroads');
INSERT INTO `mcc_master` VALUES ('4111', 'Local/Suburban Commuter Passenger Transportation – Railroads, Feries, Local Water Transportation.');
INSERT INTO `mcc_master` VALUES ('4112', 'Passenger Railways');
INSERT INTO `mcc_master` VALUES ('4119', 'Ambulance Services');
INSERT INTO `mcc_master` VALUES ('4121', 'Taxicabs and Limousines');
INSERT INTO `mcc_master` VALUES ('4131', 'Bus Lines, Including Charters, Tour Buses');
INSERT INTO `mcc_master` VALUES ('4214', 'Motor Freight Carriers, Moving and Storage Companies, Trucking – Local/Long Distance, Delivery Servi');
INSERT INTO `mcc_master` VALUES ('4215', 'Courier Services – Air or Ground, Freight forwarders');
INSERT INTO `mcc_master` VALUES ('4225', 'Public warehousing, Storage');
INSERT INTO `mcc_master` VALUES ('4411', 'Cruise and Steamship Lines');
INSERT INTO `mcc_master` VALUES ('4457', 'Boat Rentals and Leases');
INSERT INTO `mcc_master` VALUES ('4468', 'Marinas, Marine Service, and Supplies');
INSERT INTO `mcc_master` VALUES ('4511', 'Airlines, Air Carriers ( not listed elsewhere)');
INSERT INTO `mcc_master` VALUES ('4582', 'Airports, Airport Terminals, Flying Fields');
INSERT INTO `mcc_master` VALUES ('4722', 'Travel Agencies and Tour Operations');
INSERT INTO `mcc_master` VALUES ('4723', 'Package Tour Operators (For use in Germany only)');
INSERT INTO `mcc_master` VALUES ('4784', 'Toll and Bridge Fees');
INSERT INTO `mcc_master` VALUES ('4789', 'Transportation Services, Not elsewhere classified)');
INSERT INTO `mcc_master` VALUES ('4812', 'Telecommunications Equipment including telephone sales');
INSERT INTO `mcc_master` VALUES ('4814', 'Fax services, Telecommunication Services');
INSERT INTO `mcc_master` VALUES ('4815', 'VisaPhone');
INSERT INTO `mcc_master` VALUES ('4816', 'Computer Network Services');
INSERT INTO `mcc_master` VALUES ('4821', 'Telegraph services');
INSERT INTO `mcc_master` VALUES ('4829', 'Money Orders – Wire Transfer');
INSERT INTO `mcc_master` VALUES ('4899', 'Cable and other pay television (previously Cable Services)');
INSERT INTO `mcc_master` VALUES ('4900', 'Electric, Gas, Sanitary and Water Utilities');
INSERT INTO `mcc_master` VALUES ('5013', 'Motor vehicle supplies and new parts');
INSERT INTO `mcc_master` VALUES ('5021', 'Office and Commercial Furniture');
INSERT INTO `mcc_master` VALUES ('5039', 'Construction Materials, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5044', 'Office, Photographic, Photocopy, and Microfilm Equipment');
INSERT INTO `mcc_master` VALUES ('5045', 'Computers, Computer Peripheral Equipment, Software');
INSERT INTO `mcc_master` VALUES ('5046', 'Commercial Equipment, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5047', 'Medical, Dental Ophthalmic, Hospital Equipment and Supplies');
INSERT INTO `mcc_master` VALUES ('5051', 'Metal Service Centers and Offices');
INSERT INTO `mcc_master` VALUES ('5065', 'Electrical Parts and Equipment');
INSERT INTO `mcc_master` VALUES ('5072', 'Hardware Equipment and Supplies');
INSERT INTO `mcc_master` VALUES ('5074', 'Plumbing and Heating Equipment and Supplies');
INSERT INTO `mcc_master` VALUES ('5085', 'Industrial Supplies, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5094', 'Precious Stones and Metals, Watches and Jewelry');
INSERT INTO `mcc_master` VALUES ('5099', 'Durable Goods, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5111', 'Stationery, Office Supplies, Printing, and Writing Paper');
INSERT INTO `mcc_master` VALUES ('5122', 'Drugs, Drug Proprietors, and Druggist’s Sundries');
INSERT INTO `mcc_master` VALUES ('5131', 'Piece Goods, Notions, and Other Dry Goods');
INSERT INTO `mcc_master` VALUES ('5137', 'Men’s Women’s and Children’s Uniforms and Commercial Clothing');
INSERT INTO `mcc_master` VALUES ('5139', 'Commercial Footwear');
INSERT INTO `mcc_master` VALUES ('5169', 'Chemicals and Allied Products, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5172', 'Petroleum and Petroleum Products');
INSERT INTO `mcc_master` VALUES ('5192', 'Books, Periodicals, and Newspapers');
INSERT INTO `mcc_master` VALUES ('5193', 'Florists’ Supplies, Nursery Stock and Flowers');
INSERT INTO `mcc_master` VALUES ('5198', 'Paints, Varnishes, and Supplies');
INSERT INTO `mcc_master` VALUES ('5199', 'Non-durable Goods, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5200', 'Home Supply Warehouse Stores');
INSERT INTO `mcc_master` VALUES ('5211', 'Lumber and Building Materials Stores');
INSERT INTO `mcc_master` VALUES ('5231', 'Glass, Paint, and Wallpaper Stores');
INSERT INTO `mcc_master` VALUES ('5251', 'Hardware Stores');
INSERT INTO `mcc_master` VALUES ('5261', 'Nurseries – Lawn and Garden Supply Store');
INSERT INTO `mcc_master` VALUES ('5271', 'Mobile Home Dealers');
INSERT INTO `mcc_master` VALUES ('5300', 'Wholesale Clubs');
INSERT INTO `mcc_master` VALUES ('5309', 'Duty Free Store');
INSERT INTO `mcc_master` VALUES ('5310', 'Discount Stores');
INSERT INTO `mcc_master` VALUES ('5311', 'Department Stores');
INSERT INTO `mcc_master` VALUES ('5331', 'Variety Stores');
INSERT INTO `mcc_master` VALUES ('5399', 'Misc. General Merchandise');
INSERT INTO `mcc_master` VALUES ('5411', 'Grocery Stores, Supermarkets');
INSERT INTO `mcc_master` VALUES ('5422', 'Meat Provisioners – Freezer and Locker');
INSERT INTO `mcc_master` VALUES ('5441', 'Candy, Nut, and Confectionery Stores');
INSERT INTO `mcc_master` VALUES ('5451', 'Dairy Products Stores');
INSERT INTO `mcc_master` VALUES ('5462', 'Bakeries');
INSERT INTO `mcc_master` VALUES ('5499', 'Misc. Food Stores – Convenience Stores and Specialty Markets');
INSERT INTO `mcc_master` VALUES ('5511', 'Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing');
INSERT INTO `mcc_master` VALUES ('5521', 'Automobile and Truck Dealers (Used Only)');
INSERT INTO `mcc_master` VALUES ('5531', 'Automobile Supply Stores');
INSERT INTO `mcc_master` VALUES ('5532', 'Automotive Tire Stores');
INSERT INTO `mcc_master` VALUES ('5533', 'Automotive Parts, Accessories Stores');
INSERT INTO `mcc_master` VALUES ('5541', 'Service Stations ( with or without ancillary services)');
INSERT INTO `mcc_master` VALUES ('5542', 'Automated Fuel Dispensers');
INSERT INTO `mcc_master` VALUES ('5551', 'Boat Dealers');
INSERT INTO `mcc_master` VALUES ('5561', 'Recreational and Utility Trailers, Camp Dealers');
INSERT INTO `mcc_master` VALUES ('5571', 'Motorcycle Dealers');
INSERT INTO `mcc_master` VALUES ('5592', 'Motor Home Dealers');
INSERT INTO `mcc_master` VALUES ('5598', 'Snowmobile Dealers');
INSERT INTO `mcc_master` VALUES ('5599', 'Miscellaneous Auto Dealers ');
INSERT INTO `mcc_master` VALUES ('5611', 'Men’s and Boy’s Clothing and Accessories Stores');
INSERT INTO `mcc_master` VALUES ('5621', 'Women’s Ready-to-Wear Stores');
INSERT INTO `mcc_master` VALUES ('5631', 'Women’s Accessory and Specialty Shops');
INSERT INTO `mcc_master` VALUES ('5641', 'Children’s and Infant’s Wear Stores');
INSERT INTO `mcc_master` VALUES ('5651', 'Family Clothing Stores');
INSERT INTO `mcc_master` VALUES ('5655', 'Sports Apparel, Riding Apparel Stores');
INSERT INTO `mcc_master` VALUES ('5661', 'Shoe Stores');
INSERT INTO `mcc_master` VALUES ('5681', 'Furriers and Fur Shops');
INSERT INTO `mcc_master` VALUES ('5691', 'Men’s and Women’s Clothing Stores');
INSERT INTO `mcc_master` VALUES ('5697', 'Tailors, Seamstress, Mending, and Alterations');
INSERT INTO `mcc_master` VALUES ('5698', 'Wig and Toupee Stores');
INSERT INTO `mcc_master` VALUES ('5699', 'Miscellaneous Apparel and Accessory Shops');
INSERT INTO `mcc_master` VALUES ('5712', 'Furniture, Home Furnishings, and Equipment Stores, ExceptAppliances');
INSERT INTO `mcc_master` VALUES ('5713', 'Floor Covering Stores');
INSERT INTO `mcc_master` VALUES ('5714', 'Drapery, Window Covering and Upholstery Stores');
INSERT INTO `mcc_master` VALUES ('5718', 'Fireplace, Fireplace Screens, and Accessories Stores');
INSERT INTO `mcc_master` VALUES ('5719', 'Miscellaneous Home Furnishing Specialty Stores');
INSERT INTO `mcc_master` VALUES ('5722', 'Household Appliance Stores');
INSERT INTO `mcc_master` VALUES ('5732', 'Electronic Sales');
INSERT INTO `mcc_master` VALUES ('5733', 'Music Stores, Musical Instruments, Piano Sheet Music');
INSERT INTO `mcc_master` VALUES ('5734', 'Computer Software Stores');
INSERT INTO `mcc_master` VALUES ('5735', 'Record Shops');
INSERT INTO `mcc_master` VALUES ('5811', 'Caterers');
INSERT INTO `mcc_master` VALUES ('5812', 'Eating places and Restaurants');
INSERT INTO `mcc_master` VALUES ('5813', 'Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques');
INSERT INTO `mcc_master` VALUES ('5814', 'Fast Food Restaurants');
INSERT INTO `mcc_master` VALUES ('5832', 'Antique Shops – Sales, Repairs, and Restoration Services');
INSERT INTO `mcc_master` VALUES ('5912', 'Drug Stores and Pharmacies');
INSERT INTO `mcc_master` VALUES ('5921', 'Package Stores – Beer, Wine, and Liquor');
INSERT INTO `mcc_master` VALUES ('5931', 'Used Merchandise and Secondhand Stores');
INSERT INTO `mcc_master` VALUES ('5932', 'Antique Shops');
INSERT INTO `mcc_master` VALUES ('5933', 'Pawn Shops and Salvage Yards');
INSERT INTO `mcc_master` VALUES ('5935', 'Wrecking and Salvage Yards');
INSERT INTO `mcc_master` VALUES ('5937', 'Antique Reproductions');
INSERT INTO `mcc_master` VALUES ('5940', 'Bicycle Shops – Sales and Service');
INSERT INTO `mcc_master` VALUES ('5941', 'Sporting Goods Stores');
INSERT INTO `mcc_master` VALUES ('5942', 'Book Stores');
INSERT INTO `mcc_master` VALUES ('5943', 'Stationery Stores, Office and School Supply Stores');
INSERT INTO `mcc_master` VALUES ('5944', 'Watch, Clock, Jewelry, and Silverware Stores');
INSERT INTO `mcc_master` VALUES ('5945', 'Hobby, Toy, and Game Shops');
INSERT INTO `mcc_master` VALUES ('5946', 'Camera and Photographic Supply Stores');
INSERT INTO `mcc_master` VALUES ('5947', 'Card Shops, Gift, Novelty, and Souvenir Shops');
INSERT INTO `mcc_master` VALUES ('5948', 'Leather Foods Stores');
INSERT INTO `mcc_master` VALUES ('5949', 'Sewing, Needle, Fabric, and Price Goods Stores');
INSERT INTO `mcc_master` VALUES ('5950', 'Glassware/Crystal Stores');
INSERT INTO `mcc_master` VALUES ('5960', 'Direct Marketing- Insurance Service');
INSERT INTO `mcc_master` VALUES ('5961', 'Mail Order Houses Including Catalog Order Stores, Book/Record Clubs (No longer permitted for U.S. or');
INSERT INTO `mcc_master` VALUES ('5962', 'Direct Marketing – Travel Related Arrangements Services');
INSERT INTO `mcc_master` VALUES ('5963', 'Door-to-Door Sales');
INSERT INTO `mcc_master` VALUES ('5964', 'Direct Marketing – Catalog Merchant');
INSERT INTO `mcc_master` VALUES ('5965', 'Direct Marketing – Catalog and Catalog and Retail Merchant');
INSERT INTO `mcc_master` VALUES ('5966', 'Direct Marketing- Outbound Telemarketing Merchant');
INSERT INTO `mcc_master` VALUES ('5967', 'Direct Marketing – Inbound Teleservices Merchant');
INSERT INTO `mcc_master` VALUES ('5968', 'Direct Marketing – Continuity/Subscription Merchant');
INSERT INTO `mcc_master` VALUES ('5969', 'Direct Marketing – Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('5970', 'Artist’s Supply and Craft Shops');
INSERT INTO `mcc_master` VALUES ('5971', 'Art Dealers and Galleries');
INSERT INTO `mcc_master` VALUES ('5972', 'Stamp and Coin Stores – Philatelic and Numismatic Supplies');
INSERT INTO `mcc_master` VALUES ('5973', 'Religious Goods Stores');
INSERT INTO `mcc_master` VALUES ('5975', 'Hearing Aids – Sales, Service, and Supply Stores');
INSERT INTO `mcc_master` VALUES ('5976', 'Orthopedic Goods Prosthetic Devices');
INSERT INTO `mcc_master` VALUES ('5977', 'Cosmetic Stores');
INSERT INTO `mcc_master` VALUES ('5978', 'Typewriter Stores – Sales, Rental, Service');
INSERT INTO `mcc_master` VALUES ('5983', 'Fuel – Fuel Oil, Wood, Coal, Liquefied Petroleum');
INSERT INTO `mcc_master` VALUES ('5992', 'Florists');
INSERT INTO `mcc_master` VALUES ('5993', 'Cigar Stores and Stands');
INSERT INTO `mcc_master` VALUES ('5994', 'News Dealers and Newsstands');
INSERT INTO `mcc_master` VALUES ('5995', 'Pet Shops, Pet Foods, and Supplies Stores');
INSERT INTO `mcc_master` VALUES ('5996', 'Swimming Pools – Sales, Service, and Supplies');
INSERT INTO `mcc_master` VALUES ('5997', 'Electric Razor Stores – Sales and Service');
INSERT INTO `mcc_master` VALUES ('5998', 'Tent and Awning Shops');
INSERT INTO `mcc_master` VALUES ('5999', 'Miscellaneous and Specialty Retail Stores');
INSERT INTO `mcc_master` VALUES ('6010', 'Financial Institutions – Manual Cash Disbursements');
INSERT INTO `mcc_master` VALUES ('6011', 'Financial Institutions – Manual Cash Disbursements');
INSERT INTO `mcc_master` VALUES ('6012', 'Financial Institutions – Merchandise and Services');
INSERT INTO `mcc_master` VALUES ('6051', 'Non-Financial Institutions – Foreign Currency, Money Orders (not wire transfer) and Travelers Cheque');
INSERT INTO `mcc_master` VALUES ('6211', 'Security Brokers/Dealers');
INSERT INTO `mcc_master` VALUES ('6300', 'Insurance Sales, Underwriting, and Premiums');
INSERT INTO `mcc_master` VALUES ('6381', 'Insurance Premiums, (no longer valid for first presentment work)');
INSERT INTO `mcc_master` VALUES ('6399', 'Insurance, Not Elsewhere Classified ( no longer valid forfirst presentment work)');
INSERT INTO `mcc_master` VALUES ('6513', 'Real Estate Agents and Managers - Rentals');
INSERT INTO `mcc_master` VALUES ('7011', 'Lodging – Hotels, Motels, Resorts, Central Reservation Services (not elsewhere classified)');
INSERT INTO `mcc_master` VALUES ('7012', 'Timeshares');
INSERT INTO `mcc_master` VALUES ('7032', 'Sporting and Recreational Camps');
INSERT INTO `mcc_master` VALUES ('7033', 'Trailer Parks and Camp Grounds');
INSERT INTO `mcc_master` VALUES ('7210', 'Laundry, Cleaning, and Garment Services');
INSERT INTO `mcc_master` VALUES ('7211', 'Laundry – Family and Commercial');
INSERT INTO `mcc_master` VALUES ('7216', 'Dry Cleaners');
INSERT INTO `mcc_master` VALUES ('7217', 'Carpet and Upholstery Cleaning');
INSERT INTO `mcc_master` VALUES ('7221', 'Photographic Studios');
INSERT INTO `mcc_master` VALUES ('7230', 'Barber and Beauty Shops');
INSERT INTO `mcc_master` VALUES ('7251', 'Shop Repair Shops and Shoe Shine Parlors, and Hat Cleaning Shops');
INSERT INTO `mcc_master` VALUES ('7261', 'Funeral Service and Crematories');
INSERT INTO `mcc_master` VALUES ('7273', 'Dating and Escort Services');
INSERT INTO `mcc_master` VALUES ('7276', 'Tax Preparation Service');
INSERT INTO `mcc_master` VALUES ('7277', 'Counseling Service – Debt, Marriage, Personal');
INSERT INTO `mcc_master` VALUES ('7278', 'Buying/Shopping Services, Clubs');
INSERT INTO `mcc_master` VALUES ('7296', 'Clothing Rental – Costumes, Formal Wear, Uniforms');
INSERT INTO `mcc_master` VALUES ('7297', 'Massage Parlors');
INSERT INTO `mcc_master` VALUES ('7298', 'Health and Beauty Shops');
INSERT INTO `mcc_master` VALUES ('7299', 'Miscellaneous Personal Services ( not elsewhere classifies)');
INSERT INTO `mcc_master` VALUES ('7311', 'Advertising Services');
INSERT INTO `mcc_master` VALUES ('7321', 'Consumer Credit Reporting Agencies');
INSERT INTO `mcc_master` VALUES ('7332', 'Blueprinting and Photocopying Services');
INSERT INTO `mcc_master` VALUES ('7333', 'Commercial Photography, Art and Graphics');
INSERT INTO `mcc_master` VALUES ('7338', 'Quick Copy, Reproduction and Blueprinting Services');
INSERT INTO `mcc_master` VALUES ('7339', 'Stenographic and Secretarial Support Services');
INSERT INTO `mcc_master` VALUES ('7342', 'Exterminating and Disinfecting Services');
INSERT INTO `mcc_master` VALUES ('7349', 'Cleaning and Maintenance, Janitorial Services');
INSERT INTO `mcc_master` VALUES ('7361', 'Employment Agencies, Temporary Help Services');
INSERT INTO `mcc_master` VALUES ('7372', 'Computer Programming, Integrated Systems Design and Data Processing Services');
INSERT INTO `mcc_master` VALUES ('7375', 'Information Retrieval Services');
INSERT INTO `mcc_master` VALUES ('7379', 'Computer Maintenance and Repair Services, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('7392', 'Management, Consulting, and Public Relations Services');
INSERT INTO `mcc_master` VALUES ('7393', 'Protective and Security Services – Including Armored Carsand Guard Dogs');
INSERT INTO `mcc_master` VALUES ('7394', 'Equipment Rental and Leasing Services, Tool Rental, Furniture Rental, and Appliance Rental');
INSERT INTO `mcc_master` VALUES ('7395', 'Photofinishing Laboratories, Photo Developing');
INSERT INTO `mcc_master` VALUES ('7399', 'Business Services, Not Elsewhere Classified');
INSERT INTO `mcc_master` VALUES ('7511', 'Truck Stop');
INSERT INTO `mcc_master` VALUES ('7512', 'Car Rental Companies ( Not Listed Below)');
INSERT INTO `mcc_master` VALUES ('7513', 'Truck and Utility Trailer Rentals');
INSERT INTO `mcc_master` VALUES ('7519', 'Motor Home and Recreational Vehicle Rentals');
INSERT INTO `mcc_master` VALUES ('7523', 'Automobile Parking Lots and Garages');
INSERT INTO `mcc_master` VALUES ('7531', 'Automotive Body Repair Shops');
INSERT INTO `mcc_master` VALUES ('7534', 'Tire Re-treading and Repair Shops');
INSERT INTO `mcc_master` VALUES ('7535', 'Paint Shops – Automotive');
INSERT INTO `mcc_master` VALUES ('7538', 'Automotive Service Shops');
INSERT INTO `mcc_master` VALUES ('7542', 'Car Washes');
INSERT INTO `mcc_master` VALUES ('7549', 'Towing Services');
INSERT INTO `mcc_master` VALUES ('7622', 'Radio Repair Shops');
INSERT INTO `mcc_master` VALUES ('7623', 'Air Conditioning and Refrigeration Repair Shops');
INSERT INTO `mcc_master` VALUES ('7629', 'Electrical And Small Appliance Repair Shops');
INSERT INTO `mcc_master` VALUES ('7631', 'Watch, Clock, and Jewelry Repair');
INSERT INTO `mcc_master` VALUES ('7641', 'Furniture, Furniture Repair, and Furniture Refinishing');
INSERT INTO `mcc_master` VALUES ('7692', 'Welding Repair');
INSERT INTO `mcc_master` VALUES ('7699', 'Repair Shops and Related Services –Miscellaneous');
INSERT INTO `mcc_master` VALUES ('7829', 'Motion Pictures and Video Tape Production and Distribution');
INSERT INTO `mcc_master` VALUES ('7832', 'Motion Picture Theaters');
INSERT INTO `mcc_master` VALUES ('7841', 'Video Tape Rental Stores');
INSERT INTO `mcc_master` VALUES ('7911', 'Dance Halls, Studios and Schools');
INSERT INTO `mcc_master` VALUES ('7922', 'Theatrical Producers (Except Motion Pictures), Ticket Agencies');
INSERT INTO `mcc_master` VALUES ('7929', 'Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('7932', 'Billiard and Pool Establishments');
INSERT INTO `mcc_master` VALUES ('7933', 'Bowling Alleys');
INSERT INTO `mcc_master` VALUES ('7941', 'Commercial Sports, Athletic Fields, Professional Sport Clubs, and Sport Promoters');
INSERT INTO `mcc_master` VALUES ('7991', 'Tourist Attractions and Exhibits');
INSERT INTO `mcc_master` VALUES ('7992', 'Golf Courses – Public');
INSERT INTO `mcc_master` VALUES ('7993', 'Video Amusement Game Supplies');
INSERT INTO `mcc_master` VALUES ('7994', 'Video Game Arcades/Establishments');
INSERT INTO `mcc_master` VALUES ('7995', 'Betting (including Lottery Tickets, Casino Gaming Chips, Off-track Betting and Wagers)');
INSERT INTO `mcc_master` VALUES ('7996', 'Amusement Parks, Carnivals, Circuses, Fortune Tellers');
INSERT INTO `mcc_master` VALUES ('7997', 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses');
INSERT INTO `mcc_master` VALUES ('7998', 'Aquariums, Sea-aquariums, Dolphinariums');
INSERT INTO `mcc_master` VALUES ('7999', 'Recreation Services (Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('8011', 'Doctors and Physicians (Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('8021', 'Dentists and Orthodontists');
INSERT INTO `mcc_master` VALUES ('8031', 'Osteopaths');
INSERT INTO `mcc_master` VALUES ('8041', 'Chiropractors');
INSERT INTO `mcc_master` VALUES ('8042', 'Optometrists and Ophthalmologists');
INSERT INTO `mcc_master` VALUES ('8043', 'Opticians, Opticians Goods and Eyeglasses');
INSERT INTO `mcc_master` VALUES ('8044', 'Opticians, Optical Goods, and Eyeglasses (no longer validfor first presentments)');
INSERT INTO `mcc_master` VALUES ('8049', 'Podiatrists and Chiropodists');
INSERT INTO `mcc_master` VALUES ('8050', 'Nursing and Personal Care Facilities');
INSERT INTO `mcc_master` VALUES ('8062', 'Hospitals');
INSERT INTO `mcc_master` VALUES ('8071', 'Medical and Dental Laboratories');
INSERT INTO `mcc_master` VALUES ('8099', 'Medical Services and Health Practitioners (Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('8111', 'Legal Services and Attorneys');
INSERT INTO `mcc_master` VALUES ('8211', 'Elementary and Secondary Schools');
INSERT INTO `mcc_master` VALUES ('8220', 'Colleges, Junior Colleges, Universities, and ProfessionalSchools');
INSERT INTO `mcc_master` VALUES ('8241', 'Correspondence Schools');
INSERT INTO `mcc_master` VALUES ('8244', 'Business and Secretarial Schools');
INSERT INTO `mcc_master` VALUES ('8249', 'Vocational Schools and Trade Schools');
INSERT INTO `mcc_master` VALUES ('8299', 'Schools and Educational Services ( Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('8351', 'Child Care Services');
INSERT INTO `mcc_master` VALUES ('8398', 'Charitable and Social Service Organizations');
INSERT INTO `mcc_master` VALUES ('8641', 'Civic, Fraternal, and Social Associations');
INSERT INTO `mcc_master` VALUES ('8651', 'Political Organizations');
INSERT INTO `mcc_master` VALUES ('8661', 'Religious Organizations');
INSERT INTO `mcc_master` VALUES ('8675', 'Automobile Associations');
INSERT INTO `mcc_master` VALUES ('8699', 'Membership Organizations ( Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('8734', 'Testing Laboratories ( non-medical)');
INSERT INTO `mcc_master` VALUES ('8911', 'Architectural – Engineering and Surveying Services');
INSERT INTO `mcc_master` VALUES ('8931', 'Accounting, Auditing, and Bookkeeping Services');
INSERT INTO `mcc_master` VALUES ('8999', 'Professional Services ( Not Elsewhere Defined)');
INSERT INTO `mcc_master` VALUES ('9211', 'Court Costs, including Alimony and Child Support');
INSERT INTO `mcc_master` VALUES ('9222', 'Fines');
INSERT INTO `mcc_master` VALUES ('9223', 'Bail and Bond Payments');
INSERT INTO `mcc_master` VALUES ('9311', 'Tax Payments');
INSERT INTO `mcc_master` VALUES ('9399', 'Government Services ( Not Elsewhere Classified)');
INSERT INTO `mcc_master` VALUES ('9402', 'Postal Services – Government Only');
INSERT INTO `mcc_master` VALUES ('9405', 'Intra – Government Transactions');
INSERT INTO `mcc_master` VALUES ('9700', 'Automated Referral Service ( For Visa Only)');
INSERT INTO `mcc_master` VALUES ('9701', 'Visa Credential Service ( For Visa Only)');
INSERT INTO `mcc_master` VALUES ('9702', 'GCAS Emergency Services ( For Visa Only)');
INSERT INTO `mcc_master` VALUES ('9950', 'Intra – Company Purchases ( For Visa Only)');

ALTER TABLE `rat_corp_cardholders` CHANGE `gender` `gender` VARCHAR( 10 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;

INSERT INTO t_transaction_type (typecode, name, status, date_created, is_comm) 
VALUES('RCLD', 'Ratnakar Corporate CardLoad', 'active', NOW(), 'no');
INSERT INTO t_transaction_type (typecode, name, status, date_created, is_comm) 
VALUES('RCTP', 'Ratnakar Corporate Authentication & Transaction Processing', 'active', NOW(), 'no');

