<script type="text/javascript">
$(document).ready(function() {
  
  if($("#program_type").val() == '<?php echo PROGRAM_TYPE_REMIT; ?>')
    {
        $("#plan_fee_id-label").show();
        $("#plan_fee_id").show();
    }
    else
    {
        $("#plan_fee_id-label").hide();
        $("#plan_fee_id").hide();
    }
  
$.ajax({
                url: '/ajax/get-agentproduct/q/'+$("#id").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#product_id").html("");
                            
                            $("#product_id").append(response);
                            $("#product_id option[value='"+$("#product").val()+"']").attr("selected", "selected");
                            console.log(response);
                          
                        }
                    }
         
        }); 
        
        
   // Autopipulate bank list
  $.ajax({
                url: '/ajax/get-bankbyproduct/q/'+$("#product").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#bank_id").html("");
                            
                            $("#bank_id").append(response);
                            
                            console.log(response);
                          
                        }
                    }
         
        });      
  
        
        //Autopopulate product limit
          $.ajax({
                url: '/ajax/get-productlimit/q/'+$("#product").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#product_limit_id").html("");
                            
                            $("#product_limit_id").append(response);
                            $("#product_limit_id option[value='"+$("#limit").val()+"']").attr("selected", "selected");
                            console.log(response);
                          
                        }
                    }
         
        });
        
        
        
  $("#master_product_id").change(function(){
          
            $.ajax({
                url: '/ajax/get-product/q/'+$("#master_product_id").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#product_id").html("");
                            
                            $("#product_id").append(response);
                            console.log(response);
                          
                        }
                    }
         
        });
    });   
    
      $("#bank_id").change(function(){
  
            $.ajax({
                url: '/ajax/get-product/q/'+$("#bank_id").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#product_id").html("");
                            
                            $("#product_id").append(response);
                            console.log(response);
                          
                        }
                    }
         
        });
    });  
    
      $("#product_id").change(function(){
  
            $.ajax({
                url: '/ajax/get-productlimit/q/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            $("#product_limit_id").html("");
                            
                            $("#product_limit_id").append(response);
                            console.log(response);
                          
                        }
                    }
         
        });
    }); 
     $("input#date_start").change(function() {
         var date_start = this.value;
        if(date_start) {             
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x <= curdate)
            {
                alert("Please enter start date greater than last product's start date");
                $("#date_start").val('');
                $("#date_start").focus();
                return false;
            } else{      
            
                    if (!date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                        alert('Please enter valid start date');
                        $("#date_start").val('');
                        $("#date_start").focus();
                        return false;
                    }
                } 

        }
        
    });
    
    $("form").submit(function(){
        if($("#program_type").val() == '<?php echo PROGRAM_TYPE_REMIT; ?>')
        {
            if($("#plan_fee_id").val() == '')
            {
                alert('Please select fee plan');
                $("#plan_fee_id").focus();
                return false;
            }
        }
        if($("#date_start").val() == '')
        {
            alert('Please enter valid start date');
            $("#date_start").focus();
            return false;
        }
        else 
        {
            var date_start = $("#date_start").val();
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x <= curdate)
            {
                alert("Please enter start date greater than today's date");
                $("#date_start").val('');
                $("#date_start").focus();
                return false;
            } else{      
            
                    if (!date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                        alert('Please enter valid start date');
                        $("#date_start").val('');
                        $("#date_start").focus();
                        return false;
                    }
                } 

        }
            
        return true;
    });
    
    
});      
  </script>

<?php
/**
 * Edit a privilege
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Edit product, product limit and commission for Agent: '.$this->productName;

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);
?>
