<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$name = ucfirst($this->first_name) .' '.ucfirst($this->last_name);
// messages
$config['pageTitle'] = 'Products List: '.$name;
$config['addMessage'] = 'Add New Product for Corporate';
$config['emptyMessage'] = 'There is no corporate product at this time.';
$config['addURL'] = '/approvedcorporate/corporateproduct?id='.$this->id;
$aclAction = 'corporateproduct';
// column names & indexes
$config['columnNames'] = array(
    'Product Name',
    'Commission Plan',
    'Fee Plan',
    'Start Date',
    'End Date'

);
$config['columnIndexes'] = array(
    'product_name',
    'commission_name',
    'fee_name',
    'date_start_formatted',
    'date_end_formatted',
    
);

// Approve actions
/*$config['actions'] = array(
    'edit'    =>  array(
        'action'        => 'editagentproduct',
        'title'         => 'Edit',
        'parameter'     => TRUE,
        'icon'          => FALSE,
    ),
);


$config['linkOrder'] = array('edit');*/

$config['columnNA'] = array('date_end_formatted');
/*$config['conditional'] = array(
    0     =>  array(
        'param'     => 'date_end_formatted',
        'value'     => '00-00-0000'
    )
);*/

$config['linkCol'] = array (
        array(
            'linkColName'       => 'product_name',
            'linkController'    => 'product',
            'linkAction'        => 'limit',
            'linkTitle'         => 'View Product Details',
            'linkParamReqd'     => TRUE,
            'linkParamName'     => 'pid',
            'linkParamValue'    => 'pid',
        ),
        array(
            'linkColName'       => 'corporate_limit_name',
            'linkController'    => 'product',
            'linkAction'        => 'limit',
            'linkTitle'         => 'View Product Limit Details',
            'linkParamReqd'     => TRUE,
            'linkParamName'     => 'plid',
            'linkParamValue'    => 'plid',
        ),
        array(
            'linkColName'       => 'commission_name',
            'linkController'    => 'commissionplan',
            'linkAction'        => 'commitems',
            'linkTitle'         => 'View Commission Details',
            'linkParamReqd'     => TRUE,
            'linkParamName'     => 'cid',
            'linkParamValue'    => 'c_id',
        ),
       array(
            'linkColName'       => 'fee_name',
            'linkController'    => 'feeplan',
            'linkAction'        => 'feeitems',
            'linkTitle'         => 'View Fee Details',
            'linkParamReqd'     => TRUE,
            'linkParamName'     => 'fid',
            'linkParamValue'    => 'f_id',
        ),
    ) ;

$helper = $this->listingUtilities($config);
if(!$this->isSubAgent) {
    $addbutton = FALSE ;
} else {
    $addbutton = TRUE;
    $config['showActions'] = FALSE;
}
    $addURL = isset($config['addURL']) ? $config['addURL'] : '' ;


$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
?>
<div class="Boldtext"><?php $helper->pageTitle();?></div>
<?php if(!$addbutton):?>
    <?php if($helper->canShowAddButton() && ($helper->canAdd() || $helper->can($aclAction))):?>
        <?php if(isset($addURL) && $addURL !='' ) {
                    $href = $addURL;
                } else {
                    $href = $helper->addUrl(FALSE);
                }?> 
<div class="filterbox">
<div style="width:950px;">
    <a class="ocean" href="<?php echo $this->formatURL($href);?>" style="float:right;" title="<?php $helper->addMessage();?>"><?php $helper->addMessage();?></a>
</div><!--Inner Style Div END-->
</div>


<?php endif;?> 
<?php endif;?>  

<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($helper->getColumnNames() as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
                <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>
                    <th><span><?php echo 'Actions';?></span></th>
                <?php endif; ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            $prevId = 0;
            $prevProductId = 0;
            $prevProductLimitId = 0;
            $prevCommPlanId = 0;
            foreach($this->paginator as $item) : ?>
                <?php $helper->data = $item;?>
                <tr>
                    <!--<td class="tc">
                        <input type="checkbox" name="checkall" value="true" />
                    </td>--> 
                    <?php /********** displaying the inner columns **********/ ?>
                    <?php 
                    //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                    ?>
                    <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                        <td>
                            <?php 
                            if(is_array($config['columnNA']) && in_array($index, $config['columnNA']) && $item[$index] == '00-00-0000'){
                                echo 'NA'; //$helper->displayItem('NA', $index);
                            }
                            else {
                                $helper->displayItem($item, $index);
                            }
                            ?>
                        </td>
                    <?php endforeach;?>
                <?php if(!isset($config['showActions']) || (isset($config['showActions']) && $config['showActions'])) : ?>

                    <?php
                    //$url = $this->baseUrl . '/' . $this->controllerName . '/editlimit' ;
                    $url = '../' . $this->controllerName . '/editcorporateproduct' ;
                    //$url = '../editagentproduct' ;
                    $url .= '?id=' . $item->id;
                            if($item['date_end_formatted'] == '00-00-0000')
                            {
                                if ($helper->can('editcorporateproduct')) {
                                    //$links[] = $this->link($action, $item, FALSE);
                                    $link = 
                                    '<td><a href="'. $this->formatURL($url) . '" title="Edit">' . PHP_EOL .
                                    '<img src="' . $this->baseUrl . '/images/icons/edit.png' . 
                                        '" alt="Edit" border="0"/>' . PHP_EOL .
                                    '</a></td>';
                                    echo $link;
                                }
                                else {
                                    echo '<td><img src="' . $this->_baseUrl . $disabled_icons['edit']['img_url'] . '" alt="' . $disabled_icons['edit']['alt'] . '" border="0"/></td>';
                                }
                                //echo $helper->link($link, $item, $echo = TRUE)
                            }
                            else {
                                echo '<td><img src="' . $this->_baseUrl . $disabled_icons['edit']['img_url'] . '" alt="' . $disabled_icons['edit']['alt'] . '" border="0"/></td>';
                            }
                    if($prevProductId == $item->product_id)
                    {
                        $url = '../' . $this->controllerName . '/deletecorporateproduct' ;
                        $url .= '?id=' . $item->id;
                            if($item['date_end_formatted'] == '00-00-0000' && $item['date_start_formatted'] > date("d-m-Y") && $prevId != 0)
                            {
                                $url .= '&pid=' . $prevId;
                                if ($helper->can('deletecorporateproduct')) {
                                    //$links[] = $this->link($action, $item, FALSE);
                                    $link = 
                                    '<td><a href="'. $this->formatURL($url) . '" title="Delete">' . PHP_EOL .
                                    '<img src="' . $this->baseUrl . '/images/icons/del.png' . 
                                        '" alt="Delete" border="0"/>' . PHP_EOL .
                                    '</a></td>' ;
                                    echo $link;
                                }
                                else
                                {
                                    echo '<td><img src="' . $this->_baseUrl . $disabled_icons['delete']['img_url'] . '" alt="' . $disabled_icons['delete']['alt'] . '" border="0"/></td>';
                                }
                                //echo $helper->link($link, $item, $echo = TRUE)
                            }
                            else {
                                echo '<td><img src="' . $this->_baseUrl . $disabled_icons['delete']['img_url'] . '" alt="' . $disabled_icons['delete']['alt'] . '" border="0"/></td>';
                            }
                    }
                    else {
                                echo '<td>&nbsp;</td>';
                            }
                    ?>
                <?php endif; ?>                                                
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            $prevProductId = $item->product_id;
            $prevCommPlanId = $item->plan_commission_id;
            $prevId = $item->id;

            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php $helper->columnCount();?>">
                    <?php $helper->emptyMessage();?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
</div>
</div>
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php
