<div class="Boldtext">Payment Status Report</div>

<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
?>
<?php echo $this->form; ?> 
<?php
if($this->sub != ''){
    

$config = array();

// messages
$config['pageTitle'] = 'Payment Status Report';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';

// column names & indexes
$config['columnNames'] = array(
        'AOF Reference Number ',
        'Account No.',
        'Application Date',
        'Branch Code',
        'Title',
        'Name (of the Trainee)', 
        'Middle Name',
        'Surname',
        'Aadhaar Number',
        'Aadhaar Enrollment ID',
        'NSDC Enrollment Number',
        'Debit Mandate Amount',
        'Training Center ID',
        'Traning Center Name',
        'Training Partner Name',
        'TP Account Number',   
        'TP Bank name',
        'TP IFSC',
        'PAN',
        'Gender',
        'Date of Birth',
        'Marital Status',
        'Occupation',
        'Permanent Address Line 1',
        'Permanent Address Line 2',
        'State',
        'City',
        'Pincode',
        'Correspondence Address Line 1',
        'Correspondence Address Line 2',
        'Correspondence State',
        'Correspondence City',
        'Correspondence Pincode',
        'Telephone',
        'Mobile',
        'Email',
        'Nomination Flag',
        'Nominee Name',
        'Nominee_Relationship',
        'Nominee DOB',
        'Nominee Address 1',
        'Nominee Address 2',
        'Nominee City',
        'Nominee Guardian',
        'Card No',
        'Authorizer Status',
        'Checker Status',  
        'ACTION DATE',
        'UID',
        'BoI Cust ID',
        'Wallet Load date',
        'Wallet load amount',
        'Auto Reversal date',  
        'Wallet balance',
        'Wallet status'
    );
$config['columnIndexes'] = array(
        'ref_num',
        'account_no',
        'date_created',
        'sol_id',
        'title',
        'first_name',
        'middle_name',
        'last_name',
        'aadhaar_no',
        '',
        'nsdc_enrollment_no',
        'debit_mandate_amount',
        'training_center_id',
        'traning_center_name',
        'training_partner_name',
        'bank_account_number',
        'bank_name',
        'bank_ifsc_code',
        'pan',
        'gender',
        'date_of_birth',
        'marital_status',
        'occupation',
        'address_line1',
        'address_line2',
        'state',
        'city',
        'pincode',
        'comm_address_line1',
        'comm_address_line2',
        'comm_state',
        'comm_city',
        'comm_pin',
        'landline',
        'mobile',
        'email',
        'nomination_flg',
        'nominee_name',
        'nominee_relationship',
        'nominee_dob',
        'nominee_add_line1',
        'nominee_add_line2',
        'nominee_city_cd',
        'nominee_minor_guradian_cd',
        'card_number',
        'status_bank',
        'status_ops',
        '',  
        'uid_no',
        'cust_id',
        'load_date',
        'load_amount',
        'auto_rev_date',
        'wallet_bal',
        'wallet_status'
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
//$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
//$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>

<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            $rctModel = new RctMaster();
            foreach($this->paginator as $item) :
                
                $nominee_relationship_code = $item[$config['columnIndexes'][38]];
                $nominee_city_code = $item[$config['columnIndexes'][42]];
                $nominee_gaurdian = $item[$config['columnIndexes'][43]];

                if($nominee_relationship_code){
                    $nominee_relation = $rctModel->getRelationName($nominee_relationship_code);
                }  else {
                    $nominee_relation = '';
                }

                if($nominee_city_code){
                   $cityName = $rctModel->getCityName($nominee_city_code);
                } else {
                    $cityName = '';
                }

                if($nominee_gaurdian){
                    $nominee_gaurdian = $rctModel->getRelationName($nominee_gaurdian);
                } else {
                    $nominee_gaurdian = '';
                } 
                
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo ucfirst($item[$config['columnIndexes'][0]]);?></td> 
                        <td><?php echo Util::maskCard($item[$config['columnIndexes'][1]],4);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][2]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][3]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][4]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][5]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][6]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][7]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][8]]);?></td> 
                        <td><?php echo '';?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][10]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][11]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][12]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][13]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][14]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][15]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][16]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][17]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][18]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][19]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][20]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][21]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][22]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][23]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][24]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][25]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][26]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][27]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][28]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][29]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][30]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][31]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][32]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][33]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][34]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][35]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][36]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][37]]);?></td> 
                        <td><?php echo $nominee_relation;?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][39]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][40]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][41]]);?></td>
                        <td><?php echo $cityName;?></td> 
                        <td><?php echo $nominee_gaurdian;?></td>
                        <td><?php echo Util::maskCard($item[$config['columnIndexes'][44]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][45]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][46]]);?></td> 
                        <td><?php echo '';?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][48]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][49]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][50]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][51]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][52]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][53]]);?></td> 
                        <td><?php echo ucfirst($item[$config['columnIndexes'][54]]);?></td> 
                        <!--<td><?php echo ucfirst($item[$config['columnIndexes'][55]]);?></td>--> 

                   <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } } ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
              
            var url = '<?php echo $this->formatURL("/corp_boi_reports/exportpaymentstatus?to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']."&aof_number=".$this->formData['aof_number']."&account_number=".$this->formData['account_number']."&tp_name=".$this->formData['tp_name']."&tp_account_number=".$this->formData['tp_account_number']);?>';    
            $(location).attr('href',url);
       
    });  
    
    $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
    
    $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
      /**** From and To date validation ****/
     if((from == '') || (to == '') ) {
                    alert('Please specify both From and To date.');
                    $("#from_date").focus();
                    return false;
               }  
   else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                    alert('Please specify both From and To date.');
                    $("#from_date").focus();
                    return false;
               } else if(diff < 0){
                  alert('From date cannot be greater than To date.');
                    $("#from_date").focus();
                    return false; 
               }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                    $("#to_date").focus();
                    return false; 
               }
              
       /**** From and To date validation over ****/
          
     return true; 
   });    
});
</script>