<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if(count($this->paginator) > 0){
$config = array();

// messages
$config['pageTitle'] = isset($this->title) ? $this->title: '';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Request Date',
    'Report Name',
    'Generation Date',
    'TP Mobile',
    'Agent Mobile',
    'TP Code',
    'Agent Code',
    'Wallet Load From',
    'Wallet Load To',
    'By Ops',
    'Download',
    );


$config['showActions'] =FALSE;

// render the default listing
$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;

?>


<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                     
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

		           
                        
                        <td><?php echo $item['date_request'];?></td>
                        <td><?php echo $item['file_name'];?></td>
                        <td><?php echo $item['date_processed'];?></td>
                        <td><?php echo $item['tp_mobile'];?></td>
                        <td><?php echo $item['agent_mobile'];?></td>
                        <td><?php echo $item['tp_code'];?></td>
                        <td><?php echo $item['agent_code'];?></td>
                        <td><?php echo $item['wallet_load_from'];?></td>
                        <td><?php echo $item['wallet_load_to'];?></td>
                        <td><?php echo $item['ops_name'];?></td>
                        <?php $formatUrlId = $this->formatURL("/filedownload/index?file=".$item['file_name']."&path=tp_mis");
               
                        ?><td>
                            <?php if($item['file_name'] != ''){ ?>
                            <a href="<?php echo $formatUrlId; ?>">Download</a>
                                <?php } 
                                else echo $item['remarks'];
                                ?>
                        
                        
                        </td>
               
                        <!--<td><?php // echo $item[$config['columnIndexes'][22]];?></td>-->
                       
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php 
}?>

<div class="back" style="margin-left:30px;margin-top:15px"><a class="alt" href="<?php echo $this->formatURL($this->backlink); ?>">← Back</a></div>
