<div class="Boldtext">TP MIS Generic Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if(count($this->paginator) > 0){
$bankUnicodeArr = Util::bankUnicodesArray();    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Cardholder Activations Report for period '.$duration;
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'File',
    'Request Date',
    'File Generation Date',
    'Download',
    
    
    );


$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
// render the default listing
$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");

?>


<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                     
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        
                        <td><?php echo $item['file_name'];?></td>
                        <td><?php echo $item['date_request'];?></td>
                        <td><?php echo $item['date_processed'];?></td>
                        <?php $formatUrlId = $this->formatURL("/filedownload/index?file=".$item['file_name']."&path=tp_mis");
               
                        ?><td><a href="<?php echo $formatUrlId; ?>">Download</a></td>
               
                        <!--<td><?php // echo $item[$config['columnIndexes'][22]];?></td>-->
                       
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php 
}

//if($helper->can('tpmisgeneratedfiles','corp_boi_reports'))
//{
$url = '/corp_boi_reports/tpmisgeneratedfiles';
$link =  '<a href="'. $this->formatURL($url) . '" title="Generated Files">View Generated Files</a>' ;
echo $link;

//}
?>



<script type="text/javascript">
$(document).ready(function() {    
    

    
  
 
     $('form').submit(function(){
       var agent_mobile = $.trim($("#agent_mobile").val()); 
       var tp_mobile = $.trim($("#tp_mobile").val()); 
       var agent_code = $.trim($("#agent_code").val()); 
       var tp_code = $.trim($("#tp_code").val());
       var from_date = $.trim($("#wallet_load_from").val());
       var to_date = $.trim($("#wallet_load_to").val());
       
      if(agent_mobile == '' && tp_mobile == '' && agent_code == ''&& tp_code == '' && from_date == '' && to_date == '') {
            
                    alert('Please select at least one search criteria');
                    return false;
            }
      
    
         
     return true; 
   });    
});
</script>