<div class="Boldtext">Accept Physical Document</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$config = array();

// messages
$config['pageTitle'] = 'Pending Customers List';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found';
if($this->sub == 1){
// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Last Name',
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Date of Birth',
    'Mobile',
    'Email',
    'Bank Status',
    'Submission Date -Maker',
    'Date -Checker',
    'Date -Authorizer',
    );
$config['columnIndexes'] = array(
    'first_name',
    'last_name',
    'member_id',
    'card_number',
    'card_pack_id',
    'date_of_birth',
    'mobile',
    'email',
    'status_bank',
    'date_created',
    'date_approval',
    'date_authorize',
);
$config['viewLinkColumn'] = 'member_id';
$cntColNames = count($config['columnNames']) ;



$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>

 
<div class="tablebox" style="clear:both;">
    <div style="margin:auto;   overflow-x: scroll;width: 960px;float: left; margin-top: 10px;">
    <table width="950" cellspacing='0'>
        <form name ="frm1" id ="frm1" action ="<?php $this->formatURL('/corp_ratnakar_cardholders/uploadcardholders')?>" method = "POST"> 
       
        <thead><!-- universal table heading --> 
            <tr>
                  <th><input type="checkbox" id="selectall"/></th>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
           <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                           
                            <?php /********** displaying the inner columns **********/ ?>
                            
                            <?php  /********** displaying the inner columns **********/
                    
                    $cardId = $item['id'];
                    ?>
                  
                    <td><input type="checkbox" class="reqid" name="reqid[]" value="<?php echo $cardId; ?>"/></td>

                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                       
                
                                     if ($index == 'card_number'){
                                         echo util::maskCard($item[$config['columnIndexes'][3]],4);
                                     }
                                     else{
                                          $helper->displayItem($item, $index);
                                     }
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                           
                        </tr>    
                    <?php endforeach;?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
        

    
    
    </div>
</div>

<div style="clear: both;height: 5px;"></div>
<p>Date *: <input type="text" id="date_recd_doc" name="date_recd_doc">&nbsp;&nbsp;&nbsp;<input id="upload_cardholder" class="tangerine" type="submit" title="Mark as Delivered" value="Mark as Delivered" name="submit_success"></p>



</form>
<div style="clear: both;height: 5px;margin-bottom: 60px;">&nbsp;</div>

<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php } ?>
<script type="text/javascript">
$(document).ready(function() {
 
$("#date_recd_doc").datepicker({ dateFormat: "dd-mm-yy" });
$("input#date_recd_doc").change(function() {
    
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            
            if(x > curdate)
            {
                alert("Please enter date not greater than today's date");
                this.value = '';
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $("#date_recd_doc").focus();
                      return false;
                    }
                }


        }
        
    });
 $("#frm1").submit(function(e) {
    if($("#date_recd_doc").val() == ''){
                alert('Please enter valid date');  
                return false;
            }
           //remit_boi_remitter-neftresponse
       
    if(!$('input[type=checkbox]:checked').length) {
        //stop the form from submitting
        e.preventDefault();
        alert("Please select at least one to process.");
    }

    return true;
    });  
$("#selectall").click(function () {
$('.reqid').attr('checked', this.checked);
});

// if all checkbox are selected, check the selectall checkbox
// and viceversa
$(".reqid").click(function(){

if($(".reqid").length == $(".reqid:checked").length) {
$("#selectall").attr("checked", "checked");
} else {
$("#selectall").removeAttr("checked");
}
});
 var pincode = $("#pin").val();

 if($("#state").val() != ''){
         $.ajax({
                url: '/ajax/get-pincode-list-by-state/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                         
                        } else {
                            
                            $("#pincode").html("");
                            
                            $("#pincode").append(response);
                             $("#pincode option[value='"+pincode+"']").attr("selected", "selected");
                            console.log(response);
                         

                        }
                    },
         
        });
}  
   
  $("#state").change(function(){
    
            $.ajax({
                url: '/ajax/get-pincode-list-by-state/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                            $("#pincode").html("");
                            $("#pincode").append(response);
                        }
                    },
         
        });
    }); 
    
    

});      
</script>