<?php
/**
 * Delete a product
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Approve Customer: '.$this->item->first_name.' '.$this->item->last_name;
$config['areYouSureMessage'] = 'Are you sure you want to approve this customer?';

// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Email',
    'Mobile'
   );
$config['columnIndexes'] = array(
    'first_name',
    'email',
    'mobile'
   );

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);