<div class="Boldtext"><?php echo $this->heading ?></div>
<div class="filterbox"> 
    <a title="<?php echo $this->addifscLink[1]; ?>" style="float:right;margin-right: 25px;" href="<?php echo $this->addifscLink[0]; ?>" class="ocean"><?php echo $this->addifscLink[1]; ?></a> 
</div>
<?php echo $this->form; ?>
<?php
$config = array();
// messages
$config['pageTitle'] = isset($this->title) ? $this->title : '';
$config['emptyMessage'] = 'No record found.';
$config['no_add'] = 1;
$config['showActions'] = TRUE;
if ($this->sub) {

// column names & indexes
    $config['columnNames'] = array(
	'Bank name',
	'IFSC Code',
	'Micr Code',
	'Branch Name',
	'Address',
	'Contact',
	'City',
	'District',
	'State',
	'Enable_for',
	'Action'
    );


    $config['columnIndexes'] = array(
	'bank_name',
	'ifsc_code',
	'micr_code',
	'branch_name',
	'address',
	'contact',
	'city',
	'district',
	'state',
	'enable_for',
	'action'
    );
    $config['showActions'] = FALSE;
    $config['duration'] = $this->formData['dur'];
    $cntColNames = count($config['columnNames']) - 1;
    ?>

    <div class="Boldtext"><?php echo $config['pageTitle']; ?></div>
    <div style="clear:both;">
        <div class="tablebox">
    	<div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    	    <table width="950" cellspacing='0'>
    		<thead><!-- universal table heading --> 
    		    <tr>
			    <?php foreach ($config['columnNames'] as $columnName) : ?>
				<th><span><?php echo $columnName; ?></span></th>
			    <?php endforeach; ?> 
    		    </tr> 
    		</thead>
    		<tbody>
			<?php if (count($this->paginator)) : ?>
			    <?php
			    foreach ($this->paginator as $item) :
				?>
	    		    <tr>
	    			<td><?php echo $item['bank_name']; ?></td> 
	    			<td><?php echo $item['ifsc_code']; ?></td> 
	    			<td><?php echo $item['micr_code']; ?></td> 
	    			<td><?php echo $item['branch_name']; ?></td> 
	    			<td><?php echo $item['address']; ?></td> 
	    			<td><?php echo $item['contact']; ?></td> 
	    			<td><?php echo $item['city']; ?></td> 
	    			<td><?php echo $item['district']; ?></td> 
	    			<td><?php echo $item['state']; ?></td> 
	    			<td><?php echo strtoupper($item['enable_for']); ?></td>
	    			<td>
	    			    <a href="<?php echo $this->formatURL('/settings/updateifsc?bank_name=' . $item['bank_name'] . '&ifsc_code=' . $item['ifsc_code']); ?>" title="Update this IFSC Code : <?php echo $item['ifsc_code'] ; ?>"><img border="0" src="/images/icons/edit.png" alt="Update IFSC Code : <?php echo $item['ifsc_code'] ; ?>"></a> 
	    			</td>
	    		    </tr>    
				<?php
			    endforeach;
			    ?>
			<?php else: ?> 
			    <tr>
				<td colspan="<?php echo $cntColNames + 1; ?>">
				    <?php echo $config['emptyMessage']; ?>
				</td>
			    </tr>
			<?php endif; ?>
    		</tbody> 
    	    </table>
    	</div>
        </div>
        <div>&nbsp;</div> 

	<?php if (count($this->paginator) > 0) { ?>
	    <div class="pagination">
		<?php if ($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
		    <?php echo $this->paginator; ?>
		<?php endif; ?>
	    </div>
	    <?php
	}
    }
    ?>