 <?php //echo Util::getCardholderSignupTab("step1"); ?> 
 <div class="Boldtext">Add Cardholder</div> 
  <span><?php echo $this->msg?></span>
  <?php 
  echo $this->form;  
  ?>
  
  
  <script type="text/javascript">
   var sendAuthButton = false;   
   function sendAuthCode(){
        $("#send_auth_code").val('1');
         sendAuthButton = true;
        $("#frmAdd").submit();   
   }
   
   function isValidEmail(emailText) {
    var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
    return pattern.test(emailText);
};
 var city = $("#cty").val();
 var pincode = $("#pin").val();

 if($("#cty").val() != ''){
  $.ajax({
                url: '/ajax/get-pincode/q/'+city,
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#pincode").html("");                            
                            $("#pincode").append(response);
                            $("#pincode option[value='"+pincode+"']").attr("selected", "selected");
                             console.log(response);                            
                        }
                    }     
        });
 }
 if($("#state").val() != ''){
         $.ajax({
                url: '/ajax/get-city/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                         
                        } else {
                            
                            $("#city").html("");
                            
                            $("#city").append(response);
                             $("#city option[value='"+city+"']").attr("selected", "selected");
                            console.log(response);
                         

                        }
                    },
         
        });
}  
  $("#city").change(function(){
            $.ajax({
                url: '/ajax/get-pincode/q/'+$("#city").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#pincode").html("");                            
                            $("#pincode").append(response);
                             console.log(response);                            
                        }
                    }     
        });
    });      
  $("#state").change(function(){
    
            $.ajax({
                url: '/ajax/get-city/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#city").html("");
                            $("#city").append(response);
                            console.log(response);
                        
                        }
                    },
         
        });
    });   
   //COMMUNICATION ADDRESS
 
  var commcity = $("#comm_cty").val();
 var commpincode = $("#comm_pin").val();

 if($("#comm_cty").val() != ''){
  $.ajax({
                url: '/ajax/get-pincode/q/'+commcity,
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#comm_pincode").html("");                            
                            $("#comm_pincode").append(response);
                            $("#comm_pincode option[value='"+commpincode+"']").attr("selected", "selected");
                             console.log(response);                            
                        }
                    }     
        });
 }
 if($("#comm_state").val() != ''){
         $.ajax({
                url: '/ajax/get-city/q/'+$("#comm_state").val(),
                    success: function(response) {
                        if(response == 1) {
                         
                        } else {
                            
                            $("#comm_city").html("");
                            
                            $("#comm_city").append(response);
                            $("#comm_city option[value='"+commcity+"']").attr("selected", "selected");
                            console.log(response);
                         

                        }
                    },
         
        });
}  
  $("#comm_city").change(function(){
            $.ajax({
                url: '/ajax/get-pincode/q/'+$("#comm_city").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#comm_pincode").html("");                            
                            $("#comm_pincode").append(response);
                             console.log(response);                            
                        }
                    }     
        });
    });      
  $("#comm_state").change(function(){
    
            $.ajax({
                url: '/ajax/get-city/q/'+$("#comm_state").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#comm_city").html("");
                            $("#comm_city").append(response);
                            console.log(response);
                        
                        }
                    },
         
        });
    });
    $("#first_name").focusout(function(){ 
        var lname = $("#last_name").val();
        var fname = $("#first_name").val();
        $("#name_on_card").val(fname+' '+lname);
    });
    
    $("#last_name").focusout(function(){
        var lname = $("#last_name").val();
        var fname = $("#first_name").val();
        $("#name_on_card").val(fname+' '+lname);                            
    });
  
   
    $('form').submit(function(){
       var dob = $.trim($("#date_of_birth").val());
       var productId = $.trim($("#product_id").val());
       var card_type = $.trim($("#card_type").val());
       var card_pack_id = $.trim($("#card_pack_id").val());
       var employee_id = $.trim($("#employee_id").val());
       var employer_name = $.trim($("#employer_name").val());
       var corporate_id = $.trim($("#corporate_id").val());
       var mobile_country_code = $.trim($("#mobile_country_code").val());
       var mobile = $.trim($("#mobile").val());
       var mobile_country_code = $.trim($("#mobile_country_code").val());
       var first_name = $.trim($("#first_name").val());
       var last_name = $.trim($("#last_name").val());
       var mother_maiden_name = $.trim($("#mother_maiden_name").val());
       var gender = $.trim($("#gender").val());
       var address_line1 = $.trim($("#address_line1").val());
       var state = $.trim($("#state").val());
       var city = $.trim($("#city").val());
       var pincode = $.trim($("#pincode").val());
       var email = $.trim($("#email").val());
       var comm_address_line1 = $.trim($("#comm_address_line1").val());
       var comm_state = $.trim($("#comm_state").val());
       var comm_city = $.trim($("#comm_city").val());
       var comm_pincode = $.trim($("#comm_pincode").val());
       var auth_code = $.trim($("#auth_code").val());
      
      
      
      if(productId == ""){
          alert('Please specify product.'); 
          $("#product_id").focus();
          return false;
      }
     
      /**** date of birth validation ****/
        if(mobile_country_code == ""){
          alert('Please select mobile country code.'); 
          $("#mobile_country_code").focus();
          return false;
      }else if(mobile == ""){
          alert('Please enter mobile number.'); 
          $("#mobile").focus();
          return false;
      } 
        
        if(!sendAuthButton) {
            var alphaNum = /[^a-zA-Z0-9]/;
            var idtype = $('#Identification_type').val();  
            var adtype = $('#address_proof_type').val();
            var idnum = $('#Identification_number').val();  
            var adnum = $('#address_proof_number').val();
            var id_doc_path = $('#id_doc_path').val();
            var address_doc_path = $('#address_doc_path').val();
          
      if(card_type == ""){
          alert('Please select activation type.'); 
          $("#card_type").focus();
          return false;
      }else if(card_pack_id == ""){
          alert('Please enter card pack ID.'); 
          $("#card_pack_id").focus();
          return false;
      }else if(employee_id == ""){
                alert('Please enter employee ID.'); 
                $("#employee_id").focus();
                return false;
      }else if(first_name == ""){
          alert('Please enter first name.'); 
          $("#first_name").focus();
          return false;
      }else if(last_name == ""){
          alert('Please enter last name.'); 
          $("#last_name").focus();
          return false;
      }else if(mother_maiden_name == ""){
          alert('Please enter mother maiden name.'); 
          $("#mother_maiden_name").focus();
          return false;
      }else if(gender == ""){
          alert('Please select gender.'); 
          $("#gender").focus();
          return false;
      }else if(dob=='' || dob=='00-00-0000') {
            alert('Please specify date of birth');
            $("#date_of_birth").focus();
            return false;
        }else if(address_line1 == ""){
          alert('Please select address.'); 
          $("#address_line1").focus();
          return false;
         }else if(state == ""){
          alert('Please select state.'); 
          $("#state").focus();
          return false;
         }else if(city == ""){
          alert('Please select city.'); 
          $("#city").focus();
          return false;
         }else if(pincode == ""){
          alert('Please select pincode.'); 
          $("#pincode").focus();
          return false;
         }else if(email == ""){
          alert('Please enter email ID.'); 
          $("#email").focus();
          return false;
      }else if(!isValidEmail(email)){
          alert('Please enter valid email ID.'); 
          $("#email").focus();
          return false;
      }else if(employer_name == ""){
          alert('Please enter employer name.'); 
          $("#employer_name").focus();
          return false;
      }else if(corporate_id == ""){
          alert('Please enter corporate ID.'); 
          $("#corporate_id").focus();
          return false;
      }else if(comm_address_line1 == ""){
          alert('Please enter corporate address.'); 
          $("#comm_address_line1").focus();
          return false;
      }else if(comm_state == ""){
          alert('Please enter corporate state.'); 
          $("#comm_state").focus();
          return false;
      }else if(comm_city == ""){
          alert('Please select corporate city.'); 
          $("#comm_city").focus();
          return false;
         }else if(comm_pincode == ""){
          alert('Please select corporate pincode.'); 
          $("#comm_pincode").focus();
          return false;
         }else if(!sendAuthButton && auth_code=='') {
                    alert('Please enter valid Authorization Code.');
                    $("#auth_code").focus();
                    return false;
        }else if(sendAuthButton && auth_code=='') {
                    alert('Please enter valid Authorization Code.');
                    $("#auth_code").focus();
                    return false;
        }else if(dob!='' && dob!='00-00-0000' && !sendAuthButton) {
            var arr_dt = dob.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            var one_year=1000*60*60*24*365
            var age = Math.round((curdate - x)/one_year);
            if(age < 18)
                {
                    alert('You need to be atleast 18 years');
                    $("#date_of_birth").val('');
                    $("#date_of_birth").focus();
                    return false;
                } else {             
                    if (!dob.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                            alert('Invalid Date of Birth');
                            $("#date_of_birth").val('');
                            $("#date_of_birth").focus();
                            return false;
                    }
                }
         }else if (idtype == 'pan'){  
                var panPat = /^([a-zA-Z]{5})(\d{4})([a-zA-Z]{1})$/;
                var code = /([C,P,H,F,A,T,B,L,J,G])/;
                var code_chk = idnum.substring(3,4);
                var pancode_chk = idnum.substring(3,4);
    
                if (idnum.search(panPat) == -1) {
                    alert("Invalid Pan No");
                    $('#pan_number').focus();
                    return false;
                }else if (code.test(code_chk) == false) {
                    alert("Invaild PAN Card No.");
                    $('#pan_number').focus();
                    return false;
                }
            }
            if (idtype == adtype ){
                if (idnum != adnum){
                     alert ('Identification and address proof number do not match');
                     return false;  
                }
            }
            if(idtype == ''){
                   alert('Please select Identification type');
                   $('#Identification_type').focus();  
                   return false;
            }else if(idnum == '' || alphaNum.test(idnum)){
                   alert('Identification number is not alphanumeric');
                   $('#Identification_number').focus();  
                   return false;
            }else if(adtype == ''){
                   alert('Please select Address Proof Type');
                   $('#address_proof_type').focus();  
                   return false;
            }else if(adnum == '' || alphaNum.test(adnum)){
                   alert('Address proof number is not alphanumeric');
                   $('#address_proof_number').focus();  
                   return false;
            }else if( (id_doc_path != '') || (id_doc_path.length > 0) ){
                    var extension = id_doc_path.split('.').pop().toUpperCase();
                    if (extension!="JPG" && extension!="JPEG" && extension!="PDF"){
                        alert('Invalid file extension of Identification Document.\n Please upload only .jpg , .jpeg or .pdf file.');
                        $('#id_doc_path').focus(); 
                        return false;
                    }
                    
              }else if( (address_doc_path != '') || (address_doc_path.length > 0) ){
                    var extension_add_doc = address_doc_path.split('.').pop().toUpperCase();
                    if (extension_add_doc!="JPG" && extension_add_doc!="JPEG" && extension_add_doc!="PDF"){
                        alert('Invalid file extension of Address Document.\n Please upload only .jpg , .jpeg or .pdf file.');
                        $('#address_doc_path').focus(); 
                        return false;
                    }
                    
              }
          return true;
        }
      
    return true;
         
});
    
    
 <?php
    $session = new Zend_Session_Namespace('App.Corporate.Controller');    
 ?>
     var cardholder_auth = <?php echo isset($session->corp_cardholder_auth)?$session->corp_cardholder_auth:0;?>;
     var validated_cardholder_auth = <?php echo isset($session->corp_validated_cardholder_auth)?$session->corp_validated_cardholder_auth:0;?>    

     //alert(cardholder_auth);
     //alert(validated_cardholder_auth);
     
     if(cardholder_auth!='' && cardholder_auth>0){       
         //$("#btn_auth_code").attr("disabled","disabled");
         $("#btn_auth_code").html('Resend Authorization Code');
         //$('#btn_auth_code').after("<a id='resend_auth' href=''> Resend Auth Code</a>").show('slow');
         //$('#resend_auth_code').val('resend');
         

     }   
     
     if(validated_cardholder_auth==1){
         $("#mobile").attr("readonly","readonly");
     }
   </script>