<div class="Boldtext">Cardholder Batch Status</div>

<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Cardholder Batch: '.$this->batch_name;
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';
//$config['addURL'] = '/agents/signup/';

// column names & indexes
$config['columnNames'] = array(
    'Medi Assist Id',
    'Employee Id',
    'Card Number',
    'Name',
    'Name on Card',
    'Gender',
    'Date of Birth',
    'Mobile',
    'Email',
    'Employer Name',
    'Corporate Id',
    'Status',
    'Failed Reason',
    );
$config['columnIndexes'] = array(
    'medi_assist_id',
    'employee_id',
    'card_number',
    'cardholder_name',
    'name_on_card',
    'gender',
    'date_of_birth',
    'mobile',
    'email',
    'employer_name',
    'corporate_id',
    'status',
    'failed_reason',
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("REMIT_STATUS");
?>
<?php echo $this->form; ?> 
<?php if($this->sub):?>  
<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox" style="margin-bottom:10px;">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                    //foreach($dateArr as $item) :?>
            

                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><a href="<?php echo $this->formatURL('/corp_ratnakar_cardholder/view?id='.$item['id'].'&'.$this->backLink);?>"><?php echo $item[$config['columnIndexes'][2]];?></a></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][5]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][6]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]]?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]]?></td>
                        <td><?php  echo $cardholderStatus[$item[$config['columnIndexes'][11]]]?></td>
                        <td><?php  echo $item[$config['columnIndexes'][12]]?></td>
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<?php if(count($this->paginator)>0){?>
<div class="show-xls" style="text-align: right;"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php }
?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php endif;?>
<script>
  $(document).ready(function(){
      
    var batch = $("#batch").val();
   
    if($("#start_date").val() != '' && $("#start_date").val() != ''){
       
      $.ajax({
          url: '/ajax/get-batchbydate/u/'+<?php echo $this->userId;?>+'/q/'+$("#start_date").val()+'/p/'+$("#end_date").val(),
          success: function(response) {
          if(response == 1) {                            
          } else { 
            $("#batch_name").html("");                            
            $("#batch_name").append(response);
            $("#batch_name option[value='"+batch+"']").attr("selected", "selected");
            console.log(response);                            
          }
        }     
      });
    }  
      
      
   
    $("#end_date").change(function(){
        if($("#start_date").val() != ''){
            $.ajax({
                url: '/ajax/get-batchbydate/u/'+<?php echo $this->userId;?>+'/q/'+$("#start_date").val()+'/p/'+$("#end_date").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
                             console.log(response);                            
                        }
                    }     
        });
        }
        
    }); 
    
    $("#start_date").change(function(){
        if($("#end_date").val() != ''){
            $.ajax({
                url: '/ajax/get-batchbydate/u/'+<?php echo $this->userId;?>+'/q/'+$("#start_date").val()+'/p/'+$("#end_date").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batch_name").html("");                            
                            $("#batch_name").append(response);
                             console.log(response);                            
                        }
                    }     
        });
      }
      
    });
    
    $('form').submit(function(){
    
	var from = $.trim($("#start_date").val()); 
	var to = $.trim($("#end_date").val()); 
	//var duration = $("#dur").val();
	
	
	var from_dt = from.split("-");
	var to_dt = to.split("-");
	var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
	var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
	var diff = y - x;
	var one_day=1000*60*60*24;
	var date_range = diff/one_day;
	var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
	/**** From and To date validation ****/
        if (from == '' || to == '') {
                   alert('Please specify both From and To date.');
                   $("#start_date").focus();
                   return false;
        }else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                   alert('Please specify both From and To date.');
                   $("#start_date").focus();
                   return false;
              } else if(diff < 0){
                 alert('From date cannot be greater than To date.');
                   $("#start_date").focus();
                   return false; 
              }
        /**** From and To date validation over ****/
           
        return true; 
     });    
    
    
         
     $("#btn_exportcsv").click(function(){
       
         var url = '<?php echo $this->formatURL("/corp_ratnakar_cardholder/exportbatchstatus?batch_name=".$this->batch_name."&start_date=".$this->start_date."&end_date=".$this->end_date."&status=".$this->status);?>';    
         //alert(url);
         $(location).attr('href',url);
       
    });  
});
</script>
