<div class="Boldtext">Operations Rejected List</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$config = array();
if($this->sub){
// messages
$config['pageTitle'] = 'Operations Rejected List';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found';

// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Last Name',
    'Medi Assist Id',
    'Card Number',
    'Card pack Id',
    'Date of Birth',
    'Mobile',
    'Email'   
    );
$config['columnIndexes'] = array(
    'first_name',
    'last_name',
    'medi_assist_id',
    'card_number',
    'card_pack_id',
    'date_of_birth',
    'mobile',
    'email'
);
$config['viewLinkColumn'] = 'medi_assist_id';
$cntColNames = count($config['columnNames']) ;

$helper = $this->listingUtilities($config);
?>
 
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox" style="clear:both;">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                    <th colspan="2"><span>Action</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
           <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php 
                            //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                            ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php $helper->displayItem($item, $index); ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                               <td>
                                   
                                
                        <?php if ($helper->can('view','corp_ratnakar_cardholder')) {?>
                        <a href="<?php echo $this->formatURL('/corp_ratnakar_cardholder/view?id='.$item['id'])."#user-comment";?>"><?php echo 'View Comments';?></a>
                        <?php } ?>
                                  
                        </td>
                            <td>
                                <?php if ($helper->can('edit','corp_ratnakar_cardholder')) {?>
                                <a href="<?php echo $this->formatURL('/corp_ratnakar_cardholder/edit?id='.$item['id']);?>"><?php echo 'Edit';?></a>
                                <?php } ?>  
                            </td>
                        </tr>    
                    <?php endforeach;?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; 
}?>
</div>
