<div class="Boldtext">Upload Documents: <?php echo $this->item->first_name.' '.$this->item->last_name;?> </div>
<div class="tablebox">
  
    <table style="width: 930px;align:center;">
        
        
        <tr><th style="width:20%">Identification Proof Type</th><td style="width: 80%" align="left"><?php echo $this->item->id_proof_type;?></td></tr>
        <tr><th style="width:20%">Identification Proof Number</th><td style="width: 80%" align="left"><?php echo $this->item->id_proof_number;?></td></tr>
        <tr><th style="width:20%">Address Proof Type</th><td style="width: 80%" align="left"><?php echo $this->item->address_proof_type;?></td></tr>
        <tr><th style="width:20%">Address Proof Number</th><td style="width: 80%" align="left"><?php echo $this->item->address_proof_number;?></td></tr>
        
             
    </table>
   
</div>
    
<?php    
echo $this->form;
?>

<script type="text/javascript" charset="utf-8"> 
   $(document).ready(function() {
}); 
</script>