<script>
  $(document).ready(function(){
     
        $('.cancel').attr('href',document.referrer);
   
});
</script><?php
/**
 * Delete a product
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Delete Transaction Type in Fee Plan: '.$this->name;
$config['areYouSureMessage'] = 'Are you sure you want to delete the Transaction type?';

// column names & indexes
$config['columnNames'] = array(
    'Name',
   
    
);
$config['columnIndexes'] = array(
    'typecode_name',
   
    
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);