<?php
/**
 * Displays all pending agent request
 * @copyright company
 */
//Util::pr($this->paginator,1);

$config = array();
$approveUrl = 'confirmvirtualfundrequset?conformAction=' . STATUS_APPROVED . '&' ;
$rejectUrl = 'confirmvirtualfundrequset?conformAction=' . STATUS_REJECTED . '&' ;
// messages
$config['pageTitle'] = $this->heading;
$config['emptyMessage'] = 'There is no pending virtual fund requests at this time.';

$config['no_add'] = TRUE;
// column names & indexes
$config['columnNames'] = array(
    'Request Date',
    'Agent Code',
    'Agent Name',
    'Agent Virtual Funding Amount (<span class="WebRupee"></span>)',
    'National UTR No.',
);
$config['columnIndexes'] = array(
    'format_date_request',
    'agent_code',
    'agent_name',
    'amount',
    'utr',
);
 

$config['actions'] = array(
    'confirmbeforesettlement' => array(
        'action' => $approveUrl,
        'title' => 'Approve',
        'parameter' => FALSE,
        'icon' => TRUE,
        'img_url' => '/images/icons/approve.png',
        'img_alt' => 'Approve',
    ),
    'confirmbeforerejectfundrequest' => array(
        'action' => $rejectUrl,
        'title' => 'Reject',
        'parameter' => FALSE,
        'icon' => TRUE,
        'img_url' => '/images/icons/reject.png',
        'img_alt' => 'Reject',
    ),
);
$config['linkOrder'] = array('confirmbeforesettlement', 'confirmbeforerejectfundrequest');

echo $this->partial(
        'partials/default-listing.phtml', array(
    'config' => $config,
    'paginator' => $this->paginator,
        )
);

if (count($this->paginator) > 0) {
    echo '<div class="show-xls"><input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv"></div>';
}
?>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btn_exportcsv").click(function () {
            var url = '<?php echo $this->formatURL("/agentfunding/exportvirtualfundrequest"); ?>';
            $(location).attr('href', url);
        });
    });
</script>