<?php

/**
 * Displays all pending agent request
 * @copyright company
 */
//Util::pr($this->paginator,1);
$config = array();

$config['formAction'] = '';
// messages
$config['pageTitle'] = 'Settled Fund Requests';
$config['emptyMessage'] = 'There is no Settled bank statementsat available.';

$config['no_add'] = TRUE;
$config['showActions'] = false;
// column names & indexes

$config['columnNames'] = array(
    'Corporate Code',
    'Corporate Name',
    'Fund Transfer Type',
    'Journal/Cheque No.',
    'Amount',
    'Details',
    'Settled By',
    'Settlement Remarks',
    'Request Date',
    'Settlement Date',
    'Status'
);

$config['columnIndexes'] = array(
    'corporate_code',
    'corporate_name',
    'transfer_type_name',
    'funding_no',
    'amount',
    'funding_details',
    'settlement_by',
    'settlement_remarks',
    'date_request',
    'settlement_date',
    'corporate_funding_status'
);


//$config['linkCol'] = array(
//    array(
//        'linkColName' => 'agent_name',
//        'linkController' => 'agentsummary',
//        'linkAction' => 'view',
//        'linkTitle' => 'View Agent Details',
//        'linkParamReqd' => TRUE,
//        'linkParamName' => 'id',
//        'linkParamValue' => 'agent_id',
//    ),
//);
echo $this->partial(
        'partials/default-listing.phtml', array(
    'config' => $config,
    'paginator' => $this->corporateFunding,
        )
);
if(count($this->agentFunding)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php }  ?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        
            var url = '<?php echo $this->formatURL("/corporatefunding/exportsettledfundrequest");?>';    
            $(location).attr('href',url);
       
    });
    
       
});
</script>