<div class="Boldtext">Bank Status Application List</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
echo $this->form;
// messages
$config['pageTitle'] = 'Bank Status Application';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found';
if(isset($this->paginator)){
// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Last Name',
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Date of Birth',
    'Mobile',
    'Email',
//    'Comments',
    'Bank Status',
    );
$config['columnIndexes'] = array(
    'first_name',
    'last_name',
    'member_id',
    'card_number',
    'card_pack_id',
    'date_of_birth',
    'mobile',
    'email',
//    'comments',
    'status_bank',
);
$config['viewLinkColumn'] = 'member_id';
$cntColNames = count($config['columnNames']) ;



$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>

 
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox" style="clear:both">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                  <th><span>Actions</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
           <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <!--<td class="tc">
                                <input type="checkbox" name="checkall" value="true" />
                            </td>--> 
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php 
                            //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                            ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                    
                                        $helper->displayItem($item, $index);
                                    
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                                <td>
                                    <?php if($item['status_bank'] == STATUS_REJECTED){ ?>
                                
                        <?php if ($helper->can('resubmit','corp_kotak_customer')) {?>
                        <a href="<?php echo $this->formatURL('/corp_kotak_customer/resubmit?id='.$item['id']);?>"><?php echo 'Resubmit';?></a>
                        <?php } ?>
                                    <?php }
                                    else
                                    {
                                        echo '-';
                                    }?>
                                </td>
                                 <td>
                                    <?php if($item['status_bank'] == STATUS_REJECTED){ ?>
                                
                        <?php if ($helper->can('view','corp_kotak_customer')) {?>
                        <a href="<?php echo $this->formatURL('/corp_kotak_customer/view?id='.$item['id']);?>"><?php echo 'View Comments';?></a>
                        <?php } ?>
                                    <?php }
                                    else
                                    {
                                        echo '-';
                                    }?>
                                </td>
                        </tr>    
                    <?php endforeach;?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php } ?>
