<div class="Boldtext">Customer Search</div>
<script>
  $(document).ready(function(){
     
     $("#searchCriteria").change(function(){
         
         $("#keyword").val('');
       });      
       
     $('form').submit(function(){
        var search = $("#searchCriteria").val();
        var keyword = $("#keyword").val();
       
        if(search == ''){
            alert('Search Criteria cannot be blank');
            return false;
        }
       if(keyword == ''){
            alert('Search Keyword cannot be blank');
            return false;
        }
            return true;
});
     });
</script>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Customers';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';
//$config['addURL'] = '/agents/signup/';

// column names & indexes
$config['columnNames'] = array(
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Name',
    'Name on Card',
    'Date of Birth',
    'Mobile',
    'Email',
    );
$config['columnIndexes'] = array(
    'member_id',
    'card_number',
    'card_pack_id',
    'name',
    'name_on_card',
    'date_of_birth',
    'mobile',
    'email',
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>
<?php echo $this->form; ?> 
<?php if($this->sub):?>  
<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                     <th><span>Status</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        
                       <td>
                        <?php if ($helper->can('view','corp_kotak_customer')) {?>
                        <a href="<?php echo $this->formatURL('/corp_kotak_customer/view?id='.$item['id'].'&'.$this->backLink);?>"><?php echo $item[$config['columnIndexes'][0]];?></a>
                        <?php }
                        else {
                            echo $item[$config['columnIndexes'][0]];
                        }?>
                        </td>
                        <td><?php echo util::maskCard($item[$config['columnIndexes'][1]],4);?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][6]]);?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][7]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo Util::getKotakCustStatus(array('status'=> $item['status'],'status_ops'=> $item['status_ops'],'status_bank'=> $item['status_bank'],'status_ecs'=> $item['status_ecs']));?></td>
                       
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php endif;?>