<div class="Boldtext">Delivery File Status</div>
<script>
  $(document).ready(function(){
     var batch = $("#batch").val();
     
 if($("#product_id").val() != ''){
  $.ajax({
                url: '/ajax/get-kotakbatchname/q/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {                            
                        } else {                            
                            $("#batchname").html("");                            
                            $("#batchname").append(response);
                            $("#batchname option[value='"+batch+"']").attr("selected", "selected");
                             console.log(response);                            
                        }
                    }     
        });
 }
     $("#product_id").change(function(){
    
            $.ajax({
                url: '/ajax/get-kotakbatchname/q/'+$("#product_id").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#batchname").html("");
                            $("#batchname").append(response);
                        
                        }
                    },
         
        });
    });       
         
     });
</script>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form; 
$config = array();
if($this->sub){
// messages
$config['pageTitle'] = 'Delivery File Status';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found.';

// column names & indexes
$config['columnNames'] = array(
    'Product Name',
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Date',
    'Delivery Status',
    'Date Registration',
    'Failed Reason',
    'ECS Status'
    );
$config['columnIndexes'] = array(
    'name',
    'member_id',
    'card_number',
    'card_pack_id',
    'delivery_date',
    'delivery_status',
    'date_ecs',
    'failed_reason',
    'status'
);

$cntColNames = count($config['columnNames']) ;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>


<div class="Boldtext"><?php $helper->pageTitle();?></div>
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
              ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo util::maskCard($item[$config['columnIndexes'][2]],4);?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][4]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][5]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][6]]);?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][7]]);?></td>
                        <td><?php echo ucfirst($item[$config['columnIndexes'][8]]);?></td>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif; 
}?>
</div>
