<div class="Boldtext">Pending Customers List</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$config = array();
if($this->sub){
// messages
$config['pageTitle'] = 'Pending Customers List';
$config['no_add'] = TRUE;
$config['emptyMessage'] = 'No record found';

// column names & indexes
$config['columnNames'] = array(
    'First Name',
    'Last Name',
    'Member Id',
    'Card Number',
    'Card pack Id',
    'Date of Birth',
    'Mobile',
    'Email',
    'Bank Status',
    'Submission Date -Maker',
    'Submission Date -Checker',
    'Authorized Date',
    );
$config['columnIndexes'] = array(
    'first_name',
    'last_name',
    'member_id',
    'card_number',
    'card_pack_id',
    'date_of_birth',
    'mobile',
    'email',
    'status_bank',
    'date_created',
    'date_approval',
    'date_authorize',
);
$config['viewLinkColumn'] = 'member_id';
$cntColNames = count($config['columnNames']) ;
$config['actions'] = array(
        'approve'    =>  array(
        'action'        => 'approve',
        'title'         => 'Approve Customer',
        'parameter'     => TRUE,
        'icon'          => TRUE,
        'img_url'       => '/images/icons/approve.png',
        'img_alt'       => 'Approve Customer',
      ),
        'reject'    =>  array(
        'action'        => 'reject',
        'title'         => 'Reject Customer',
        'parameter'     => TRUE,
        'icon'          => TRUE,
        'img_url'       => '/images/icons/reject.png',
        'img_alt'       => 'Reject Customer',
      ),
    );

$config['linkOrder'] = array('approve','reject');
$config['showActions'] = true;


$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$disabled_icons = Zend_Registry::get("DISABLED_ICON_DETAILS");
$cardholderStatus = Zend_Registry::get("CORP_CARDHOLDER_STATUS");
?>

 
<form class="plain" action="" method="post" enctype="multipart/form-data"> 
<div class="tablebox" style="clear:both;">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                  <th><span>Actions</span></th>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
           <?php foreach($this->paginator as $item) : ?>
                        <?php $helper->data = $item; ?>
                        <tr>
                            <!--<td class="tc">
                                <input type="checkbox" name="checkall" value="true" />
                            </td>--> 
                            <?php /********** displaying the inner columns **********/ ?>
                            <?php 
                            //echo "<pre>";print_r($helper->getColumnIndexes());exit;
                            ?>
                            <?php foreach($helper->getColumnIndexes() as $index): /* start displaying columns */?>
                                <td>
                                    <?php 
                                    
                                        $helper->displayItem($item, $index);
                                    
                                    ?>
                                </td>
                            <?php endforeach;?>
                            <?php /********** finished displaying the inner columns **********/ ?>
                            <?php if(!isset($this->config['showActions']) || (isset($this->config['showActions']) && $this->config['showActions'])) : ?>
                                <!--<td style="margin:0; padding:0;">
                                    <div class="iconbox">-->
                                    <?php echo $helper->links($item);
                                    ?>
                                    <!--</div>
                                </td> -->
                            <?php endif; ?>
                        </tr>    
                    <?php endforeach;?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
    
</form>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
    
        <?php echo $this->paginator; ?>
    <?php endif;
}?>
</div>
<script type="text/javascript">
$(document).ready(function() {

 
 var pincode = $("#pin").val();

 if($("#state").val() != ''){
         $.ajax({
                url: '/ajax/get-pincode-list-by-state/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                         
                        } else {
                            
                            $("#pincode").html("");
                            
                            $("#pincode").append(response);
                             $("#pincode option[value='"+pincode+"']").attr("selected", "selected");
                            console.log(response);
                         

                        }
                    },
         
        });
}  
   
  $("#state").change(function(){
    
            $.ajax({
                url: '/ajax/get-pincode-list-by-state/q/'+$("#state").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                            $("#pincode").html("");
                            $("#pincode").append(response);
                        }
                    },
         
        });
    }); 
    
    

});      
</script>