<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Rejected Agents Listing';

$config['emptyMessage'] = 'There is no rejected agent list at this time.';

$config['no_add']=1;  //to not have add button
// column names & indexes
$config['columnNames'] = array(
    
    'Name',
    'Agent Code',
    'Email',
    'Mobile no.',
    'Registration Date',
    'Action'

);
$config['columnIndexes'] = array(
    
    'name',    
    'email',
    'agent_code',
    'mobile1',
    'reg_datetime',
   // 'status'
    
);
?>
<div class="Boldtext">Show Rejected Agents</div>

 <div class="tablebox">
            <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <thead><!-- universal table heading --> 
                    <tr>
                        <?php /********** display the column names **********/ ?>
                        <?php foreach($config['columnNames'] as $columnName) : ?>
                            <th><span><?php echo $columnName;?></span></th>
                        <?php endforeach;?>
                        <?php /********** finished displaying the column names **********/ ?>
                    </tr> 
                </thead>
                <tbody>

                <?php /********** do we have items? **********/ ?>
                <?php if (count($this->paginator)) : ?>
				           <?php 
				            foreach($this->paginator as $item) : 
				                ?>
			                    <?php /********** we do! start displaying the items **********/ ?>
			                    
			                    		<tr>
			
							                    <?php /********** displaying the inner columns **********/ 
							                        
							                        ?>
							                        <td><?php 
                                                                                $url = '/agentsummary/view?id='.$item['id'].'&searchCriteria=email&keyword='.$item['email'];
                                                                                //echo $item[$config['columnIndexes'][0]];
                                                                                echo '<a href="'. $this->formatURL($url) . '" title="Agent Summary">'.$item[$config['columnIndexes'][0]].'</a>'
                                                                                ?></td>
							                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
							                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
							                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
							                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                                                                                <td><a href="<?php echo $this->formatURL('/agentsummary/block?id='.$item['id']) ?>" title="Block Agent"><img src='<?php echo $this->_baseUrl . '/images/icons/reject.png'; ?>' alt="reject" border="0"/>&nbsp;</a></td>
							                    <?php /********** finished displaying the inner columns **********/ ?>
							                </tr>    		
				                <?php endforeach;?>
                    <?php /********** finished displaying the items **********/ ?>
                <?php else:?>
                    <?php /********** we don't have any items **********/ ?>
                    <tr>
                          <td colspan="<?php echo count($config['columnIndexes'])+1;?>">
					                    <?php echo $config['emptyMessage'];?>
					                </td>
                    </tr>
                <?php endif;?>
                <?php /********** finished do we have items? **********/ ?>
                </tbody> 
            </table>
        </div>
    </div>
</div>
<?php if(count($this->paginator) > 0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>
<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
</div>
<?php }?>

<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
            var url = '<?php echo $this->formatURL("/aml/exportamlrejectedagents");?>';    
            $(location).attr('href',url);
   
    });
});
</script>