<?php
/**
 * Displays an user
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */
$config = array();

// messages
//$config['pageTitle'] = 'Beneficiary Listing for: '.$this->remitterdetails['name'];
$config['addMessage'] = 'Show Boi Beneficiaries';

$config['emptyMessage'] = 'No records found.';

$config['columnNames'] = array(
    'Name',
    'Registration Date',
    'Email',
    'AML',
    'Status'
);

$config['columnIndexes'] = array(
    'name',
    'email',
    'date_created',
    'is_aml',
    'status'
);
?>

<div class="Boldtext">Show Boi Beneficiaries</div>
<div class="filterbox"> 
    <div style="width:950px;">
        <a href="<?php echo $this->formatURL('/aml/boiindex'); ?>" class="ocean" style="float:right;" title="Back">Back</a>
    </div>
</div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
        <table width="950" cellspacing='0'>
            <thead><!-- universal table heading --> 
                <tr>
                    <?php /*                     * ******** display the column names ********* */ ?>
                    <?php foreach ($config['columnNames'] as $columnName) : ?>
                        <th><span><?php echo $columnName; ?></span></th>
                    <?php endforeach; ?>
                    <?php /*                     * ******** finished displaying the column names ********* */ ?>
                </tr> 
            </thead>
            <tbody>

                <?php /** ******** do we have items? ********* */ ?>
                <?php if (count($this->paginator)) : ?>
                    <?php
                    foreach ($this->paginator as $item) :
                        ?>
                        <?php /** ******** we do! start displaying the items ********* */ ?>

                        <tr>

                            <?php /********* displaying the inner columns ********* */ ?>
                            <td><?php echo $item[$config['columnIndexes'][0]]; ?></td>
                            <td><?php echo $item[$config['columnIndexes'][2]]; ?></td>
                            <td><?php echo $item[$config['columnIndexes'][1]]; ?></td>
                            <td><?php if ($item[$config['columnIndexes'][4]]) {
                        echo '<a href="' . $this->formatURL('/aml/boibeneficiarydetail?id=' . $item['id']) . '" title="">' . PHP_EOL . '<img alt="Warning" src="' . $this->baseUrl() . '/images/icons/warning-icon.png" border="0"></a>';
                    } ?></td>
                            <td><?php
                                if ($item[$config['columnIndexes'][3]]) {
                                    if ($item[$config['columnIndexes'][4]] == "active") {
                                        echo '<a href="' . $this->formatURL('/aml/boibeneficiaries?status=inactive&id=' . $item['id']) . '" title="">Inactive</a>';
                                    } else {
                                        echo '<a href="' . $this->formatURL('/aml/boibeneficiaries?status=active&id=' . $item['id']) . '" title="Active">Active</a>';
                                    }
                                } else {
                                    echo $item[$config['columnIndexes'][4]];
                                }
                                ?>
                            </td>
                        <?php /********* finished displaying the inner columns ********* */ ?>
                        </tr>    		
                    <?php endforeach; ?>
                    <?php /*                     * ******** finished displaying the items ********* */ ?>
<?php else: ?>
                            <?php /** ******** we don't have any items ********* */ ?>
                    <tr>
                        <td colspan="<?php echo count($config['columnIndexes']) + 2; ?>">
                    <?php echo $config['emptyMessage']; ?>
                        </td>
                    </tr>
<?php endif; ?>
<?php /* * ******** finished do we have items? ********* */ ?>
            </tbody> 
        </table>
    </div>
</div>
</div>
    <?php if (count($this->paginator) > 0) { ?>
    <div class="pagination">
        <?php if ($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
    </div>
<?php } ?>

<?php if (count($this->paginator) > 0) { ?>
    <div class="show-xls"> 
        <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
    </div>
<?php } ?>


<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_exportcsv").click(function() {
            var url = '<?php echo $this->formatURL("/aml/exportboibeneficiaries"); ?>';
            $(location).attr('href', url);
        });
    });
</script>