<?php
/**
 * Displays an user
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */
$config = array();


// messages
$config['addMessage'] = 'Show Kotak Corp Card Holders';

$config['emptyMessage'] = 'No record(s) found.';


$config['columnNames'] = array(
    'Name',
    'Card No.',
    'Member Id',
    'Mobile No.',
    'Registration Date',
    'AML',
    'Action'
);
$config['columnIndexes'] = array(
    'name',
    'card_number',
    'member_id',
    'mobile',
    'date_created',
    'is_aml',
    'status'
);

// render the default listing
?>

<div class="Boldtext">Show Kotak Corp Card Holders</div>
<div class="filterbox"> 
    <div style="width:950px;">
        <a href="<?php echo $this->formatURL('/aml/bankindex'); ?>" class="ocean" style="float:right;" title="Back">Back</a>
    </div><!--Inner Style Div END-->
</div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
        <table width="950" cellspacing='0'>
            <thead><!-- universal table heading --> 
                <tr>
<?php /* * ******** display the column names ********* */ ?>
<?php foreach ($config['columnNames'] as $columnName) : ?>
                        <th><span><?php echo $columnName; ?></span></th>
                    <?php endforeach; ?>
                    <?php /*                     * ******** finished displaying the column names ********* */ ?>
                </tr> 
            </thead>
            <tbody>

<?php /* * ******** do we have items? ********* */ ?>
<?php if (count($this->paginator)) : ?>
    <?php
    foreach ($this->paginator as $item) :
        ?>
                        <?php /*                         * ******** we do! start displaying the items ********* */ ?>

                        <tr>

                        <?php /*                         * ******** displaying the inner columns ********* */
                        ?>
                            <td><?php echo $item[$config['columnIndexes'][0]]; ?></td>
                            <td><?php echo Util::maskCard($item[$config['columnIndexes'][1]], 4); ?></td>
                            <td><?php echo $item[$config['columnIndexes'][2]]; ?></td>
                            <td><?php echo $item[$config['columnIndexes'][3]]; ?></td>
                            <td><?php echo $item[$config['columnIndexes'][4]]; ?></td>
                            <td><?php if ($item[$config['columnIndexes'][5]]) {
                        echo '<a href="' . $this->formatURL('/aml/kotakcardholderdetail?id=' . $item['id']) . '" title="">' . PHP_EOL . '<img alt="Warning" src="' . $this->baseUrl() . '/images/icons/warning-icon.png" border="0"></a>';
                    } ?></td>

                            <td><?php
                    if ($item[$config['columnIndexes'][6]] == "active") {
                        echo '<a href="' . $this->formatURL('/aml/kotakcardholders?status=inactive&id=' . $item['id']) . '" title="Inactive"><img border="0" alt="reject" src="/images/icons/reject.png"></a>';
                    } else {
                        echo '<a href="' . $this->formatURL('/aml/kotakcardholders?status=active&id=' . $item['id']) . '" title="Active"><img border="0" alt="approve" src="/images/icons/approve.png"></a>';
                    }
                        ?>
                            </td>
                                <?php /*                                 * ******** finished displaying the inner columns ********* */ ?>
                        </tr>    		
                        <?php endforeach; ?>
                        <?php /*                         * ******** finished displaying the items ********* */ ?>
                <?php else: ?>
                    <?php /*                     * ******** we don't have any items ********* */ ?>
                    <tr>
                        <td colspan="<?php echo count($config['columnIndexes']) + 1; ?>">
                    <?php echo $config['emptyMessage']; ?>
                        </td>
                    </tr>
                        <?php endif; ?>
<?php /* * ******** finished do we have items? ********* */ ?>
            </tbody> 
        </table>
    </div>
</div>
</div>
<?php if (count($this->paginator) > 0) { ?>
    <div class="pagination">
    <?php if ($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
        <?php endif; ?>
    </div>
    <?php } ?>
    <?php if (count($this->paginator) > 0) { ?>
    <div class="show-xls"> 
        <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
    </div>
<?php } ?>


<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_exportcsv").click(function() {
            var url = '<?php echo $this->formatURL("/aml/exportkotakcardholders"); ?>';
            $(location).attr('href', url);

        });
    });
</script>