<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<?php 

$config = array();
$config['pageTitle'] = 'Add Beneficiary for: '.$this->remitter_name;

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);



$session = new Zend_Session_Namespace('App.Agent.Controller'); 

$bankList = new BanksIFSC();
$bankListOptions = $bankList->getBank();
array_shift($bankListOptions);


?>

<script type="text/javascript">
  $(document).ready(function() {
      var beneficiary_auth = <?php echo isset($session->beneficiary_auth)?$session->beneficiary_auth:0;?>;
      var ifsc = $("#ifsc").val();
      var bank = $("#bank_name").val(); 
       if($("#ifsc").val() != ''){
             $.ajax({
                url: '/ajax/get-bankdetails/q/'+$("#ifsc").val()+'/t/imps',
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            var resArr = response.split('^');
                         var resArr = response.split('^');
                        $("#bank_name").html("<option value='"+resArr['0']+"'>"+resArr['0']+"</option>");    
                       	$("#bank_state").html("<option value='"+resArr['1']+"'>"+resArr['1']+"</option>");    
                        $("#branch_city").html("<option value='"+resArr['2']+"'>"+resArr['2']+"</option>");    
                        $("#branch_name").html("<option value='"+resArr['3']+"'>"+resArr['3']+"</option>");    
                        $("#branch_address").val(resArr['4']);
                            
                        }
                    }
         
        });
     }
     if($("#bank_name").val() != ''){
     $.ajax({
                url: '/ajax/get-ifsc/q/'+$("#bank_name").val()+'/t/imps',
                    success: function(response) {
                        if(response == 1) {
                          
                        } else {
                            
                            $("#ifsc_code").html("");                           
                            $("#ifsc_code").append(response);
                            
                            if(beneficiary_auth!='' && beneficiary_auth>0){  
                            var optionsIfsc = document.getElementById('ifsc_code').options;
                        
                            for (var i=0, iLen=optionsIfsc.length; i<iLen; i++) {
                              optionsIfsc[i].disabled = true;}
                           
                            $("#ifsc_code option[value='"+ifsc+"']").removeAttr('disabled');
                            }
                             $("#ifsc_code option[value='"+ifsc+"']").attr("selected", "selected");
                            
                        }
                    }
         
        });
     }
   
      
    $('form').submit(function() {
    	if(!validateBeniForm()){
   				return false;
   			}  
var acountno = $("#bank_account_number").val();
var confacountno = $("#conf_bank_account_number").val();

if(acountno != confacountno){
    alert('Account No. and confirm Account No. values do not match');
    return false;
}
else {
    return true;
}

}); 
   $("#btn_auth_code").click(function() { 
    	
   $("#send_auth_code").val('1');           
   $("form").submit();
   });
     
 
     if(beneficiary_auth!='' && beneficiary_auth>0){       
         
         $("#btn_auth_code").html('Resend Beneficiary Authorization Code');
         $("#name").attr('readOnly', 'readOnly');
         $("#nick_name").attr('readOnly', 'readOnly');
         $("#branch_name").attr('readOnly', 'readOnly');
         $("#bank_account_number").attr('readOnly', 'readOnly');
         $("#conf_bank_account_number").attr('readOnly', 'readOnly');
         var optionsBank = document.getElementById('bank_name').options;
        for (var i=0, iLen=optionsBank.length; i<iLen; i++) {
         optionsBank[i].disabled = true;
            }  
       $("#bank_name option[value='"+bank+"']").removeAttr('disabled');
       } 
       $( "#ifsc_code" ).focusout(function() {
	  		if(this.value==""){
	  			return false;
	  		}
         $.ajax({
            url: '/ajax/get-bankdetails/q/'+this.value+'/t/imps',
                success: function(response) {
                    if(response == 1) {
                      alert("IFSC Code does not exist");
                      $("#ifsc_code").val("");  
                    } else {
                        var resArr = response.split('^');
                        $("#bank_name").html("<option value='"+resArr['0']+"'>"+resArr['0']+"</option>");    
                       	$("#bank_state").html("<option value='"+resArr['1']+"'>"+resArr['1']+"</option>");    
                        $("#branch_city").html("<option value='"+resArr['2']+"'>"+resArr['2']+"</option>");    
                        $("#branch_name").html("<option value='"+resArr['3']+"'>"+resArr['3']+"</option>");    
                        $("#branch_address").val(resArr['4']);
                        
                    }
                }
     
    		});
			
		});
			 $("#bank_name").change(function(){
    
            $.ajax({
                url: '/ajax/get-state/q/'+$("#bank_name").val(),
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#bank_state").html("");
                            $("#bank_state").append(response);
                        
                        }
                    },
         
        });
    }); 
		$("#bank_state").change(function(){
    
            $.ajax({
                url: '/ajax/get-cities/q/'+$("#bank_name").val()+'/r/'+this.value,
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#branch_city").html("");
                            $("#branch_city").append(response);
                        
                        }
                    },
         
        });
    }); 
    $("#branch_city").change(function(){
    
            $.ajax({
                url: '/ajax/get-branches/q/'+$("#bank_name").val()+'/i/'+this.value,
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                            $("#branch_name").html("");
                            $("#branch_name").append(response);
                        
                        }
                    },
         
        });
    }); 
     $("#branch_name").change(function(){
    
            $.ajax({
                url: '/ajax/get-branchadd/q/'+$("#bank_name").val()+'/i/'+this.value+'/t/imps',
                    success: function(response) {
                        if(response == 1) {
                        } else {
                        
                           var resArr = response.split('^');
	                          $("#branch_address").val(resArr['0']);
	                          $("#ifsc_code").val(resArr['1']);
                        
                        }
                    },
         
        });
    }); 
    
			
			
       
});  

function validateBeniForm(){
	
			var regex = /^[a-zA-Z\s]+$/;
			var mob = /^[1-9]{1}[0-9]{9}$/;
   		var acountno = $("#bank_account_number").val();
			var confacountno = $("#conf_bank_account_number").val();
			
			
			if($.trim($('#name').val())==""){
   			alert("Please Enter Beneficiary Name");
   			$('#name').focus();
   			return false;
   		}else if($('#name').val().length <= 1){
   			alert("Beneficiary name should be more than 2 characters");
   			$('#name').focus();
   			return false;
   		}else if(!regex.test($('#name').val())){
   			alert("Beneficiary name contains non alphabetic characters");
   			$('#name').focus();
   			return false;
   		}else if($.trim($('#nick_name').val())==""){
   			alert("Please Enter Beneficiary Nick Name");
   			$('#nick_name').focus();
   			return false;
   		}else if($('#nick_name').val().length <= 1){
   			alert("Beneficiary nick name is less than 2 characters long");
   			$('#nick_name').focus();
   			return false;
   		}else if(!regex.test($('#nick_name').val())){
   			alert("Beneficiary nick name contains non alphabetic characters");
   			$('#nick_name').focus();
   			return false;
   		}else if(mob.test($.trim($("#mobile").val())) == false) {
					alert("Please enter valid mobile number.");
					$('#mobile').focus();
   				return false;
   		}else if($.trim($('#address_line1').val())==""){
   			alert("Please Enter Address Line 1");
   			$('#address_line1').focus();
   			return false;
   		}else if($.trim($('#ifsc_code').val())==""){
   			alert("Please Enter IFSC Code");
   			$('#ifsc_code').focus();
   			return false;
   		}else if($('#bank_name').val()==""){
   			alert("Please Enter Bank Name");
   			$('#bank_name').focus();
   			return false;
   		}else if($('#bank_state').val()==""){
   			alert("Please Enter Branch State");
   			return false;
   		}else if($('#branch_city').val()==""){
   			alert("Please Enter Branch City");
   			return false;
   		}else if($('#bank_account_type').val()==""){
   			alert("Please Enter Account Type");
   			return false;
   		}else if($('#bank_account_number').val()==""){
   			alert("Please Enter Bank Account No. ");
   			return false;
   		}else if($('#conf_bank_account_number').val()==""){
   			alert("Please Enter Confirm Bank Account No. ");
   			return false;
   		}else	if(acountno != confacountno){
			    alert('Account No. and confirm Account No. values do not match');
			    return false;
			}else{
                            var ifsccode =  $.trim($('#ifsc_code').val());
                            $('#ifsc_code').val(ifsccode);
				return true;
			}
}  
</script>
