<?php
/**
 * View for the login action
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */
?>
<div class="toplogbg">
                <div class="confirm-details">Authorization Code</div>
            </div>
            <div class="middlebg">

            <div class="div1">
        <?php if (isset($this->resent)):?>
            <div class="error">
                <p><?php echo '<strong>Oops!</strong><br />Authorization Code Resent Sucessfully';?></p>
            </div>
        <?php endif;?>
        <?php if (isset($this->notresent)):?>
            <div class="error">
                <p><?php echo '<strong>Oops!</strong><br /> Authorization Code could not be resent';?></p>
            </div>
        <?php endif;?>
        <?php if (isset($this->error)):?>
            <div class="error">
                <p><?php echo '<strong>Oops!</strong><br />Invalid Authorization Code. You have '.$this->num.' login attempts remaining.';?></p>
            </div>
        <?php endif;?>
        <?php if (isset($this->empty)):?>
            <div class="error">
                <p><?php echo '<strong>Oops!</strong><br />Authorization Code.';?></p>
            </div>
        <?php endif;?>
       <?php if (isset($this->locked)):?>
            <div class="error">
                <p><?php echo '<strong>Oops!</strong><br />Your Account is Locked. Please contact the Operation Help Center.';?></p>
            </div>
        <?php endif;?>
        <div class="agentbox">

            <div  style="font-family:Arial, Helvetica, sans-serif; font-size:14px; margin-top:99px; font-weight:bold; text-align:center;">OPERATIONS LOGIN</div>

            </div>
        <?php echo $this->form;?>
          <div class="div3">
             <div class="link2"><a href='<?php echo $this->formatURL("/profile/resend-authcode/");?>'>Resend Authorization Code</a></div>
 
        </div>

    
    </div>
                <div class="clear"></div>
            </div>
<script type="text/javascript">
$(document).ready(function() {
    
  $("#resend").click(function(){
         document.getElementById('resend').style.cursor = 'wait';
         document.getElementById('submit').style.cursor = 'wait';
         document.body.style.cursor = 'wait';
            $.ajax({
                url: '/profile/resend-authcode',
                    success: function(response) {
                        if(response == 1) {
                            
                        } else {
                            
                            alert('Auth code Resent!');
                            
                              document.getElementById('resend').style.cursor = 'default';
                              document.getElementById('submit').style.cursor = 'default';
                              document.body.style.cursor = 'default';
                     
                        }
                    }
         
        });
    });   
    
    
    
    
    
     
});      
  </script>

