<?php
/**
 * View that allows the user to change his/her password
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */

$config = array();

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);
?>

<script type="text/javascript">
$(document).ready(function() {  
    var alphaNumFilter = /^.*(?=.{7,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[=!:.#%&*()$@=<>,.?-])(^[a-zA-Z0-9@\$=!:.#%&*()=<>,.?-]+$)/;
         //^.*(?=.{7,20})(?=.*\d)(?=.*[A-Z])(^[a-zA-Z0-9@\$=!:.#%&*()=<>,.?-_]+$
    
    $('form').submit(function(){
        
       /**** password field validation, Password must be 7 to 20 chars long including alteast one small char, one capital char,
        one digit and one special char *****/
       var password = $("#password").val();

           if(alphaNumFilter.test(password)==false){
              alert('Password must be 7 to 20 chars long including alteast one capital letter, one digit and one special character (any of =!:.#%&*()$@=<>,.?-)');
              $("#password").focus();
              return false;
           } 
       
       /**** password field validation over here *****/
    });     
});
</script>