<div style="margin: auto 0px; border: 1px solid red">
    <div class="Boldtext" style="text-align: center;">"For those who dare to dream, there is a whole world to win… </div>
<div>
        <div class="Boldtext"><b>About Us</b></div>
        <div class="landing dotted-vertical">
            TranServ was formed with the primary objective to offer <b>end to end Prepaid Program Management Service</b> using Cards and Mobile Technology. We have been engaged by  multiple banks to create and distribute various financial products and services.  
We appoint business partners who are located across India to source new customers and enable them to transact electronically. <a href="#">Know  more</a>
        </div>
       
    </div>

<div class="clearfix"></div>    
</div>


    
    <div class="index-right-box landing-bold"><span style="float:right;">Enable customers to transact online</span></div>
    
    <div class="index-left-box">Dream and dare." </div>
    <div class="index-right-box landing-bold"><span style="float:right;">Be an enabler for e-commerce revolution in India</span></div>
    
    <div class="clear"></div>
    <div class="index-left-box"><a class="ocean" href="<?php echo $this->formatURL('/signup/index/');?>" style="float:left; font-size: 14px;padding:20px;" title="Register Now and <br/>Start Making Money">Register Now and <br/>Start Making Money</a></div>
    <div class="index-right-box landing-bold"><span style="float:right;"><a href="<?php echo $this->formatURL('/signup/index/');?>">Become a Shmart! Business Partner</a> for TranServ and Start Making Money</span></div>

    <div class="clear"></div>
    <div class="dotted"></div>

    
    <div class="index-right-box">
        <div class="landing-bold">Contact Us</div>
        <div class="landing"> <a href="mailto:partner@shmart.in">partner@shmart.in</a><br/>
         Customer Care Number: <?php echo AGENT_AUTH_CALL_CENTRE_NUMBER;?><br/>
        </p>

        <p><div class="landing-bold">Safe and Secure</div>
            <a href="#" title="www.shmart.in">www.shmart.in</a> is a safe and secure website.
        </p>
        </div>
    </div>