<?php
/**
 * Displays the user's dashboard
 *
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_profile
 * @copyright company
 */
   $dataArr = "[['Date', 'Amount'],";
   $dataArr .= $this->agentStats['agent_remittance'];
   $dataArr .= "]";
    
   $datargnArr = "[['Date', 'No. of Remitters'],";
   $datargnArr .= $this->agentStats['agent_remittersrgn'];
   $datargnArr .= "]";
   
   $datacommArr = "[['Date', 'Commission Amount'],";
   $datacommArr .= $this->agentStats['agent_commission'];
   $datacommArr .= "]";
   
    $agentBal = isset($this->agentStats['agentBal'])?$this->agentStats['agentBal']:0;
    ?>


<!--First Row-->
<div class="today_date"><?php echo Util::getFormattedDate('F d, Y');?></div>
<div style ="clear:both;"></div>
<div class="grid-heading">General Updates</div>

<div class="grid3col">
  <div class="column first">
      <div class="column-heading">My balance</div>
    <?php echo CURRENCY_INR.' '.Util::numberFormat($agentBal);?>      
  </div>
  
</div>
