<?php
/**
 * Holds the default paginator view
 *
 *
 * @category backoffice
 * @package backoffice_paginators
 * @copyright company
 */

$par = Zend_Controller_Front::getInstance()->getRequest()->getParams();
$new_array = array();
foreach($par as $key=>$val) {
	if($key!='page' && $key!='a' && $key!='csrfhash') {
		$new_array[$key] = $val;
	}
}
?>

<?php if ($this->pageCount): ?>
    <ul class="pagination paginationA paginationA01">
         <li>
        <!-- Range page link -->
       
                   
         <a class="first" href="#">Page 1 to <?php echo $this->pageCount;?></a>
        </li>
        <li>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a class="text" href="<?php echo Util::formatURLforPaginator($this->url(array_merge($new_array,array('page' => $this->previous)))); ?>"> ← Previous</a>
            
        <?php  else: ?>
            <span class="disabled"> ← Previous</span>
        <?php  endif; ?>
        </li>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo Util::formatURLforPaginator($this->url(array_merge($new_array,array('page' => $page)))); ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <span class="current"><?php echo $page; ?></span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <li>
        <?php if (isset($this->next)): ?>
            <a class="text" href="<?php echo Util::formatURLforPaginator($this->url(array_merge($new_array,array('page' => $this->next)))); ?>">Next →</a>
        <?php  else: ?>
            <span class="disabled">Next →</span>
        <?php  endif; ?>
    </li>
    </ul>
<?php endif; ?>