<div class="Boldtext">Sample Load</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
//$duration = isset($this->duration)?$this->duration:'';

if($this->records){
$bankUnicodeArr = Util::bankUnicodesArray();    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';//'Cardholder Activations Report for period '.$duration;
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Card Number',
    'Card PackID',
    'Cardholder Name',
    'CRN',
    'Mobile Number',
    'Product Code',
    'Address 1',
    'Address 2',
    'City',
    'State',
    'Pin',
    'Country',    
    'Channel'
    //'Address',
    
      
);

$config['columnIndexes'] = array(
    'date_created',
    'card_number',
    'card_pack_id',
    'cardholder_name',
    'crn',
    'mobile',
    'product_name',
    'corp_address_line1',
    'corp_address_line2',
    'corp_city',
    'corp_state',
    'corp_pin',
    'corp_country',
    'channel'
    //'address_line1', 
    //'agent_pincode',         
);

$config['showActions'] =FALSE;
//$config['duration'] = $this->formData['dur'];
$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox" style="margin-bottom:10px;">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0' >
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                    //foreach($dateArr as $item) :?>
                <tr>

                    <?php /********** displaying the inner columns **********/ 
                    			
                    ?>
																
                     <td><?php echo $item[$config['columnIndexes'][0]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][1]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][2]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][3]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][4]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][5]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][6]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][7]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][8]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][9]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][10]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][11]];?></td> 
                     <td><?php echo $item[$config['columnIndexes'][12]];?></td> 
                     <td><?php echo ucfirst($item[$config['columnIndexes'][13]]);?></td> 
             
                        
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>

<?php if(count($this->paginator)>0){?>
<div class="show-xls" style="text-align: right;"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php }  ?>

<?php
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } }?>




<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
	var dur = '<?php echo $this->formData['dur'];?>';
	var url = '<?php echo $this->formatURL("/corp_ratnakar_reports/exportsampleload?to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date'].'&product_id='.$this->formData['product_id'].'&bank_unicode='.$this->formData['bank_unicode'].'&status='.$this->formData['status'].'&department='.$this->formData['department'].'&location='.$this->formData['location']);?>'; 
	//alert(url);
	$(location).attr('href',url);
    });
     //alert("sdfsdf");
    $('#corp_ratnakar_reports-sampleload').submit(function(){
    
	var from = $.trim($("#from_date").val()); 
	var to = $.trim($("#to_date").val()); 
	var product_id = $("#product_id").val();
	
	
	var from_dt = from.split("-");
	var to_dt = to.split("-");
	var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
	var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
	var diff = y - x;
	var one_day=1000*60*60*24;
	var date_range = diff/one_day;
	var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
	/**** From and To date validation ****/
	
	if(product_id == ''){	   
		   alert('Please specify Product.');
                   return false;
	}else if(from == '' || to == ''){	   
		   alert('Please specify both From and To date.');
                   $("#from_date").focus();
                   return false;
	}else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000')) || ((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                   alert('Please specify both From and To date.');
                   $("#from_date").focus();
                   return false;
              } else if(diff < 0){
                 alert('From date cannot be greater than To date.');
                   $("#from_date").focus();
                   return false; 
              }
              else if(date_range > max_range){
                 alert('Report can be fetched for a duration not more than '+max_range+' days');
                   $("#to_date").focus();
                   return false; 
              }
             
      /**** From and To date validation over ****/
         
    return true; 
   });    
});
</script>