<div class="Boldtext">Kotak Remittance</div> 
<?php
echo $this->form;

if (!empty($this->paginator)) {

    $config = array();

    // messages
    $config['pageTitle'] = 'Transactions';
    $config['no_add'] = TRUE;
    if($this->showBackLink){
    	$config['back_url'] = '/remit_kotak_beneficiary/searchremitter?flgSess=1';
    }
    $config['showActions'] = FALSE;
    $config['emptyMessage'] = 'There is no transaction associated with this phone number.';

   
    $config['columnNames'] = array(
        'Transaction Date',        
        'Reference No.',
        'Remitter Name',
        'Beneficary Name',
        'Amount',
        'Status'
    );
    $config['columnIndexes'] = array(
        'date_created',
        'txn_code',
        'name',
        'beneficiary_name',
        'amount',
        'status',
    );

$config['actions'] = array();
$config['showComma'] = array('amount');
$helper = $this->listingUtilities($config);
$addURL = isset($config['addURL']) ? $config['addURL'] : '' ;
$addbutton = isset($config['no_add']) ? $config['no_add'] : '' ;
$cntColNames = count($config['columnNames']) - 1;

?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            
            foreach($this->paginator as $item) : 
                   $datePrev = '';?>
                
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][0]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][4]]);?></td>
                        <td><?php if( $helper->can('transactioninfo','remit_kotak_remitter')){
                            ?> <a href="<?php echo $this->formatURL("/remit_kotak_remitter/transactioninfo?txn_code=".$item['txn_code']."&mobile=".$this->formData['mobile']."&id=".$item['id']);?>" title="See agent commissions"><?php echo $item[$config['columnIndexes'][5]];?></a>
                            <?php } else echo $item[$config['columnIndexes'][5]]; ?>
                        </td>
                        
                        
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } }
?>