<div class="Boldtext">Bulk Upload of Card Load</div>
<?php
echo $this->form;
if ($this->records) {
    $config['pageTitle'] = 'Bulk Upload of Card Load';
    $config['no_add'] = TRUE;
    $itemPerPage = $this->items_per_page;
// column names & indexes
    $config['columnNames'] = array(
        'Txn Identifier Type',
        'Card Number',
        'Member Id',
        'Employee Id',
        'Amount',
        'Currency',
        'Narration',
        'Wallet Code',
        'Txn Number',
        'Card Type',
        'Corporate Id',
        'Mode'
    );
    $config['columnIndexes'] = array(
        'txn_identifier_type',
        'card_number',
        'member_id',
        'employee_id',
        'amount',
        'currency',
        'narration',
        'wallet_code',
        'txn_no',
        'card_type',
        'corporate_id',
        'mode'
    );




// render the default listing


    /**
     * Displays all the user groups
     *
     * @package backoffice_views
     * @subpackage backoffice_views_privileges
     * @copyright company
     */
// messages
    $config['emptyMessage'] = 'No record found.';
    $config['no_add'] = 1;

    $cntColNames = count($config['columnNames']) - 1;
    $helper = $this->listingUtilities(array());
// render the default listing
    ?>

    <?php /** ******** do we have items? ********* */ ?>
    <?php if (count($this->failedpaginator)) : ?>
    <div class="Boldtext">Failed Wallet Details</div>
    <div class="tablebox">
        <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <thead><!-- universal table heading --> 
                    <tr>
                        <?php /*                         * ******** display the column names ********* */ ?>
                        <?php foreach ($config['columnNames'] as $columnName) : ?>
                            <th><span><?php echo $columnName; ?></span></th>
                        <?php endforeach; ?>
                        <th>Failed Reason</th>
                        <?php /** ******** finished displaying the column names ********* */ ?>
                    </tr> 
                </thead>
                <tbody>
                        <?php /** ******** we do! start displaying the items ********* */ ?>
                        <?php foreach ($this->failedpaginator as $item) : ?>
                            <tr>
                                <td><?php echo strtoupper($item[$config['columnIndexes'][0]]); ?></td> 
                                <td><?php if($item[$config['columnIndexes'][1]] < 0 || empty($item[$config['columnIndexes'][1]])){ echo " ";}else{  echo util::maskCard($item[$config['columnIndexes'][1]], 4);} ?></td>
                                <td><?php if($item[$config['columnIndexes'][2]] < 0 || empty($item[$config['columnIndexes'][2]])){ echo " ";}else{  echo $item[$config['columnIndexes'][2]];} ?></td> 
                                <td><?php echo $item[$config['columnIndexes'][3]]; ?></td>
                                <td><?php echo $item[$config['columnIndexes'][4]]; ?></td> 
                                <td><?php echo $item[$config['columnIndexes'][5]]; ?></td> 
                                <td><?php echo $item[$config['columnIndexes'][6]]; ?></td> 
                                <td><?php echo strtoupper($item[$config['columnIndexes'][7]]); ?></td> 
                                <td><?php echo $item[$config['columnIndexes'][8]]; ?></td> 
                                <td><?php echo strtoupper($item[$config['columnIndexes'][9]]); ?></td> 
                                <td><?php echo $item[$config['columnIndexes'][10]]; ?></td> 
                                <td><?php echo strtoupper($item[$config['columnIndexes'][11]]); ?></td>
                                <td><?php echo strtoupper($item['failed_reason']); ?></td>

                                <?php /* * ******** finished displaying the inner columns ********* */ ?>
                            </tr>    
                            <?php
                            //endforeach;
                        endforeach;
                        ?>
                        <?php /** ******** finished displaying the items ********* */ ?>
                </tbody> 
            </table>
        </div>
        <div>&nbsp;</div>
    </div>
    <?php endif; ?>
    <?php /********** finished do we have items? ********* */ ?>
    
    <div class="Boldtext">Wallet Details</div>
    <div class="tablebox">
        <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
            <table width="950" cellspacing='0'>
                <form name ="frm1" id ="frm1" action ="<?php $this->formatURL('/corp_ratnakar_cardload/corporateload') ?>" method = "POST"> 
                    <input type="hidden" id="batch" name="batch" value ="<?php echo $this->batch_name; ?>">
                    <thead><!-- universal table heading --> 
                        <tr>
                            <th><input type="checkbox" id="selectall"/></th>
                            <?php /*                             * ******** display the column names ********* */ ?>
                            <?php foreach ($config['columnNames'] as $columnName) : ?>
                                <th><span><?php echo $columnName; ?></span></th>
                            <?php endforeach; ?>

                            <?php /*                             * ******** finished displaying the column names ********* */ ?>
                        </tr> 
                    </thead>
                    <tbody>

                        <?php /*                         * ******** do we have items? ********* */ ?>
                        <?php if (count($this->paginator)) : ?>
                            <?php /*                             * ******** we do! start displaying the items ********* */ ?>
                            <?php
                            foreach ($this->paginator as $item) :
                                ?>

                                <tr>

                                    <?php
                                    /*                                     * ******** displaying the inner columns ********* */

                                    $cardId = $item['id'];
                                    ?>

                                    <td><input type="checkbox" class="reqid" name="reqid[]" value="<?php echo $cardId; ?>"/></td>

                                    <td><?php echo strtoupper($item[$config['columnIndexes'][0]]); ?></td>
                                    <td><?php if($item[$config['columnIndexes'][1]] < 0 || empty($item[$config['columnIndexes'][1]])){ echo " ";}else{  echo util::maskCard($item[$config['columnIndexes'][1]], 4);} ?></td>
                                    <td><?php if($item[$config['columnIndexes'][2]] < 0 || empty($item[$config['columnIndexes'][2]])){ echo " ";}else{  echo $item[$config['columnIndexes'][2]];} ?></td> 
                                    <td><?php echo $item[$config['columnIndexes'][3]]; ?></td>
                                    <td><?php echo $item[$config['columnIndexes'][4]]; ?></td>
                                    <td><?php echo $item[$config['columnIndexes'][5]]; ?></td> 
                                    <td><?php echo $item[$config['columnIndexes'][6]]; ?></td> 
                                    <td><?php echo strtoupper($item[$config['columnIndexes'][7]]); ?></td> 
                                    <td><?php echo $item[$config['columnIndexes'][8]]; ?></td> 
                                    <td><?php echo strtoupper($item[$config['columnIndexes'][9]]); ?></td> 
                                    <td><?php echo $item[$config['columnIndexes'][10]]; ?></td> 
                                    <td><?php echo strtoupper($item[$config['columnIndexes'][11]]); ?></td> 

                                    <?php /*                                     * ******** finished displaying the inner columns ********* */ ?>
                                </tr>    
                                <?php
                                //endforeach;
                            endforeach;
                            ?>
                            <?php /*                             * ******** finished displaying the items ********* */ ?>

                        <?php else: ?>
                            <?php /*                             * ******** we don't have any items ********* */ ?>
                            <tr>
                                <td colspan="<?php echo $cntColNames + 2; ?>">
                                    <?php echo $config['emptyMessage']; ?>
                                </td>
                            </tr>
                        <?php endif; ?>
                        <?php /*                         * ******** finished do we have items? ********* */ ?>
                    </tbody> 
            </table>
        </div>
        <div>&nbsp;</div>
        <input id="upload_cardholder" class="tangerine" type="submit" title="Submit" value="Submit" name="submit_success">
    </div>
    </form>


    <?php if (count($this->paginator) > 0) { ?>
        <div class="pagination">
            <?php if ($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
                <?php echo $this->paginator; ?>
            <?php endif; ?>
        </div>

    <?php }
}
?>
<script>
    $(document).ready(function() {
        $("#frm1").submit(function(e) {

            //remit_boi_remitter-neftresponse

            if (!$('input[type=checkbox]:checked').length) {
                //stop the form from submitting
                e.preventDefault();
                alert("Please select at least one to process.");
            }

            return true;
        });
        $("#selectall").click(function() {
            $('.reqid').attr('checked', this.checked);
        });

// if all checkbox are selected, check the selectall checkbox
// and viceversa
        $(".reqid").click(function() {

            if ($(".reqid").length == $(".reqid:checked").length) {
                $("#selectall").attr("checked", "checked");
            } else {
                $("#selectall").removeAttr("checked");
            }
        });

        var sample = '<?php echo $this->sample; ?>';
        if(sample == 0)
        {
            $("#doc_path").after("<br/><span style='font-size:12px;font-weight:normal;display:block;margin-top:10px;'><a href='<?php echo "/uploads/sample/CARD_LOAD_SAMPLE.csv";?>'>Download</a> sample file</span>");
        }
        else
        {
            $("#doc_path").after("<br/><span style='font-size:12px;font-weight:normal;display:block;margin-top:10px;'><a href='<?php echo $this->formatURL("/corp_kotak_reports/sampleload"); ?>' target='_blank'>Download</a> sample file</span>");
        }
    });
</script>
