<div class="Boldtext">Remitter Transactions Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

if($this->sub!=''){
    
$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;
$bankBoi = App_DI_Definition_Bank::getInstance(BANK_BOI);
$bankBoiUnicode = $bankBoi->bank->unicode;
$RatnakarBank = App_DI_Definition_Bank::getInstance(BANK_RATNAKAR);
$bankRatnakarUnicode = $RatnakarBank->bank->unicode;
// column names & indexes
$config['columnNames'] = array(
    'Transaction Date',
    'Remitter Registration Date',
    'Remitter Name',
    'Remitter Mobile',
    'Remit Amount',
    'Bene Name',
    'Bene Bank Name',
    'Bene IFSC Code',
);

$config['columnIndexes'] = array(
    'txn_date',
    'remitter_reg_date',
    'remitter_name',       
    'mobile',
    'amount',
    'bene_name',
    'bene_bank_name',
    'bene_ifsc_code',
    
);
if( ($this->formData['bank_unicode'] == $bankBoiUnicode) || ($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){
    array_push($config['columnNames'], 'Batch Name');
    array_push($config['columnIndexes'], 'batch_name');
    
}
if(($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){
    array_push($config['columnNames'], 'UTR');
    array_push($config['columnIndexes'], 'utr');
    array_push($config['columnNames'], 'Shmart reference number');
    array_push($config['columnIndexes'], 'txn_code');
    array_push($config['columnNames'], 'Status');
    array_push($config['columnIndexes'], 'status');
    
}
$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$cntColNames = count($config['columnNames']) - 1 ;
// render the default listing
/*echo $this->partial(
    'partials/report-agent-load-reload.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);*/


?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php 
        $totalRecords = count($this->paginator);
        if ($totalRecords) : ?>
            <?php /********** we do! start displaying the items **********/ 
            
            $totalRemitAmount='0.00';

            foreach($this->paginator as $item) : 
                $datePrev = '';
               
                    //foreach($dateArr as $item) :
                    //$tnxCode = $item[$config['columnIndexes'][5]];
                    //$item[$config['columnIndexes'][5]] = isset($TXN_TYPE_LABELS[$tnxCode])?$TXN_TYPE_LABELS[$tnxCode]:''; 
                ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][0]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo Util::returnDateFormatted($item[$config['columnIndexes'][1]], "Y-m-d", "d-m-Y", "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][4]]);?></td>
                        
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][6]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                         <?php if( ($this->formData['bank_unicode'] == $bankBoiUnicode) || ($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){ ?>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td><?php }?>
                        <?php if(($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){ ?>
                            <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                            <td><?php echo $item[$config['columnIndexes'][10]];?></td>
                            <td><?php echo $item[$config['columnIndexes'][11]];?></td>
                        <?php }?>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>
                <?php // calculating total remit amount to show below of remit amount column
                      $totalRemitAmount = $totalRemitAmount + $item[$config['columnIndexes'][4]];
                //endforeach;
            endforeach;?>
                <tr>
                    <td colspan="<?php echo $cntColNames+1;?>" style="text-align:right;"><b>Total Remit Amount</b> &nbsp;<?php echo Util::numberFormat($totalRemitAmount);?></td>
                </tr>
                        
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } }?>


<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        var dur = '<?php echo $this->formData['dur'];?>';
        if(dur==''){
            alert('Please specify duration');
        } else {
            var url = '<?php echo $this->formatURL("/remit_reports/exportremittertransaction?dur=".$this->formData['dur']."&bank_unicode=".$this->formData['bank_unicode']);?>';    
            $(location).attr('href',url);
       }
    }); 
    
    $('form').submit(function(){
       var bank_unicode = $.trim($("#bank_unicode").val()); 
       var dur = $.trim($("#dur").val()); 
       
       $('#bank_unicode').css('background', '#fff');
       $('#dur').css('background', '#fff');
      
         if( (bank_unicode == '') || (bank_unicode == '0') ){
             alert("Please select bank name.");
              $('#bank_unicode').css('background', '#ff0'); // will change the background to red
              $("#bank_unicode").focus();
              return false;
         }else if( (dur == '') || (dur == '0') ){
             alert("Please select specify duration.");
              $('#dur').css('background', '#ff0'); // will change the background to red
              $("#dur").focus();
              return false;
         } 
         return true;
        }); 
});
</script>