<div class="Boldtext">Remittance Commission Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$frmSubmit = isset($this->btnSubmit)?$this->btnSubmit:'';

if($frmSubmit){
    
$config = array();

// messages
$config['pageTitle'] = $this->pageTitle;
$config['emptyMessage'] = 'No record found.';

// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Super Distributor Code',
    'Super Distributor Name',
    'Distributor Code',
    'Distributor Name',
    'Agent Code',
    'Agent Name',
    'Agent City',
    'Agent Pincode', 
    'Transaction Narration',
    'Transaction Amount',
    'Transaction Fee',
    'Transaction Service Tax',
    'Commission Plan',
    'Commission Amount',
    'Agent Saving Account No.',
    'Agent IFSC Code',
);

$config['columnIndexes'] = array(
    'date_formatted',
    'agent_code',
    'name',
    'estab_city',
    'estab_pincode',
    'transaction_type_name',
    'transaction_amount',
    'transaction_fee',
    'transaction_service_tax',
    'plan_commission_name',
    'comm_amount',
    'bank_account_number',
    'bank_ifsc_code',
    'sup_dist_code',
    'sup_dist_name',
    'dist_code',
    'dist_name'
);

$config['actions'] = array();
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
                
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][14]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][15]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][16]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][17]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][4]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][6]]);?></td>
                        <td><?php echo $item[$config['columnIndexes'][7]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][8]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][9]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][10]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][11]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][12]];?></td>
                        
                        

                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 


<?php

if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } 


/*// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);*/

}

//echo "<pre>";print_r($this->paginator);exit;

?>


<script type="text/javascript">
$(document).ready(function() {    
    $("#btn_exportcsv").click(function(){
        
        var dur = '<?php $dur = isset($this->formData['duration'])?$this->formData['duration']:''; echo $dur;?>';
       
    
            var url = '<?php echo $this->formatURL("/remit_reports/exportremittancecommission?duration=".$this->formData['duration']."&bank_unicode=".$this->formData['bank_unicode']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']);?>';    
            
            $(location).attr('href',url);
       
    });  
    
    $("input#from_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter From date not greater than today's date");
                this.value = '';
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid From date');
                      this.value = '';
                      $('#from_date').css('background', '#ff0');
                      $("#from_date").focus();
                      return false;
                    }
                }


        }
        
    });
          
       $("input#to_date").change(function() {
        if(this.value) {
            var date_start = this.value; 
            var arr_dt = date_start.split("-");
            var x = new Date();
            x.setFullYear(arr_dt[2],arr_dt[1]-1,arr_dt[0]);
            var curdate = new Date();
            if(x > curdate)
            {
                alert("Please enter To date not greater than today's date");
                this.value = '';
                $('#bank_unicode').css('background', '#ff0');
                $("#to_date").focus();
                return false;
            }
            else{      
            
                    if (date_start.match(/^(0[1-9]|[12][0-9]|3[01])[\- \/.](?:(0[1-9]|1[012])[\- \/.](19|20)[0-9]{2})$/)){
                      return true;
                    }else{
                        alert('Please enter valid To date');
                      this.value = '';
                      $('#to_date').css('background', '#ff0');
                      $("#to_date").focus();
                      return false;
                    }
                }


        }
        
    });
    
    $('form').submit(function(){
  
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var bank_unicode = $("#bank_unicode").val();
       var duration = $("#duration").val(); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";
       /**** From and To date validation ****/
       $('#bank_unicode').css('background', '#fff');
       $('#duration').css('background', '#fff');
       $('#from_date').css('background', '#fff');
       $('#to_date').css('background', '#fff');
      
         if( (bank_unicode == '') || (bank_unicode == '0') ){
             alert("Please select bank name.");
              $('#bank_unicode').css('background', '#ff0'); // will change the background to red
              $("#bank_unicode").focus();
              return false;
         }else if((duration=='' && (from=='' && to=='') ) || (duration!='' && (from!='' || to!='') )){
                alert('Please select either duration or from and to date.');
                $('#duration').css('background', '#ff0');    
                $("#duration").focus();
            return false;
         } else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                alert('Please specify From date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false;
            }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                 alert('Please specify To date.');
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                 return false;
            } else if(diff < 0){
                alert('From date cannot be greater than To date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false; 
            }
               else if(date_range > max_range){
                  alert('Report can be fetched for a duration not more than '+max_range+' days');
                  $('#to_date').css('background', '#ff0');
                  $("#to_date").focus();
                  return false; 
               }
              
       /**** From and To date validation over ****/
      
          
     return true; 
   });     
});
</script>