<div class="Boldtext">Advanced Remittance Report</div>
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;

$config = array();
$duration = $this->from.' - '.$this->to;

// messages
$config['pageTitle'] = isset($this->title)?$this->title:'';
$config['emptyMessage'] = 'No record found.';
$config['no_add']=1;
$config['showActions'] = false;

$TXN_TYPE_LABELS = Zend_Registry::get("TXN_TYPE_LABELS");
$bankBoi = App_DI_Definition_Bank::getInstance(BANK_BOI);
$bankBoiUnicode = $bankBoi->bank->unicode;
$RatnakarBank = App_DI_Definition_Bank::getInstance(BANK_RATNAKAR);
$bankRatnakarUnicode = $RatnakarBank->bank->unicode;
$KotakBank = App_DI_Definition_Bank::getInstance(BANK_KOTAK);
$bankKotakUnicode = $KotakBank->bank->unicode;
if($this->sub){
           
// column names & indexes
$config['columnNames'] = array(
    'Transaction Date',
    'Super Distributor Code',
    'Super Distributor Name',
    'Distributor Code',
    'Distributor Name',
    'Agent Code',
    'Agent Mobile Number',
    'Agent Email ID',
    'Agent Name',
    'Agent City',
    'Agent Pincode',
    'Transaction Code',
    'Transaction Amount',
    'Customer Mobile Number',
    'Transaction Reference Number',
    'FTL Transaction ID',
    'Refund/Reversed Trx Ref Number',
    'Remitter Name',
    'Remitter Mobile Number',
    'Remitter Email',
    'Remitter Registration Date',
    'Bene Name',
    'Bene Bank Name',
    'Bene IFSC Code',
    'Current Transaction Status',
    'Reason',
    'Reason Code'
);

$config['columnIndexes'] = array(
    'txn_date',
    'agent_code',
    'agent_name',       
    'estab_city',
    'estab_pincode',
    'txn_type',
    'amount',
    'mobile_number',    
    'txn_code',
    'txnrefnum',
    'agent_mobile',
    'agent_email',
    'remit_name',
    'mobile_number',
    'remitter_email',
    'remit_regn_date',
    'bene_name',
    'bene_bankname',
    'bene_ifsccode',
    'txn_status',
    'final_response',
    'final_response',
    'sup_dist_code',
    'sup_dist_name',
    'dist_code',
    'dist_name',
    'refund_txn_code'
);
if(($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){
    array_push($config['columnNames'], 'UTR No');
    array_push($config['columnIndexes'], 'utr');
    
}
if( ($this->formData['bank_unicode'] == $bankBoiUnicode) || ($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){
    array_push($config['columnNames'], 'Batch Name');
    array_push($config['columnIndexes'], 'batch_name');
    
}

$config['showActions'] =FALSE;
$config['duration'] = $this->formData['dur'];
$cntColNames = count($config['columnNames']) - 1 ;
?>

<div class="Boldtext"><?php echo $config['pageTitle'];?></div>
<div style="clear:both;">
<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>
          
        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            
            foreach($this->paginator as $item) : 
                $datePrev = '';?>
                <?php 
                    $tnxCode = $item[$config['columnIndexes'][5]];
                    $item[$config['columnIndexes'][5]] = isset($TXN_TYPE_LABELS[$tnxCode])?$TXN_TYPE_LABELS[$tnxCode]:''; 
                ?>
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>

                        <td><?php echo $item['txn_date'];?></td>
                        <td><?php echo $item['sup_dist_code'];?></td>
                        <td><?php echo $item['sup_dist_name'];?></td>
                        <td><?php echo $item['dist_code'];?></td>
                        <td><?php echo $item['dist_name'];?></td>
                        <td><?php echo $item['agent_code'];?></td>
                        <td><?php echo $item['agent_mobile'];?></td>
                        <td><?php echo $item['agent_email'];?></td>
                        <td><?php echo $item['agent_name'];?></td>
                        <td><?php echo $item['estab_city'];?></td>
                        <td><?php echo $item['estab_pincode'];?></td>
                        <td><?php echo $item['txn_type'];?></td>
                        <td><?php echo Util::numberFormat($item['amount']);?></td>
                        <td><?php echo $item['mobile_number'];?></td>
                        <td><?php echo $item['txn_code'];?></td> 
			<td><?php
			if($this->formData['bank_unicode'] == $bankKotakUnicode) {
			    echo $item['txnrefnum'] ; 
			} else {
			    echo '';
			} 
			?></td>
		      <td><?php echo $item['refund_txn_code'];?></td>
                       
                      <td><?php echo $item['remit_name'];?></td>
                      <td><?php echo $item['mobile_number'];?></td>
                      <td><?php echo $item['remitter_email'];?></td>
                      <td><?php echo $item['remit_regn_date'];?></td>
                      
                      <td><?php echo $item['bene_name'];?></td>
                      <td><?php echo $item['bene_bankname'];?></td>
                      <td><?php echo $item['bene_ifsccode'];?></td>
                      <td><?php 
                      if($item['txn_status'] == STATUS_IN_PROCESS) {
                                $status  = 'In Process';
                            } else {
                                $status  = ucwords($item['txn_status']);
                            }
                      echo $status;?></td>
                      
                      <?php
                        $reason = explode(')', $item['final_response']);
                      ?>
                      <td><?php echo ltrim($reason[1]);?></td>
                      <td><?php echo str_replace('(', '', $reason[0]);?></td>
                     <?php if(($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){ ?>
                      <td><?php echo $item['utr'];?></td>
                          <?php }?>         
                     <?php if( ($this->formData['bank_unicode'] == $bankBoiUnicode) || ($this->formData['bank_unicode'] == $bankRatnakarUnicode) ){ ?>
                      <td><?php echo $item['batch_name'];?></td>
                          <?php }?>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>    
            <?php 
                //endforeach;
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 

<?php
if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>

<?php } 
if(count($this->paginator)>0){?>
<div class="show-xls"> 
       
         <input id="btn_exportcsv" src="/images/DOW-XLS.png" type="image" title="Export to CSV" name="btn_exportcsv">
       
</div>
<?php } }?>
<script type="text/javascript">
$(document).ready(function() {    
    
    $("#btn_exportcsv").click(function(){       
        var url = '<?php echo $this->formatURL("/remit_reports/exportsearchremit?bank_unicode=".$this->formData['bank_unicode']."&to_date=".$this->formData['to_date']."&from_date=".$this->formData['from_date']."&mobile_no=".$this->formData['mobile_no']."&txn_no=".$this->formData['txn_no'].'&duration='.$this->formData['duration']);?>';
        $(location).attr('href',url);       
    }); 
    
    var product = $("#product").val();  
    if($("#bank_unicode").val() != ''){
     $.ajax({
            url: '/ajax/get-productslistbyprogram/q/'+$("#bank_unicode").val(),
            success: function(response) {
                if(response == 1) {                            
                } else {                            
                    $("#product_id").html("");                            
                    $("#product_id").append(response);
                    $("#product_id option[value='"+product+"']").attr("selected", "selected");
                     console.log(response);                            
                }
            }     
        });
    }

    $("#bank_unicode").change(function(){
        $.ajax({
            url: '/ajax/get-productslistbyprogram/q/'+$("#bank_unicode").val(),
                success: function(response) {
                    if(response == 1) {                            
                    } else {                            
                        $("#product_id").html("");                            
                        $("#product_id").append(response);
                         console.log(response);                            
                }
            }    
        });
    });  
    
    $('form').submit(function(){
       var bank_unicode = $("#bank_unicode").val();
       var duration = $.trim($("#duration").val()); 
       var from = $.trim($("#from_date").val()); 
       var to = $.trim($("#to_date").val()); 
       var mobile = $.trim($("#mobile_no").val()); 
       var txn_no = $.trim($("#txn_no").val()); 
       var to = $.trim($("#to_date").val()); 
       var from_dt = from.split("-");
       var to_dt = to.split("-");
       var x = new Date(from_dt[2],from_dt[1],from_dt[0]);
       var y = new Date(to_dt[2],to_dt[1],to_dt[0]);
       var diff = y - x;
       var one_day=1000*60*60*24;
       var date_range = diff/one_day;
       var max_range = "<?php echo SEARCH_DURATION_MAX; ?>";

       
       /**** From and To date validation ****/
       $('#bank_unicode').css('background', '#fff');
       $('#from_date').css('background', '#fff');
       $('#to_date').css('background', '#fff');
      if( (bank_unicode == '') || (bank_unicode == '0') ){
             alert("Please select bank name.");
              $('#bank_unicode').css('background', '#ff0'); // will change the background to red
              $("#bank_unicode").focus();
              return false;
         }else if(mobile == '' && txn_no == '' && from == '' && duration == ''){
             alert("Please select at least one search criteria.");
              return false;
         }
    else if(mobile != '' && from == '' &&  duration == '' ){
             alert("Please select date range along with mobile no.");
              return false;
         }
    else if((duration!='' && (from!='' || to!='') )){
                alert('Please select either duration or from and to date.');
                $('#dur').css('background', '#ff0');    
                $("#dur").focus();
            return false;
         } 
    else if(((from == '' || from =='00-00-0000') && (to!='' && to!='00-00-0000'))) {
                alert('Please specify From date.');
                $('#from_date').css('background', '#ff0');
                $("#from_date").focus();
                return false;
            }else if(((to == '' || to=='00-00-0000') && (from!='' && from!='00-00-0000'))) {
                 alert('Please specify To date.');
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                 return false;
            } else if(diff < 0){
               alert('From date cannot be greater than To date.');
                $('#from_date').css('background', '#ff0');
                 $("#from_date").focus();
                 return false; 
            }
            else if(date_range > max_range){
               alert('Report can be fetched for a duration not more than '+max_range+' days');
                 $('#to_date').css('background', '#ff0');
                 $("#to_date").focus();
                 return false; 
            }
            
       /**** From and To date validation over ****/
          
     return true; 
   }); 
   
   $('input#mobile_no').keydown(function(event) {
        // Allow special chars + arrows 
        if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 
            || event.keyCode == 27 || event.keyCode == 13 
            || (event.keyCode == 65 && event.ctrlKey === true) 
            || (event.keyCode >= 35 && event.keyCode <= 39)){
                return;
        }else {
            // If it's not a number stop the keypress
            if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
                event.preventDefault(); 
            }   
        }
    });
});
</script>