<?php
/**
 * Layout used to display error pages
 *
 * @category backoffice
 * @package backoffice_layouts
 * @copyright company
 */

// configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Shmart!Pay - Business Partner');

// add generic scripts
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.min.js');

// add generic CSS files
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/login.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/navigation.css');

//Add the ZFDebug Toolbar only if enabled in app.ini
if(App_DI_Container::get('ConfigObject')->zfdebug->enabled){
    $this->headScript()->appendFile($this->baseUrl() . '/js/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
    <head> 
        <meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
        <meta http-equiv="content-style-type" content="text/css" /> 
        <meta http-equiv="content-script-type" content="text/javascript" /> 
        <noscript><meta http-equiv="refresh" content="1;url=/index/noscript"></noscript>
        <!-- link rel="shortcut icon" type="image/ico" href="<?php echo $this->baseUrl();?>/images/favicon.png" / -->
        
        <?php echo $this->headTitle() . PHP_EOL;?>
        <?php echo $this->headScript() . PHP_EOL;?>
        <?php echo $this->headLink() . PHP_EOL;?>
        
        <!--[if !IE 7]>
            <style type="text/css">
                div.wrapper {display:table;height:100%}
            </style>
        <![endif]-->
        
        <script type="text/javascript" charset="utf-8"> 
            //Set focus on username field
            $(document).ready(function() {
                $('input#username').focus();
            });
        </script> 
               <script language="javaScript" type="text/javascript">
        function are_cookies_enabled()
        {
                var cookieEnabled = (navigator.cookieEnabled) ? true : false;

                if (typeof navigator.cookieEnabled == "undefined" && !cookieEnabled)
                { 
                        document.cookie="testcookie";
                        cookieEnabled = (document.cookie.indexOf("testcookie") != -1) ? true : false;
                }
                return (cookieEnabled);
        }        
        if(!are_cookies_enabled()) {
            document.location.href = '/index/nocookie';
        }
    </script>        
    </head>
    <body>
        <div id="wrapper">
            <div id="content1">
                <div style="width:1000px; float:left; background-color:#000;">
                <div id="topheader">
                <div class="logo"><img src="<?php echo $this->baseUrl();?>/images/logo/logo-shmart.png" width="228" height="51" /></div>
                <div class="topheader-right">Business</div>
                </div>
                </div>
                
                <div id="navBOX">
                    <ul class="mainnav">
                      <li><a href="<?php echo $this->formatURL('/');?>">Home</a></li> 
                        <li><a id="logout" href="<?php echo $this->formatURL('/signup/index/');?>">Become a Shmart! Business Partner</a></li>
                        <li><a href="#">Contact Us</a></li> 
                    </ul>
                    <div class="navbox-right">Partner</div>
                </div>
                <div style="width:1000px;">
                <div class="leftbox">

                 <div class="boxtext">
                <div>
                  <div style="font:Arial, Helvetica, sans-serif; font-style:italic; font-size:16px; font-weight:bold; padding:10px 10px 0px 10px;">Important Notice:</div>
                  <div class="notice" >
                    <p>This is a Transerv Private Limited system, which may be accessed and used only for authorized purpose by authorized personnel only. Unauthorized access or use of this computer system may subject violators to criminal, civil, and/or administrative action.</p>

                    <p>Please report any unexpected or suspicious system behavior to <span class="link1"><a href="#" >admin@shmart.in</a></span></p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                  </div>
                  <div>&#13;</div>
                  <div></div>
                  <div></div>
                </div>
                </div>
                </div>


                <div class="rightbox">
                

                <?php echo $this->flashMessenger();?>
            <?php echo $this->layout()->content;?>


                <div class="clear"></div>
                <div class="bottomlogbg"></div>
                </div>
                </div>
                
                
            <div class="clear"></div>
            
            <div id="footer">  

            <div class="copyright">
                <div  class="footer-cc">Customer Care Number: <?php echo AGENT_AUTH_CALL_CENTRE_NUMBER;?></div>
            <div class="footer-left-box">
            <div class="footer-box">
<!--            <div class="text2">Connect with us on</div>-Text 2 END-
            <div class="facebook">
                <img src="<?php echo $this->baseUrl();?>/images/icons/facebook.png"  border="0" usemap="#Map10" />
              <map name="Map10" id="Map10">
                <area shape="rect" coords="-1,1,35,33" href="https://www.facebook.com/pages/Shmart/582198341805655" target="_blank" />
              </map>
            </div>
            <div class="twitter">
                <img src="<?php echo $this->baseUrl();?>/images/icons/twitter.png" border="0" usemap="#Map11" />
              <map name="Map11" id="Map11">
                <area shape="rect" coords="-3,2,31,36" href="https://twitter.com/ShmartPay" target="_blank" />
              </map>
            </div>-->
            <div class="term"><a href="#">Terms &amp; Conditions</a></div>
            <div class="clear"></div>




            </div><!---Footer Box END--->


            </div>
            <div class="footer-rights">2013 Shmart!Pay® Prepaid System. Worldwide rights reserved by TranServ Private Limited</div>

            <div class="clear"></div>
            </div> <!-- copyright ends -->
             </div>
 
 
        </div><!---Content End--->
        </div><!---Wrapper End--->
           
                
                
    </body>
</html>