<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

    
$config = array();

// messages
$config['pageTitle'] = 'Ratnakar Remittance Failed Transactions '.$this->remitterDetail['name'];
$config['emptyMessage'] = 'No record found.';
$config['no_add'] = 1;
$config['showActions'] = false;

// column names & indexes
$config['columnNames'] = array(
    'Date',
    'Beneficiary Name',
    'Beneficiary Bank',
    'Amount',
    'Refundable Amount',
//    'Refund Fee',
    'Remitter\'s Message',
'Transfer Mode'
);

$config['columnIndexes'] = array(
    'date_created',
    'beneficiary_name',
    'bank_name',
    'amount',    
    'refundable_amount',    
//    'refund_fee',    
    'sender_msg',
'flag'    
);

$config['actions'] = array(
        'refund'    =>  array(
        'action'        => 'refund',
        'title'         => 'Refund',
        'parameter'     => TRUE,
        'icon'          => FALSE,
        'img_url'       => '/images/icons/BAG.png',
        'img_alt'       => 'Refund',
    ),
      
    );

$config['linkOrder'] = array('refund');
$cntColNames = count($config['columnNames']) - 1 ;
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/ ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php endforeach;?>
                    <?php if(!isset($this->config['showActions']) || (isset($this->config['showActions']) && $this->config['showActions'])) : ?>
                            <th><span><?php echo 'Actions';?></span></th>
                        <?php endif; ?>
                <?php /********** finished displaying the column names **********/ ?>
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/ ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
               
                <tr>

                    <?php /********** displaying the inner columns **********/ ?>
                       <td><?php 

//echo ($item[$config['columnIndexes'][0]] == $datePrev) ? "" : $item[$config['columnIndexes'][0]];
                        echo Util::returnDateFormatted($item[$config['columnIndexes'][0]], $formatIn = "Y-m-d", $formatOut = "d-m-y", $separator = "-");?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][3]]);?></td>
                        <td><?php echo Util::numberFormat($item[$config['columnIndexes'][4]]);?></td>
<td><?php echo $item[$config['columnIndexes'][5]];?></td>
                        
                        <td><?php $flag = $item[$config['columnIndexes'][6]];
                        		  if($flag==2){
                        		  	echo "IMPS";
                        		  }else if($flag==3){
                        		  	echo "NEFT";
                        		  }else{
                        		  	echo "";
                        		  }
                        	?>
                        </td>
                       

 
                    <?php /********** finished displaying the inner columns **********/ ?>
                        <?php if(!isset($this->config['showActions']) || (isset($this->config['showActions']) && $this->config['showActions'])) : ?>
                        <td>
                            <a href="<?php echo $this->formatURL('/remit_ratnakar_beneficiary/failuretxn?rrid='.$item['remittance_request_id']);?>" title="Process Refund"><img alt="Process Refund" title ="Process Refund" src="<?php echo $this->baseUrl();?>/images/icons/icon-refund.jpg" border="0" height="22" width="20"></a>
                        </td>
                       
                        <?php endif; ?>
                </tr>    
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<?php if(count($this->paginator) != $this->countTotalRefunds['count_refund_requests']) {
    ?>
    <div class="note"><b>*Note: </b>There is/are failed transactions for the remitter for the products not assigned to you. Please ask the Remitter to call Helpdesk for assistance.</div>
<?php } ?>
