<div class="Boldtext">Fund Transfer</div> 
<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
echo $this->form;
$config = array();
$user = Zend_Auth::getInstance()->getIdentity();  
$countRefund = isset($this->countRefunds)?$this->countRefunds:'';
if ($this->showlist){
    if($this->remitterdetails['profile_photo'] == NULL){
        $profilePhoto = $this->baseUrl().'/uploads/photo/remitter/agnt-icon-big.gif'; 
    }  else {
       $profilePhoto = $this->baseUrl().'/uploads/photo/remitter/ratnakar/'.$this->remitterdetails['profile_photo'];  
    }

?>
<div class="clearboth"></div>
<div class="tablebox">
   
    <table style="width: 96%; align:centre;margin-left:18px;">
    <!--<tr> <td colspan ="2" style="align:right;"><img src="<?php //echo $profilePhoto;?>" width="85"></td></tr>-->
            <tr>
                <th style="width:20%">Name</th>            
                <td style="width: 80%" align="left"><?php echo $this->remitterdetails['name'];?></td>
            </tr>  
            <tr>
                <th style="width:20%">Mobile</th>            
                <td style="width: 80%" align="left"><?php echo $this->remitterdetails['mobile'];?></td>
            </tr>  
            <tr>
                <th style="width:20%">Email</th>            
                <td style="width: 80%" align="left"><?php echo $this->remitterdetails['email'];?></td>
            </tr>  
             
            <tr>
                <th style="width:20%">Remittance Done for the Month of <?php echo date('M');?></th>            
                <td style="width: 80%" align="left" id="remittanceDone"><?php echo $this->remittanceArr['total'];?></td>
            </tr> 
            <tr>
                <th style="width:20%">Status</th>            
                <td style="width: 80%" align="left"><?php echo $this->remitterdetails['status'];?></td>
            </tr> 
    </table>
   
</div>
<div class="clearboth"></div>

<div>&nbsp;</div> 
<?php
// messages
$config['pageTitle'] = 'Beneficiary Listing for: '.$this->remitterdetails['name'];
$config['addMessage'] = 'Add New Beneficiary'; 

$config['emptyMessage'] = 'There is no beneficiary enrolled at this time.';

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Bank Name',
    'Account Number',
    'IFSC Code'
    
);
$config['columnIndexes'] = array(
    'name',
    'bank_name',
    'bank_account_number',
    'ifsc_code'
);


$config['linkOrder'] = array('transferfund','deactivatebeneficiary');

// render the default listing
if($this->remitterdetails['status'] == STATUS_ACTIVE){
?>
<div class="Boldtext"><?php echo $config['pageTitle'];?></div>
<div class="filterbox" style="width:950px;"> 
    <a class="ocean" title="<?php echo $config['addMessage'];?>" style="float:right;" href="<?php echo $this->formatURL('/remit_ratnakar_beneficiary/add');?>"><?php echo $config['addMessage'];?></a>
</div>

<div class="tablebox">
    <div style="width:950px; margin:auto; overflow-x: auto; overflow-y: hidden;">
    <table width="950" cellspacing='0'>
       
        <thead><!-- universal table heading --> 
            <tr>
                <?php /********** display the column names **********/
                 $cntColNames = 0;
                ?>
                <?php foreach($config['columnNames'] as $columnName) : ?>
                    <th><span><?php echo $columnName;?></span></th>
                <?php 
                $cntColNames++;
                endforeach;?>
                 <th colspan ="3" class="last tc"><span><?php echo 'Actions';?></span></th>
                       
            </tr> 
        </thead>
        <tbody>

        <?php /********** do we have items? **********/
       ?>
        <?php if (count($this->paginator)) : ?>
            <?php /********** we do! start displaying the items **********/ ?>
            <?php 
            foreach($this->paginator as $item) : 
                ?>
                
                <tr id="<?php echo $item['id'];?>">

                    <?php /********** displaying the inner columns **********/ 
                        
                        $url = '/remit_ratnakar_beneficiary/transferfund?id='.$item['id'];
                        $transactionsUrl = '/remit_ratnakar_remitter/transactions?mobile='.$this->remitterdetails->mobile.'&id='.$item['id'];
                        $urldeactivate = '/remit_ratnakar_beneficiary/deactivatebeneficiary?id='.$item['id'];
                        $name = $item[$config['columnIndexes'][0]];
                        ?>
                        <td><?php echo $item[$config['columnIndexes'][0]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][1]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][2]];?></td>
                        <td><?php echo $item[$config['columnIndexes'][3]];?></td>
                        <?php 
						$rat_status = isset($item['rat_status']) ? $item['rat_status'] : 0;
  if($item['enable_for']=='all')
						$transfer_flag = '<input data-ratStatus="'.$rat_status.'" id="'.$item['id'].'" name="transfer_falg_'.$item['id'].'" type="radio" value="3" />NEFT<input data-ratStatus="'.$rat_status.'" id="'.$item['id'].'" name="transfer_falg_'.$item['id'].'" type="radio" value="2" />IMPS'; 
                                                else  if($item['enable_for']=='neft')
						$transfer_flag = '<input data-ratStatus="'.$rat_status.'" id="'.$item['id'].'" name="transfer_falg_'.$item['id'].'" type="radio" value="3" />NEFT'; 
                                                else if($item['enable_for']=='imps')
						$transfer_flag = '<input data-ratStatus="'.$rat_status.'" id="'.$item['id'].'" name="transfer_falg_'.$item['id'].'" type="radio" value="2" />IMPS'; ?>
                      
                        <?php 
						$otpField = $amountField = '';
						
						  $otpField =  '<div style="display:none" id="otp_div_'.$item['id'].'">OTP:<input type="text" id="otp_value"  value="" name="opt_'.$item['id'].'"><input data-pid="'.$item['id'].'" id="otp_submit" value="Validate" type="submit" onClick="return validateOtp(\''.$item['id'].'\'); return false;" id="otp_submit.'.$item['id'].'"></div>';
					
						 $ammoutState = $item['rat_status'] ? 'style=""' : 'style="display:none"';
						  $amountField = '<span id="span_amount_'.$item['id'].'" '.$ammoutState.'>Amount:<input  type="text" name="amount_'.$item['id'].'" id="amount_'.$item['id'].'" size="6" maxlength="6"></span>';
						
						?>
					   <?php echo  '<td align="left">'.$amountField.$transfer_flag.$otpField.'<a id="transfer_button_'.$item['id'].'" '.$ammoutState.' href="javascript:void(0);" onClick="doAlert(\''.$item['id'].'\',\''.$name.'\');" title="Transfer Fund">' . PHP_EOL . '<img alt="Transfer Fund" src="'.$this->baseUrl().'/images/icons/BAG.png" border="0"></a></td>'; ?>
                       <td><a url="<?php echo $this->formatURL($urldeactivate) ?>" onclick="javascript:confirmDeactivate('<?php echo $item['id']?>','<?php echo $name;?>');" class ="deactivate<?php echo $item['id']?>"  title="Deactivate" ><?php echo '<img alt="Deactivate" src="'.$this->baseUrl().'/images/icons/blocked.png" border="0"></a></td>'; ?>
                        <?php echo  '<td><a href="'. $this->formatURL($transactionsUrl) . '" title="Transactions">' . PHP_EOL . 'Transactions</a></td>';?>
                    <?php /********** finished displaying the inner columns **********/ ?>
                </tr>
                <tr id="transfer_<?php echo $item['id']?>" style="display: none;">
                    <td colspan="<?php echo $cntColNames+3;?>"></td>  
                </tr>
            <?php 
            endforeach;?>
            <?php /********** finished displaying the items **********/ ?>
        <?php else:?>
            <?php /********** we don't have any items **********/ ?>
            <tr>
                <td colspan="<?php echo $cntColNames+1;?>">
                    <?php echo $config['emptyMessage'];?>
                </td>
            </tr>
        <?php endif;?>
        <?php /********** finished do we have items? **********/ ?>
        </tbody> 
    </table>
    </div>
</div>
<div>&nbsp;</div> 
<?php
}


if(count($this->paginator)>0){?>
<div class="pagination">
    <?php if($this->paginator Instanceof Zend_Paginator && $this->paginator->count() > 1) : ?>
        <?php echo $this->paginator; ?>
    <?php endif; ?>
</div>


<?php } 

}   $session = new Zend_Session_Namespace('App.Agent.Controller');    
    if($countRefund >0){
 ?>
<div class="filterbox" style="width:950px;"> 
    <a class="ocean" title="Refund" style="float:right;" href="<?php echo $this->formatURL('/remit_ratnakar_beneficiary/failuretxn');?>">Refund</a>
</div>
<?php } ?>

<script type="text/javascript">
function validateOtp(id) {
	var val = $('input[name="opt_'+id+'"]').val();
	   $.ajax({
					url:"/ajax/get-rblotpvalidate/otp/"+val+'/id/'+id,
					success: function(response) {
						if(response > 0) {
							$('#otp_div_'+response).hide();
							$('#transfer_button_'+response).show();
							$('#span_amount_'+response).show();
						}
					}
		});
	}
$(document).ready(function(e) {
	
	
	  
	 


    $('table input[type=radio]').change(function(){ 
	    var id = $(this).attr('id');
		var ratStatus = $(this).attr('data-ratStatus');
		if(ratStatus != 1){ 
		
   $( "#transfer_"+id+" td" ).html('<img src="/images/ajax-loader.gif">');
   $( "#transfer_"+id ).show();
			
		$.ajax({
					url:"/ajax/get-rblregistercheck/id/"+id,
					success: function(response) {
						if(response == 1) {
							$( "#transfer_"+id+" td" ).html('Authorization code has been sent on remitter mobile number.');
							$('#otp_div_'+id).show();
						}else if(response == 0) {
							$( "#transfer_"+id+" td" ).html('Authorization code has been re-sent on remitter mobile number.');
							$('#otp_div_'+id).show();
						}else {
							 $( "#transfer_"+id+" td" ).html(response); 
						}
						$( "#transfer_"+id ).slideUp( 4000, function() {
							 $( "#transfer_"+id+" td" ).html('');   
						}).delay(3200).fadeOut(300);						
					}
		});
		}
	});
});
    function confirmDeactivate(id, name) {
        var discardResp = confirm('Are you sure you want to deactivate beneficiary: '+name);
        var url = $('.deactivate'+id).attr('url');
        if(discardResp == true){
            window.location.href= url;
           return true;
        }else {
            return false;
        }
    }
     var active = true;
    
     function doAlert(rowid,name) {
           if(!active){
            return;
        }
        var agentId = "<?php echo $user->id;?>";
		var flag = $("input[name=transfer_falg_"+rowid+"]:checked").val();
        $( "#transfer_"+rowid+" td" ).html('');
      
          var amt = $('#amount_'+rowid).val();
            if($('#amount_'+rowid).val() == '')  {
                alert('Please enter valid amount for fund transfer') ;
                $('#amount_'+rowid).focus();
                
                return ;
            } else{
                
                var isnum = /^\d+$/.test(amt);
                if(!isnum)
                {
                    alert('Please enter valid amount') ;
                   $('#amount_'+rowid).focus();
                  
                    return ;
                }
            }
			
			var flag_selector = 'input[name=transfer_falg_'+rowid+']:checked';
			if(!$(flag_selector).val())  {
                alert('Please select transfer type') ;
                $(flag_selector).focus();
                
                return ;
            } 
			
			
			
        
        
        var confirmTransfer = confirm('Are you sure you want to transfer Rs.'+$('#amount_'+rowid).val()+' to beneficiary: '+name);
        if(confirmTransfer == true){
            //$( "#transfer_"+rowid ).slideDown( "slow", function() {
            $( "#transfer_"+rowid+" td" ).html('<img src="/images/ajax-loader.gif">');
            $( "#transfer_"+rowid ).show();
            //}).delay(200).fadeIn(300);;
            active = false; $( "#transfer_button_"+rowid ).hide();
            $.ajax({
                url: '/ajax/get-fundtransfer/flag/'+flag+'/aid/'+agentId+'/bid/'+rowid+'/amount/'+$('#amount_'+rowid).val(),
                success: function(response) {
                        active = true; $( "#transfer_button_"+rowid ).show();
                        $('#amount_'+rowid).val('');
                        $( "#transfer_"+rowid+" td" ).html(response);
                        $( "#transfer_"+rowid ).slideUp( 4000, function() {
                         $( "#transfer_"+rowid+" td" ).html('');   
                        }).delay(3200).fadeOut(300);
                }
            });
        }
    }
  
</script>
     
     
