<?php
/**
 * Displays all the user groups
 *
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */
$config = array();
?>

<?php
// messages
$config['pageTitle'] = 'Transfer Fund';
if($this->showBackLink){
    	$config['back_url'] = '/remit_ratnakar_beneficiary/searchremitter?flgSess=1';
    }
echo $this->partial(
        'partials/default-add-edit.phtml', array(
    'form' => $this->form,
    'config' => $config
        )
);

$session = new Zend_Session_Namespace('App.Agent.Controller');
?>
<div class="clearboth"></div>
<div style="width:950px;">
    <a href="<?php echo $this->formatURL($config['back_url']);?>" class="ocean" style="float:right;" title="Back">Back</a>
</div><!--Inner Style Div END-->
<div class="clearboth"></div>

<div class="tablebox">
 

    <table style="width: 96%;margin-left: 17px;">
        <tr>
            <th style="width:20%">Remitter Name</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['remitter_name']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Remitter Mobile</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['remitter_mobile']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Remitter Email</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['remitter_email']; ?></td>
        </tr>  

    </table>

    <table style="width: 96%;margin-left: 17px;">

        <tr>
            <th style="width:20%">Beneficiary Name</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['name']; ?></td>
        </tr>  
<!--        <tr>
            <th style="width:20%">Nick Name</th>            
            <td style="width: 80%" align="left"><?php //echo $this->detail['nick_name']; ?></td>
        </tr>  -->
        <tr>
            <th style="width:20%">Bank Name</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['bank_name']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">IFSC Code</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['ifsc_code']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Account Type</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['bank_account_type']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Account No.</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['bank_account_number']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Branch Name</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['branch_name']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Branch Address</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['branch_address']; ?></td>
        </tr>  
        <tr>
            <th style="width:20%">Branch City</th>            
            <td style="width: 80%" align="left"><?php echo $this->detail['branch_city']; ?></td>
        </tr>  

    </table>

</div>
<div>&nbsp;</div> 

<script type="text/javascript">
    $(document).ready(function() { 
     
        $('form').submit(function() {
            
            
            var amt = $("#amount").val();
            if($("#amount").val() == '')  {
                alert('Please enter valid amount for fund transfer') ;
                $("#amount").focus();
                return false;
            } else{
                
                var isnum = /^\d+$/.test(amt);
                if(!isnum)
                {
                    alert('Please enter valid amount') ;
                    $("#amount").focus();
                    return false;
                }
            }
            
            return true;
        });  
    });      
</script>

