<?php
/**
 * Displays all the registered users
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_users
 * @copyright company
 */

$config = array();

// messages
$config['pageTitle'] = 'Manage Users';
$config['addMessage'] = 'Add New User'; 
$config['emptyMessage'] = 'We don\'t have users registered at this time.';

// column names & indexes
$config['columnNames'] = array(
    'Username',
    'First Name',
    'Last Name',
    'Group',
);

$config['columnIndexes'] = array(
    'username',
    'firstname',
    'lastname',
    'groupname',
);

$config['viewLinkColumn'] = 'username';

// render the default listing
echo $this->partial(
    'partials/default-listing.phtml',
    array(
        'config' => $config,
        'paginator' => $this->paginator,
    )
);