<?php
/**
 * Active a cardholder with its tids 
 *
 */

 
$config = array();
$config['pageTitle'] = sprintf('Activate "%s"?', $this->item['cardholder_name']);
$config['areYouSureMessage'] = sprintf('Are you sure you want to activate cardholder "%s"?', $this->item['cardholder_name']);

// column names & indexes
$config['columnNames'] = array(
    'Card Number',
    'Member Id',
    'Employee Id',
    'Cardholder Name',
    'Gender',
    'Aadhaar Number',
    'PAN',
    'Mobile',
    'Email',
    'Employer Name',
);

$config['columnIndexes'] = array(
    'card_number',
    'member_id',
    'employee_id',       
    'cardholder_name',
    'gender',
    'aadhaar_no',
    'pan',
    'mobile',
    'email',
    'employer_name',
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);
